### ISSUE TITLE
[Feature Request] Set a time for auto update to occur

### ISSUE THREAD

**Issue by ClammyMantis488** [Jays2Kings/tachiyomiJ2K#100]
### Why/User Benefit/User Problem
It would help people who want their manga to auto update at not some random time/make it update after all their manga has usually been released for the day. Personally when I get home my manga hasn't updated so I have to hit it manually. It would be nice if when I got home my manga would be all updated.

### What/Requirements
There would be a time setting for when it would auto update when you turn it on. It would only need to be set one time, you wouldn't need more slots for different update intervals because it's implied that if it's set to for example 2:00PM then the next X hours it would update at 2:00PM+X.

**Comment by Jays2Kings** [comment]
Not gonna happen. Even in that specific case, there can be a time you get home later (or it's the weekend, you're on vacation etc.), and then what? If you made it so your library doesn't sync on mobile it won't update at the set time anyway. Sorry but you'll have to just continue to update manually, which you can already do by pulling to refresh in the updates screen

**Comment by ClammyMantis488** [comment]
I don't understand why being able to control the auto update time is such a bad feature
