### ISSUE TITLE
Library/Recents/Browse --- Position

### ISSUE THREAD

**Issue by xlixAxilx** [Jays2Kings/tachiyomiJ2K#1001]
**Issue/Request:**
I know you are going for a different look, but can you give us the option to have this tab be on the right or left?
I hold my tablet with the left hand and travers with my right, I have to jump over the screen to tap on them. 

You could give us a setting where we can have it on the left or right

Thank you.

**Comment by Jays2Kings** [comment]
Not going to happen. theres an option if you want to have the navigation back on the bottom, but there wont be an option for a side switch
