### ISSUE TITLE
[Feature Request] horizontal tabs

### ISSUE THREAD

**Issue by Blackklegend** [Jays2Kings/tachiyomiJ2K#1005]
### Why/User Benefit/User Problem
So, I have a lot of mangas on my library, close to 100 and i think the app overall is great, but it's really difficult for me to localize myself properly using the scroll down system, which would significantly improve if it had the option to see the categories in tabs instead of a scroll list

### What/Requirements
You would be able to choose to see the categories in a scroll system like actually is, or to use tabs as categories. A toggle in options or when you first open the app should do the trick

**Comment by CarlosEsco** [comment]
No.  Go use regular tachiyomi if you want tabs
