### ISSUE TITLE
[Feature Request] Store chapter in cbz/zip format instead of directory

### ISSUE THREAD

**Issue by Fahad1998** [Jays2Kings/tachiyomiJ2K#101]
### Why/User Benefit/User Problem
Having too many files wastes space because of cluster size. Specially if user keep downloaded manga in microsd card. Because microsd cards file system use large cluster size. 

### What/Requirements
User will have option to save downloaded chapter as directory or zip format. Files will be zipped uncompressed or will have option to select compression level.

**Comment by CarlosEsco** [comment]
#84
