### ISSUE TITLE
[Feature Request] Please add a feature that would allow users to change fonts!

### ISSUE THREAD

**Issue by rsmyst** [Jays2Kings/tachiyomiJ2K#1012]
### Why/User Benefit/User Problem
Recently began using J2K fork after using the standard one for a year or so. I find the UI of J2K 10x better than the standard one's. It just feels a bit smoother and more user friendly to me. The only gripe i had atm is that i can't choose mono space or something similar as a font. I tried neko fork of tachi and it had this really nice font. I didn't use that fork because mangadex is slow for me and many chapters are missing.

### What/Requirements
A font changing feature between a couple fonts. Maybe like a drop down with font previews we can choose from in the appearance section?

Good work btw! the app is great and seems a tad bit faster in loading manga than the standard one.

**Comment by fleurc** [comment]
I second this feature, would be even nicer if one of the fonts was for dyslexic people, there one which is free of charge, i think called OpenDyslexic. Just tad more personalization for a better UI experience.

**Comment by lasersPew** [comment]
And add a custom font button that when clicked, opens a file picker.

**Comment by arkon** [comment]
How many apps even let you choose the font within it? Why wouldn't you just change it at the system level if you really had a need to?

**Comment by lasersPew** [comment]
> How many apps even let you choose the font within it? Why wouldn't you just change it at the system level if you really had a need to?

You'll need to root your phone to add custom fonts and if your phone is Samsung, the selection of fonts in the app store that doesn't need root to apply.

**Comment by rsmyst** [comment]
> How many apps even let you choose the font within it? Why wouldn't you just change it at the system level if you really had a need to?

I just thought a feature like font changing would make the app more unique to use. I don't recall any apps allowing font changes so maybe it's just not possible on android. 
I also really like the monospace style font so i requested the feature

**Comment by CarlosEsco** [comment]
This won't be added
