### ISSUE TITLE
Accounts to sync data across different devices

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#1013]
### Why/User Benefit/User Problem
(explain why this feature should be added)
If you read manga on many different devices having to manually sync everything can be a hassle

### What/Requirements
(explain how this feature would behave)
settings> account make a tachiyomi account and sign in

**Comment by CarlosEsco** [comment]
Great idea!  Please provide a monthly payment for the servers, as this a free app without servers.
