### ISSUE TITLE
[Bug] ReadComicOnline extension improperly reads comics as manga

### ISSUE THREAD

**Issue by ggermain1** [Jays2Kings/tachiyomiJ2K#1014]
### Device information
* Tachiyomi version: 1.3.1
* Android phone & version: Samsung Galaxy A50 / Android 11

## Steps to reproduce
1. Open a comic chapter on ReadComicOnline extension
2. Scroll through chapter

### Expected behavior
The reader should be set to read from left to right.

### Actual behavior
The reader is set to read from right to left.

### Other details
The proper behavior can be demonstrated with other comicbook extensions such as ComicExtra.

**Comment by Jays2Kings** [comment]
This is a request not a bug, not all sources with comic in the name have only comics that are read left to right.

Also note: this change only applies to newly added comics, anything else you will manually have to set
