### ISSUE TITLE
[Feature request] ON webtoon mod can't choose Split two pages

### ISSUE THREAD

**Issue by recycle007** [Jays2Kings/tachiyomiJ2K#1017]
Excuse me for add a new issue, i haved tested the regular tachiyomi app. ON webtoon mod can't choose Split two pages in j2k witch have on the regular tachiyomi app.

**Comment by recycle007** [comment]
actually, not just Split two pages, the button at the bottom is not customized as what i set on webtoon mod.

**Comment by Jays2Kings** [comment]
provide a screenshot of what you're talking about because I have no idea what you mean

**Comment by Jays2Kings** [comment]
this is a request not a bug, how can it be a bug for a feature not even implemented?
