### ISSUE TITLE
[Feature Request] Ability to make custom themes in-app

### ISSUE THREAD

**Issue by rsmyst** [Jays2Kings/tachiyomiJ2K#1019]
### Why/User Benefit/User Problem
It'd add a ton more customization options. Preferably options for custom fonts can also be added along with custom colour selections for things.
For me personally, I want a darker shade of orange in my main dark theme but the current orange-ish theme doesn't fit that look.

### What/Requirements
Users would be able to get a new set of "advanced" features as a dropdown. Perhaps they can choose colours for different things from there and an option to revert to default.
And an option to change fonts and styles too maybe.

**Comment by lasersPew** [comment]
It should also have a share button so if the user wants to share his'/her' solarised theme, they could click that button to share it with others.

**Comment by rsmyst** [comment]
> It should also have a share button so if the user wants to share his'/her' solarised theme, they could click that button to share it with others.

Yea that sounds pretty good too. Features like this would really make j2k more unique and beautiful as compared to tachiyomi.

**Comment by lasersPew** [comment]
You can make the layout like in the NamanSherill/diohub.

**Comment by arkon** [comment]
> You can make the layout like in the NamanSherill/diohub.

Yeah, just rewrite the whole app as a Flutter app. /s

**Comment by CarlosEsco** [comment]
This isn't happening unless android supports better dynamic xml theming
