### ISSUE TITLE
[Bug/Feature Request] Sync to tracker when a chapter is marked as read. 

### ISSUE THREAD

**Issue by pranavtifr** [Jays2Kings/tachiyomiJ2K#102]
**App version: 0.9.761**

**Android version: Q**

**Issue/Request:** When trying to sync chapters with MAL after reading, The app syncs chapters only if the chapter is opened and we reach the last page. It would be nicer if the app also does it when a chapter is marked as read

**Steps to reproduce**

 1. Read the chapter in the app. The MAL syncs automatically. 
 2. Mark a chapter as read. MAL Doesn't.

**Comment by Battler624** [comment]
Requesting this.

**Comment by CarlosEsco** [comment]
No plans to add this.  It then comes with a downside of you marking duplicate chapters read and your tracker not being correct.  its  not that much to click the tracker icon and quick update them
