### ISSUE TITLE
[Bug] Loading screen of tachiyomiJ2K not matching actual in-app theme

### ISSUE THREAD

**Issue by rsmyst** [Jays2Kings/tachiyomiJ2K#1020]
###Basic Info:
For example, choosing pure black theme in app doesn't make loading screen pure black as well.

### Device information
* Tachiyomi version: v1.3.2
* Android phone & version: 10

## Steps to reproduce
1. Set in app theme to pure dark mode supported by OLEDs
2. Close the app and open it.

### Expected behavior
The loading screen has a shade of grey instead of pure black like the user chose.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by DaviDeMeo** [comment]
While the splash screen is open the app is loading so it has no knowledge of your custom theme, it only know if it's in dark mode.
Android 12 will only add icon animations but no way of using custom background color

**Comment by CarlosEsco** [comment]
see above
