### ISSUE TITLE
[Bug] My downloads from Mangaowl are deleted.

### ISSUE THREAD

**Issue by MedKing3** [Jays2Kings/tachiyomiJ2K#1021]
### Device information
* Tachiyomi version: v 1.3.2
* Android phone & version: Redmi Note 10 Android 11

## Steps to reproduce
1. Download manga from Mangaowl
2. Open the manga that you downloaded afterwards

### Expected behavior
You can read the downloaded manga.

### Actual behavior
The manga is not downloaded.

### Other details
This doesn't happen instantly. I downloaded mangas from Mangaowl three days ago and was about to read it yesterday but the mangas were deleted. I downloaded those mangas again and tried to read it just now but the same thing happened. This issue doesn't happen on my Tachiyomi stable app so it's not really an issue of the extension Mangaowl.

**Comment by Jays2Kings** [comment]
Mangaowl and similar sources constantly delete and reupload chapters. If a chapter is deleted it will be deleted from downloads too.

You can go to download settings and disable automatic removal to keep them
