### ISSUE TITLE
[Bug] Latest chapter of Rent-A-Girlfriend from catmanga returns null when opened

### ISSUE THREAD

**Issue by lasersPew** [Jays2Kings/tachiyomiJ2K#1035]
---

### Device information
* Tachiyomi version: 1.3.2
* Android phone & version: Samsung Galaxy J7 Pro(2017) Android 9

## Steps to reproduce
1. Add Rent-A-Girlfriend manga from catmanga
2. Refresh to get the new chapters.
3. Click the latest chapter(208)

### Expected behavior
Should load the manga

### Actual behavior
Doesn't load and returns null.

### Other details
![Screenshot_20211011-210218_TachiyomiJ2K](https://user-images.githubusercontent.com/87552756/136794992-008bbab5-700b-4e5c-bc24-fe5905fa6920.jpg)

**Comment by Jays2Kings** [comment]
See above
