### ISSUE TITLE
[Visual request / Bug] Downloaded Badge 

### ISSUE THREAD

**Issue by coldroman** [Jays2Kings/tachiyomiJ2K#1044]
**App version:**1.4.2

**Android version:**8.1

**Issue/Request:**Fix the font of the title to bold, remove the outline around the cover too spoils the appearance of the cover, change the shape of the indicator of unread chapters or downloaded chapters to a circle (or add the ability to change the shape)

Other details:
![PicsArt_10-16-04 04 34](https://user-images.githubusercontent.com/83245450/137588868-e35ad74a-0747-413c-adc2-3850e7b75ea2.jpg)
![PicsArt_10-16-04 02 44](https://user-images.githubusercontent.com/83245450/137588869-e2e6b501-d027-4797-8d41-63dcf94a325b.jpg)

**Comment by Jays2Kings** [comment]
closing this because 2 of these are covered for next release, the other one isn't happening
