### ISSUE TITLE
[Feature Request] Bring back tinted backdrop in manga info (or make it optional)

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#1046]
### Why/User Benefit/User Problem
The coloured tint backdrop has been a signature UI element of J2K, and imo it looks much better than the bland and dark backdrop in main Tachi.

### What/Requirements
Restore the old backdrop, or make it [optional](https://github.com/Jays2Kings/tachiyomiJ2K/commit/7cc73ba503b6643b5453663960414052c226eb19) like the cover outline.

Nice update btw :)

**Comment by Jays2Kings** [comment]
Already back for next release
