### ISSUE TITLE
[Bug] post decimal chapter numbering system 

### ISSUE THREAD

**Issue by AbdullahMehiz** [Jays2Kings/tachiyomiJ2K#1047]
No### Device information
* Tachiyomi version: 1.14.2
* Android phone & version: Xiaomi Redmi Note 8 Pro, Android 11

## Steps to reproduce
1. Have few chapters numbered after the decimal point like 0.1, 0.2, 0.3 ... 0.10, 0.11... etc
2. Browse them chapters and see the order they come in

### Expected behavior
This should happen.
Chapters should be ordered as 
1. 0.1
2. 0.2
3. 0.3
4. 0.4
5. ...
6. 0.10
7. 0.11
8. ...
9. 0.20
10. 0.21
### Actual behavior
This happened instead.
Chapters are ordered in this way 
1. 0.1
2. 0.10
3. 0.11
4. 0.12
5. ...
6. 0.2
7. 0.20
8. 0.21
9. ...
10. 0.3
### Other details
Soo it kinda got fixed https://github.com/tachiyomiorg/tachiyomi/commit/f057440cc1ebfc62bd1d3b85b284781ea9bce9bc
Additional details and attachments.
This issue is similar to #964
Screenshot from berserk, from mangakakalot extension
![Screenshot_2021-10-16-22-36-45-058_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/85505634/137602704-88a97f29-8c91-42c3-b0af-edf052680b8e.jpg)

**Comment by Jays2Kings** [comment]
Don't make an issue recent commits from.main tachiyomi, it'll be added in later
