### ISSUE TITLE
[Bug] App shortcuts almost not visible

### ISSUE THREAD

**Issue by RafaelHerzog** [Jays2Kings/tachiyomiJ2K#105]
### Device information
* Tachiyomi version: 0.9.761
* Android phone & version: Moto G5, Android 8.1.0

## Steps to reproduce
1. Long press the app
2. The shortcuts are almost black (there's an attachment)

### Expected behavior
The shortcuts must be visible

### Actual behavior
The shortcuts can only be distincted by the text

### Other details
![Screenshot_20200209-222752](https://user-images.githubusercontent.com/49111482/74115076-1e0e9c00-4b8c-11ea-88ae-bec48f844439.png)

**Comment by Jays2Kings** [comment]
Fixed as of 0.9.8

**Comment by Poopooracoocoo** [comment]
uh. are they being removed?
