### ISSUE TITLE
[Feature Request] Create dummy entries for manga when backup restore fails

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#106]
### Why/User Benefit/User Problem
Currently when a source is down, backup restoration doesn't work since it can't fetch data from website. This would allow to restore backups of failed entries (partially), thus not being forced to check the error log and manually add all the missing entries back.

### What/Requirements
After restoration, dummy manga entries will be created instead of full entries in My library, which would only have title and whatever's available on the backup file. Similar to Dummy Rock apk on Discord.

Optional request ( for better user experience): If source website is back up and running, restoring backup again would replace the existing dummy entries with actual ones. Ignore this if too difficult to implement or seems unimportant.

**Comment by Jays2Kings** [comment]
Tested and this one wont be happening due to how manga is currently saved

**Comment by joseph619** [comment]
Sy was trying something like this, but apparently it broke backup backward compatibility

https://github.com/inorichi/tachiyomi/pull/3129
