### ISSUE TITLE
[Bug] Kuma Scans not showing Cover image

### ISSUE THREAD

**Issue by curryturtle** [Jays2Kings/tachiyomiJ2K#1062]
### Device information
* Tachiyomi version: v1.4.3
* Android phone & version: Galaxy S21 | Android 11

## Steps to reproduce
1. Download Kuma Scans (Kuma Translation)
2. Open any manga/manhwa 

### Expected behavior
See the cover image at all times

### Actual behavior
The cover page blacks out as if missing the image and persists after refreshing library metadata

### Other details
Additional details and attachments.
Before opening Eleceed
![SmartSelect_20211018-130408_TachiyomiJ2K](https://user-images.githubusercontent.com/92747339/137776424-c4c06905-6420-4dd2-b88a-5492e771c3c5.jpg)
After opening Eleceed
![SmartSelect_20211018-130447_TachiyomiJ2K](https://user-images.githubusercontent.com/92747339/137776394-a4a05d4d-2793-4c02-b35a-7b823f205341.jpg)

**Comment by InfernalPhantasm** [comment]
I have the same issue but clearing the database only resets the covers like it should, only to have the covers disappear again when the manga is refreshed
