### ISSUE TITLE
[Feature Request] Add a way to remove the warning for large libraries

### ISSUE THREAD

**Issue by sharedkestrel** [Jays2Kings/tachiyomiJ2K#1063]
**App version:** 1.4.3

**Android version:** 11

**Issue/Request:** I have a library of around 150 manga, and each time I fetch for updates I get the warning about large libraries.
Can you differentiate the notification type or add an opt out toggle? The constant spam won't make me read less manga and is just an annoiance at most.

**Comment by CarlosEsco** [comment]
No
