### ISSUE TITLE
[Bug] Split images on some chapters

### ISSUE THREAD

**Issue by Jaysum57** [Jays2Kings/tachiyomiJ2K#1079]
### Device information
* Tachiyomi version: 1.4.3
* Android phone & version: Xiaomi mi note 10 lite, Android 11

## Steps to reproduce
1. Go to webtoons.com source
2. Open "The four of them" webtoon
3. Go to episode 43 chapter 44 (also on some other chapters)

### Expected behavior
No images are split

### Actual behavior
Images are split into two on the whole chapter

### Other details

* Settings of the two forks are identical. 
* Both are in webtoon reading mode
* Crop borders are disabled. 
* Downloading did not fix the splitting.

Comparison on the two forks:

![IMG_20211026_124540](https://user-images.githubusercontent.com/93185080/138834165-b9f722b2-ae4c-4c92-b953-e7a6576bba71.jpg)
![ezgifcom-gif-maker](https://user-images.githubusercontent.com/93185080/138951697-7f9e2dc3-c9c8-412e-bfcd-e159e186a2fb.GIF)

**Comment by notRyuk** [comment]
[Temporary solution] Change the reading mode to webtoon that happened since the manga set has some other format did not get auto configure. So I changed my reading mode to *Webtoon* when i read some manga like that.
