### ISSUE TITLE
[Feature Request] Auto track with the tracker

### ISSUE THREAD

**Issue by notRyuk** [Jays2Kings/tachiyomiJ2K#1080]
While I was changing with multiple devices from my mobile, tab and my laptop I felt it difficult to get the chapter from my tracker to the read part. So if I read some manga from my laptop and after sometime I shifted to my phone due some reason and I want to get to the same chapter without going to my tracker section in the manga panel

**Comment by Jays2Kings** [comment]
You can follow along the pr in the main tachi https://github.com/tachiyomiorg/tachiyomi/pull/3705 but I won't be implementing this myself
