### ISSUE TITLE
"In Library" button should show the user defined category the manhwa is part of

### ISSUE THREAD

**Issue by arndom** [Jays2Kings/tachiyomiJ2K#1087]
Currently, the display page to read a manhwa shows this:

![stuff](https://user-images.githubusercontent.com/40564798/140232583-d39522d4-b0bd-45fb-a745-123989a4aecf.jpg)

I think it would give a better feel if the "In Library" after the 🖤 icon was changed to the category name where the manhwa is placed. Something like this I guess:

![stuffedit](https://user-images.githubusercontent.com/40564798/140232596-438cc831-928c-4caf-8cf4-3fdb820fe600.jpg)

**Comment by CarlosEsco** [comment]
This would be horrible when a user has the same entry in multiple categories.

**Comment by arndom** [comment]
In that case side scrolling could work

**Comment by Jays2Kings** [comment]
Denied, this is a pointless addition when you usually get here from library. And even if you didn't you can see this info by going to edit categories
