### ISSUE TITLE
Rename chapters

### ISSUE THREAD

**Issue by ItachiUrasu** [Jays2Kings/tachiyomiJ2K#1089]
Allow us to rename chapters of the works we have added into our library.

This would allow us to rename miss labeled/numbered or misspelt chapters so they can show up in the correct order.

Could be implemented into the current long press menu that pops up to mark chapters

**Comment by AbdullahMehiz** [comment]
Technically you can rename chapters of works that are in your library by renaming the folder of the chapter you want to rename in a files manager

**Comment by ItachiUrasu** [comment]
Renaming the folder of a manga didn't change the chapter name in the app, so the chapter was still out of place in the chapter list (unless I did something wrong?).

**Comment by notRyuk** [comment]
**This is not related to this request directly**

It would be better if there is a setting to auto edit the manga details of the manga according to the tracker/primary tracker (if there are multiple trackers)

**Comment by Jays2Kings** [comment]
Renaming chapters is far to extra and complicated to add, If typos or formatting of chapters bothers you then 
A) Change sources
B) Use local or a self hosted source
C) Ask in Tachiyomi Extensions repo for a format update (which will likely be denied but still
D) if the source has some sort of reporting, mention typos
E) Live with them

> **This is not related to this request directly**
> 
> It would be better if there is a setting to auto edit the manga details of the manga according to the tracker/primary tracker (if there are multiple trackers)

you can already copy and paste tracker titles, there's no point to add an auto add
