### ISSUE TITLE
[Bug] Package installer crashes on trying to uninstall this

### ISSUE THREAD

**Issue by Sohil876** [Jays2Kings/tachiyomiJ2K#109]
### Device information
* Tachiyomi version: 0.9.8
* Android phone & version: Mi A1, Android 10

## Steps to reproduce
1. Install the app (xD)
2. Try uninstalling it, package installer crashes

### Expected behavior
Should uninstall, like any app or even the original tachiyomi.

### Actual behavior
Package installer crashes.

### Other details
Reporting this here because package installer only crashes on trying to uninstall this app, otherwise it works normally. 
Here's a log, https://del.dog/wocubimoha

**Comment by Jays2Kings** [comment]
If your phone is crashing from that, that's more something wrong with the phone than the app. No app should be able to crash the uninstaller (or loads of people would use it for bloatware). Try clearing data before uninstalling maybe?

**Comment by Sohil876** [comment]
Did that, nd the phone is not crashing, only package installer crashes only while trying to uinstall this app otherwise it works totally fine, i can install uninstall any app no prob.

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi/issues/2551

**Comment by Sohil876** [comment]
> If your phone is crashing from that, that's more something wrong with the phone than the app. No app should be able to crash the uninstaller (or loads of people would use it for bloatware). Try clearing data before uninstalling maybe?

Ive just clean flashed another rom and yes package installer still crashes on every android 10 rom i try while trying to uninstall, try arkons suggestion?

**Comment by Jays2Kings** [comment]
If you look at what he linked it's still your phone's issue, you should try the methods linked in that issue because there's nothing on my end I can do about it
