### ISSUE TITLE
[Bug] Page Gap

### ISSUE THREAD

**Issue by Ravienc** [Jays2Kings/tachiyomiJ2K#1090]
I just watch and then there's this
![Screenshot_2021-11-05-14-45-30-398_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/82885431/140475844-9db905e4-7ea8-458c-a417-f19d9731b639.jpg)
Its sometimes happening when seeing Webtoon

**Comment by Ravienc** [comment]
Oh yea if you still asking me what wrong. 
It's the gap

**Comment by CarlosEsco** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/1079
