### ISSUE TITLE
[Feature Request] Let us change the language of app.

### ISSUE THREAD

**Issue by kyoyacchi** [Jays2Kings/tachiyomiJ2K#1094]
### Why/User Benefit/User Problem
(explain why this feature should be added)

I want to change language of the app without changing system language, like in old versions. I want to use app as English, also Turkish has Incorrect translations; It feels like translated from google translate.....

### What/Requirements
(explain how this feature would behave)

The app should show a option that let us change language of the app.

**Comment by CarlosEsco** [comment]
#991
