### ISSUE TITLE
[Bug] Reader Menu appearing when it shouldn't

### ISSUE THREAD

**Issue by Jerrk** [Jays2Kings/tachiyomiJ2K#1100]
### Device information
* Tachiyomi version: 1.4.3
* Android phone & version: Galaxy Note 8 & Android 9

## Steps to reproduce
1. Open any chapter
2. Lock your device
3. Unlock your device

[heres a video of the issue](https://thumbs.gfycat.com/LiquidDisastrousCanvasback-mobile.mp4)

1. Open any chapter
2. Minimize TachiyomiJ2K
3. Reopen TachiyomiJ2K

### Expected behavior
The chapter view should be the same after locking and unlocking your device, and when minimizing and reopening the app.

### Actual behavior
The top bar is always visible after locking and unlocking your device, and when minimizing and reopening the app

### Other details
i mentioned this in issue #1048 and i believe it started happening in the versions 1.4.0-1.4.2, not sure which one since they were all released within a couple days so i'm not sure which of the version the issue first started.

i know for sure the issue was not present in 1.3.2

There is also an issue where this top bar will just appear randomly when reading a chapter. I haven't gotten a 100% way to reproduce it yet but i think it has something to do with having a next chapter being available or an item appearing in the notifications bar

if it's unclear, by "top bar" i mean this one. don't know if it has a specific name
![](https://i.imgur.com/bWbV86N.jpeg)

**Comment by notRyuk** [comment]
I think its happening especially with your device mine seems fine and for which ever chapter it appears it goes off after scrolling some part

**Comment by Jerrk** [comment]
This is now also happening in [Neko 2.7.0](https://github.com/CarlosEsco/Neko/releases/tag/2.7.0)

**Comment by Jerrk** [comment]
Weirdly enough the 1.5.3 changes does **not** "fix" the issue
> Reader menu now hides when changing pages or scrolling

https://i.imgur.com/0XBxoAA.mp4
