### ISSUE TITLE
[Feature Request] update all extensions

### ISSUE THREAD

**Issue by TronTheGamer** [Jays2Kings/tachiyomiJ2K#1111]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (latest J2K is v1.4.3)
- I will not repeat a request for a feature already requested
- If this is an request for an extension/source, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

---

### Why/User Benefit/User Problem
(explain why this feature should be added)
When there are multiple extension updates, it would be better to update all of them with one button instead of updating them individually.

### What/Requirements
(explain how this feature would behave)
An update all button on the header section of available updates.

**Comment by Jays2Kings** [comment]
This feature already exists, and is coming to older versions in a future update
