### ISSUE TITLE
[Bug]Readcomiconline won’t work

### ISSUE THREAD

**Issue by Devthereader** [Jays2Kings/tachiyomiJ2K#1118]
---

### Device information
* Tachiyomi version: latest
* Android phone & version: 7.1.1

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Comic opens and I read it

### Actual behavior
Open s and closes in a second and says that pages not found

**Comment by Jays2Kings** [comment]
Extensions issues go to the extensions repo. Reread the bug template
