### ISSUE TITLE
add new extension name mangareader.to

### ISSUE THREAD

**Issue by Bikeam-tech** [Jays2Kings/tachiyomiJ2K#1119]
### Why/User Benefit/User Problem
this is a new site from popular anime streaming site (zoro.to). this site name is mangareader.to.
 this site provides an ads-free reading experience, fast content update with vast genres, and is safe to use.
![Screenshot (600)](https://user-images.githubusercontent.com/55379619/146922696-182073ec-8b15-46e5-8a73-8f8cbf9dea61.png)

### What/Requirements
no requirements are needed. 

thank you and looking forward to this new extension (mangareader.to)

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/
