### ISSUE TITLE
[Bug] Applying filters in chapter list causes it to display out of order.

### ISSUE THREAD

**Issue by Tempest32** [Jays2Kings/tachiyomiJ2K#112]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: Lenovo K4 Note (A7010a48), Android 7.1.2

## Steps to reproduce
1. Open chapter list for a manga
2. Apply unread filter

### Expected behavior
Unread chapter based on sorting should be on the top.

### Actual behavior
A chapter number around x2 of the last read chapter is on the top.
For example in the attached images, the last read chapter is 17, and after applying the filter chapter 34 is on the top.

### Other details
Before applying filter
![no filter](https://i.postimg.cc/6pp2GqrT/image.png)
After applying filter
![filter](https://i.postimg.cc/KzJCj9x1/image.png)

**Comment by Jays2Kings** [comment]
Fixed
