### ISSUE TITLE
[Bug] App crashes when clicking "update all" 

### ISSUE THREAD

**Issue by Axe090** [Jays2Kings/tachiyomiJ2K#1121]
### Device information
* Tachiyomi version: 1.4.4 latest
* Android phone & version: Zenfone Max on Android 10

## Steps to reproduce
1. Go to extensions
2. Press update all

### Expected behavior
Should start updating apps

### Actual behavior
App insta crashes

### Other details
Have tried fresh installing, shifting between internal/external storage but app still crashes. Manual app updating works fine.

**Comment by BeatChoAss** [comment]
go to settings, advanced then enable "use shizuku to install extensions" under the extensions header

**Comment by Axe090** [comment]
> go to settings, advanced then enable "use shizuku to install extensions" under the extensions header

Thank you! Working flawlessly now. This is pretty neat
