### ISSUE TITLE
random sorting for library titles

### ISSUE THREAD

**Issue by lukewma** [Jays2Kings/tachiyomiJ2K#1122]
**App version:**
v 1.4.4

**Android version:**
12

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1. press sort option
 2. press random/shuffle
 3. reshuffle every time the option is selected again 

**Other details:**
its dumb, but would it be possible to shuffle to be suggested a series when I have nothing to read? kind of like how Netflix has play anything.

**Comment by CarlosEsco** [comment]
Just use the open random series button

**Comment by lukewma** [comment]
thanks! my category hopper was hidden so I didn't know about this option. unrelated, but are settings searchable
