### ISSUE TITLE
[Feature Request] Filter manga nsfw from recent

### ISSUE THREAD

**Issue by AethersKz** [Jays2Kings/tachiyomiJ2K#1128]
Why/User Benefit/User Problem

Well, it is not very comfortable to look for an action manga that I have read, among so many nsfw manga that I cannot filter, and the only way to remove them from there is to mark all its chapters as read (if the manga is added to the library) or delete it from the history (when it is not in the library)

The benefit of the user is to be able to separate the normal manga from the NSFW

User problem is not being able to filter, hide or separate nsfw from non-nsfw manga

![a](https://user-images.githubusercontent.com/96607644/147512732-b60e73a2-2c57-46f3-8d60-9c6cf7b4b109.jpg)

What/Requirements

a filter in recent to hide manga nsfw or at least an option so that this manga does not appear again in "Grouped" and "All"
![-2147483648_-213508](https://user-images.githubusercontent.com/96607644/147512881-f9a89291-a6a4-4b5d-9016-51fa7e423200.jpg)

also a filter in the library would be good
![21350](https://user-images.githubusercontent.com/96607644/147513040-b446d676-dddb-45b1-803e-ec71c0ee1f87.jpg)

If it is not possible to add the option to filter nsfw at least consider adding a function to remove manga from "Grouped" and "All" that the user does not want to be there ;')

**Comment by Jays2Kings** [comment]
This is not a lewd/hentai fork so im not going to add any kind of feature like that unless the main tachiyomi adds a simple way to know. There's incognito mode and ways to clone the app if you want to separate your library
