### ISSUE TITLE
[Feature Request] Backup bookmarked chapter

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#113]
Currently, Tachiyomi does not backup bookmarked chapters, making the function completely useless during migration/restoration. It would be nice if bookmarked chapters were backed up.

**Comment by Jays2Kings** [comment]
You're better off asking in dev for such a thing, I don't want to end up breaking backups/restores for other forks, and if dev decides to add something else to the backup json that's not that, then they'll be completely broken on j2k

**Comment by joseph619** [comment]
It's already been asked in main repo, but you know how slow Dev is in adding features thus I asked here.. If you don't mind, please consider creating a PR for Dev. I'm closing this.
