### ISSUE TITLE
[Feature Request] Holding "Add to Library" button to select categories

### ISSUE THREAD

**Issue by KazKaz90** [Jays2Kings/tachiyomiJ2K#1133]
### Why/User Benefit/User Problem

Efficient app navigation

### What/Requirements

I know there's already a way to change the category by clicking the add library button again after the first time and there's a pop-up asking if you want to change the category, but I believe holding the "Add to Library" button to select the category is far more efficient than clicking it three times.

**Comment by AndrielFR** [comment]
> Half second of time saved lol

yes
