### ISSUE TITLE
[Bug] MangaDex not recognized as installed, only happens on J2K. 

### ISSUE THREAD

**Issue by nowhipcreamplz** [Jays2Kings/tachiyomiJ2K#1138]
### Device information
* Tachiyomi version: 1.4.4 (Lastest)
* Android phone & version: Pixel 6/Android 12

### Expected behavior
MangaDex should show in the extension list, and should show as installed with the extension installed on the phone. 

### Actual behavior
Shows MangaDex as a source that is not installed after selecting a manga in your library. Also not showing at all in the extension browser, even when installed. (current extension version is 1.2.151)

### Other details
I've tried force stopping the app, reinstalling the extension. 
The main Tachiyomi recognizes the current extension as installed so I am putting in an issue here. Sorry if isn't anything you can look at. 
The issue is not urgent as I use a plethora of different extensions but I thought I'd let you know something is going wrong.

**Comment by CarlosEsco** [comment]
is it getting hidden by the r18 filter?

**Comment by nowhipcreamplz** [comment]
Ah.. that was it. I didn't think that option would have triggered MangaDex. I happened to have E-Hentai installed for Eorzea Encyclopedia since that's the only source for that book that I have found out about. 

Sorry to bother you with this!
