### ISSUE TITLE
[Extension] Extension Mangaowl isn't working

### ISSUE THREAD

**Issue by Saltyapplepies** [Jays2Kings/tachiyomiJ2K#1139]
---

### Device information
* Tachiyomi version: 1.4.4
* Android phone & version: Samsung tab 6 lite, v 11
## Steps to reproduce
1. First step
2. Second step

### Expected behavior
should be able to read the files

### Actual behavior
says 'cannot open image'

### Other details
looked at other files on the same etaetension, same issue

**Comment by CarlosEsco** [comment]
extension issues go here
https://github.com/tachiyomiorg/tachiyomi-extensions/

and there is one already open for mangaowl.
