### ISSUE TITLE
[Feature Request] Per-Manga, Auto New Chapter Download

### ISSUE THREAD

**Issue by SunBreaker1** [Jays2Kings/tachiyomiJ2K#1144]
### Why/User Benefit/User Problem
While the option of downloading new chapters exists in the app, the feature might be more usefull on a per-manga basis. As probably many users have many series marked, they may choose to follow only a select few, and of those select few they may wish to download the chapters for later. However, downloading certain chapters has to be done manually and using the download new chapters feature may download more than what the user may want.

### What/Requirements
This option should be a toggle option in the drop down top right menu. Activating it allows the app to download the newest chapter(s) only for the chosen manga(s) and an not all the newest.

P.S sorry if this is a repeat request.

![Screenshot_20220117-232223_TachiyomiJ2K.jpg](https://user-images.githubusercontent.com/85519676/149870620-d87c6a4c-29b3-4ed8-8b31-ca803e16b58e.jpg)

**Comment by AndrielFR** [comment]
you can put the mangas you want to download in a new category and select only that in the option to download new chapters
