### ISSUE TITLE
Reading Mode Bug Shows Chapters as Blank

### ISSUE THREAD

**Issue by Saud-97** [Jays2Kings/tachiyomiJ2K#1146]
**App version:**
1.4.4
**Android version:**
7.1.2
**Issue/Request:**
When reading a chapter in webtoon or vertical continous (possibly other reading modes not sure as I don't use them)
Long pictures (such as all pages of webtoon chapter is combined in 1 very long image (similar to mentioned below 1110x11643 pictures inside a chapter). The application will not show the image but you can still scroll as if it was showing until you can go to next chapter as if the chapter is invisible.

**I noticed the issue also happens in vertical mode too when you go to Scale Type and Page Layout and try different combinations**

If you didn't get what I mean compare these two chapters in terms of number of images loading when you first open the page and see the difference.
https://azoraworld.com/series/peerless-battle-spirit/271/ **(this has 4 pictures)**
https://azoraworld.com/series/peerless-battle-spirit/270/ **(this has 34 pictures)**
Despite them both chapters have same length.

**Steps to reproduce (if applicable)**

1. Use webtoon reading mode
2. Use resolution **2560x1440** ( I'm currently using bluestacks 5 as Android emulator)
3. Go read a chapter that has similar charastaristics as I showed above. 
- You can do so by installing Azora extension from (arabic language) then go open chapters 271 and 270 and see that 270 can be viewed normally and 271 shows a blank screen.
5. If you noticed it's blank go change the reading mode to Vertical for example, the picture will show up normal.

**Other details:**

**Here is a video that shows the issue clearly.**
https://user-images.githubusercontent.com/39028181/150127105-b2378d74-04b3-48db-b810-1edcbb1c0fbd.mp4

**Comment by saud-97** [comment]
I suggest adding an if statement to chapters downloaded. Once downloaded check image length and compare with the screen resolution (I assume it's linked with the issue). If the length of image is too long then split the images based on multiples of the screen length (1024 length for example for each image).

**Comment by saud-97** [comment]
Can I get an update on this? Is it going to be implemented or ?

**Comment by saud-97** [comment]
@Jays2Kings Up

**Comment by saud-97** [comment]
This was solved in main, to be closed later when it reaches here.

**Comment by Saud-97** [comment]
The issue was fixed via auto splitting.
