### ISSUE TITLE
[Feature Request] Show only one/latest chapter from the updates tab

### ISSUE THREAD

**Issue by mIsmanX** [Jays2Kings/tachiyomiJ2K#1149]
### Why/User Benefit/User Problem
(explain why this feature should be added)
![Screenshot_20220126-081500_TachiyomiJ2K](https://user-images.githubusercontent.com/54562368/151081895-d1b506b8-1096-45c5-bb55-f0899ea83988.png)
It's hard to find updated manga when you had to scroll through 100-1000 chapters of this
### What/Requirements
(explain how this feature would behave)

**Comment by nzoba** [comment]
It's already possible to activate that, you can choose `Group chapters together` in the options (top right next to the 3 points on your screenshot)
