### ISSUE TITLE
[Bug] 'double pages' page layout feature doesn't work with 'webtoon' mode

### ISSUE THREAD

**Issue by RaviMohanVerma** [Jays2Kings/tachiyomiJ2K#1152]
### Device information
* Tachiyomi version:  TachiyomiJ2K 1.4.4
* Android phone & version: Samaung Galaxy M51 & Android 11

## Steps to reproduce
1. First step: Select reading mode as 'webtoon'
2. Second step: 'Double pages' layout option disappears.

### Expected behavior
There should be double pages option with webtoon mode

### Actual behavior
Double pages layout option disappears when reading mode is 'webtoon' or 'continuous vertical' 

### Other details
Double pages layout with webtoon will be benefical for many manhuas/manhwas which have split images; e.g. Xcalibr releases many mahuas with split images.

**Comment by CarlosEsco** [comment]
Do you have a link, to a webtoon where the dumb scanlator splits the image horizontally as well as vertically and its not just them trying to prevent scraping?

**Comment by RaviMohanVerma** [comment]
> Do you have a link, to a webtoon where the dumb scanlator splits the image horizontally as well as vertically and its not just them trying to prevent scraping?

https://xcalibrscans.com/above-ten-thousand-people-chapter-72/

**Comment by Jays2Kings** [comment]
There's no bug here, because there's no real reason why double pages for webtoons should exist. 

> > Do you have a link, to a webtoon where the dumb scanlator splits the image horizontally as well as vertically and its not just them trying to prevent scraping?
> 
> https://xcalibrscans.com/above-ten-thousand-people-chapter-72/

This example isnt what was asked for: this is done to prevent scraping, there's no other reason why the site would support such a silly way to layout a webtoons aside from to prevent scraping

Use a different extension.

**Comment by RaviMohanVerma** [comment]
Thanks for replying. I think it would be great if double pages option could
be enabled for webtoon mode. It'll help us read such sources which
intentionally vertically split webtoon pages.
