### ISSUE TITLE
[Feature Request] Choose default webview

### ISSUE THREAD

**Issue by Rubberxgum** [Jays2Kings/tachiyomiJ2K#1158]
### Why/User Benefit/User Problem
It would be useful to have an option to use another browser's webview instead of the stock android webview as a default webview. Since I'm using Firefox browser with ublock origin ad blocker, it would be nice to have that adblocking when on webview too. Of course, I know that you can use your default browser's webview by selecting 'open in browser'. But it'd be more convenient to be able to use your default browser's webview by default instead of having to do that.

### What/Requirements
There should be an option to choose your default webview.

**Comment by CarlosEsco** [comment]
having a different browser doesn't mean you have the option for a different webview.
