### ISSUE TITLE
[Feature Request] browsing with newest filter

### ISSUE THREAD

**Issue by Mechanical-sanity** [Jays2Kings/tachiyomiJ2K#116]
### Why/User Benefit/User Problem
Could you guys allow the browsing feature of sources to default to showing the newest mangas? Because I believe that is the most convenient way for readers to find new and exciting mangas or manhuas.

### What/Requirements
So we should be able to change the display settings into showing the newest mangas or manhuas in a source browser, and it will save our preferences instead of going back to the default after we leave.

**Comment by CarlosEsco** [comment]
That's dependent on the extension. Some don't even support that.

**Comment by joseph619** [comment]
I am strongly against changing default behavior, also what Carlos said.

**Comment by Jays2Kings** [comment]
Others have gave the reason why this won't happen so this is being closed
