### ISSUE TITLE
[Feature Request] App Icon *better presentation* 

### ISSUE THREAD

**Issue by mohammed-mohamdy-eisa** [Jays2Kings/tachiyomiJ2K#1163]
### First of all, Sorry
Sorry, I know I'm causing you guys headache, but please hear me out
I know I submitted this suggestion couple of days ago #1160  and it was declined @CarlosEsco , but I believe I didn't present it as it should be
So, Please give me a chance and Thanks for all your efforts for putting such a great app

### Why/User Benefit/User Problem
(explain why this feature should be added)
I know it's not a necessity. I mean the current app icon is all good and everything but I envy Neko app for having such a simple minimal app icon which have the same color scheme or color palette of the app, I mean the same lime green in and out. TBH it looks great. 

### What/Requirements
(explain how this feature would behave)
Go to Settings -> Appearance -> App Themes
once you change the theme the app icon changes to much the theme too

So, I made couple designs to much each theme hope you like them

### Themes

- > ### Default

> this is the default app icon. There are no changes because my intention isn't changing the design 
![default](https://user-images.githubusercontent.com/74384750/153723648-1d7d5f69-6c5d-42a1-b982-c3ef97f3ec62.png)

- > ### Pure White

![pure white](https://user-images.githubusercontent.com/74384750/153723737-b73f7047-2cfa-4e17-bc8b-483f88684ad3.png)

- > ### Spring Blossom

![spring blossom](https://user-images.githubusercontent.com/74384750/153723799-294b96c6-7a35-4d94-98ae-7184c2e37f4c.png)

- > ### Strawberry Daiquiri

> This one looks like japan flag 
![strawberry daiquiri](https://user-images.githubusercontent.com/74384750/153723829-a3b3ac2b-fcd2-42bb-af4d-11ce5308b196.png)

- > ### Teal Ocean

![teal ocean](https://user-images.githubusercontent.com/74384750/153723849-7f91501a-c5c8-45d9-b756-07ac30c81e69.png)

- > ### Tako Light

![tako](https://user-images.githubusercontent.com/74384750/153723861-68099879-144b-49be-91a2-2cae7f878239.png)

- > ### Yang

>Minimal Peaceful 
![yang](https://user-images.githubusercontent.com/74384750/153723871-fd14485c-7dfb-452a-883d-f8362e7a0210.png)

- > ### Lime Time

> This one assembles Neko color palette 
![lime time](https://user-images.githubusercontent.com/74384750/153723901-ac08bd09-5d8b-43bf-903c-98744f807e2a.png)

- > ### Yotsuba

![yotsuba](https://user-images.githubusercontent.com/74384750/153723955-6e50264a-4a39-4a81-b74e-c7744c63e06c.png)

- > ### Dark

![dark](https://user-images.githubusercontent.com/74384750/153723967-10a0ce0f-f8af-40e9-895a-d705524c1e39.png)

- > ### Midnight Dusk

![midnight dusk](https://user-images.githubusercontent.com/74384750/153723975-df837595-b23d-4603-9ea7-9403cbf2befd.png)

- > ### Chocolate Strawberries

> This one is a tribute for the old app icon
![chocolate strawberries](https://user-images.githubusercontent.com/74384750/153724036-9e7db5e1-0794-4fcd-8ddf-1dbf9607a53f.png)

- > ### Sapphire Dusk

![sapphire dusk](https://user-images.githubusercontent.com/74384750/153724053-cca5b8bd-4913-4ff3-9178-87ed677394b7.png)

- > ### Tako dark

![tako_1](https://user-images.githubusercontent.com/74384750/153724064-11c02aea-de06-455c-aa38-5bc1186f01c8.png)

- > ### Yin

> Minimal dark and simple (also the one I submitted last time)
![yin](https://user-images.githubusercontent.com/74384750/153724086-7172f9ef-797f-4ee7-b5f5-d5f5797f421d.png)

- > ### Flate Lime

![flat lime](https://user-images.githubusercontent.com/74384750/153724111-c5d1eee9-34b8-4528-ad34-9bd84804080b.png)

### Last but not least
I'm just a guy who love this app so much and have huge enthusiasm for manga reading and graphic designing so, I thought I wanted to do something for you guys
I understand your priorities and tasks so thanks anyway and I won't bother you and submit this again

### Thanks

**Comment by Jays2Kings** [comment]
The issue wasn't presentation it's implementation. These are cool icons but unless main app or someone else does the logic for custom icons I won't be adding these

**Comment by mohammed-mohamdy-eisa** [comment]
### CUSTOM ICONS LOGIC
> The issue wasn't presentation it's implementation. These are cool icons but unless main app or someone else does the logic for custom icons I won't be adding these

@Jays2Kings 
I've been searching actively for the last couple days for someone who done code for this feature and finally I found this https://github.com/myinnos/AppIconNameChanger
This code contains the exact feature of changing app icon so I hope it helps
