### ISSUE TITLE
[Bug] In the local manga, the pages are not in order

### ISSUE THREAD

**Issue by Saumyavilasroy** [Jays2Kings/tachiyomiJ2K#117]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: Asus max m1, 8 (Oreo)

## Steps to reproduce
1. Take local manga with numbering as this
![Screenshot_20200219-104013](https://user-images.githubusercontent.com/59217434/74804011-f397ae00-5304-11ea-8a04-f68b229f0178.jpg)

2. Open it in tachiyomi from local manga 

### Expected behavior
All the pages should be displayed in order.

### Actual behavior
Pages are displayed in random order

### Other details
![Screenshot_20200219-104747](https://user-images.githubusercontent.com/59217434/74804184-7e78a880-5305-11ea-97cd-6bf50149126c.jpg)
As in this shot pages order are 0-1-11 and other random pages.

**Comment by CarlosEsco** [comment]
I feel like whereever you downloaded those, should know thats a horrible naming convention

**Comment by Saumyavilasroy** [comment]
I can see that but unfortunately I have a huge local manga library consisting of manga's and manhawa named this way, and giving names starting from 1 to -number- seems pretty solid to me.

**Comment by arkon** [comment]
This is related to how sorting works in general in the app, and it only handles up to 3 digits (i.e. chapters 000 - 999). I feel like it should sort numbers properly, but maybe there was a reason for that...

**Comment by Saumyavilasroy** [comment]
I have about a half a million manga pages and renaming then all will be a hell of a task, it would be much appreciated if the sorting from 0 to -number is also included, as renaming half a million pages is no smol task..

**Comment by Jays2Kings** [comment]
Changing the way sorting works is a high task I'm most definitely not taking up. There's plenty of batch renaming tools for Android or PC, use one of them to fix the names

**Comment by Saumyavilasroy** [comment]
Its a option but even after using a batch renaming tool there are more than 5,000 chapters that have to be separately configured. This a request and will be highly appreciated

**Comment by joseph619** [comment]
As Jay said, what you are asking for is not a reasonable request. It's the users responsibility to make sure their local manga follows Tachiyomi naming convention, not the other way around.

**Comment by Saumyavilasroy** [comment]
I do understand what you guys are getting at but if you can try to understand my side a bit I have been downloading Manga since I was kid a kid that's how the collection became this huge and now for only 1 year I have been using tachiyomi and I had no idea about the naming convention and all. So it's up to you guys whether you guys can accept my request even if it seems unreasonable but 0 to - number- seems a good numbering convention to me. I won't be reopening this thread, please try to help me otherwise I will have to spend weeks renaming my mangas.
Have a great day ahead.
