### ISSUE TITLE
Way to recover deleted titles

### ISSUE THREAD

**Issue by Powsin** [Jays2Kings/tachiyomiJ2K#1172]
**App version:**
1.4.4

**Android version:**
11

**Issue/Request:**
Recover accidentally deleted manga in a form of history. Wasn't recently read. Was meant to download unread.

**Steps to reproduce (if applicable)**

 1. Select multiple manga
 2. Select download unread
 3. But pressed delete instead

**Comment by Powsin** [comment]
I’m aware that this is a user error. This is a feature request and not a bug.

**Comment by Powsin** [comment]
Also accidentally mark as read

It could show up on recents that was marked as read chapter 50-59 or something

**Comment by Powsin** [comment]
Select multiple titles then mark as read needs a yes/no confirmation

**Comment by Jays2Kings** [comment]
There's no way to recover deleted manga. There's a prompt to confirm if you're sure you want to remove the manga. Then a snackbar to undo the removal. If you remove manga after all that, there's nothing that can be done.
