### ISSUE TITLE
[Feature Request] Covers for chapters

### ISSUE THREAD

**Issue by xFaultx** [Jays2Kings/tachiyomiJ2K#1178]
This same issue was brought up on the main Tachiyomi, but I feel like it was ignored for silly reasons. Here is that discussion https://github.com/tachiyomiorg/tachiyomi/issues/2577

### Why/User Benefit/User Problem
Instead of just showing a list of chapters, it would be nice to also show the covers for the chapters. I started using Tachiyomi along with Komga so I could sync my library, and not need to keep it locally. I don't really read that much manga, and moreso use it for reading comics. The problem is that when I go under a section, it lists all the comics only as text, not showing the covers for that series. I would love to be able to see the covers under this heading. Not only for visual purposes, but also just as sort of a reminder of previous covers.

### What/Requirements
Add an option to show the Covers for Chapters. What's exactly involved in coding that, I have no idea. I just think it would look really nice. I don't know enough about manga to say if manga readers would benefit, but I would imagine some people out there would like the option.

**Comment by Jays2Kings** [comment]
Since only self-hosted services would work well with this + it would be a very niche feature + a lot of work for that niche feature, I'm declining it as well
