### ISSUE TITLE
[Feature Request] Rotation button in manga

### ISSUE THREAD

**Issue by ghost** [Jays2Kings/tachiyomiJ2K#118]
### Why/User Benefit/User Problem
Troublesome to change oriantation every time read different manga. 

### What/Requirements
A button for rotation in manga reader menu.

**Comment by joseph619** [comment]
You can already set orientation in Reader settings 

https://tachiyomi.org/help/guides/reader/#default-viewer

**Comment by Fahad1998** [comment]
Yeah. but i mean when reading manga. Tachiyomi doesn't support oriantation per manga so i have to change oriantation for every different manga.

**Comment by joseph619** [comment]
It does support orientation per manga, please colored the app more before making requests
![screenshot_20200219-140145_tac](https://user-images.githubusercontent.com/34897862/74866371-c953e980-5320-11ea-8cf5-eaa200c787a5.jpg)

**Comment by Fahad1998** [comment]
I tried but it changed oriantation for all manga.

**Comment by joseph619** [comment]
My apologies, you're correct changing Rotation is not applied to individual manga.

**Comment by joseph619** [comment]
Rotation button is already added, manga wise rotation can be taken from this PR

https://github.com/Jays2Kings/tachiyomiJ2K/issues/118
