### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by laufeyss** [Jays2Kings/tachiyomiJ2K#1181]
Top of the reader pops up while taking a long screenshot
![Screenshot_2022-03-17-16-11-17-20](https://user-images.githubusercontent.com/99605276/158765678-41af6db1-1acb-4f7e-9ac7-e88154abef93.jpg)

**Comment by Jays2Kings** [comment]
dupe of https://github.com/Jays2Kings/tachiyomiJ2K/issues/977
