### ISSUE TITLE
Can the animate page transition(the last page) be made into black?

### ISSUE THREAD

**Issue by 7sevenseven** [Jays2Kings/tachiyomiJ2K#1183]
I am used to using a black background, and it suddenly appears white at the end of the cartoon, which feels very strange.
![Screenshot_2022-03-25-10-15-33-07_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/49519653/160041252-51b8deab-1832-48c2-9ec5-4af02df11c29.jpg)

**Comment by Jays2Kings** [comment]
It's by your theme color and im not adding an option to choose between theme or background color for transition pages
