### ISSUE TITLE
[Feature Request] category columns

### ISSUE THREAD

**Issue by Enlil50** [Jays2Kings/tachiyomiJ2K#1185]
### Why/User Benefit/User Problem
As for now, categories are placed one on top of another. If I have to switch I need them to be collapsed and then expanded again.

### What/Requirements
When I use tachiyomi, there are n columns of categories when opening library section. I find it more confortable to slide from left to right, rather than scrolling all the books.

This also make it possible to switch without collapsing them.

**Comment by CarlosEsco** [comment]
No and has been declined before.  US regular Tachi if that's what you want

**Comment by Enlil50** [comment]
Guess I'll do
