### ISSUE TITLE
[Bug] External links dealing and extension language

### ISSUE THREAD

**Issue by Caio99BR** [Jays2Kings/tachiyomiJ2K#1191]
This issue contains 2 bugs:

1. TachiJ2K is not dealing right with external links on a multi lang extension. It should use the same way as the Tachiyomi to solve the issue (not found the commit that fixed the issue)

| Tachiyomi | TachiJ2K |
| - | - |
| ![Screenshot_2022-04-10-22-43-33-527_eu kanade tachiyomi](https://user-images.githubusercontent.com/7280407/162661624-019e5416-5532-4a35-85e2-57843a9782fa.jpg) | ![Screenshot_2022-04-10-22-44-13-527_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/7280407/162661626-f0abe6c3-f833-4779-9264-d8336740cd7a.jpg) |
| Takes the ID and search it on the extension lang | Randomly take one of yhe options |

2. A extension lang is always on ever after you disable they. This problem affects both Tachi.
I don't know if Tachi is taking the phone language and enabling it regardless of user choose or if it takes effects after the usage of a lang other than EN.
It affects a Tachiyomi fresh installation, since it comes with everything enabled (necessary because first time users), but is solved when you disable the option "All" and all the other languages on the extension (it is atrange because the option "All" is enabled, and the manga have more than Portuguese translation, but it's just a detail?)

3. The option to force enable a language on tab option (enable for global search) when selecting on the extension language page is not required on Tachiyomi but required on TachiJ2K (maybe related to the issue?)

Manga used:
id:d422ddc8-eea3-4b0a-82a4-291bbd8c9285

---

### Device information
* Tachiyomi version: latest on both cases (0.13.2 and 1.4.5)
* Android phone & version: Black Shark 4 Android 11 (JoyUi 12.8 based on Miui 12.5)

**Comment by Jays2Kings** [comment]
1. Is a valid bug
2. Not sure what you mean, if you're disabling for example the mangadex Portuguese, but not Portuguese language in the filters, then the app will still expect you're using mutlple languages, this is intended behavior
3. Not an issue, the prompt is there because the source wont show in global search + browse list otherwise

**Comment by Caio99BR** [comment]
1. Thanks

2. I will try to reproduce it in an another explainable way (my english sucks) and open a new issue

3. I think the prompt need a better "phrasing" (sorry for my english again), something like "Enable language first to show on Global Results (or double tap to enable only on extension)". On Tachi it simple enable no matter if global configuration is enabled, but should have at least show a warning "Enabling only on extension", but well it's only a detail, it's not necessary
