### ISSUE TITLE
[Bug] Update time not appearing on recently updated chapters.

### ISSUE THREAD

**Issue by marcohohoho** [Jays2Kings/tachiyomiJ2K#1192]
### Device information
* Tachiyomi version: J2K 1.4.5
* Android phone & version: Xiaomi MI10T - Android 11

## Steps to reproduce
1. Open a title with a recently updated chapter in Toonily
2. Update it (Manual/Automatic)
3. View Latest chapter

### Expected behavior
There should be a time on when was the update pushed to the website

### Actual behavior
The Update time below the chapter number is blank.

### Other details
![image](https://user-images.githubusercontent.com/26383458/162687485-bc6d1290-6899-4279-b2d2-d2bf8c979a87.png)
![image](https://user-images.githubusercontent.com/26383458/162687518-7e9382ec-099a-46a6-910e-879d4913d8f3.png)
![image](https://user-images.githubusercontent.com/26383458/162687542-0a88ef9c-f200-4b4d-9533-8fe57dd6a423.png)

This is probably an extension issue specific to J2K, I tested the issue with the Vanilla Tachiyomi version 0.13.1 and there's no issue with the chapters, it shows "Today" for recently updated chapters as opposed to J2K's blank as shown above with the attached images.

My issue here is that these recently updated chapters doesn't appear when sorting library by "Latest Chapter".

**Comment by Jays2Kings** [comment]
Can you add which source this is from?

**Comment by marcohohoho** [comment]
> Can you add which source this is from?

This is from toonily, it got fixed yesterday by this https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11784

**Comment by Jays2Kings** [comment]
Closing this then
