### ISSUE TITLE
[Feature Request] Add Navigate to pan and landscape zoom from Stable 

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#1195]
Relevant PR

https://github.com/tachiyomiorg/tachiyomi/pull/6481

**Comment by CarlosEsco** [comment]
I dunno why people like this, its very jarring.

**Comment by joseph619** [comment]
I personally much prefer it over dual page split, as it doesn't split the pages and requires snap to view rest of the image (which breaks immersion). And I also don't have to manually zoom into dual page spreads every time. Very useful for manga like One Piece which have a gazillion dual page spreads.

**Comment by Jays2Kings** [comment]
I did plan to add it and still do, won't be putting on default though

**Comment by joseph619** [comment]
yeah it's all good as long there's option :)
