### ISSUE TITLE
[Feature Request] Filter third-party self-promo pages by skipping last x pages per chapter

### ISSUE THREAD

**Issue by jacklinzoho** [Jays2Kings/tachiyomiJ2K#1196]
### Why/User Benefit/User Problem
the scangroup promo pages that gets included at the end of chapters can get very obnoxious and flow-breaking, especially when it includes some full-sized image. especially especially if it includes some kind of retexted manga panel begging for donations. There should be options to filter them out.

### What/Requirements
Simplest way I can think of: option to skip the last x pages per chapter for specific manga.

**Comment by joseph619** [comment]
Note to Jay, this was rejected in main as for various reasons, including respecting the scanlators

**Comment by Jays2Kings** [comment]
and its rejected by me too
