### ISSUE TITLE
[Bug] Unable to login through web-view (tapas)

### ISSUE THREAD

**Issue by Jerrk** [Jays2Kings/tachiyomiJ2K#120]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: galaxy note 8 - android 9

## Steps to reproduce
1. Open a comic through the Tapas source
2. in the top right tap web-view
3. scroll to the top right and tap log in
4. scroll around the page to try to find the login area

### Expected behavior
the login area should appear in the middle of the webpage

### Actual behavior
The webpage has some sort of error that makes it load with incredible height, i scrolled for over a minute but never reached the bottom of the page, the login area is supposed to appear in the middle of the screen but since the height is so big it's incredibly hard to find it.

### Other details
This does not appear to be a problem on inorichi/tachiyomi so i don't think it is related to the tapas extension in that sense.

**Comment by joseph619** [comment]
Update your extension and webview.
