### ISSUE TITLE
[Bug] Reader has blue tint after using physical keyboard

### ISSUE THREAD

**Issue by agustinmorantes** [Jays2Kings/tachiyomiJ2K#1200]
### Device information
* Tachiyomi version: Tachiyomi J2K 1.4.5
* Android phone & version: Samsung Galaxy S21 FE & Android 12 (OneUI 4.1)

## Steps to reproduce
1. Open any manga/comic with a physical keyboard connected
2. Tap any key in the physical keyboard

### Expected behavior
Pressing, for example the left arrow key, should move to next page without any degradation to visuals.

### Actual behavior
When pressing any key in a physical keyboard, the screen turns to a blueish tint, as if a blue overlay was enabled. Touching the screen reverts the blue tint temporarily.

### Other details
This seems similar to #927, probably related in some way. The issue happens consistently in all the devices that I tested it: My S21 FE, Android Emulator, Bluestacks, Windows Subsystem for Android, Samsung DeX and my old Xiaomi Mi A2 phone.
I tried messing with the reader settings to see if I could find a workaround, like using the custom color filter or custom brightness, but I haven't been able to circumvent it as even with both filters on, the issue happens on top. It's as if a third overlay was laid on top of both.

Here is a gif I captured using Samsung DeX:

![2022-04-18 20-20-45](https://user-images.githubusercontent.com/21344464/163892361-2b8c8873-4d34-4e57-8614-2cec881260e2.gif)

**Comment by Vals9** [comment]
Same issue with controller when scrolling with either dpad or joystick (https://github.com/Jays2Kings/tachiyomiJ2K/issues/1203). From what I understood, it picks up accent color from the theme and adds it as overlay over the page, kind of like highlighting menu items when using non-touch inputs for navigation.

**Comment by agustinmorantes** [comment]
Yes, you're right!! Comparing the source of tachiyomij2k to the main tachiyomi repo (which doesn't have this issue), tachiyomij2k is missing `android:descendantFocusability="blocksDescendants"` property in the layout for the reader, which prevents the viewer from focusing. I tried compiling with that and the issue is gone!! I'm making a pull request.
