### ISSUE TITLE
[Bug] The comic name is abnormal when the comic plugin Haomanwu is used in J2K

### ISSUE THREAD

**Issue by zhongfly** [Jays2Kings/tachiyomiJ2K#1202]
**I have tested in https://github.com/tachiyomiorg/tachiyomi, the problem doesn't happen, but it happens in J2K version**

### Device information
* Tachiyomi version: tachiyomiJ2K 1.4.5
* Android phone & version: Android 10 (oneplus 5)

## Steps to reproduce
0. install zh.haomanwu(`好漫屋`) 1.2.1
1. open Popular Manga by click this extension in tachiyomiJ2K
2. You can see that the manga names are normal (for the English demo, I searched for the keyword "love")
![image](https://user-images.githubusercontent.com/11155705/164158306-edd29a84-0472-4e9e-9ebb-4cb17d126168.png)

3. open one manga to see its detail(for example, we open `Lovecraft Girls`),the name is changed and is wrong (`Lovecraft Girls 男生宿舍303 端脑（全彩版） 新极品全能高手 就吸你阳气！ 某天成为祭品公主 我什么时候无敌了 大国师 这个王爷他克妻，得盘! 成为王的男人 奇怪的情敌增加了`)
![image](https://user-images.githubusercontent.com/11155705/164158447-7efbe0a8-2e52-44d5-966c-b5acea06060f.png)

4. Going back to the previous page, the names here are also tainted and become wrong
![image](https://user-images.githubusercontent.com/11155705/164158546-78a661ca-8a4e-4c83-931e-01ca9ab2e677.png)

### Expected behavior
The manga name is displayed correctly as in the step 2(`Lovecraft Girls`), instead of being added a lot of extraneous characters at the end(` 男生宿舍303 端脑（全彩版） 新极品全能高手 就吸你阳气！ 某天成为祭品公主 我什么时候无敌了 大国师 这个王爷他克妻，得盘! 成为王的男人 奇怪的情敌增加了`)

### Actual behavior
The manga name is displayed like step 3 or 4, with lots of extraneous characters added at the end(` 男生宿舍303 端脑（全彩版） 新极品全能高手 就吸你阳气！ 某天成为祭品公主 我什么时候无敌了 大国师 这个王爷他克妻，得盘! 成为王的男人 奇怪的情敌增加了`)

### Other details
**I have tested in https://github.com/tachiyomiorg/tachiyomi 0.13.3, the problem doesn't happen, but it happens in J2K version**

**Comment by zhongfly** [comment]
The problem has been determined, the plugin uses the css seletor to get the comic title, however the css seletor used can match multiple tags. In tachiyomi only the value of the first matching tag will be used, in J2K the values of all matching tags will be concatenated together.

I don't know if J2K is behaving correctly, so keep this issue open

**Comment by anenasa** [comment]
Oops. Maybe I should use first() next time.

> In tachiyomi only the value of the first matching tag will be used

No, tachiyomi doesn't have this problem because title is not changed, no matter what title is set in mangaDetailsParse().
