### ISSUE TITLE
[Bug] Theme accent color hue over page when scrolling with controller

### ISSUE THREAD

**Issue by Vals9** [Jays2Kings/tachiyomiJ2K#1203]
### Device information
* Tachiyomi version: 1.4.5
* Android phone & version:
     Samsung Galaxy S22 Ultra, Android 12
     Galaxy Tab S7, Android 12

## Steps to reproduce
1. Connect any controller to the device
2. Select theme with strong accent color (e.g. Midnight Dusk)
3. Open any chapter (black and white manga is preferable since it's easier to see the difference). Reading mode does not matter.
4. Attempt to scroll, either with dpad or joystick adds accent color hue overlay from theme (in case of using Minight Dusk, it is pink) over the page. When using touch inputs (e.g. fingers, stylus), accent color hue overlay disappears.

### Expected behavior
When scrolling with controller (dpad or joystick), no hue overlay should appear over the page.

### Actual behavior
Hue overlay with accent color from the theme appears as overlay over the page when using non-touch inputs for page scrolling.

### Other details

Additional details and attachments.
On the video no hue overlay appears when using touch input (fingers) and pink hue overlay appears when scrolling with controller.

https://user-images.githubusercontent.com/58896973/164301441-f154d23f-4841-469a-b4c9-e012a9d1b59a.mp4

**Comment by Jays2Kings** [comment]
Closed with https://github.com/Jays2Kings/tachiyomiJ2K/pull/1204
