### ISSUE TITLE
[Bug] Picacomic not working properly in J2K

### ISSUE THREAD

**Issue by zhongfly** [Jays2Kings/tachiyomiJ2K#1206]
### Device information
* Tachiyomi version: 1.4.5
* Android phone & version: Android 10

## Steps to reproduce
0. Install Picacomic(1.2.1 or 1.2.2) in TachiyomiJ2K
1. Input username and password in extension setting
2. open Picacomic's popular Manga

### Expected behavior
Display manga list like other manga plugins or as normal in Tachiyomi

### Actual behavior
Show nothing

### Other details
Don't know if it's a problem with TachiyomiJ2K, as it was working fine on J2K before and can read/update comics from Picacomic that were previously added to the shelf. @anenasa

**Comment by anenasa** [comment]
I tried tachiyomiJ2K 1.4.5 and it didn't work, but it works fine with tachiyomiJ2K built from latest commit. I think this is already fixed in https://github.com/Jays2Kings/tachiyomiJ2K/commit/67e048a20cf80f06519a588030834a00af6846c1.

**Comment by zhongfly** [comment]
> I tried tachiyomiJ2K 1.4.5 and it didn't work, but it works fine with tachiyomiJ2K built from latest commit. I think this is already fixed in [67e048a](https://github.com/Jays2Kings/tachiyomiJ2K/commit/67e048a20cf80f06519a588030834a00af6846c1).

Thanks
