### ISSUE TITLE
[Feature Request][From Stable] Verify if Manga exist before adding to library 

### ISSUE THREAD

**Issue by saud-97** [Jays2Kings/tachiyomiJ2K#1207]
### Why/User Benefit/User Problem
To avoid duplication in case user forgot that he had this manga already in Library.

### What/Requirements
When a user click "Add to Library" a check should be done to see if there is a duplicate. 
If there is a duplicate then show 3 options (**View Manga**, **Add**, **Cancel**). Otherwise keep the same default behavior.

This is available in other forks.

**Comment by joseph619** [comment]
Relevant commit https://github.com/tachiyomiorg/tachiyomi/commit/71ddb1657440d54178f10fd62e3d0c66ee95a5a0
