### ISSUE TITLE
[Feature Request] Add option to disable navigation layout (from Stable)

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#1210]
Relevant PR https://github.com/tachiyomiorg/tachiyomi/pull/6876

Additional relevant commit? https://github.com/tachiyomiorg/tachiyomi/commit/2dfafa387baa4bee5f0524b1e0c5cf98c21f6b2d

This should fine until summer 2023 :risitas:

**Comment by joseph619** [comment]
Yeah my bad 😂 Would you prefer a single ticket with checkboxes? Like this https://github.com/jobobby04/TachiyomiSY/issues/154

I personally have nothing to request, but could be useful for others in future

**Comment by Jays2Kings** [comment]
Please don't do that, that's worse than opening a bunch of issues, even though that pushes other things down. 

Though if there's a feature someone wants from upstream let them make an issue, don't do it for them. I still actively watch the main commits, even when I was inactive. It's just the same as usual "I dont want every main feature". Even some that are older I do later backtrack on adding, whether it's added yesterday or a year ago

**Comment by joseph619** [comment]
Makes sense, since J2K receives updates sporadically, I wasn't sure if certain upstream features are missed or skipped deliberately. And yeah, if I make any further issues, I will only make for myself lol. 

Also nice to see you around Jay :)
