### ISSUE TITLE
[Feature Request] Auto divide Long Images after download [Reader crash issue related]

### ISSUE THREAD

**Issue by saud-97** [Jays2Kings/tachiyomiJ2K#1211]
### Why/User Benefit/User Problem
Tachi Reader cannot handle extremely long pages like 20k height or something.
This will solve many memory and loading issues / crashes affecting webtoons especially. 

**My suggestion is only affecting downloaded chapters so this has nothing to do with the reader code spaghetti and no need to rewrite at all to simplify solving the issue.**

### What/Requirements
The feature is basically to add an **optional** setting to enable auto splitting of the long images of (5000px+? height) or more to equal parts. To make the processing and loading of images much much faster and effective.
This is doable via [ImageMagick](https://imagemagick.org/ ) package or maybe make use of this project [TachiyomiImageSplitter](https://github.com/Lightjohn/TachiyomiImageSplitter).

Whole idea is to split the images after they are downloaded. For example:
image 001.png [1280x12000] will be divided to:
001.1.png [1280x4000]
001.2.png [1280x4000]
001.3.png [1280x4000]

**Note**: I have tried naming the images the same way described above and the reader loaded the images seamlessly without issues.

related to issue https://github.com/Jays2Kings/tachiyomiJ2K/issues/1146

**Comment by Jays2Kings** [comment]
Nah I'm not gonna add a plugin to the app just for this case. Since TachiyomiImageSplitter exists I'd recommend continuing to use that. Otherwise it's better asked on the main tachi, then i'll pick it if its done

**Comment by saud-97** [comment]
@Jays2Kings Unfortunately this plugin has very limited support for android 8+. And I couldn't install it due to that.

Also that plugin only works manually and will be bothersome to use all the time. Unlike if this is implemented it would be automated without interaction.

**Comment by Jays2Kings** [comment]
The fact that plugin is only android 8 (not sure the full reason) is kind of telling how niche that addition would be. The usage versus the effort to implement is way too unbalanced for me to do

**Comment by saud-97** [comment]
I’m interested in implementing this and do a PR. Can you highlight where I should look for and where to miss around and I will do my best to find a solution?

**Comment by Jays2Kings** [comment]
It would be somehlwhere where the download logic is, I suppose the best place is where downloads are changed to cbz. I can't really give much better guidance in a GitHub thread than the internet can do for you after this post

**Comment by saud-97** [comment]
I have done a PR for this fyi.
