### ISSUE TITLE
[Feature Request] Toggle to show cover images in chapters list

### ISSUE THREAD

**Issue by Gin-no-kami** [Jays2Kings/tachiyomiJ2K#122]
Why/User Benefit/User Problem
When reading volumes, i.e. not individual chapters, the cover art is not displayed for each volume in the chapter list. By adding the ability to toggle the chapter list to be a grid, which would display the first page of each volume as the cover, users will be able to see all the nice cover art when browsing the volumes of their manga.

What/Requirements
Implement a layout similar to the Library display's Grid/List mode for the Chapter List, thus allowing users to toggle between a list view or a grid view displaying the cover art for each "chapter" (or volume)

**Comment by joseph619** [comment]
Please post a screenshot as an example.

**Comment by CarlosEsco** [comment]
This is very nice. And would only be valuable for local manga when they broken into volumes

**Comment by Gin-no-kami** [comment]
@joseph619 Here is a mockup of what I had in mind. I essentially overlayed the library grid view onto the chapter view and then overlaid volume covers on top of that. I don't know where it would be best to put the toggle, maybe under "Display mode".
![UI Mockup](https://user-images.githubusercontent.com/15571712/75112843-db31d700-5615-11ea-8dd4-3a774f547d85.png)

**Comment by joseph619** [comment]
Interesting stuff

**Comment by Jays2Kings** [comment]
This looks nice but is impossible unless youre saving all this for local manga, or Mangadex v5 apis come out, supporting covers, and for the latter that's not going to happen with extensions

So yeah, it's not happening

**Comment by Gin-no-kami** [comment]
Don't you already grab and display the first page of new chapters for the notification system? Also what's wrong with it being for local manga or for komga? Is there just not a big enough use case for it?

**Comment by Jays2Kings** [comment]
No the cover is used for notifications. Having such a grand feature for local manga only is a waste since local manga isn't commonly used anyway.
