### ISSUE TITLE
[Bug] Height is off in V1.5.0

### ISSUE THREAD

**Issue by Jerrk** [Jays2Kings/tachiyomiJ2K#1223]
### Device information
* Tachiyomi version: 1.5.0
* Android phone & version: Galaxy Note 8 & Android 9

## Steps to reproduce
1. open any of the main 3 tabs

### Expected behavior
the dimension of the top bar should be better

### Actual behavior
the top bar is huge

### Other details
![](https://i.imgur.com/K8qb2OG.jpeg)

**Comment by nzoba** [comment]
Read the first line of the changelogs, it's a feature... You can deactivate it in the settings

**Comment by Jays2Kings** [comment]
I applaud the effort you took to go and make a github issue instead of reading the changelog or looking into settings

**Comment by BedHedd** [comment]
> Read the first line of the changelogs, it's a feature... You can deactivate it in the settings

To change it, go to Settings > Appearance > Expanded Toolbar

Flip the switch to disable it

**Comment by Jerrk** [comment]
no idea why that would be turned on by default
