### ISSUE TITLE
Can't see category list when switching categories if any filter to the library is active

### ISSUE THREAD

**Issue by ForgetfulJones** [Jays2Kings/tachiyomiJ2K#1224]
### Device information
* Tachiyomi version: 1.5.0
* Android phone & version: samsung galaxy s3, android 9

## Steps to reproduce
1. Make sure any library filter is in place, such as 'unread' or 'downloaded'.
2. Tap category name

### Expected behavior
Should show category list

### Actual behavior
Screen expands area to show category list, but the expanded area is blank.
IFF all filters are off, this area shows the category list properly.

**Comment by Jays2Kings** [comment]
Fixed in 0f81fb21c
