### ISSUE TITLE
[Revert Changes] Remove popups when adding same manga from different sources

### ISSUE THREAD

**Issue by alfaxxromeo** [Jays2Kings/tachiyomiJ2K#1229]
![Screenshot_20220502-045904_TachiyomiJ2K](https://user-images.githubusercontent.com/100927629/166166239-a2c93b68-929f-4bf3-a0d3-94d023126fde.jpg)
Please enable an option to remove the popups.

**Comment by Jays2Kings** [comment]
Why??? you can just tap "add to library" anyway

**Comment by Jays2Kings** [comment]
Since there hasn't been an argument for removing it for a whole month I'm closing this
