### ISSUE TITLE
[Bug] search button isn't working when opening through the migration page

### ISSUE THREAD

**Issue by H7XXY** [Jays2Kings/tachiyomiJ2K#1233]
### Device information
* Tachiyomi version: 1.5.0 (J2K)
* Android phone & version: Realme GT Neo 2 5G, Android 12 (REALME UI 3.0 OFFICIAL BETA)

## Steps to reproduce
1. Open any manga from thr J2K app
2. Go to More Options
3. Click on Migrate Manga
4. Then select your sources 
5. Click on the Migrate Button
6. Click on the (Vertical Three Dots) menu
7. Then Search Manually
8. The search bar isn't working properly

### Expected behavior
The search bar should work properly like it usually does.

### Actual behavior
The search bar isn't working.

### Other details

https://user-images.githubusercontent.com/96281738/166187807-e2f136d4-df01-483d-a3da-1e1c66158d44.mp4

**Comment by Jays2Kings** [comment]
was fixed in 8aca07d5f
