### ISSUE TITLE
[Feature Request] Snap expanded toolbar

### ISSUE THREAD

**Issue by tanuukii** [Jays2Kings/tachiyomiJ2K#1234]
### Why/User Benefit/User Problem
Because in A12 Settings app, the behavior of expanded toolbar is snapping.  So I guess j2k shud match with it too.

### What/Requirements
(explain how this feature would behave)

**Comment by Jays2Kings** [comment]
it snaps already when scrolling up. do you mean have it not autohide?

If you mean snap it when you scroll slightly so its not between expanded and collapsed state, then thats not happening. Refer to how the main screen of settings behave to understand why

**Comment by tanuukii** [comment]
Ah okay, closing this.
