### ISSUE TITLE
[Bug] scrolling in library feels laggy

### ISSUE THREAD

**Issue by ghost** [Jays2Kings/tachiyomiJ2K#1238]
### Device information
* Tachiyomi version: 1.5.0
* Android phone & version:  11

## Steps to reproduce
1. open library of app
2. just scroll

### Expected behavior
smooth scrolling
### Actual behavior
Feels lagging

**Comment by Jays2Kings** [comment]
please actually add your phone, not just the android version

**Comment by ShiSix** [comment]
poco x2 with AOSP android 11 based rom

**Comment by Caio99BR** [comment]
Well, i don't wanted to open an issue about this (because idk if it's a problem of incompatibility with 120hz display) but it lags on library tab (shows a lot of unloaded covers), sometimes when downloading a chapter or when updating.
It's "smooth" on other tabs

It's a BlackShark 4 (870 + 6GB) Android 11 JoyUi 12.8

**Comment by ShiSix** [comment]
i have 120hz screen too

**Comment by cybermuse** [comment]
It happens on my SD625 tablet and SD845 phone as well and both are running 1.5.0 at 60hz whereas anything earlier was way more fluid.

**Comment by Jays2Kings** [comment]
Lockingv this for now since this isn't a chat room

**Comment by Jays2Kings** [comment]
Unlocking this now since there's some improvements to this in v1.5.1. If the library lagged for you before 1.5.0 (ie 1.4.5 and below), this isn't going to change that

**Comment by Caio99BR** [comment]
Sometimes you can see like it's hitting something on the way (not "full" smooth [nobody will die with or without this]), but there's is no lag like on 1.5.0,. definitely better i think

**Comment by Jays2Kings** [comment]
Good enough for me to close this then. There're other issues for lag in the past and i'll continue looking for more improvements as time goes
