### ISSUE TITLE
[Bug] nhentai short title not working

### ISSUE THREAD

**Issue by ShiSix** [Jays2Kings/tachiyomiJ2K#1239]
**PLEASE READ THIS**

### Device information
* Tachiyomi version: 1.5.0
* Android phone & version: 11

## Steps to reproduce
1. open nhentai extensions setting
2. display manga title as :  short title
3. go to nhentai (it will show short title)
4. reopen app
5. go to nhentai

### Expected behavior
titles should be small

### Actual behavior
titles are big

### Other details
1. It is happing only on J2K . tachiyomi is working fine
2. if seleted small titles in nhentai then manga already in library should have small titles but they are long

**Comment by Jays2Kings** [comment]
Actually checking it, the setting is a bit finnicky but it's working as expected from what I can see. Try the setting again and use refresh library metadata in advanced settings

**Comment by ShiSix** [comment]
> Try the setting again and use refresh library metadata in advanced settings

library problem is solved by refreshing metadata. after setting small titles in nhentai latest is showing small title but after closing and reoping app is titles go back to lang titles

**Comment by Jays2Kings** [comment]
This will be fixed next release but you will have to reapply the extension setting for it to work
