### ISSUE TITLE
Auto download for selected series

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#124]
It would be great to have a feature where we are able to select certain series for automatic downloads of new chapters.

**Comment by CarlosEsco** [comment]
This is already doable. Make a category put those series in that category then go to settings downloads and download new chapters

**Comment by vongdong** [comment]
This is already doable. Make a category put those series in that category then go to settings downloads and download new chapters

I don't want to make a downloads only category though.

**Comment by CarlosEsco** [comment]
So go to settings and have it download all?

**Comment by vongdong** [comment]
> So go to settings and have it download all?

That downloads everything though

**Comment by CarlosEsco** [comment]
So make a new category. Then filter and always hide it but keep it to download everything

**Comment by CarlosEsco** [comment]
Just don't think individual is a feasible option to add to downloading when there are other options

**Comment by vongdong** [comment]
> Just don't think individual is a feasible option to add to downloading when there are other options

It just makes it faster to read imo there have been many times where i open up to read and it takes a while to load and some pages don't even load so it's frustrating.

**Comment by CarlosEsco** [comment]
But if you are opening up to read a new series.  Just click in 3 dot download however many chapters. If it's an older series that are current on add it to a downloading category and set that category to auto update. Manga can be in multiple categories and you don't need to even use the category just a visual representation of the individual manga you want to download. It's no different really then what you want

**Comment by vongdong** [comment]
> But if you are opening up to read a new series. Just click in 3 dot download however many chapters. If it's an older series that are current on add it to a downloading category and set that category to auto update. Manga can be in multiple categories and you don't need to even use the category just a visual representation of the individual manga you want to download. It's no different really then what you want

Oh Jesus Christ, I just found that i could select what categories I can choose to auto download new chapters. My apologies. I just thought that option meant it downloads new chapters for all my manga.
