### ISSUE TITLE
Ruined j2k - Inability to track updates to library - DO NOT INSTALL 1.5

### ISSUE THREAD

**Issue by Urfdur** [Jays2Kings/tachiyomiJ2K#1240]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by CrepeTF** [comment]
Lmao

**Comment by CrepeTF** [comment]
May I suggest you migrate over to this fork instead:
https://github.com/NerdNumber9/TachiyomiEH/releases/tag/v8.4.5-EH

It has absolutely 0 restrictions

**Comment by Jays2Kings** [comment]
what you even saying

**Comment by Urfdur** [comment]
The recent update stopped tracking new chapters for the manga in my library. Soon as I went back to 1.45 it was all good.

**Comment by Jays2Kings** [comment]
Try reading the notification next time https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries
