### ISSUE TITLE
I want to support the install function of shizuku

### ISSUE THREAD

**Issue by hanxin1997** [Jays2Kings/tachiyomiJ2K#1241]
### Describe your suggested feature

I'm using shizuku from magisk's zygisk-sui, but tachiyomiJ2K doesn't recognize it.

### Other details

https://github.com/tachiyomiorg/tachiyomi
The main project supports this function
hope tachiyomiJ2K will follow up with this feature.
![3333](https://user-images.githubusercontent.com/58620096/166624558-79b1ce96-1d7b-4e13-9acf-ced4ada62dd1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
It's already there, check advanced settings again
