### ISSUE TITLE
Excessive borders on every menu

### ISSUE THREAD

**Issue by JulesDeLaT** [Jays2Kings/tachiyomiJ2K#1242]
### Steps to reproduce

1. Install v1.5.0
2. Open the app
3. Scroll upwards

### Expected behavior

Border size to be adequate to the size of the title, no excessive space misused

### Actual behavior

A big border left unused on top remains when scrolling up

### TachiyomiJ2K version

1.5.0

### Android version

Android 10

### Device

Poco X3 NFC

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by JulesDeLaT** [comment]
![Screenshot_2022-05-04-09-16-20-216_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/51096769/166707216-da64f5e8-aad8-4073-a8c2-7752f3ae0994.jpg)
![Screenshot_2022-05-04-09-09-27-924_eu kanade tachiyomi j2k~3](https://user-images.githubusercontent.com/51096769/166707655-2cf92af9-09ba-4c95-aa06-8abf884f6f4e.jpg)

**Comment by CarlosEsco** [comment]
read the changelog
