### ISSUE TITLE
Opening supported links in TachiyomiJ2K shows the results improperly. 

### ISSUE THREAD

**Issue by Syzygos** [Jays2Kings/tachiyomiJ2K#1243]
### Steps to reproduce

1. Go to mangadex and browse to a series of your choice. 
2. Share the series link with TachiyomiJ2K.
3. TachiyomiJ2k opens and displays the result as intended but it's displayed improperly. 

### Expected behavior

It should show the source name, full series cover and series name when it's been opened in TachiyomiJ2k like in the image below. 

![Screenshot_20220505-210528_TachiyomiJ2K](https://user-images.githubusercontent.com/9330669/167065164-2b2a6f2c-ce26-4455-9cfe-ba082c1f9ff2.png)

### Actual behavior

The source name, cover and name of the series gets cut off from the screen and looks like in the image below. This does not happen in the main version of Tachiyomi. 

![Screenshot_20220505-210005_TachiyomiJ2K](https://user-images.githubusercontent.com/9330669/167064959-1571fb01-a884-4c80-91bc-a9bf62e6db86.png)

### TachiyomiJ2K version

1.5.0

### Android version

Android 12

### Device

Device: Samsung Galaxy Tab S6, Model: SM-T860

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Fixed in 81fce9300
