### ISSUE TITLE
Custom theme colors

### ISSUE THREAD

**Issue by xxroyalxtigerxx** [Jays2Kings/tachiyomiJ2K#1246]
### Describe your suggested feature

Being able to customize the existing themes or be able to make your own, a simple color selection tool to change certain elements would probably be the easiest way to go about this. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Duplicate issues that's already been rejected. Android 12 exists for such a feature
