### ISSUE TITLE
UI/UX 

### ISSUE THREAD

**Issue by casualmind** [Jays2Kings/tachiyomiJ2K#1248]
### Steps to reproduce

Scroll up or do refresh, the UI between headbar still have some huge gap space (look at the sceenshot below later) 

### Expected behavior

Should make it fixed than floating. 

### Actual behavior

You scroll up, then the UI make different. Look at this I marked up with box. There is some space. 
![IMG_20220508_055413](https://user-images.githubusercontent.com/33999214/167274572-82eff739-fefb-4e80-a47e-581b1e95b838.jpg)

### TachiyomiJ2K version

1.5.1

### Android version

Android 12

### Device

Xiaomi Redmi Note 8

### Other details

Nothing much, this UI issue is happened when update to the newest version 1.5.0 previous version before an update the Ui looking greaf,  just the smol UI problem. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Try reading anything about the app or the update before making an issue. The changelog, other GitHub issues, settings in the app
