### ISSUE TITLE
Multiple select for downloading multiple series

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#125]
This would be a huge time saver for downloading multiple series at one time. Just like holding onto a certain series in the catalogues we are able to multi select or select all. Add an option to download just like the move or delete function.

**Comment by joseph619** [comment]
I don't think this will be added.

**Comment by vongdong** [comment]
> I don't think this will be added.

Why not? Bit of a pain to go into each series to download all chapters.

**Comment by joseph619** [comment]
Because the download code is apparently very complicated already, and it will be even more complicated. Jay doesn't want to touch downloads anytime soon.

**Comment by vongdong** [comment]
> Because the download code is apparently very complicated already, and it will be even more complicated. Jay doesn't want to touch downloads anytime soon.

Ah righto. Fair enough. Maybe in the future there could be a way to download all manga in a selected category?

**Comment by joseph619** [comment]
Perhaps. He's working on a beta build at the moment so he doesn't have time for current feature requests. You can learn more about beta on Discord.

**Comment by XxJibril** [comment]
i would like to suggest a little more specific option that might make it easier, like for a specific category (we can create different categories in the library), have an option to download ALL unread chapters

**Comment by joseph619** [comment]
This is already added
