### ISSUE TITLE
[feature request] Page Error Notification Lacks Context

### ISSUE THREAD

**Issue by saud-97** [Jays2Kings/tachiyomiJ2K#1251]
### Steps to reproduce

if a page was not found during a download. the notification will not be helpful since it would only write the chapter number without including the manga title.

Inside downloader `getOrDownloadImage() `method

```
            // Mark this page as error and allow to download the remaining
            .onErrorReturn {
                page.progress = 0
                page.status = Page.ERROR
                notifier.onError(it.message, download.chapter.name)
                page
            }
```

I tired to do a PR to match this with the upstream since they have `notifier.onError() `with an extra string parameter but there were conflicts and I'm not sure how you would like them resolved.

### Expected behavior

`onError` method should allow `download.manga.title` string to be in the notification same as upstream.

```
           notifier.onError(it.message, download.chapter.name, download.manga.title)
```

### Actual behavior

Only chapter number is displayed in the error.

**Comment by Jays2Kings** [comment]
I'm not sure why you skipped using the templates but expecting something that different from what was originally intended is a feature request, not a bug

**Comment by saud-97** [comment]
Yeah my bad I was thinking which one to chose but wasn't sure if it was intended or not.

**Comment by saud-97** [comment]
I forgot to mention this also applies everywhere when using `onError `and only mentioning the chapter name not only in the Page errors.
So this applies to `downloadChapter `error handler and possibly other places where `onError `was used.
