### ISSUE TITLE
[Feature request] the webtoon reader hiding menu on scroll from the original tachiyomi 

### ISSUE THREAD

**Issue by Jjjggh** [Jays2Kings/tachiyomiJ2K#1252]
### Describe your suggested feature

I hope that  it's not much , 

It's just the same as in tachiyomi webtoon reader sitting ( sensitivity for hiding menu on scroll)
If the menu is shown and the you scroll to continue enjoying your webtoon the menu goes boof,  just like the 

 I'm really looking forward to this feature because it annoys the one when the menu stays there 

I really like the app and the interface is the just fantastic 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [x] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Why did you remake this request?

**Comment by Jays2Kings** [comment]
closed in 918d70e63
