### ISSUE TITLE
[bug] Empty space before the search bar and title

### ISSUE THREAD

**Issue by m-a-hannan** [Jays2Kings/tachiyomiJ2K#1253]
### Steps to reproduce

1. Open the app and the empty space shows up

### Expected behavior

There shouldn't be any unnecessary empty space before the seach bar

### Actual behavior

There is empty space before the seach bar which goes away when scrolling down 

### TachiyomiJ2K version

1.5.2

### Android version

MIUI Global 13.0.4 Stable

### Device

Xiaomi Poco X3 Pro 

### Other details

There wasn't any unnecessary spaces before/ on top of  the search bar in older version of the app, but after updating it to the latest version 1.5.2 there is empty space which is annoying.

![Picsart_22-05-09_09-03-21-959](https://user-images.githubusercontent.com/28342175/167333579-880799c3-512d-4e12-8fbb-424669bfe55a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Didnt check the box yet still a 🤡

**Comment by m-a-hannan** [comment]
> Didnt check the box yet still a 🤡

Seriously? 🥴
