### ISSUE TITLE
Version Update notification update button does nothing.

### ISSUE THREAD

**Issue by AefRal** [Jays2Kings/tachiyomiJ2K#1255]
### Steps to reproduce

1. Open TachiJ2K when update available.
2. Be notified of update.
3. Tap update button.
4. Notification closes and nothing downloads.
5. Come here for manual download.
6. Create issue post.
7. Install update.

### Expected behavior

After pressing update, it should download the new version and ask me to install it.

### Actual behavior

Nothing happens when pressing update within the notification.

### TachiyomiJ2K version

1.4.5.

### Android version

Android 10

### Device

Huawei P20 Pro

### Other details

There's a chance this was fixed in the update I was trying to download through the app.

Funny one, about the clown checkbox.
I really wanted to check that box for giggles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Can you record a video of what happens? Since this is an older version I'm not sure if it's fixed

**Comment by AefRal** [comment]
I've manually updated already...

Also, the notification that states there's a new version does not appear
every time I freshly open TachiJ2K.
I even tried to get it to appear again by hitting the square button that
shows all open apps and swiping it away.
Then reopening it.
Until there's a newer update than 1.5.2, I won't be able to take a video.

Side note, there's way to much headway, or empty space, at the top now. It
feels weird.

**Comment by Jays2Kings** [comment]
You can open a new issue if it happens again then. Also read the changelogs
