### ISSUE TITLE
[Bug] Long tap dialog option doesn't work

### ISSUE THREAD

**Issue by DragoCubed** [Jays2Kings/tachiyomiJ2K#126]
### Device information
* Tachiyomi J2K version: 0.9.81
* Android phone & version: Galaxy S5, Android 6.0.1

## Steps to reproduce
1. Open a manga (could be any type)
2. Set mode to right to left (could be any mode)
3. Disable long tap dialog

### Expected behavior
I could totally be misunderstanding what the option does. I expect the option to disable the little sheet that lets you set a page as a cover, share or download. 

### Actual behavior
Even after restarting Tachiyomi J2K, the long tap dialog still appears. 

### Other details
Issue also appears in regular Tachiyomi.

**Comment by arkon** [comment]
I believe it only affects when the toolbars are hidden.

**Comment by DragoCubed** [comment]
@arkon thank you! Do you think a description should be added mentioning this?

**Comment by Jays2Kings** [comment]
Honestly I'd sooner remove it, it's not like disabling it changes it for another feature

**Comment by DragoCubed** [comment]
@Jays2Kings for me I found it annoying and turning it off was nice. Your call of course :)
