### ISSUE TITLE
"The image could not be decoded" when loading .gif

### ISSUE THREAD

**Issue by TheFrisianGamer** [Jays2Kings/tachiyomiJ2K#1262]
### Steps to reproduce

1. Use TachiyomiJ2K v1.5.3
1. Open chapter with a .gif page. (I.e. Credits page for Marumaru na kanojou ni dekiaisareru hanashi volume 2 chapter 1)
2. Go to the .gif page

### Expected behavior

The reader should load the.gif image correctly, like the original Tachiyomi v.0.13.4 does

### Actual behavior

Get error message reading "The image could not be decoded" 

### TachiyomiJ2K version

1.5.3

### Android version

Android 11

### Device

Nokia 8.1

### Other details

The gif used as an example is a large file, have not checked smaller gif files if those have the same issue. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Which source is this from? I've checked one and this gif is loading fine

Also are you sure you're on 1.5.3 this was a big in an earlier version of tachi

**Comment by TheFrisianGamer** [comment]
I am sure I'm using 1.5.3, as the about page says so ![Screenshot_20220518-070948~2.png](https://user-images.githubusercontent.com/45695624/168961654-f10bfc3a-796a-4dc1-9a1a-4a268c114b94.png)

The app info:
App version: 1.5.3 (standard, ae15cf3, 91, 2022-05-17T18:15:38.559931)
Android version: 11 (SDK 30)
Android build ID: 00WW_6_21F
Device brand: Nokia
Device manufacturer: HMD Global
Device name: PNX_sprout
Device model: Nokia 8.1
Device product name: Phoenix_00WW


The source I was using is Mangadex, both regular Tachi and browser Mangadex work finr

**Comment by Jays2Kings** [comment]
Can you share a screenshot of this + what reader settings you have? Like I said it's showing fine when I try on dex

**Comment by TheFrisianGamer** [comment]
The problem seems to be with the dual page split, loading the page when single page is selected works fine. The dual page split in OG Tachi doesn't seem to have this problem. 
![Screenshot_20220518-083648.png](https://user-images.githubusercontent.com/45695624/168974386-a29eb625-85ff-48eb-80ed-9ced18218211.png)
![Screenshot_20220518-084104.png](https://user-images.githubusercontent.com/45695624/168974404-526132e2-6206-4be1-af71-f5485cf3a08c.png)
![Screenshot_20220518-083732~2.png](https://user-images.githubusercontent.com/45695624/168974449-0a7713ec-fd8b-4203-948c-d70a6fc0a688.png)
![Screenshot_20220518-083747~2.png](https://user-images.githubusercontent.com/45695624/168974461-9a272688-313c-4bfc-a0e2-df99246eb64f.png)
