### ISSUE TITLE
Reader menu hides when reaching the end of latest chapter in webtoon mode while tap-scrolling

### ISSUE THREAD

**Issue by asdkant** [Jays2Kings/tachiyomiJ2K#1265]
### Steps to reproduce

1. open series in webtoon mode
2. navigate in whatever fashion until near the end, but advance with tapping (not swiping) to the very end

### Expected behavior

Reader menu should be shown

### Actual behavior

Reader menu appears and very quickly disappears (it's hard to catch if the device is fast enough)

### TachiyomiJ2K version

1.5.3

### Android version

11 (+Samsung OneUI 3.1)

### Device

Samsung Galaxy Tab S5e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Fixed in 65bac70c9
