### ISSUE TITLE
[From Upstream] Increase Manga Update Concurrency to 5 sources

### ISSUE THREAD

**Issue by saud-97** [Jays2Kings/tachiyomiJ2K#1269]
### Describe your suggested feature

I suggest to increase number of concurrent update jobs in `updateChaptersJob` to 5 sources at the same time during Global Updates, similar to download concurrency from 5 sources. 

**To help in speeding up updating without putting any extra pressure on sources, and to avoid slow sources throttling the update speed.**

### Other details

This is implemented in Upstream as they show in their notification of update the list of mangas that are concurrently being updated.

![image](https://user-images.githubusercontent.com/39028181/169675420-061adf6f-48b2-4a56-8f83-0f1ec51985ea.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
it's been this way for years now, in fact it was added before main did it

**Comment by saud-97** [comment]
Oh I see, so only the notification wasn't showing all 5 mangas being updated like main.
