### ISSUE TITLE
[Bug] Cant get reader navigation in webtoon mode

### ISSUE THREAD

**Issue by ardittristan** [Jays2Kings/tachiyomiJ2K#127]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: 8.0

## Steps to reproduce
1. Set reader mode to webtoon on manga
2. Tap the very bottom of the screen

### Expected behavior
Reader navigation/settings should show up like in the other reader modes

### Actual behavior
It scrolls down the page

### Other details
Cant find any way to get the navigation to show up in webtoons

**Comment by arkon** [comment]
Tap in the middle

**Comment by Jays2Kings** [comment]
Not much else to say here
