### ISSUE TITLE
Default and/or persistent search settings sor sources

### ISSUE THREAD

**Issue by asdkant** [Jays2Kings/tachiyomiJ2K#1270]
### Describe your suggested feature

(mostly for NSFW sources) there are some tags that I always exclude when searching, I'd like a way to set those search parameters (exclude such and such categories) as the default when I search specific sources.

I can see how this could be useful as a more general feature outside of NSFW stuff, like people who have issues with specific kind of content and would like to exclude that when searching.

I understand that this may have to be a per-source thing (due to the inconsistent nature of how sources work)

Another solution could be to globally set blacklisted keywords, which would solve my particular problem but is less powerful/flexible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Been asked before
