### ISSUE TITLE
Auto-categorize by source (configurable)

### ISSUE THREAD

**Issue by asdkant** [Jays2Kings/tachiyomiJ2K#1271]
### Describe your suggested feature

I always put NSFW stuff in it's own category, and use different sources for NSFW and SFW stuff.

I'd like a way to have the app select the NSFW category automatically when I add a series from a NSFW source.

### Other details

It'd make sense to generalized for other use cases by providing a way to select, for each source, which categories to auto-select when adding a series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Theres already a way to categorize by source. Explore the app, press a filter button

**Comment by asdkant** [comment]
But that's not what I'm asking for.

The ask here is to have a way to have the app auto-select categories according to a predefined criteria (source, but it could also be tags for other similar use cases)
