### ISSUE TITLE
A secret Library or an option for multiple libraries

### ISSUE THREAD

**Issue by 12CRISTIAN12** [Jays2Kings/tachiyomiJ2K#1272]
### Describe your suggested feature

There could be a button to change the library, pressing it would show you the created libraries and you could choose which one to use.

pressing "add to library" on a font would save it to the library you're using and then you'd be able to change it to another library if you wanted to.

sorry for any typos as i don't speak english and i'm using google translate

### Other details

Each library should be independent of the other, that is, when filtering the manga it only shows the results of the library that is being used at that moment.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [x] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown to be laughed at by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Been asked before and denied before
