### ISSUE TITLE
Add Option to Sort Updates by time they were Found

### ISSUE THREAD

**Issue by senkneel** [Jays2Kings/tachiyomiJ2K#1276]
### Describe your suggested feature

I think there should be an option to sort the series updates by the time they were Found and not the time they were published on their website. Like it is in the normal Tachiyomi.

### Other details

Currently some updates are pushed back to the end of the list so I don't see them even though I just updated the list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Date Fetched should be what you are looking for

**Comment by senkneel** [comment]
> 

I dont think thats what I meant. I did not mean the Lists in the Library tab i meant the Updates page in the Recents tab.
