### ISSUE TITLE
Lewd Filter

### ISSUE THREAD

**Issue by ArchCelestial** [Jays2Kings/tachiyomiJ2K#1279]
### Describe your suggested feature

It should be a toggleable setting in the section where it allows you to filter the library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [x] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/1128 similar request that was denied
