### ISSUE TITLE
[Feature Request] Last black page (Finished/Next) disable button

### ISSUE THREAD

**Issue by UWNG99** [Jays2Kings/tachiyomiJ2K#128]
### Why/User Benefit/User Problem
There are some one pages comics or mangas, like Wonder Cat Kyuu-chan which become tedious when having one content page and one "useless" page between them.

![Screenshot_20200225-210245](https://user-images.githubusercontent.com/32283611/75307853-6aa3d980-5812-11ea-9d77-c4a7d1051286.png)

### What/Requirements
It is my opinion that a button to enable/disable that screen should be added in order to choose whether we want to see that page or not

**Comment by CarlosEsco** [comment]
Duplicate

**Comment by joseph619** [comment]
That's the buffer page, yeah I can see why you might dislike it.

**Comment by CarlosEsco** [comment]
I would switch to webtoon as a work around.  It shrinks the image to wrap the text.  So its only a small amount of screen space

**Comment by Jays2Kings** [comment]
I have no plans to remove it since it acts as a buffer. As Carlos said you can use webtoon mode instead

**Comment by UWNG99** [comment]
Hello, thanks for the answer, just to say something maybe the pull request created by morcefaster for issue #1653 in inorichi/tachiyomi could help here too.

https://github.com/inorichi/tachiyomi/issues/1653
