### ISSUE TITLE
[Bug] Anilist in Webview not loading

### ISSUE THREAD

**Issue by RYNAPU** [Jays2Kings/tachiyomiJ2K#129]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: Pixel 3 & Android 10 

## Steps to reproduce
1. Find manga through MangaDex source
2. Load manga in web view
3.Find the Information in MangaDex and try to load Anilist info page.

### Expected behavior
It should load the Anilist page.

### Actual behavior
Gets stuck on grey screen 

### Other details
Able to load Anilist page info if opened in browser but not through webview for some reason. Everything is up to date as well.

**Comment by Jays2Kings** [comment]
Closing b/c there's nothing that can be done on this end, it's on AL to support it, or webview to update
