### ISSUE TITLE
Selecting any text inside WebView crashes the App

### ISSUE THREAD

**Issue by staticV3** [Jays2Kings/tachiyomiJ2K#1290]
### Steps to reproduce

1. Choose any Manga
2. Tap on the globe symbol to open in WebView
3. Long-Press any text to select it
4. App crashes 

https://user-images.githubusercontent.com/39950625/171348372-25d674a2-da38-45da-b21d-53304fc4acda.mp4

### Expected behavior

The App should not crash

### Actual behavior

The App crashes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/8812279/tachiyomi_crash_logs.txt)
 

### TachiyomiJ2K version

1.5.4

### Android version

Android 12

### Device

Samsung Tab S7+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
@Jays2Kings this is probably the fix https://github.com/CarlosEsco/Neko/commit/0bef0ced0326b9d95d04e1931676c194e4b3d874
