### ISSUE TITLE
Updating library become slow

### ISSUE THREAD

**Issue by D1012** [Jays2Kings/tachiyomiJ2K#1307]
### Steps to reproduce

Updating library became slow unlike before

### Expected behavior

The library should update fast like before even though my internet connection is fast

### Actual behavior

Became slow on update

### TachiyomiJ2K version

1.5.4

### Android version

Android 9

### Device

Hauwei y6s 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by MahdeenSky** [comment]
so you admitted that you are a clown and did not read the acknowledgements? Lol
