### ISSUE TITLE
Shizuku toggle on extension installation/update screen

### ISSUE THREAD

**Issue by Aryan-Verma-02** [Jays2Kings/tachiyomiJ2K#1309]
### Describe your suggested feature

There should be a toggle button or a dropdown_(like for incog)_ for enabling shizuku directly through the extension screen.

As sometimes we just need to update/install a single ext. and shizuku is not running so going to the advanced settings and then coming back or attaching the device to a pc and enabling it is a bit of a hassle.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Not going to happen since shizuku is an advanced setting and would confuse the average person
