### ISSUE TITLE
[Feature Request] Add download button to manga info.

### ISSUE THREAD

**Issue by Arkcade** [Jays2Kings/tachiyomiJ2K#131]
### Why/User Benefit/User Problem
For users that want to download all chapters to be able to read for when using sources with slow loading times like mangakakalot and manganelo. There currently is a way to do this but it takes quite a long time to go trough the multiple ellipsis menus in the chapters for manga.

Say you want to download 10 new manga's going through and downloading each of them usually take 1-2 minutes (longer for slower phones) adding a button to download all would be nice making it take 10 seconds to add all chapters to downloads.

auto download dose exist but it only works for downloading new chapters not all chapters like this button will fiction for.

### What/Requirements
On the manga info page add a button near or on the opposite side to the bookmark button that is a download arrow that will function if pressed to download all chapters and if long pressed open a menu in the style of the ellipsis menu where you can download the next chapter, next 5 chapters, unread, ect.

**Comment by CarlosEsco** [comment]
On manga info page, swipe left, 3 dot at top, download, download all.

**Comment by CarlosEsco** [comment]
Takes 2 seconds max

**Comment by Arkcade** [comment]
> On manga info page, swipe left, 3 dot at top, download, download all.
> Takes 2 seconds max , and there are multiple options

i did talk about that in my user benefit text.
> There currently is a way to do this but it takes quite a long time to go trough the multiple ellipsis menus in the chapters for manga.

but its more along the lines of you want to mass download something
 like 15 manga like i usually do for mass reading it gets quite monotonous having to swipe over to the chapters just to open 2 menus to download all.

Something like this.
![Download Menu](https://user-images.githubusercontent.com/19383165/75770038-110c5380-5dac-11ea-9606-633728b60e25.jpg)
![Download all button](https://user-images.githubusercontent.com/19383165/75770041-12d61700-5dac-11ea-8c05-07aa36165410.jpg)

**Comment by CarlosEsco** [comment]
Again you can just do this

![download gif](https://user-images.githubusercontent.com/2092019/75779500-bc26f980-5d27-11ea-9c39-720807cff06d.gif)

**Comment by Jays2Kings** [comment]
This is not happening, just swipe over and stop being lazy
