### ISSUE TITLE
Crashes when opening manga and changing pages

### ISSUE THREAD

**Issue by Zazazasu** [Jays2Kings/tachiyomiJ2K#1316]
### Steps to reproduce

1. Open manga or change page
2. Progress spinner starts to fill

### Expected behavior

App not to crash

### Actual behavior

App crashes and reopens

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/8992852/tachiyomi_crash_logs.txt)

### TachiyomiJ2K version

1.5.4

### Android version

Android 11

### Device

Samsung SM-P905 Note Pro 12.2

### Other details

I tried with native webview and a freshly installed one from the play store, didn't fix it.
It doesn't always happen, I don't know why some manga crash and others dont.
It also crashes after the page has loaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Please add what manga, chapter, source, page this is happening. If its because pages are too tall, try auto split tall images in download settings

**Comment by Zazazasu** [comment]
Sono toki shuraba ga ugoita/At that time the battle began, vol 1,ch 2 first page on Mangadex. Turning on auto split doesn't seem to help.

**Comment by pavonismc** [comment]
I am experiencing the same thing but I don't have a log file of it
