### ISSUE TITLE
When you global search app decides to crash 

### ISSUE THREAD

**Issue by Ashketchup198** [Jays2Kings/tachiyomiJ2K#1325]
### Steps to reproduce

So let's say I have peerless dad in my library I click on it and the title I press global search to see other sources of the same title as I do that the app minimises and crashes.

### Expected behavior

What normally happens you tap the global search it opens up showing the different sources of the same title. 

### Actual behavior

Rather what happens it crashes and prevents this action 

### Crash logs

beginning of main
07-06 01:05:19.290  5617  5617 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
07-06 01:05:19.292  5617  5617 E USNET   : USNET: appName: eu.kanade.tachiyomi.j2k
07-06 01:05:20.213  5617  5826 E SQLiteLog: (284) automatic index on C(manga_id)
07-06 01:05:20.213  5617  5826 E SQLiteLog: (284) automatic index on R(manga_id)
07-06 01:05:20.213  5617  5826 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-06 01:05:21.694  5617  5829 E SQLiteLog: (284) automatic index on mangas(_id)
07-06 01:06:20.000  5617  5617 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@e3ad007 was not the current floating action mode! Expected null
07-06 01:06:20.841  5617  6445 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi.j2k
07-06 01:06:20.841  5617  6445 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
07-06 01:06:20.841  5617  6445 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:4)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at java.lang.Thread.run(Thread.java:920)
07-06 01:06:20.841  5617  6445 E ACRA    : Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/salomonbrys/kotson/BuilderKt;
07-06 01:06:20.841  5617  6445 E ACRA    : 	at eu.kanade.tachiyomi.extension.en.mangarock.MangaRock.searchMangaRequest(MangaRock.kt:113)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource.fetchSearchManga(HttpSource.kt:1)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at eu.kanade.tachiyomi.ui.source.globalsearch.GlobalSearchPresenter$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:2)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
07-06 01:06:20.841  5617  6445 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
07-06 01:06:20.841  5617  6445 E ACRA    : 	... 6 more
07-06 01:06:20.841  5617  6445 E ACRA    : Caused by: java.lang.ClassNotFoundException: com.github.salomonbrys.kotson.BuilderKt
07-06 01:06:20.841  5617  6445 E ACRA    : 	... 15 more
07-06 01:06:22.778  6536  6536 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
07-06 01:06:22.779  6536  6536 E USNET   : USNET: appName: eu.kanade.tachiyomi.j2k
07-06 01:06:23.216  6536  6622 E SQLiteLog: (284) automatic index on C(manga_id)
07-06 01:06:23.216  6536  6622 E SQLiteLog: (284) automatic index on R(manga_id)
07-06 01:06:23.216  6536  6622 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-06 01:06:23.340  6630  6630 E hiyomi.j2k:acr: Not starting debugger since process cannot load the jdwp agent.
07-06 01:06:23.341  6630  6630 E USNET   : USNET: appName: eu.kanade.tachiyomi.j2k:acra
07-06 01:06:24.957  6536  6622 E SQLiteLog: (284) automatic index on mangas(_id)

### TachiyomiJ2K version

1.5.5

### Android version

Android 12 

### Device

Note 10 plus 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.5](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Is this still happening on 1.5.9?

**Comment by Ashketchup198** [comment]
Hi this happens on latest update 1.6 as well as the previous hasn't changed

**Comment by Jays2Kings** [comment]
Looking at the dogs, it's because you have the mangarock extension installed, which is no longer supported by the app. You need to uninstall it for global search to work

**Comment by Jays2Kings** [comment]
Closing this since there is no fix for outdated extensions
