### ISSUE TITLE
Sorting by number of chapters left to read

### ISSUE THREAD

**Issue by Rikioh-NE** [Jays2Kings/tachiyomiJ2K#1328]
### Describe your suggested feature

Like the title says. For now, it's only possible to sort the various manga by the number of total chapters, but I think it would be a nice little improvement of quality of life in certain situations if someone could just sort them by how many chapters are still unread. 
I recognize that maybe it would look unclean and confusing to have multiple similar sorting options, but maybe this can be solved with some sort of sub-menu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] I have updated the app to version **[1.5.5](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
check the sorting options again
