### ISSUE TITLE
[Feature Request] Custom Tags

### ISSUE THREAD

**Issue by notsonata** [Jays2Kings/tachiyomiJ2K#1330]
### Describe your suggested feature

A way to create our own custom tags would be greatly appreciated. Some of the series in my library have complete tags while some only have 2-3. I am aware that this is an issue with the sources. However, having incomplete tags also poses a problem for the sorting system. Here is an example: https://imgur.com/a/IDKUaJ4

A great solution to this would be letting users create their own tags. They allow for further library customizations. Letting users manually tag their series would also indirectly fix the sorting issue. Here is an example: https://imgur.com/a/EoAjsl1

I think custom tags would give way for greater library customizations. In addition to letting users add their own missing tags, it could also be used as a sort of crude rating system. Create a tag, put in your rating and save. It would be awesome if I can search for "10/10" on the search bar and easily find the best of my library. That's just the tip of the iceberg. The possibilities are limitless. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.5](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by nzoba** [comment]
The feature already exists. When you are on a manga page, juste click on the three-dot menu then `Edit`. There you can edit all the manga info, such as title, status, series type and tags

PS: You should explore the app
