### ISSUE TITLE
CloudFlare loop 

### ISSUE THREAD

**Issue by Rubberxgum** [Jays2Kings/tachiyomiJ2K#1335]
### Steps to reproduce

1. Go to browse section.
2. Browse on NHentai.
3. Press the "Open on WebView" button to bypass cloudflare. 

### Expected behavior

1. After waiting for a few seconds, cloudflare will be automatically bypassed and I should be able to browse on NHentai.

### Actual behavior

1. It keeps restarting endlessly without bypassing cloudflare.

### Crash logs

The app doesn't exactly crash so crazy logs doesn't show anything.

### TachiyomiJ2K version

1.5.5

### Android version

Android 12

### Device

Redmi Note 10

### Other details

OG Tachi can bypass cloudflare on NHentai without any problems so this isn't an extension issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.5](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
🤡 it's already fixed for next release
