### ISSUE TITLE
comments section 

### ISSUE THREAD

**Issue by AlejandroTodoroki26** [Jays2Kings/tachiyomiJ2K#1339]
### Describe your suggested feature

Add a comment section for readers to comment on what they think of what they are reading, whether it is a manga/manhua/manwha etc. It can help to have a better fit and thus readers can give their opinion regarding what they are reading  

### Other details

Put a translator in case the comments are in another language 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
tachiyomi doesnt have servers to host comments. If you want to comment on what youre reading you can check if yhr source youre using has a comment section, or talk about manga on the [tachiyomi discord](https://discord.gg/tachiyomi) (you must speak english in it however)

**Comment by Jays2Kings** [comment]
The extensions tachiyomi uses doesn't have a way to get comments and likely never since a lot of sites also use their own commenting system and it's not worth it

If the site has a comment section you can open the WebView and view the comments that way
