### ISSUE TITLE
The library's scroll bar doesn't actually scroll anymore.

### ISSUE THREAD

**Issue by ArjixWasTaken** [Jays2Kings/tachiyomiJ2K#1347]
### Steps to reproduce

1. Go to the library
2. Touch and drag up/down the scroll bar.
3. See that it only snaps to categories instead of scrolling.

### Expected behavior

To scroll through all the rows in a category instead of scrolling directly to the start of the next category.

### Actual behavior

*Sighs*, I believe I already told you...

### TachiyomiJ2K version

1.5.6

### Android version

12

### Device

Irrelevant to be honest, but it is `Xiaomi 11 Lite 5G NE`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by ArjixWasTaken** [comment]
I would actually tick the clown checkbox, but I really want this issue fixed and I doubt you would find it funny.

**Comment by Jays2Kings** [comment]
> Irrelevant to be honest, but it is Xiaomi 11 Lite 5G NE

It's irrelevant because it's the intended behavior, which is actually mentioned in the release notes. Make an actual feature request and I'll consider it, even though this post still reeks of clown behavior

**Comment by ArjixWasTaken** [comment]
> > Irrelevant to be honest, but it is Xiaomi 11 Lite 5G NE
> 
> It's irrelevant because it's the intended behavior, which is actually mentioned in the release notes. Make an actual feature request and I'll consider it, even though this post still reeks of clown behavior

Wait...so you destroyed the scroll bar and that is an intended feature?
Sounds like a downgrade to me.

**Comment by ArjixWasTaken** [comment]
@Jays2Kings 

This here is an intended feature?

https://user-images.githubusercontent.com/53124886/179979985-571f9ff3-e706-4613-9305-015109034615.mp4

**Comment by Jays2Kings** [comment]
> Are you sure about that?

![aaf.png](https://user-images.githubusercontent.com/8617760/180026686-cf226077-fa25-4864-8ed4-e3c911424ec8.png)

I've already told you what you should to do so no further discussion on this page is needed
