### ISSUE TITLE
Turning off 'Animate Page Transition' does nothing

### ISSUE THREAD

**Issue by rikuddo91** [Jays2Kings/tachiyomiJ2K#1349]
### Steps to reproduce

1. Go to settings -- Reader
2. Switch Off 'Animate Page Transition'

### Expected behavior

It should turn of any transition effect while moving through page with a tap on bottom of screen.

### Actual behavior

The page still transition with a sliding effect when tapping at bottom of screen (to go to next page).

### TachiyomiJ2K version

1.5.6

### Android version

Anroid 12

### Device

Pixel 4A

### Other details

I've tried the same function with original Tachiyomi and it behaves as it should, but in J2K, it doesn't seems to work at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Is this still happening? It's working as of 1.5.9?

**Comment by rikuddo91** [comment]
> Is this still happening? It's working as of 1.5.9?

Yes, it has been fixed. Thank you so much for your work. This has been my most used app for a while now.

**Comment by MissingNerd** [comment]
You guys sure it's fixed? I still have this problem
