### ISSUE TITLE
Webtoon reader lag

### ISSUE THREAD

**Issue by jafri-jahan-s** [Jays2Kings/tachiyomiJ2K#1350]
### Steps to reproduce

Scrolling through webtoons are supper laggy sometimes. specific pages are supper laggy while scrolling. 
If scroll past a point it is smooth but comes back to previous it stutters exactly the same place 

For example the first chapter of 'the first order' from Asura scans. You can see that it stutters a lot but there is a small portion after page 3 that is smooth after that the whole chapter is pretty much a stuttery read

### Expected behavior

Smooth scrolling 

### Actual behavior

Stuttery mess

### TachiyomiJ2K version

1.5.6

### Android version

12

### Device

OnePlus 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
try auto split tall downloaded images in the download settings
