### ISSUE TITLE
Manual color selection

### ISSUE THREAD

**Issue by edmxn** [Jays2Kings/tachiyomiJ2K#1351]
### Describe your suggested feature

It would be great if in the Appearance section we could choose the color of the app manually

### Other details

Example: I want to choose Violet for everything, but the blue is next to Violet, it would be great to be able to choose only one color :)

I have no idea if that option already exists in this version of Tachiyomi, but I have searched and found nothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
🤡
