### ISSUE TITLE
WebView - Disquis Login

### ISSUE THREAD

**Issue by edmxn** [Jays2Kings/tachiyomiJ2K#1352]
### Steps to reproduce

1. Open comments and try to log in with Disquis

### Expected behavior

The session should start as in any external browser

### Actual behavior

Disquis does not go beyond the "Please Wait..." window.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/9173081/tachiyomi_crash_logs.txt)

### TachiyomiJ2K version

1.5.6

### Android version

Android 12

### Device

Samsung S10+

### Other details

It's a WebView problem, I guess

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Why did you raise this expecting something different from what you had here? https://github.com/tachiyomiorg/tachiyomi/issues/7044
🤡 moment

**Comment by edmxn** [comment]
> Why did you raise this expecting something different from what you had here? [tachiyomiorg#7044](https://github.com/tachiyomiorg/tachiyomi/issues/7044) 🤡 moment

It's a fork, I thought they would give more importance to that.
