### ISSUE TITLE
"Skip update log"

### ISSUE THREAD

**Issue by cojoMan** [Jays2Kings/tachiyomiJ2K#1353]
### Describe your suggested feature

Currently with the latest TY update, there are a few checkboxes for the library to skip completed/not started comics. That is great, but can we also have something to skip those in the error log as well ? I for one would like to see in the error log the errors, and the succesfully updated ones, but I am filled like 80% of the log with the ones that were skipped because "completed". From what I understand this behaviour does not happen to the original TY.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
If I'm understanding this right, you want an extra option in the skips to also skip it but not show in the skips log?

Yeah thats not worth it for a temp log thats reset each update, it's already grouped up you can just scroll past the completed ones
