### ISSUE TITLE
Sync downloads on backup

### ISSUE THREAD

**Issue by MrChuw** [Jays2Kings/tachiyomiJ2K#1355]
### Describe your suggested feature

When creating the backup give the option to put which chapters are downloaded.

When restoring give the option to download/delete the chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
not going to happen since downloads are massive, you can ask on main tachi to do but they'll also decline

**Comment by MrChuw** [comment]
I expressed myself badly, not the download itself, but which chapters are downloaded, so would put it to download or delete automatically.

**Comment by MrChuw** [comment]
I expressed myself badly, not the download itself, but which chapters are downloaded, so would put it to download or delete automatically.
