### ISSUE TITLE
[Feature Request] Hiding chapters

### ISSUE THREAD

**Issue by GreatestFool** [Jays2Kings/tachiyomiJ2K#136]
Not sure if it's bad form or not, but this is just a continuation of [this issue](https://github.com/Jays2Kings/tachiyomiJ2K/issues/89).

I think the issue should be reconsidered and not simply marked as wont-fix.

As previously mentioned, yes there _are_ very cumbersome ways around very specific issues when it comes to hiding chapters. On Mangadex you can block a translator group to hide the chapters they release. However, there are also situations where that wouldn't solve anything. Case in point being Tsugumomo. The translator group releases two versions of the same chapter, one translated and another translated and edited, chapters are defined as 1 and 1.1 which makes sorting by chapter number to hide them also not work. You _could_ enable the setting to skip read chapters, however that's a global setting and isn't really practical the second you want to re-read an already read series. There's also the fact that not all content aggregators even give the option to hide scanlator groups.

Being able to simply long-press to select an n-amount of chapters and adding a 'hide chapter' button to the menu would solve basically all these problems and much more practically than all the currently available sometimes-working solutions.

**Comment by CarlosEsco** [comment]
Just long press and mark as read. Then in settings skip chapters marked as read

**Comment by GreatestFool** [comment]
Did you read my post through? I already mention this setting. And like I said, that works only in specific situations. Had the setting been per manga, it'd been more of a valid solution. However it is a global setting, and any and all chapters marked as read will be skipped over even if you want to or not.

**Comment by CarlosEsco** [comment]
If you are rereading something just mark it unread.

**Comment by GreatestFool** [comment]
That still solves nothing in the grand scheme of things. I can, of course, set the particular manga I'm re-reading to unread so not every chapter gets skipped over. But what about all the other ones I am actively reading? I don't know about you, but I know I'm not the only one that tends to re-read a chapter or two before the newest release to get a refresh. Having to mark a chapter as unread when you're getting a refresh of more than one chapter every time you do it is simply tedious and the complete opposite of being user friendly.

Hiding chapters is what I really want, but I'd settle for a skip-read-chapters on a per-manga basis instead of it being a global setting. It's not as good a solution as simply hiding a chapter is, but at the very least it is a start. Just for the sake of mentioning an example, a manga that has duplicate/alternate chapters from the same translator group wouldn't be skipped if they're all marked as read, and if you want an enjoyable binge read, you'd have to manually mark each of the chapters that you're supposed to read as unread, which _will_ be incredibly cumbersome on larger series. To the point that most people would simply give up.

**Comment by Jays2Kings** [comment]
Making another issue isn't going to change my mind. It's an extreme edge case between laziness by the user and functionality of the source. 

Adding this is cumbersome on its own so I still won't be adding it
