### ISSUE TITLE
Reader crashes.

### ISSUE THREAD

**Issue by CodeGrogu** [Jays2Kings/tachiyomiJ2K#1361]
### Steps to reproduce

When reading downloaded chapters of One Punch the app shows the starting screen of TachiyomiJ2K and acts like it's just been opened. The only solution I could find was to delete the chapter and read it without downloading.

### Expected behavior

It should behave as it does with other downloaded chapters from the same extension without crashing/closing the reader.

### Actual behavior

Crashing/closing (not out of the app, it restarts the app without showing the android launcher) after reading for less then 30 seconds.

### TachiyomiJ2K version

1.5.6

### Android version

Android 11

### Device

Samsung Galaxy A30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by xXAceNoob** [comment]
Forgot to mention it does not track the pages read when this happens.

**Comment by Jays2Kings** [comment]
add more details to this:
Crash logs,
Manga/Chapter/Source
recording of this crash

**Comment by Jays2Kings** [comment]
closing this since this is stale, comment back if its still happening
