### ISSUE TITLE
multiple download folders

### ISSUE THREAD

**Issue by alexis4** [Jays2Kings/tachiyomiJ2K#1363]
### Steps to reproduce

sources get multiple download folders when downloading manga example mangahub then another mangahub (1)  and then mangahub (2) and so on not sure what caused it.
had to check my files directory directly to find out and sometimes it causes an invalid download directory error but not always

in case it helps i am using a samsung galaxy s20fe android 12 and have downloads set to custom folder created on micro sd card. i prefer tachiyomij2k but because of this issue i use normal version with does not have this problem

### Expected behavior

a way to fix it if its a setting or hopfully you can patch it in an update

### Actual behavior

sources get multiple download folders when downloading manga example mangahub then another mangahub (1)  and then mangahub (2) and so on not sure what caused it.
had to check my files directory directly to find out and sometimes it causes an invalid download directory error but not always

### TachiyomiJ2K version

1.5.6

### Android version

12

### Device

samsung galaxy s20fe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Rename the download folder from "Mangahub" to "MangaHub"
