### ISSUE TITLE
Duplicate manga, poor discription and update helper.

### ISSUE THREAD

**Issue by dh1ll0n** [Jays2Kings/tachiyomiJ2K#1367]
### Describe your suggested feature

There are 3 issues I have with tachiyomi.
1. Sometimes I end up with duplicate manga in my library. They are either of same name from different sources or different name in a single/multiple source. Like manga park with eng/jap names.
2. The discription of manga in some sources is messed up or not present. With very poor quality of thumbnails.
3. Sometimes I have a manga that is being updated on another source but not my source like mangadex or mangasee. Or manga is cancelled, droped, etc

Now my solution is simple. Like adding a ability to see the bookmarked manga with some details from a site like baka update.
When you open your bookmarked manga you will see a small box with discription from baka updates and the status of manga in baka update. Like discription and published/ translation status of manga.

Now since baka update also holds all the name of a manga ints discription you could also see if you have duplicate manga.

I know it sounds easy said then done but it's a feature that will help alot in keeping track.

I could add  some ui pics that I could design on Photoshop to help you under stand better if someone will try adding this feature.

Sorry if I did something wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
There isn't an easy way to get the manga details from any of the tracking sites when sources are all different not just in descriptions but also the name of the manga, so this isn't really possible.

You can manually go to manga updates and add in the description yourself
