### ISSUE TITLE
Select multiple non-sequential chapters

### ISSUE THREAD

**Issue by cole-h** [Jays2Kings/tachiyomiJ2K#1371]
### Describe your suggested feature

I would like to be able to select multiple disparate chapters (and not the chapters between them) and mark them as read / mark them for download.

Right now (as far as I can tell), the only options are "mark all below this chapter as (un)read" and "mark this range of chapters as (un)read". However, if I wanted to mark all chapters except for a certain few (e.g. reading from MangaDex and there is a scanlator I prefer, and others also competing for the same chapter, I would like to be able to mark the non-preferred-scanlator chapters as read so they are skipped when binge-reading), I have to use the swipe gesture on them all individually.

I've already read https://github.com/Jays2Kings/tachiyomiJ2K/issues/319 and related issues and I don't think this overlaps with those, because (to the best of my comprehension) those are asking for the current range-based operations we have, while I am asking for the ability to select chapters out of order (e.g. if I wanted to download / mark as read chapters 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 22.5, etc.; there's no way to batch the operations).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by cole-h** [comment]
Sure, that works, but it would be very nice for highly-contentious manga on e.g. MangaDex, where there are duplicate chapters uploaded by a multitude of groups. With this feature, I'd be able to quickly select all the chapters by groups A, B, and C, but not D, and mark them as read instead of having to swipe chapters (especially since I seem physically incapable of swiping straight across most times and instead end up scrolling the view :sweat_smile: ).

That said, I can appreciate you not wanting to implement this. Hopefully, my example is enough to convince you that this would be valuable, but otherwise, I can certainly make do with the current functionality. Thanks for all your work on this app, regardless!

**Comment by Jays2Kings** [comment]
You can also filter out scan groups so there's even more of a reason not to go about this

**Comment by cole-h** [comment]
Oh, I didn't know there was a way to filter out scan groups per-manga. Good to know, I'll give that a shot.
