### ISSUE TITLE
Option to let us hide source name from manga screen

### ISSUE THREAD

**Issue by Xorio71** [Jays2Kings/tachiyomiJ2K#1373]
### Describe your suggested feature

The toggle could be an option in the library display settings, and it would basically hide the source name that is displayed beneath the manga status.

### Other details

Nothing much.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
this seems too niche of a setting to add, it changes far too little to add

**Comment by Xorio71** [comment]
True. It's only for design-obsessed nerds like me.
