### ISSUE TITLE
Let us specify the Global Update time-frame

### ISSUE THREAD

**Issue by Xorio71** [Jays2Kings/tachiyomiJ2K#1374]
### Describe your suggested feature

In the 'Library' section of the Settings, there could be an option that would let us pick when Tachi should start updating manga.

### Other details

Nothing much.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Android doesn't work this way, as it would requires more permissions and would be a serious battery killer. The time you change the library global update setting is when it will run again, as in if you set 12 hours at 3PM, it run around 3AM then 3PM etc

**Comment by Xorio71** [comment]
Okay, I see. Thanks for the clarification.
