### ISSUE TITLE
Ability to edit the user agent string

### ISSUE THREAD

**Issue by asdkant** [Jays2Kings/tachiyomiJ2K#1381]
### Describe your suggested feature

I'm facing an issue of an extension not passing the cloudflare validation. One workaround suggested in the GH issue was to change the user agent string, but I can't seem to find the setting in TachiyomiJ2K
(I'm assuming this functionality is present in regular Tachiyomi since this was suggested in the context of an issue of a tachiyomi extension)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
> If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.

This is already in for next release
