### ISSUE TITLE
Add borders to page

### ISSUE THREAD

**Issue by NikSeah** [Jays2Kings/tachiyomiJ2K#1384]
### Describe your suggested feature

I'm using this app with surface duo.

With the auto crop function, the size is great and I can read the text perfectly. However on dual pages, some text is cut off by the hinge of the device in the middle. Without cropping, the text is too small.

Hopefully, you can add a simple function where I can add borders to the page after cropping it. If you can make the app 'hinge-aware' that'll be even better. Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.7](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by chrishunt93** [comment]
I just wanted to second this feature. If the interior border between two pages (or in the middle of a double spread) could be specified by pixel count, that would be great. Thank you.

**Comment by mkmonkey** [comment]
Good day , I'm a surface duo user as well .
For the double page issue , it is pity that the missing pixel in the gap causing the issue .
Besides the adding border / setting the double page pixel size limit , 
I would also like to suggest to anchor the image starting position to the upper left and right corner .

Currently the image is trying to line up both left and right image and eliminate the gap between two image .
However , such great idea will get the worse result in surface duo . 
Instead , if separate the image will have the best viewing result in surface duo .
So hope that the app will allow user to select the starting position of each image in double page view , thank you .
