### ISSUE TITLE
add Chapter page previews

### ISSUE THREAD

**Issue by BigDogg99** [Jays2Kings/tachiyomiJ2K#1390]
### Describe your suggested feature

as tittle say add Chapter page previews it will help preview an entire chapter, with each page being a small thumbnail.

### Other details

kotatsu have this feature and it really helps 
![Screenshot_20220821-120047_Kotatsu](https://user-images.githubusercontent.com/109841554/185949615-90d63871-d308-42f0-9d53-84fa43af9075.png)
!
![Screenshot_20220821-120058_Kotatsu](https://user-images.githubusercontent.com/109841554/185949782-ff56c0b4-cb0b-4732-baf4-58618fa71e2b.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.7](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/1245
