### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by y314315** [Jays2Kings/tachiyomiJ2K#1394]
### Describe your suggested feature

Hello，Jays2Kings .The taciyomi you developed has helped me a lot, but there are still some problems that plague me. When I merge two pages of manga into one for reading, they often don't merge properly, as shown in the attachment. I hope this problem is solved soon, you may be able to solve this problem by adding a blank page before the first page, or leaving the first page alone. Thanks for your efforts.
![image](https://user-images.githubusercontent.com/110112440/186132174-8348dbf8-e35f-45fd-8ead-025c34bcd320.png)
what i want to see
![image](https://user-images.githubusercontent.com/110112440/186132688-1f6e9de2-372d-41c6-9dfa-590e11438d90.png)
![image](https://user-images.githubusercontent.com/110112440/186132868-45843308-2e15-43db-8c19-6a304819e46a.png)
what i actually see

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.8](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by nzoba** [comment]
You can already change which pages are attached by clicking the top right button in the reader `Shift one page over`
