### ISSUE TITLE
Can't delete downloaded chapters

### ISSUE THREAD

**Issue by MindFlayeR57** [Jays2Kings/tachiyomiJ2K#1395]
### Steps to reproduce

1 Delete a downloaded chapter
2 close the app
3 open the app again
4 chapter is still downloaded

### Expected behavior

The chapter stays deleted

### Actual behavior

The chapter doesn't stay deleted

### TachiyomiJ2K version

1.5.8

### Android version

Android 10

### Device

Lenovo TB-X605FC

### Other details

I have it set to automatically delete chapters I've read but neither that nor manually deleting them works.

The "remove downloads" > "all read chapters" button at the 3 dot menu seems to partially work, deleting a single random chapter of the ones I've read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.8](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by KazKaz90** [comment]
Need a hotfix for this asap

**Comment by KazKaz90** [comment]
Wait, I just realized why you can't delete chapters, now j2k is downloading chapters without the `_` *underscore* at the beginning of each downloaded chapter, whereas previously it had the `_` *underscore but it changed. That is why it is not being deleted.

**Comment by MindFlayeR57** [comment]
> Wait, I just realized why you can't delete chapters, now j2k is downloading chapters without the `_` *underscore* at the beginning of each downloaded chapter, whereas previously it had the `_` *underscore but it changed. That is why it is not being deleted.

Yep, tested it and looks like you are correct.

**Comment by Saud-97** [comment]
> Wait, I just realized why you can't delete chapters, now j2k is downloading chapters without the `_` _underscore_ at the beginning of each downloaded chapter, whereas previously it had the `_` *underscore but it changed. That is why it is not being deleted.

yeah I figured it must be something went unnoticed lol. Because some downloads can be deleted and some can't.

**Comment by Jays2Kings** [comment]
Fixed in c458f276a0b47664b72ccb89cc3fcf544f341787
