### ISSUE TITLE
It's bugging me.

### ISSUE THREAD

**Issue by AefRal** [Jays2Kings/tachiyomiJ2K#1396]
### Describe your suggested feature

![Screenshot_20220824_000643](https://user-images.githubusercontent.com/68062495/186344034-28a0b703-ef6d-48cf-a456-03a59aa5637b.jpg)
![Screenshot_20220824_001009](https://user-images.githubusercontent.com/68062495/186344056-bd9baa4f-c825-46cf-af7d-6340b8ae29ba.jpg)

### Other details

Great job on the 'update all' button though.
Much easier now.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.8](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by nzoba** [comment]
1. Explore the app, you may find a magical setting
2. Read the release notes

**Comment by AefRal** [comment]
Guess I missed that update. Lol thanks.

**Comment by Saud-97** [comment]
Then close the issue if its resolved.
