### ISSUE TITLE
Clean up downloaded chapters deleted unread

### ISSUE THREAD

**Issue by MrChuw** [Jays2Kings/tachiyomiJ2K#1398]
### Steps to reproduce

Just put it to clear the downloads.

### Expected behavior

Delete read chapters, not added to library etc.

### Actual behavior

Delete read and unread chapters, not added to the library, etc.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/9420301/tachiyomi_crash_logs.txt)

I don't think there will be anything, but it's there.

### TachiyomiJ2K version

1.5.8

### Android version

Android 10

### Device

Poco M3

### Other details

Puts not to delete bookmark chapters, or the option to choose whether or not to delete.

I was forgetting, apparently with few mangas in the library the bug doesn't happen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.8](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
should be fixed with https://github.com/Jays2Kings/tachiyomiJ2K/issues/1395
