### ISSUE TITLE
Disable automatic Tracker selection 

### ISSUE THREAD

**Issue by senkneel** [Jays2Kings/tachiyomiJ2K#1404]
### Describe your suggested feature

Add option to disable the tracker automatically picking the only thing he finds in his service.

Or just disable it.

### Other details

Right now I often have the problem, that when I want to enable the AniList Tracker on a relatively new Manga/Manhwa, that maybe is not already on Anilist it finds something else and just selects it because it's the only thing it finds. It often creates the problem of having to delete the activity and so on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.8](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
You can just remove it if it tracks wrong. It shouldn't be occurring that often

**Comment by Jays2Kings** [comment]
if it selects wrong you can remove it from anilist from the cross button, if it gets it wrong you can tap it again, manually search for what you want and it will replace it (ie remove the old from anilist)

So no need for it really

**Comment by garvongithub** [comment]
Please consider this, as someone who reads a lot of one shots and other webcomic on mangadex, this happens many times and also selects nsfw manga sending it to anilist feed. I wouldn't want my friends to see those stuff, which I didn't even read
