### ISSUE TITLE
Stats Page Improper Tracking of Read Duration

### ISSUE THREAD

**Issue by SunBreaker1** [Jays2Kings/tachiyomiJ2K#1413]
### Steps to reproduce

1. Spend time reading a manga series (ex 1hr)
2. Check stats page, Read Duration should have increased by 1hr
3. Clear manga series from history
4. Check stats page, that 1hr from before will have been removed from the total.
5. Re-adding the manga series briefly will not refresh the stats page and return that 1hr time spent reading

### Expected behavior

No matter what Read Duration (time spent reading) should stay persistent even if the series has been removed from the history.
I.e the same way steam remembers hours spent playing even if the game gets un-installed, the hours remain persistent

### Actual behavior

Every time a manga series is removed from the history, Read Duration time is reduced by the time spent reading that series.

### TachiyomiJ2K version

1.5.9

### Android version

Android 12

### Device

Samsung S10e

### Other details

Just as a little extra for the long time users who like keeping track of stats (myself included), maybe add a edit button for Read Duration to more accurately adjust actual time spent reading since first using this app since the stats page is very inaccurate.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by nzoba** [comment]
Won't happen at least for the details. The read duration time is based on the history, why would you remove a manga from history if you want stats about it ?
Removing from history is like saying it never happened. If you uninstall a game you are not removing it from history, you just can't use it anymore
I guess it would be possible to keep it for the read duration total but the problem would be when you do a backup

**Comment by SunBreaker1** [comment]
> Won't happen at least for the details. The read duration time is based on the history, why would you remove a manga from history if you want stats about it ?
> Removing from history is like saying it never happened. If you uninstall a game you are not removing it from history, you just can't use it anymore
> I guess it would be possible to keep it for the read duration total but the problem would be when you do a backup

Guess it actually makes sense when you put it that way, but like my browsing history, I like to keep it clean. Guess it part of the feature, and not a bug. Thnx for clarifying.
