### ISSUE TITLE
Crop setting gets reset if rapidly switching between continuous and webtoon in the same series

### ISSUE THREAD

**Issue by jferdous70** [Jays2Kings/tachiyomiJ2K#1416]
### Describe your suggested feature

~~A separate crop border for continuous vertical reader mode doesn't exist for TachiJ2K. To use crop border, I need to turn it on for webtoon mode.~~

~~However, I use continuous vertical only for paged manga, and not for webtoons (as crop border works badly with webtoons). This forces me to turn on/off crop border per manga/webtoon manually.~~

~~Thus, a separate setting would be very appreciated and would enhance the reading experience.~~

Crop setting gets reset if rapidly switching between continuous and webtoon in the same series
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
This is already the case, crop border for continuous vertical isnt tied to webtoon mode, its tied to the other paginated reader modes.

There is a bug if youre rapidly switching between continuous and webtoon in the same series that the crop setting gets reset but aside from that, its working as intended.

I'll keep this open to fix that bug but theres no feature to add here

**Comment by jferdous70** [comment]
oh ok, thanks for the information

**Comment by jferdous70** [comment]
Thank you for the information, i rename the issue title
