### ISSUE TITLE
Add an "Open in Neko" button

### ISSUE THREAD

**Issue by Raidou13** [Jays2Kings/tachiyomiJ2K#1419]
### Describe your suggested feature

I dunno if this is complicated, but i think it is because it needs 2 separate apps to communicate with each other and it need Neko's devs to cooperate.

Add an option or a button somewhere in the Series Title screen to open the Series in Neko, and/or Search the Series in Neko Browser

### Other details

Is this even possible? I'd like to transfer mangadex stuff to neko, and quickly search what I'm currently reading if it's available in MD.

And yeah Mangadex is also currently not working in J2K. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [x] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
You can just try to migrate the manga to the  mangadex extension.  Then if you migrate some, backup in j2k and restore in neko
