### ISSUE TITLE
Refresh button on main library page

### ISSUE THREAD

**Issue by Light-Wing** [Jays2Kings/tachiyomiJ2K#142]
**App version:** latest .91

**Android version:** 10

**Issue/Request:** library 3 dots refresh button

**Other details:** there used to be a refresh button on the main library page, which would refresh all manga on demands, and now that button is gone

**Comment by joseph619** [comment]
There is still pull down to refresh, so refresh button is unnecessary.

**Comment by Light-Wing** [comment]
the thing is I use it to refresh a few tabs together, I have my comics and
most read manga in different tabs, and I like to refresh them at the
same time...

as such I think its actually still very useful... right now I'm going to
the library updates page every time I want to do that update... then I go
back to the library page to better visualize what I want to read at what
time...

**Comment by Jays2Kings** [comment]
You can pull to refresh categories and you can update via recent updates, it was a button repeating functions that exist other places

**Comment by Light-Wing** [comment]
alright, np, I'll tru to add it back to a custom version for myself, thanks
for the reply, it was one of those things I used a lot in the app... maybe
I'll move to the auto update function🧐

**Comment by joseph619** [comment]
Close the issue if it's answered @Light-Wing
