### ISSUE TITLE
Sync latest episode in recents view

### ISSUE THREAD

**Issue by GanderwaD** [Jays2Kings/tachiyomiJ2K#1421]
### Steps to reproduce

In recents screen when you tap the photo if the item app routes to details and all episodes page of selected item

### Expected behavior

When app routes to details page of selected item from recent page with items photo, episodes is not in the latest state. I mean by that is episodes list are not fetching the new list items for the latest episodes

### Actual behavior

When app routes to details page of selected item from recent page with items photo episodes is not in the latest state. I mean by that is episodes list are not fetching the new list items for the latest episodes

### TachiyomiJ2K version

"v1.5.9"

### Android version

11

### Device

Samsung galaxy a70

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by GanderwaD** [comment]
I can be a clown that not read when I need to

**Comment by Jays2Kings** [comment]
The translator you're using for English isn't great being honest so I don't understand what you're saying. Can you record a video of the problem?

**Comment by GanderwaD** [comment]
Basicly what I'm saying is when I open manga's details page from recent tab, episodes are not fetched automaticlly, for fetching latest episodes you need to refresh the page

**Comment by CarlosEsco** [comment]
thats by design

**Comment by Jays2Kings** [comment]
Yup that's not a bug, that's intentional to prevent overloading sources, so it's not going to change
