### ISSUE TITLE
Auto Update Library after opening app

### ISSUE THREAD

**Issue by mish20011** [Jays2Kings/tachiyomiJ2K#1424]
### Describe your suggested feature

Whenever I open TachiyomiJ2K I always have to manually update libraries because options are only Update automatically every 12 hours.

Everytime I wake up it has always been my go to that I open Tachiyomi, but it sucks that It doesn't automatically update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
1.  This is just another way to ddos sites
2.  Setting 12 hours will have it run roughly every 12hrs from when you set it.  So if you wake up at 7am, set the 12 library update at 6:30pm.  Then you will get updates before you wake up.
