### ISSUE TITLE
Add Feed tab for Sources

### ISSUE THREAD

**Issue by mish20011** [Jays2Kings/tachiyomiJ2K#1425]
### Describe your suggested feature

Basically Show a Feed Tab for every source added to it so I can see Previews of new chapters from those said sources (Feature in TachiyomiSY)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Sy has feed tab because it has saved searches.  Which this app does not.  So without a major rework to adding that, feeds won't be added either.
