### ISSUE TITLE
Download Next 5 Chapters button not showing

### ISSUE THREAD

**Issue by senkneel** [Jays2Kings/tachiyomiJ2K#1428]
### Steps to reproduce

1. System language on German and tachiyomi also on German
2. Click on the three dots when on a manga
3. Button has no text

### Expected behavior

The should be text in the download "Next 5 Chapters" button.

### Actual behavior

The text isn't there. But it still works as intended.
I think the text is in the box above.

![Screenshot_20220924-144737~2](https://user-images.githubusercontent.com/102804833/192098948-59f7b454-cafc-4e37-9573-98f1d2d5b3f7.jpg)

### TachiyomiJ2K version

1.5.9

### Android version

Android 11

### Device

OnePlus 8 Pro

### Other details

I don't know if it's only in German but it's the language I use so I only found it here. I checked that in English is normal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
it was missed by translators, should be fixed for next version
