### ISSUE TITLE
[Feature Request] use external image as cover of manga. feature used to exist.

### ISSUE THREAD

**Issue by harishts1998** [Jays2Kings/tachiyomiJ2K#144]
### Why/User Benefit/User Problem
(explain why this feature should be added)

### What/Requirements
(explain how this feature would behave)

**Comment by joseph619** [comment]
Feature still exists. You click on the pencil icon on INFO page and click on the cover image.

**Comment by harishts1998** [comment]
> Feature still exists. You click on the pencil icon on INFO page and click on the cover image.

I don't see info page. Where exactly is it?

**Comment by harishts1998** [comment]
> Feature still exists. You click on the pencil icon on INFO page and click on the cover image.

Got it.
