### ISSUE TITLE
App crashes and can't be used after changing the Default user agent string

### ISSUE THREAD

**Issue by kyr654** [Jays2Kings/tachiyomiJ2K#1448]
### Steps to reproduce

1. Changed the user string to "Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/8.0.8 Chrome/75.0.3770.89 Mobile Safari/537.36"
2. Restarted the app as instructed
3. Shows the TJ2K screen for a split second, then instantly crashes

### Expected behavior

Shouldn't crash

### Actual behavior

App crashes every time It is opened

### TachiyomiJ2K version

1.5.9

### Android version

Android 10

### Device

Samsung S9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Traxis** [comment]
Same issue happened to me, and now I can't use the app at all. I don't really want to delete all the app data to reset, I hope there is a solution for this.

**Comment by Jays2Kings** [comment]
fixed with fe243adb8
