### ISSUE TITLE
The library option in the "Starting scree" is accurate to the category.

### ISSUE THREAD

**Issue by 146254** [Jays2Kings/tachiyomiJ2K#1454]
### Describe your suggested feature

The library option in the "Starting scree" is accurate to the category. It could avoid some embarrassing occurrence. Or add a Hidden Category feature, it also works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Hidden Category has been requested and rejected. you can set your starting screen to recents or collaspe the category before exiting if you're that embarrassed
