### ISSUE TITLE
Can't install extensions 

### ISSUE THREAD

**Issue by poseidap** [Jays2Kings/tachiyomiJ2K#1455]
### Steps to reproduce

1, can't download extensions
2. slow load when installing the extensions

### Expected behavior

When i download the extension, and i just read some manga and done...

### Actual behavior

I already turn off the MIUI Optimizations, but when i download the extensions, it just stop and didn't progress the download

### TachiyomiJ2K version

1.5.9

### Android version

Android 8.1.0

### Device

Xiaomi Redmi 5A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
#918
