### ISSUE TITLE
Mangadex / Batoto extension disappeared

### ISSUE THREAD

**Issue by DinJerr** [Jays2Kings/tachiyomiJ2K#1457]
### Steps to reproduce

1. Opening manga in the **Library** says extension not installed.
2. Searching the extensions in the **Browse** tab shows they both mangadex and batoto missing entirely from the extensions choice.

### Expected behavior

You can browse Batoto and Mangadex as normal like the main Tachiyomi app.

### Actual behavior

Unable to even install Batoto and Mangadex extensions at all now.

### TachiyomiJ2K version

1.5.9

### Android version

Android 10

### Device

OnePlus 5T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
because you turned off 18+ sources in settings
