### ISSUE TITLE
Ignore Library Grouping And Search Entire Library When Using Search

### ISSUE THREAD

**Issue by zinklog2** [Jays2Kings/tachiyomiJ2K#1459]
### Describe your suggested feature

Because I have so many categories I have to manually ungroup library before searching to make sure it is not in my library. A setting to always search the entire library would be nice.
Alternatively it would be even better if the results of different categories are displayed on a single page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
when you search in the library, theres 2 arrows beside the ✖ in the search bar, use that to show all categories while searching
