### ISSUE TITLE
Komga extension not downloading covers, also unable to set custom covers (works OK in main branch Tachiyomi)

### ISSUE THREAD

**Issue by roseyhead** [Jays2Kings/tachiyomiJ2K#1460]
### Steps to reproduce

Simple to reproduce:
1: Browse > tap Komga extension
-all manga show a broken image icon
2: select a manga marked as "In Library" 
-cover is blank
3: select Menu > Edit
4: select a new cover (preview displays it OK), hit Save
-edit menu closes out, cover still blank

### Expected behavior

All covers visible in extension
Cover should correctly save when edited

### Actual behavior

No cover images visible
Cover doesn't update when manually edited

### TachiyomiJ2K version

1.5.9

### Android version

Android 12

### Device

Samsung Fold 4

### Other details

In mainline Tachiyomi viewing and editing covers works fine, and given that that's the case I'm making a ticket here rather than the Extensions repo (since the extension itself seems okay). I can also view and edit covers for other extensions in J2K. It's only this extension that's not doing what I'd expect. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by roseyhead** [comment]
I should add, I fixed the issue by deleting everything from that extension, backing up my settings, clearing data for J2K and restoring the backup. Covers are downloading and i can edit them normally. Must be some bad data that doesn't survive the backup and restore?

**Comment by Jays2Kings** [comment]
no sure but since its resolved im closing this
