### ISSUE TITLE
安卓平板,小窗模式打开app,阅读页,点击异常

### ISSUE THREAD

**Issue by s949492225** [Jays2Kings/tachiyomiJ2K#1462]
### Steps to reproduce

安卓平板,小窗模式打开app,阅读页,点击异常,

先全屏打开APP,然后切换到app至小窗模式,打开任意漫画阅读页,即可稳定复现

出现此处bug的原因是,切换到小窗模式下,window的宽高发生了变化,
但是代码里的点击坐标未更新,还是按照全屏下的匹配,所以导致点击失效

### Expected behavior

点击中间,菜单能正常弹出
点击上方能滑到上一页
点击下放能滑到下一页

### Actual behavior

上下页点击无效

### TachiyomiJ2K version

全部版本

### Android version

全部版本

### Device

三星 tab,小米tab,华为tab

### Other details

先全屏打开APP,然后切换到app至小窗模式,打开任意

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
open this one again in english thanks
