### ISSUE TITLE
Google sign in in web view

### ISSUE THREAD

**Issue by sinnghabhay80** [Jays2Kings/tachiyomiJ2K#1463]
### Steps to reproduce

Open tappytoon extension
Go to log in
Log in with Google 

### Expected behavior

It should open window for Google account signin

### Actual behavior

It does nothing

### TachiyomiJ2K version

1.5.9

### Android version

Android 11

### Device

Realme X

### Other details

The expected behaviour happens in tachiyomi and normal browsers 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by sinnghabhay80** [comment]
Damn, I guess I am a 🤡

**Comment by sinnghabhay80** [comment]
Though the problem is genuine

**Comment by Jays2Kings** [comment]
you are a 🤡 because it also does not work in regular tachiyomi too

**Comment by sinnghabhay80** [comment]
Nope it was working, until it didn't, then I had opened a issue regarding it in the regular tachiyomi repo as well.
