### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by NopalOls** [Jays2Kings/tachiyomiJ2K#1469]
### Steps to reproduce

when I read the manhwa why does the page display always load, even though my signal is normal, I've tried opening other applications such as YouTube and the results are normal, but when I try reading always lags, why is this please?

### Expected behavior

When I read

### Actual behavior

Suddenly

### TachiyomiJ2K version

1.6.0

### Android version

Android 11

### Device

Xiaomi redmi note 10s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
🤡
