### ISSUE TITLE
Chapter list not updating

### ISSUE THREAD

**Issue by deidouji** [Jays2Kings/tachiyomiJ2K#147]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: Samsung a8, android 9

## Steps to reproduce
1. Update Library (optional)
2. Open any manga's chapter list

### Expected behavior
Should show latest chapters

### Actual behavior
Doesn't show latest chapters until refresh chapter list, and not update library

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
That's how tachiyomi works.  It won't refresh unless a manual refresh is triggered or an automated library update is.

**Comment by deidouji** [comment]
Don't think I really explained it well, even after an automated library update or manual, the chapter list wont update unless I open the specific manga and update it. Manga outside of library also don't show the latest chapter compared to stable, where it automatically refreshes and shows the latest chapter.

**Comment by Jays2Kings** [comment]
I can tell you for a fact that both stable and update do not update the chapters not I'm library if they were fetched before

Are you sure the library update is working? Are you getting a notification saying there's new chapters? Can you see in the updating notification the manga you're having an issue with?

**Comment by deidouji** [comment]
Yeah it didn't send a notification that there were new chapters, and I had to manually update the chapter list.

**Comment by joseph619** [comment]
Did you set Library update frequency in Settings >Librar ? Seems like it's set to manual.

**Comment by deidouji** [comment]
You misunderstand, even with the Library update frequency set to hourly, for some manga I still have to go to their individual chapter list and update it that way.

**Comment by Jays2Kings** [comment]
This was been fixed by 0.9.82
