### ISSUE TITLE
Add Allow deleting bookmarked chapters from Stable Tachiyomi 

### ISSUE THREAD

**Issue by jferdous70** [Jays2Kings/tachiyomiJ2K#1470]
### Describe your suggested feature

In download setting, add the feature that already exist in main tachiyomi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
![Screenshot_20230212_182740_Tachiyomi](https://user-images.githubusercontent.com/83420659/218343692-c5a962f9-fa6c-4c8f-b1f8-9caf33ea5993.jpg)

Helps with preserving bookmarked downloads when "Removed when marked as read" is enabled 

@Jays2Kings

**Comment by Kiraonly** [comment]
Unsubscribe
