### ISSUE TITLE
Biometric lock not working

### ISSUE THREAD

**Issue by Tachi44d** [Jays2Kings/tachiyomiJ2K#1472]
### Steps to reproduce

1. open app
2. biometric lock works
3. open a manga to read
4. go out of the manga but still in the source
5. exit out of app
6. reopen the app
7. biometric lock doesn't work

### Expected behavior

On step 7 the biometric lock should show up.

### Actual behavior

On step 7 you can enter the app without any security.

### TachiyomiJ2K version

1.6.0

### Android version

android 13

### Device

Samsung galaxy a71

### Other details

It's not a problem on main tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by violetclearspark** [comment]
I tried enabling destroy apps after users leaves, and even then the biometric does not work.
