### ISSUE TITLE
Clicking button to hide keyboard removes search query

### ISSUE THREAD

**Issue by Viren070** [Jays2Kings/tachiyomiJ2K#1473]
### Steps to reproduce

1. Search anything while on the library tab
2. Press the button to hide the keyboard in the bottom right 

### Expected behavior

1. What i searched should remain and i can scroll through the results of my search

### Actual behavior

What i searched disappears and it returns to the main library page showing all my mangas/manhwa/manhua.

### TachiyomiJ2K version

1.6.0

### Android version

Android 13

### Device

Samsung Galaxy A52s 5G

### Other details

https://user-images.githubusercontent.com/71220264/208402403-1eb51ffb-a70c-4e9b-8c57-86908209c016.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Tachi44d** [comment]
I think this may be a problem with android 13, I had this problem too after updating my OS. It happened on the previous version as well as v1.6.0.
