### ISSUE TITLE
Chapter transitions (Black bars)

### ISSUE THREAD

**Issue by SaneZer0** [Jays2Kings/tachiyomiJ2K#1474]
### Describe your suggested feature
(previous chapter & next chapter)
For long chapters it isn't really much of an issue but when it comes pages <10 chapters kinda gets annoying. If not, make the transition black box smaller or an option for different sizes because current I believe the boxes are on the thicc side.

Also if you can treat paged <10 chapters like 1 big chapter as there isn't an option to preload chapters makes reading 1 paged chapters much more smoother.

E.G:
https://isekaiscan.com/manga/the-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-girl-getting-less-and-less-tsun-day-by-day/

Or I'm just blind and can't see the option to change it💀

![Screenshot_20221219-115636](https://user-images.githubusercontent.com/65837094/208421137-cc9cce1c-3fa0-45f9-b81d-205779fc3243.png)

### Other details

App version: 1.6.0 (standard, 6cb319244, 98, 2022-12-17T21:46Z)
Android version: 13 (SDK 33)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by SaneZer0** [comment]
I believe the best solution will be making the black box smaller or a custom size as that it won't effect long striped 1 paged chapters*

**Comment by Jays2Kings** [comment]
You can either turn them off or live with the current size. This is too niche of a request to implement and just adds complexity to an already large amount of settings
