### ISSUE TITLE
slow donwload only on tachi-j2k

### ISSUE THREAD

**Issue by nio04** [Jays2Kings/tachiyomiJ2K#1476]
### Steps to reproduce

i tried download 'blue lock' manga on 'neko -fork'. its downloaded 1-5MBps from 'mangaDex extension' (mangDex is auto for 'neko', right?)

then stoped download on that application and came back to j2k (v1.6.0 -armv7) downlaoded same manga from same extension (mangaDex). and now download speed is, maximum 288kbps 🙄

to be honest, after writting the above line... i re-installed 'neko' and did the same thing again... (same manga downloading) download speed is 1-7MMBps....😂

[edit] i also tried 'tachiAZ -fork' and its max download speed is 1.16MBps minimum is somewhere near 388kbps

why am i getting throttle here?

to simply solve my issue, i just need to switch to 'neko' now... but i like tachi-j2k. plz give me a proper explain, why this happen.... can i solve it anyhow?

### Expected behavior

download speed should be above 300kbps 

### Actual behavior

getting download speed throttle (max - 288kbps)

### TachiyomiJ2K version

"1.6.0"

### Android version

"Android 10"

### Device

xiaomi redmi 9c (angelica)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Entirely depends on what mangadex at home node you hit. So hard to compare. Also Neko uses a few more threads to download more then a couple images at a time.

**Comment by nio04** [comment]
> Entirely depends on what mangadex at home node you hit. So hard to compare. Also Neko uses a few more threads to download more then a couple images at a time.

@CarlosEsco so, is there no way to solve the download speed throtttle issue?

**Comment by CarlosEsco** [comment]
It's not throttled
