### ISSUE TITLE
Add Maximum Backup settings from Main Tachiyomi

### ISSUE THREAD

**Issue by ikusuba** [Jays2Kings/tachiyomiJ2K#1477]
### Describe your suggested feature

It's very useful when using automatic backup. That'll deleting older backup automatically.

### Other details

![Screenshot_2022-12-21-04-28-00-709_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/73406832/208770313-fb95b5da-fd3f-4ee8-ad80-9322cf739829.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
It's already there.
It's always been there.
Certified 🤡 moment

**Comment by ikusuba** [comment]
Sorry I turned off automatic backup and yes the settings is lost, and I don't turn to automatic to check 😅
