### ISSUE TITLE
Surface Duo Won't load .cbr in dual screen

### ISSUE THREAD

**Issue by RyanWoirol** [Jays2Kings/tachiyomiJ2K#1478]
### Steps to reproduce

Saw that the app updated to support the Duo, so I downloaded it to try.  I uploaded a few of my .cbr files to read and they will not load in double pages mode.  The only way they load is if I put it in single page mode.  

### Expected behavior

Should open 2 pages, one on each screen

### Actual behavior

I get a loading animations and nothing loads.  But if I put it in single page mode, then it loads right away.

### TachiyomiJ2K version

1.6.0

### Android version

Android 12L

### Device

Microsoft Surface Duo 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
You'll have to provide the cbr used, you can send me on discord if you don't feel comfortable here, but my guess is the cbr doesn't have usable images in double page mode

**Comment by RyanWoirol** [comment]
> You'll have to provide the cbr used, you can send me on discord if you don't feel comfortable here, but my guess is the cbr doesn't have usable images in double page mode

It's just an Indiana Jones comic, but I vang send to you on discord, where should I send it?

**Comment by Jays2Kings** [comment]
Send it to jay#3176

**Comment by RyanWoirol** [comment]
> Send it to jay#3176

It says Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends.

**Comment by Jays2Kings** [comment]
Yes add me as a friend

**Comment by RyanWoirol** [comment]
I just sent you a request, from RyeWoah#3640

**Comment by Jays2Kings** [comment]
This issue is mostly fixed but will happen again if you go from single side of the duo to both screens. This is just an issue with RAR/CBR that even main tachiyomi has when you resize the app. The real fix is to convert these files to cbz/zip
