### ISSUE TITLE
[Feature Request] Notify when a manga update fails

### ISSUE THREAD

**Issue by DuccinatorAlpha** [Jays2Kings/tachiyomiJ2K#149]
### Why/User Benefit/User Problem
Currently the update service skips silently if a manga wasn't able to update(server error for example), it would be nice to know what mangas and what source was the culprit
### What/Requirements
A log file is generated *if* there is an error and a notification popups, tapping on which, the log file opens. It would be preferable if the log file only contains the errors.

**Comment by Jays2Kings** [comment]
Added in 12b2da9
