### ISSUE TITLE
Optimize for Surface Duo 

### ISSUE THREAD

**Issue by mkmonkey** [Jays2Kings/tachiyomiJ2K#1496]
### Describe your suggested feature

First of all , I have to say Surface duo is a weird machine , it is a folding machine with a large gap .

1. Is it possible to align the pictures to the center , or stick to the side of each screen ?
As you can see , the left and right margin of the two screens are still plenty of space .
The red rectangle is the hinge location of the device and it is not visible by the user .
![No-crop](https://user-images.githubusercontent.com/17672407/214896593-ed2a131e-d327-430b-be21-bbb6f72e9a6f.jpg)

 If crop border is enabled , the result is even more weird .
The picture will be shifted to either side , and the hinge will block even more .
![crop](https://user-images.githubusercontent.com/17672407/214897494-435e1f24-18e3-4cc5-8ad2-8bb7a8e6baac.jpg)

2. If the app is span into two screen , some of the UI will missing the grey color bar .
It will be hard to find the icon if the background is light in color .
![ICON](https://user-images.githubusercontent.com/17672407/214898938-2389e57f-4110-4352-82c0-c9378783965c.jpg)

3. This is not a duo feature request ... is it possible to add a button on each comic for the recent reading chapter ?
Currently if you return to the main UI , and if you didn't remember what is the last chapter you reading , then you have to go to the recent tab to get the information .

4. Is it possible to hide some of the content manually ? For example , I wish to read the ongoing chapter , but sometimes there are some volume in between , if can manually hidden some of the content it will make the reading more fluent .

Thanks very much !

Device : Surface Duo 1
Android version : 12L

Best regards,
Kurz

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
> I have to say Surface duo is a weird machine

This is reason enough why it none of these requests are happening. Its a one of a kind device that microsoft barely supports so why should I?
