### ISSUE TITLE
Automatic enable/disable of reader filter based on scheduled time

### ISSUE THREAD

**Issue by kooper100** [Jays2Kings/tachiyomiJ2K#1497]
### Describe your suggested feature

I think having the option to create a schedule to enable and disable the reader filter based on time of day would be convenient. I frequently use the reader filter with customized colour, brightness and grayscale enabled, but only at night. Having to enable and disable those three settings daily is annoying. Currently I use a shell script to modify the preferences.xml file to do so which works perfectly, however this requires root and my next phone upgrade will most likely not be rootable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
part of the "adding extra logic for the sake of complexity" collection of request. Either use a night light filter/app for your device or continue manually toggling the filter setting

**Comment by kooper100** [comment]
> part of the "adding extra logic for the sake of complexity" collection of request. Either use a night light filter/app for your device or continue manually toggling the filter setting

Just so you're aware, using a night light/filter app for non rooted devices applies an overlay that is absolutely not the same thing as the filter settings in tachiyomi.

I'm not sure what "adding extra logic for the sake of complexity" means, you could consider every feature request that without addressing the actual request, but if that's your decision okay.
