### ISSUE TITLE
[Feature Request] auto scrolling and extension detail

### ISSUE THREAD

**Issue by nimma0001** [Jays2Kings/tachiyomiJ2K#150]
###Why/User Benefit/User Problem
(User won't need to scroll a timer can be added for auto scrolling
Usefully for when u are doing something and want to read manga
And u just don't want to scroll)

### What/Requirements
(A option to enable auto scroll in reading mode 
A timer for scroll/sec)

**Comment by CarlosEsco** [comment]
1 ticket per issue and add more info.

**Comment by nimma0001** [comment]
> 1 ticket per issue and add more info.

Done

**Comment by Jays2Kings** [comment]
Duplicate of #9 check there why it's not getting added
