### ISSUE TITLE
Use `getMangaUrl` and `getChapterUrl` methods in extensions to get the url for "open in webview"

### ISSUE THREAD

**Issue by zhongfly** [Jays2Kings/tachiyomiJ2K#1501]
### Describe your suggested feature

Extensions-lib 1.4 have add those methods to get manga and chapter url.
So we can use `getMangaUrl` and `getChapterUrl` methods to get the url for "open in webview".

### Other details
https://github.com/tachiyomiorg/tachiyomi/commit/de23226591376e998e4ff1ff7b2d4c2a0a805b09
https://github.com/tachiyomiorg/extensions-lib/commit/7be52d2c4c16b4d92effc16cae5054191cd7d238
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/5093e6a5fac3858a13eb2cc62715a788464698ee

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
this was already added, theres just a bug with this and its already been addressed for next release
