### ISSUE TITLE
Missing my extension 

### ISSUE THREAD

**Issue by Staz0271** [Jays2Kings/tachiyomiJ2K#1503]
### Steps to reproduce

Cannot find extension 

### Expected behavior

This app just running smoothly yesterday 

### Actual behavior

The extension suddenly gone

### TachiyomiJ2K version

1.5.9

### Android version

Miui 13.0.2

### Device

Xiaomi note 9s

### Other details

![Screenshot_2023-02-13-19-04-58-047_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/125267504/218443774-03753c44-f365-4088-b72a-85ea91ea6abf.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Welcome to MIUI, where everything is broken for no reason. You might have better luck on the discord support for people with other miui devices or just google why tachij2k can't see other apps

**Comment by Jays2Kings** [comment]
anyway update your app too

**Comment by TyrantZoshi** [comment]
Me Also Theres No Extension to be found 
My device is redmi note 11 pro 5g
