### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by KirigayaCedrick** [Jays2Kings/tachiyomiJ2K#1504]
### Steps to reproduce

1. I download
2. Always load
3. Download didn't start
4. Fix it

### Expected behavior

Happened can't download

### Actual behavior

It took me long to wait but it didn't start

### Crash logs

I already uninstalled the app and redownload the app again if the problem is fix

### TachiyomiJ2K version

V1.6.1

### Android version

10

### Device

Redmi 9C

### Other details

I can't download i mean when i download a chapter its always loading i wait for a few minutes it didn't start not like original tachiyomi if u click "all download" or "download one chapter " it will directly download if u have fast internet but this altenative tachiyomi didn't always loading fix it fast 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to version **[1.6.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [x] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [ ] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
this is a vague ticket but i have to guess this is already fixed for next release
