### ISSUE TITLE
[BUG] New Version Breaking Extensions

### ISSUE THREAD

**Issue by AshbornXS** [Jays2Kings/tachiyomiJ2K#1505]
### Steps to reproduce

1. Install Argos Scan extension (portuguese)
2. Try opening any of the manga they have

### Expected behavior

It should load the pages correctly 

### Actual behavior

Doesn't load the pages, instead giving the "Try again" option that even after clicked doesn't change anything

### TachiyomiJ2K version

1.6.1

### Android version

Android 13

### Device

Xiaomi Redmi Note 8 Pro

### Other details

It's actually a problem with the newer version of J2K, I installed the normal tachiyomi to see and opened normally and downgrading back to 1.6.0 also opens normally, only on 1.6.1 that happens

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
See https://github.com/Jays2Kings/tachiyomiJ2K/issues/1504
