### ISSUE TITLE
Full Changelog URL are not clickable

### ISSUE THREAD

**Issue by amarizky** [Jays2Kings/tachiyomiJ2K#1509]
### Describe your suggested feature

The full changelog URL, at the "New version available!" dialog, should be clickable. Currently the URL are not even blue and clickable.

### Other details

I've got these screenshots for comparison between this version of Tachiyomi and the original Tachiyomi. The original version has this "Open on GitHub" button.

![Screenshot_2023-02-18-15-18-33-22_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/36600028/219852133-3d9d162c-b1b7-439d-ad48-f8755ca59bdb.jpg)

![Screenshot_2023-02-18-16-10-58-59_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/36600028/219852128-9fe5c73d-bf74-4220-9978-c962778b6faf.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
this honestly isnt worth fixing, since thats a link to the commits directly. If this is a request to have a link to the release thats a different request and feature

**Comment by amarizky** [comment]
Understandable. You may close this issue now.
