### ISSUE TITLE
[Feature Request] Auto migration for chapter bookmark

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#151]
### Why/User Benefit/User Problem
Chapter bookmarks don't get migrated during Auto Migration.

### What/Requirements
Auto migration would carry over chapter bookmarks for the manga.

**Comment by specterflare** [comment]
Seconded

**Comment by GreatestFool** [comment]
This is from #671, but it's relevant to the issue so I'll include it here as well for ease of reading.

> Considering the naming conventions between sources, perhaps merely having a config option to enable manual transfer could be a decent solution? For example, it lists the chapters the original has bookmarked and makes suggestions for the new source, and if it is not right, the end user can simply edit it and fix it before the migration.
