### ISSUE TITLE
Auto Detect if manga is Webtoon

### ISSUE THREAD

**Issue by kyoyacchi** [Jays2Kings/tachiyomiJ2K#1512]
### Describe your suggested feature

![Screenshot_20230223-135113](https://user-images.githubusercontent.com/63583961/220886391-8729367e-07bc-41ba-a15f-c6bd1bcf947a.jpg)
This kind of feature would be good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
this already exists

**Comment by Jays2Kings** [comment]
The feature you're showing literally came fron this fork. Certified 🤡 moment

**Comment by kyoyacchi** [comment]
> this already exists

Where is it?

**Comment by kyoyacchi** [comment]
> The feature you're showing literally came fron this fork. Certified 🤡 moment

I didn't know that, sorry, if i'd knew it were come from this fork, i'd not put that ss

**Comment by kyoyacchi** [comment]
@Jays2Kings Can you tell how to enable this feature? I couldn't find it.

**Comment by Jays2Kings** [comment]
It's automatic, a source that exclusively uploads webtoons or has decent tagging to say that it's a webtoon will automatically show as a webtoon. You can tell the reading type by the description on the manga page alone where it says "about this webtoon/manhwa/etc"

**Comment by kyoyacchi** [comment]
> It's automatic, a source that exclusively uploads webtoons or has decent tagging to say that it's a webtoon will automatically show as a webtoon. You can tell the reading type by the description on the manga page alone where it says "about this webtoon/manhwa/etc"

I see.
