### ISSUE TITLE
Bring back per series grouping in the history tab

### ISSUE THREAD

**Issue by OlMuskie** [Jays2Kings/tachiyomiJ2K#1521]
### Describe your suggested feature

In the 1.6.3 Update, The history tab has been grouped per session, not per series like past versions.
This makes the history tab very messy for people that read 1 chapter per day.
The benefit of grouping the history per series is that readers with a gigantic library and a gigantic reading backlog can easily sort and choose between which manga they can read.
With the current format the history tab will look like this
![Screenshot_2023-03-14-11-46-31-169-edit_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/127822269/224927989-7177528f-7c3d-41ba-ad74-fdd11aa4d2a0.jpg)
This is very messy for people like me that has tens of manga backlog but read 1 chapter every few days haha

Hope you implement this <3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by katarai** [comment]
Seconding this feature request, as my history tab is a mess after the update.

I misunderstood this part of the change log to mean we could keep the previous behaviour:
> History and Updates are now grouped together by series and date, with an expandable option to show other chapters that day (Option to ungroup history still exists + option to expand the collapsed chapters by default for both views)

**Comment by RoxTheVile** [comment]
I would also like to request that new history section at least have an option to keep the old layout. I don't like it and it's a pain to navigate since I jump between different manga. I wouldn't have updated knowing this is how it would look.

**Comment by Mizukiu02** [comment]
I second this

**Comment by SunBreaker1** [comment]
I third
