### ISSUE TITLE
Mangabuddy

### ISSUE THREAD

**Issue by D1012** [Jays2Kings/tachiyomiJ2K#1524]
### Steps to reproduce

All manga in mangabuddy having 2 pages only 

### Expected behavior

Should be more than 2pages

### Actual behavior

Only 2 pages are seen

### TachiyomiJ2K version

V. 1.6.4

### Android version

Android 12

### Device

Oppo A17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Sibgeir** [comment]
Would like to add that within webview, all the pages are loaded correctly. The 2 page restriction are only on the app reader.

**Comment by Jays2Kings** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
