### ISSUE TITLE
Reader goes forward 2 pages when navigating using volume keys.

### ISSUE THREAD

**Issue by Kurrode** [Jays2Kings/tachiyomiJ2K#1532]
While reading using volume keys to navigate it will randomly turn 2 pages instead of one.

I don't have inverted volume keys nor turning page animation.

Tried it on multiple extensions.

Version: 
1.6.4

Device:
Xiaomi 11 Lite 5G NE

**Comment by Jays2Kings** [comment]
while this was reported first by you, for some reason you just to skip using the templates and open 2 seperate issues so your issue loses in favor of https://github.com/Jays2Kings/tachiyomiJ2K/issues/1534
