### ISSUE TITLE
Reader goes back to 1st page of the chapter using volume keys navigation

### ISSUE THREAD

**Issue by Kurrode** [Jays2Kings/tachiyomiJ2K#1533]
While reading using volume keys navigation, when going forward 1 page it will return to the first page of the chapter

I don't have inverted volume keys nor turning page animation.

Tried it on multiple extensions.

Version:
1.6.4

Device:
Xiaomi 11 Lite 5G NE

**Comment by Jays2Kings** [comment]
see https://github.com/Jays2Kings/tachiyomiJ2K/issues/1532#issuecomment-1489208713
