### ISSUE TITLE
（从上到下）条漫模式是否可以取消掉过度动画

### ISSUE THREAD

**Issue by kinlaevl** [Jays2Kings/tachiyomiJ2K#1539]
### Describe your suggested feature

像其它模式一样没有翻页动作。
在elink（墨水屏）设备上会有很大的残影。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
reopen this ticket in English, I can try to translate this but I still have no idea what you are asking for. You can turn off "animate page transitions", but I'm still not fully sure what you're looking for
