### ISSUE TITLE
[Bug] Webtoon covers from Webtoons.com aren't cropped to correct dimensions

### ISSUE THREAD

**Issue by hyPnOtiC-d00g** [Jays2Kings/tachiyomiJ2K#154]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: Redmi Note 3 & Android 6.0

## Steps to reproduce
1. Just comparing Tachiyomi Stable & Tachiyomi J2K

### Expected behavior
The cover image must be cropped to correct dimensions.

### Actual behavior
The complete image is displayed.

### Other details
![Screenshot_2020-03-27-13-26-48-892_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/44530973/77737050-369b1e80-7033-11ea-864a-0078001b88c3.png)

**Comment by Jays2Kings** [comment]
You're saying that showing the complete image is a bug? It's intentional because you can click the thumbnail and it expands full screen

This won't be changing

**Comment by hyPnOtiC-d00g** [comment]
Well, a few people prefered the portrait image, so I added. No problem. <(￣︶￣)>
