### ISSUE TITLE
Top/bottom margin in "full height" portrait mode

### ISSUE THREAD

**Issue by Rukishou** [Jays2Kings/tachiyomiJ2K#1540]
### Describe your suggested feature

My phone has a very wide aspect ratio and "fit width" (or smart fit) makes the page _just_ small enough to be an unpleasant read. "Fit height" instead hides part of the page behind sidescrolling which I don't mind in itself, just the amount, so I'd like to set a top/bottom margin.

### Other details

I already experimented with disabling fullscreen and cropping borders but it's not quite enough.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
you're better off asking for this request in the main tachiyomi repo. I have no desire to add such a setting, but i would eventually take it from main if they decide to
