### ISSUE TITLE
the automatic trimming function has  a bug

### ISSUE THREAD

**Issue by sqq135** [Jays2Kings/tachiyomiJ2K#1541]
### Steps to reproduce

open any comic with white edge on the top or right side，the automatic trimming function won't work

### Expected behavior

i will attach a picture below 
![Screenshot_20230414_014237_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/78015121/231842764-db63ad74-3a23-4490-8397-80c5067cb5fa.png)

### Actual behavior

i have turned on the automatic trimming function, but there are some bugs

### TachiyomiJ2K version

the latest

### Android version

12

### Device

huawei MatePad pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
you're not going to get cropped pages for double page reader, if anything i should remove the feature when double page is enabled

**Comment by sqq135** [comment]
> you're not going to get cropped pages for double page reader, if anything i should remove the feature when double page is enabled
i think this feature for double page is very useful, because this feature could amplify the words, and my pad is not very big and i like read comic with double page mode in it. Even in some conditions, there are some bugs such as gaps between two continuous pages. But i think that is not important.
And i use the "perfect viewer", the very old version, to check folder and cbz, it could crop the double page normally (i usually use it to read mobi). 
i really hope the feature can be reserved, maybe giving the client a option is a conservative approach.
