### ISSUE TITLE
Category tabs in the library

### ISSUE THREAD

**Issue by lavadragon15396** [Jays2Kings/tachiyomiJ2K#1543]
### Describe your suggested feature

Optional tabs in the library when show all categories isn't on, simillar to how they look on TachiyomiSY.

### Other details

A cleaner title count could be nice too with it being in a badge or buglbble instead of just text, again inspired from TachiyomiSY

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by lavadragon15396** [comment]
Just remembered you can attach images so I'll attach how it looks in SY 
![SmartSelect_20230414_103637_TachiyomiSY](https://user-images.githubusercontent.com/68852782/232007905-de41668c-411d-45cb-b282-094f33df831b.jpg)

**Comment by Jays2Kings** [comment]
been asked before, its not happening

**Comment by CSHM39** [comment]
So wait can you not mave it so the categories are horizontal
