### ISSUE TITLE
Use foreground install during user-initiated app update

### ISSUE THREAD

**Issue by lunarlily** [Jays2Kings/tachiyomiJ2K#1545]
### Describe your suggested feature

When you open the app and it shows the "update available" popup, if you update, the app updates in the background. This is annoying because you can't see when it's done, so you have to try reopening the app repeatedly until it's done. It'd be better if it opened Android's standard "update app" popup as when you manually download and open the APK.

Extensions should be unchanged, as Tachi can show a progress bar for those.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.5](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
It will show a notification that the update is installed, but I'll check to see if the app can automatically open itself once it's installed

**Comment by lunarlily** [comment]
IMO it's more obvious to the user that it's doing something when there's a progress bar, so I'd prefer a foreground install
