### ISSUE TITLE
历史功能加载时间过长

### ISSUE THREAD

**Issue by sha-mao** [Jays2Kings/tachiyomiJ2K#1548]
### Steps to reproduce

在书架与最近（历史）之间切换历史加载速度过慢

### Expected behavior

应该要与1.6.5版本一样才对

### Actual behavior

在书架与最近（历史）页面切换时，历史第一条不会变，第二条开始肉眼可见的转圈加载，第三条以此类推

### TachiyomiJ2K version

1.7.0-b01

### Android version

安卓13

### Device

小米11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to beta version **[1.7.0-b01](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
This isn't a beta bug, it behaves the same way in 1.6.5. Anyway, if you binge read a LOT of chapters (like 50+ chapters) in a short span it will take time to show all of the other series.

If you want it to load faster, on the history page, go to 显示选项 (the icon at the top of the screen beside the 3 dots) > 历史 > 将章节分组在一起 and select 按系列
