### ISSUE TITLE
本地漫画无法添加标签

### ISSUE THREAD

**Issue by Solapoi** [Jays2Kings/tachiyomiJ2K#1549]
### Steps to reproduce

无法添加标签

### Expected behavior

能正常添加漫画标签,并按标签分类

### Actual behavior

添加标签,并保存无任何反应

### Crash logs

无

### TachiyomiJ2K version

1.6.5

### Android version

安卓 11

### Device

Redmi K20 Pro尊享版

### Other details

无

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.5](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Please provide a video of this, I'm not able to reproduce

**Comment by Solapoi** [comment]
Uploading Screenrecorder-2023-04-18-22-32-40-484.mp4…

**Comment by Jays2Kings** [comment]
Try again @Solapoi

**Comment by Solapoi** [comment]
I have tried many times, but the TachiyomiSY version can add labels normally, but the classification is not easy to use

**Comment by Jays2Kings** [comment]
I meant try to upload the video again, it did not upload correctly the first time

**Comment by Solapoi** [comment]
Uploading Screenrecorder-2023-04-18-22-32-40-484_0_COMPRESSED.mp4…

**Comment by Solapoi** [comment]
![Uploading 1681867937231.gif…]()

**Comment by Solapoi** [comment]
https://user-images.githubusercontent.com/131011934/232956975-12efb5de-8811-416e-a5c6-3ff9013bf336.mp4

![1681867937231.gif](https://user-images.githubusercontent.com/131011934/232956973-eb7d4f1d-42b9-4b9f-83a3-a129b3eab1c2.gif)

**Comment by Jays2Kings** [comment]
So there's no big here, you just need to press the enter key to actually save the tag. I don't know how to translate so this key you need to press.

![Screenshot_20230418-233926.png](https://user-images.githubusercontent.com/8617760/232961129-d981af63-ebd6-4a59-9dac-94b0f70014c2.png)

I guess I can also use this as a means that if you go to another field to save the tag that way too. But there isn't a bug here

**Comment by Solapoi** [comment]
Thank you very much, big shot. I haven't tried this before. After waiting for a few versions, I still can't do it, so I'll ask
