### ISSUE TITLE
[Bug] Scrambled words in chapter settings

### ISSUE THREAD

**Issue by hyPnOtICDo0g** [Jays2Kings/tachiyomiJ2K#155]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: Redmi Note 3 & Android 6.0

## Steps to reproduce
1. First step: Click on a Manga & read any chapter.
2. Click on the settings icon in the top bar

### Expected behavior
This should be displayed.

"**General** Pull up for more options"

### Actual behavior
This happened instead.

![Screenshot_2020-03-27-13-10-00-571_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/44530973/77737987-081e4300-7035-11ea-9bb7-e8d325f81d4a.png)

**Comment by Jays2Kings** [comment]
Fixed as of 1.0.0
