### ISSUE TITLE
Translation error. Russian.

### ISSUE THREAD

**Issue by XlebyshekGG** [Jays2Kings/tachiyomiJ2K#1553]
### Steps to reproduce

Settings -> Security
![IMG_20230421_010907](https://user-images.githubusercontent.com/131394277/233451951-c13b90f9-e8c3-4127-aee6-cf95797ff905.jpg)

### Expected behavior

Button name: "Требовать разблокировку"

### Actual behavior

Button name: "Требует разблокировку"

### TachiyomiJ2K version

1.6.6

### Android version

Android 13

### Device

Realme GT 5G

### Other details

I made a mistake when I suggested the translation. I immediately offered a correction, but the incorrect translation was added to TachiyomiJ2K. Please fix it. Language: Russian. Key: lock_with_biometrics
![Screenshot_2023-04-21-00-38-49-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/131394277/233449155-33bea57e-74db-4744-b1ec-448084611846.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by XlebyshekGG** [comment]
forgot to attach a picture 😅
![IMG_20230421_010907](https://user-images.githubusercontent.com/131394277/233451951-c13b90f9-e8c3-4127-aee6-cf95797ff905.jpg)

**Comment by Jays2Kings** [comment]
Translations are updated on the next release, there's nothing that can be done about it now
