### ISSUE TITLE
Updating library with sources with multiple scanslators

### ISSUE THREAD

**Issue by SaharshDaNerd** [Jays2Kings/tachiyomiJ2K#1564]
### Describe your suggested feature

I love the feature to filter scanslators on sources which have multiple of them but whenever I update my library even the  new chapters from the scanslation groups which I have filtered out are shown as unread chapters in the library and I need to manually mark the series as read everytime. I wish we could have a setting to only search for chapters from the scanslators we have already selected. 

I am aware of the feature to skip reading filtered chapters is in the app settings but I couldn't find one for updating for the same. 

### Other details

An example of this 
![image](https://github.com/Jays2Kings/tachiyomiJ2K/assets/58357403/ec59a65d-2123-4b79-95f4-5ce5ddb9f14c)
![image](https://github.com/Jays2Kings/tachiyomiJ2K/assets/58357403/b9fe2d50-562b-407e-852c-9953cbebc178)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Ryanlie** [comment]
In addition, mark all as read does not appear when all unread chapter is filtered out. And mark all as read does not mark the filtered chapter as read.

**Comment by SaharshDaNerd** [comment]
It has been added in the newer versions 👍🏼
