### ISSUE TITLE
[Bug] Page not loading, 3 kind of errors

### ISSUE THREAD

**Issue by nanamiku739** [Jays2Kings/tachiyomiJ2K#157]
### Device information
* Tachiyomi version: 0.9.81
* Android phone & version: Samsung Galaxy Note 9, Android 10

## Steps to reproduce
1. Open chapter in Mangakakalot source
2. Tap any chapter

### Expected behavior
The chapter is open

### Actual behavior
The page failed to load with several kind of error message. Page not loading even though I tap retry, null object reference, and page list is empty. 

### Other details
Here are 3 the screenshot of the error I got
![Screenshot_20200326-221814_Tachiyomi](https://user-images.githubusercontent.com/62822330/77838728-a975d800-71a0-11ea-9748-0580b48a8399.jpg)
![Screenshot_20200326-221825_Tachiyomi](https://user-images.githubusercontent.com/62822330/77838730-aed32280-71a0-11ea-821d-b2d825ad18cb.jpg)
![Screenshot_20200326-221837_Tachiyomi](https://user-images.githubusercontent.com/62822330/77838732-b397d680-71a0-11ea-8c21-67aa6c0262d6.jpg)

**Comment by CarlosEsco** [comment]
This is an extension issue. Please open it on the tachiyomi extensions repository and close this
