### ISSUE TITLE
Unable to search anything in Buon Dua

### ISSUE THREAD

**Issue by garvongithub** [Jays2Kings/tachiyomiJ2K#1585]
### Steps to reproduce

1. Browse Buon Dua
2. Try to search anything

### Expected behavior

1. It should show relevant results.

### Actual behavior

It fails to show anything even there is no text but this happens while searching the source. If I use global search then it shows some results for the same term and I can open them but If open thw extension again from global search it shows that blank error screen. I am opening a issue here because it works fine in tachiyomi.
![Screenshot_2023-07-17-02-39-17-94_5901a79de973a50c74cff4cbb6149856](https://github.com/Jays2Kings/tachiyomiJ2K/assets/77321589/e43341c2-a462-4895-b3ef-e004ad8d9de6)

### TachiyomiJ2K version

1.6.6

### Android version

13

### Device

One Plus 9 pro

### Other details

Extension is NSFW.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/

**Comment by garvongithub** [comment]
@kyoyacchi As I said above already, it works fine in tachiyomi.

**Comment by redeye29O6** [comment]
Buon dua extension was working just fine in my tachiyomi j2k and yokai app but since the last 2 weeks it does not load any new entries. Is there any update coming for this extension in the near future? Just wanna know cuz it's a great place for various photo gallery, would be great if the developers decided to fix the issues.
