### ISSUE TITLE
[Reader -> Navigation] New option - wireless headphones - Next & Previous actions

### ISSUE THREAD

**Issue by ronycohen** [Jays2Kings/tachiyomiJ2K#1586]
### Describe your suggested feature

Hi, 
I use to go to the gym/cardio.
And I often put my tablet with a TV show or an Anime.

I don't know if that feature request is doable, but I would love to read some scans with the ability to navigate with the "tap options" of my wireless headphones (tap for next , double tap for previous)

That way I would be able to read scans during my run.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
I'm not sure how you're reading and running but this is a no go
