### ISSUE TITLE
Add search button on browse

### ISSUE THREAD

**Issue by Angelo-Porcu** [Jays2Kings/tachiyomiJ2K#1591]
### Describe your suggested feature

Hello devs.

My feature suggestion is to add a floating search button to the bottom-right side of the browse screen. That's it. It is more of an accessibility feature. Bless.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
The search bar is already very low, I can't imagine it needing to be any lower. If you really do, then check if your phone has a one handed mode that lowers the screen.

Either way the bottom right will be dedicated to the filter button

**Comment by Angelo-Porcu** [comment]
Thanks for taking your time to consider this suggested feature. I now realize I did leave out some rather important details:
- The device I use to run TachiyomiJ2K is a samsung tab s7+ (that is 11 inches in portrait mode).
- A screenshot that represents the tab where I was suggesting to add the feature to search for titles:

![tabs7+tachij2k](https://github.com/Jays2Kings/tachiyomiJ2K/assets/48699557/ead1cb2a-e369-4e93-a41d-a5554efb54e3)

I understand if you still consider it a trivial feature, it definitely does not affect the functionality of the app, but it would help me a great deal.

Again, thank you for your time and I hope you have a wonderful and blessed day.
Angelo
