### ISSUE TITLE
[Feature Request] Show amount of manga in My Library

### ISSUE THREAD

**Issue by GreatestFool** [Jays2Kings/tachiyomiJ2K#160]
### User Benefit
This isn't really more than something aesthetic, and something nice to see how much of a degenerate you are, but it would be nice to have a counter so you can see how many manga are present in My Library. It's similar to this [issue](https://github.com/Jays2Kings/tachiyomiJ2K/issues/21), but doesn't look like that got anywhere and also seems to have been focused on categories in sources?

Considering how categories look in My Library, having individual counters for them might end up leaving it looking a bit cluttered. However, if you think it'd be nice, and it doesn't look horrible, then that would be a nice little addition, but by no means necessary. I do, however, think a counter next to My Library would fit, something like "My Library (123)".

### Requirements
A setting somewhere under the Library options to enable or disable a counter for how many manga are in My Library.

**Comment by CarlosEsco** [comment]
You can just select them all. And in beta 2 categories is all 1 list.

**Comment by GreatestFool** [comment]
Oh right. Completely slipped my mind that there's a _Hide categories_ filter now. Hurr durr I guess.
