### ISSUE TITLE
Incorrect reading order

### ISSUE THREAD

**Issue by qwerty017** [Jays2Kings/tachiyomiJ2K#1611]
### Steps to reproduce

Happens whenever the chapters aren't labeled with actual numbers, no matter the extension or manga, but most easily seen with Swords.
Steps to reproduce:
1. Install "Swords Comic" extension.
2. Add Swords Comic to Library.
3. Click "Start Reading" and finish one chapter then go to next. 

### Expected behavior

Should go to next chapter depending on how sorted. 

### Actual behavior

Ignores chapter sorting and skips to next chapter with a Number in it like 100.

### TachiyomiJ2K version

1.7.0-b02

### Android version

13

### Device

Samsung Active tablet 3 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to beta version **[1.7.0-b02](https://github.com/Jays2Kings/tachiyomiJ2K/releases)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
This isn't a beta bug, or even a bug. That extension needs to be sorted by source order not chapter number since it uses roman numbering.
