### ISSUE TITLE
Entries that are already in library less visible when you browse

### ISSUE THREAD

**Issue by afrw** [Jays2Kings/tachiyomiJ2K#1612]
### Describe your suggested feature

Make the entries that are already in library less visible (not hiding them) when you browse like the one in the original tachiyomi.
the current option is only "Hide entries already in library" .. if it's possible to have a another option or by default the entries being less visible.
like this : 
![375692595_2541855492645890_1160517699085336889_n](https://github.com/Jays2Kings/tachiyomiJ2K/assets/135609777/cf151a6e-36a8-471f-b092-b179e1f2fd37)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [ ] I will fill out all of the requested information in this form.

**Comment by Minatowalid** [comment]
not sure if this will help but the code in tachiyomi exist in this class : BrowseSourceCompactGrid.kt and BrowseBadge.kt

![image](https://github.com/Jays2Kings/tachiyomiJ2K/assets/135609777/47d1ce20-9fe5-4c2f-9fed-2132840c67af)

CommonMangaItem.kt
![image](https://github.com/Jays2Kings/tachiyomiJ2K/assets/135609777/2fb15a26-8ed9-4a9c-a330-72e38892be04)

**Comment by afrw** [comment]
Here is the [PR](https://github.com/Jays2Kings/tachiyomiJ2K/pull/1675) for this feature.
