### ISSUE TITLE
Yugenmangas pages not found 

### ISSUE THREAD

**Issue by Unknoweird** [Jays2Kings/tachiyomiJ2K#1614]
### Steps to reproduce
[](url)
1. Entro a Yugenmangas
2. Pongo un manga al azar
3. No sé encuentran páginas 

### Expected behavior

Debería verse cualquier manga que yo sepa jaja

### Actual behavior

Aparecen nuevas actualizaciones de nuevos mangas pero ninguno tiene páginas encontradas.

### TachiyomiJ2K version

TachiJ2K 1.6.4

### Android version

Android 10

### Device

Moto E6i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
🤡 Translate the Acknowledgements before checking them
