### ISSUE TITLE
Can't use some extensions after 1.7.0 update

### ISSUE THREAD

**Issue by kyoyacchi** [Jays2Kings/tachiyomiJ2K#1615]
### Steps to reproduce

1. Use Asıra Scans (or Lunar Scans)
2. It doesn't work and shows an error message that's not related to extension.

### Expected behavior

It should work like in normal Tachiyomi

### Actual behavior

It shows an error message that starts with "No static method (blabla)..."

Screenshots:

TachiyomiJ2K:
(Asura Scans (EN)
![Screenshot_20230928-015435](https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/31bc144b-7571-43a3-bfd8-40310d227d22)
Normal Tachiyomi:
![Screenshot_20230928-015952](https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/5ea9982a-ef51-4e65-adcd-64645a6b2bac)

(Bee Hentai)
J2K:
![Screenshot_20230928-020049](https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/b826e68e-82d6-4d98-8a04-5dcac4b89fed)
Normal Tachiyomi:
![Screenshot_20230928-020107](https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/b23922c9-fa11-414e-88e5-ba92b89a4721)

And Lunar Scans 
J2K: 
![Screenshot_20230928-015533](https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/c1c0dd81-5136-4b55-ab11-6e39428d187c)

Normal Tachiyomi:
![Screenshot_20230928-020009_1](https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/92f69208-dc85-4239-af89-46a4e7571935)

I don't know how many extensions got broken with this update but these are i can reproduce on.

### TachiyomiJ2K version

1.7.0

### Android version

Android 11

### Device

Tecno Spark 7T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by ArjixWasTaken** [comment]
BeeHentai ain't censored in ur screenshot

**Comment by ArjixWasTaken** [comment]
Animated Glitched Scans is also affected

**Comment by Jays2Kings** [comment]
Fixed as part of [v1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/tag/v1.7.1)
