### ISSUE TITLE
Tv support for TachiyomiJ2k

### ISSUE THREAD

**Issue by cutterchop** [Jays2Kings/tachiyomiJ2K#1623]
### Describe your suggested feature

I downloaded the app on tv, it launched and all but you can not navigate easily, it might need a navigation update for tv UI, but it shouldn't be complex

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
u read manga on tv? 🤨

**Comment by SunBreaker1** [comment]
Pretty based, I read from time to time on my vertical monitor

**Comment by cutterchop** [comment]
> u read manga on tv? 🤨

I didn't get the chance to try it, but there's nothing wrong with it. In fact, having the ability to view two pages at once and larger fonts for better readability is a distinct advantage over small screens. It's a smart way to prevent visual fatigue and improve comprehension.

**Comment by Jays2Kings** [comment]
I'm not going to make a TV ui for a reading app no thanks
