### ISSUE TITLE
Infrequent force closing of the app

### ISSUE THREAD

**Issue by StudentSerai1181201811** [Jays2Kings/tachiyomiJ2K#1629]
### Steps to reproduce

1. Open app (most likely only from cold boot)
2. App will try to load library
3. App closes
4. Repeat steps 1 to 3 several times until app is finally able to load library

### Expected behavior

What's expected from the app is that when the app is opened whether from cold boot or not, the app will load the library and stay open while it's doing so

### Actual behavior

What happened instead was that when the app tries to load the library, it'll do so for a second or two and then forcefully close itself making it so the user must keep opening it until it doesn't forcefully close itself while loading the library

### Crash logs

[App_version_1.7.1_standard_b5a0316a6_106_2023-09-28T0041Z.md](https://github.com/Jays2Kings/tachiyomiJ2K/files/12812530/App_version_1.7.1_standard_b5a0316a6_106_2023-09-28T0041Z.md)

### TachiyomiJ2K version

1.7.1

### Android version

Android 13

### Device

Google Pixel 3 XL

### Other details

This likely happens infrequently as I've only experienced this issue twice while opening the app after updating it to 1.7.1 around 2 days ago.

Seems to be that this is only happens when the app tries loading the library as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by calops** [comment]
I second this, exact same issue on my side.

**Comment by Ghajeepan** [comment]
I have the same problem, Samsung fold 3.

**Comment by tanmaytez** [comment]
Same here.. I actually decided to issue this bug here, I'm tired of force stopping the app and open.

And anyone here experienced a bug like chapter pages will display half vertically after double tap to zoom.?

**Comment by StudentSerai1181201811** [comment]
I'm closing this issue as resolved as after updating to 1.7.2 and 1.7.3. This issue stopped occurring.

**Comment by Ghajeepan** [comment]
Issue resolved with latest update.
