### ISSUE TITLE
Frequent corruption of cache causing Force Crash after 1.7.1

### ISSUE THREAD

**Issue by 29988122** [Jays2Kings/tachiyomiJ2K#1630]
### Steps to reproduce

Update the library via automatic refrehsing,

### Expected behavior

Libraries updating normally.

### Actual behavior

App force closed.

### Crash logs

https://github.com/Jays2Kings/tachiyomiJ2K/files/12811843/tachiyomi_crash_logs.txt

### TachiyomiJ2K version

1.7.1

### Android version

Android 13

### Device

Google Pixel 4 XL

### Other details

The cache corruption issues only happens after 1.7.0.
Thanks to @ArjixWasTaken https://github.com/Jays2Kings/tachiyomiJ2K/issues/1617#issuecomment-1748106359 , I was able to pinpoint the issue, and create a new issue here instead.

I am able to clear the issue *temporarily* by clearing the cache of J2K, until next crash (it's happening rather frequently).

Thank you for the great app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
This should already be fixed by 1.7.2 and up
