### ISSUE TITLE
Emperor Scan, Manga Fénix, etc.

### ISSUE THREAD

**Issue by Unknoweird** [Jays2Kings/tachiyomiJ2K#1631]
### Steps to reproduce

1. Enter the extension
2. Java problem

### Expected behavior

The usual, just chill out and read some good stuff.

### Actual behavior

![Screenshot_20231009-170856](https://github.com/Jays2Kings/tachiyomiJ2K/assets/101126322/9732f0f9-a534-40ca-93b3-a8c64dc4720e)
![Screenshot_20231009-170919](https://github.com/Jays2Kings/tachiyomiJ2K/assets/101126322/3e2989c3-40c2-4cd0-a7ae-4d984abf57a5)

### TachiyomiJ2K version

TachiJ2K 1.7.1

### Android version

Android 10

### Device

Moto E6i

### Other details

Manga Fénix was like that for about a year I think.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
![Screenshot_20231011-224553](https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/d04bede9-eb39-48ec-a924-2b443d8a84dc)

**Comment by Jays2Kings** [comment]
🤡
