### ISSUE TITLE
Could not login to tracking

### ISSUE THREAD

**Issue by divyanshguptastudy** [Jays2Kings/tachiyomiJ2K#1640]
@garvongithub
### Steps to reproduce

My problem is that when I try to login in my anilist account and tap on it it open for a second and close I wasn't able to login to it

### Expected behavior

Open the ailist website and ask that TachiJ2K wants to have access of your Manga list

### Actual behavior

When I tap on anilist it open for a second and before loading it close.

### TachiyomiJ2K version

tachiyomij2k-v1.7.1 and tachiyomij2k-v1.7.2-b02.apk

### Android version

Android 9

### Device

Samsung Galaxy J7 NXT 

### Other details
My problem is in this video
https://drive.google.com/file/d/1xFSEXN7_1sB8fDRYh7xFNq-NP-dasyJf/view?usp=drivesdk
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by garvongithub** [comment]
![Screenshot_2023-10-17-09-47-43-97_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/Jays2Kings/tachiyomiJ2K/assets/77321589/57f6a0b2-6558-465f-9262-f5a92309d971)

More specifically indian ips will have this problem. You can still use vpn and use it with tachiyomi or use the site normally.

**Comment by divyanshguptastudy** [comment]
Thank you i was very tensed about this in some ways 
Thank you for informing

**Comment by garvongithub** [comment]
It should work now, the issue is resolved.

**Comment by prono69** [comment]
The issue is resolved now . Anilist working perfectly
