### ISSUE TITLE
Stuttering a lot while scrolling manga on S23 Ultra

### ISSUE THREAD

**Issue by AdithyanNellickal** [Jays2Kings/tachiyomiJ2K#1642]
### Steps to reproduce

This was working fine in Realme X2 Pro and Realme C30. But I recently migrated to S23 Ultra and now it's getting stuttered while scrolling in Webtoon mode every now and then. It happens especially when there's a lot of colorful or detailed drawings.

### Expected behavior

These would've scrolled perfectly fine in Realme X2 Pro and C30 btw.

### Actual behavior

The scrolling gets stuttered suddenly in specific areas. I have been experiencing this in S23 Ultra only.

Screen recording link : https://send.cm/dv14s4430mbn (expires in 30 days)

### TachiyomiJ2K version

1.7.1

### Android version

Android 13

### Device

Galaxy S23 Ultra

### Other details

Extension: Asura Scans
Experienced in many mangas
Haven't experienced in Previous phones (Realme X2 Pro & Realme C30)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
You can download the webtoons and in downloads turn on split images, turn off 32 bit color in reader settings, or use a different source that splits each page further. Aside from that there's no other solution for you.

**Comment by AdithyanNellickal** [comment]
Thanks bro.
