### ISSUE TITLE
No descarga capitulos

### ISSUE THREAD

**Issue by RayerC** [Jays2Kings/tachiyomiJ2K#1644]
### Steps to reproduce

1.- Abrir manga
2.- Descargar
3.- Descargar todo

### Expected behavior

Una ves que empiece a descargar se quedan guardados los capitulos para leer después fuera de linea

### Actual behavior

Aparece la barra de descarga, pero no avanza el progreso de descarga; después de un tiempo se detiene o desaparece la barra de progreso de descarga

### TachiyomiJ2K version

1.7.1

### Android version

Android 13

### Device

Galaxy A14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.1](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Even after translating this, youve given me nothing to work with, you need to provide a source and manga. Either make a new ticket in English or go to the discord server if you would rather speak your native language
