### ISSUE TITLE
Can't create backup after 1.7.2 update

### ISSUE THREAD

**Issue by kyoyacchi** [Jays2Kings/tachiyomiJ2K#1645]
### Steps to reproduce

1. go to settings
2. go to backup and restore
3. click on "create backup"
4. then click create button

### Expected behavior

It should create backup and show a notification.

### Actual behavior

Nothing happens.

### TachiyomiJ2K version

1.7.2

### Android version

Android 11

### Device

Tecno Spark 7T

### Other details

https://github.com/Jays2Kings/tachiyomiJ2K/assets/63583961/ba21c021-0119-440f-ae8f-65b14aa4ee4e

_Good thing i created a backup before updating.._

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Fixed in 21a4144aa0

**Comment by Jays2Kings** [comment]
Since this was fixed early, redownload [1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest), it'll have an updated fix for this
