### ISSUE TITLE
Swipe down to refresh bugs the interface

### ISSUE THREAD

**Issue by Samseys** [Jays2Kings/tachiyomiJ2K#1646]
### Steps to reproduce

Refresh via swipe down

Try to open anything that isn't in the bottom bar (for example a manga page, stats, about, settings)

### Expected behavior

I can interact with the interface normally

### Actual behavior

Clicking anywhere just opens the manga that was in that position before opening the new menu. Going back and changing menu with the bottom bar or force closing the app fixes it.

### TachiyomiJ2K version

1.7.2

### Android version

Android 13

### Device

Realme GT Neo 2 (RMX3370)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
record a video of this, because im not sure what you mean

**Comment by Samseys** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/assets/10304268/dc68427b-0fee-4c59-9580-71be9d4e18a6

**Comment by Jays2Kings** [comment]
Fixed in 4a34efdd7d

**Comment by Jays2Kings** [comment]
Since this was fixed early, redownload [1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest), it'll have an updated fix for this
