### ISSUE TITLE
IDK why was this removed but Save covers and pages in same path could just have been a default value change instead of yeeting it entirely

### ISSUE THREAD

**Issue by AryanVerma1024** [Jays2Kings/tachiyomiJ2K#1648]
### Describe your suggested feature

Re Introduce the feature removed in 7733c46ffc88591a059fa3de6197079876275329.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
You didn't even give a why, but go ask the main tachiyomi to re-add it instead, I'm cleaning up settings as they do
