### ISSUE TITLE
Invisible "in library" label

### ISSUE THREAD

**Issue by Pancakes0** [Jays2Kings/tachiyomiJ2K#1651]
### Steps to reproduce

Open a source (by lets say... the "latest")
Open a series and click the "add to library button" 

### Expected behavior

Expected to show the label "in library" after clicking the "add to library" (in the series page) after you exit the series (in the source/extension page) 

### Actual behavior

The "in library" label does not appear (in the source/extension page) 

https://github.com/Jays2Kings/tachiyomiJ2K/assets/73923883/1a316191-8e69-4edf-a6aa-d9a12ea41b9a

### TachiyomiJ2K version

1.7.2

### Android version

Android 13

### Device

Realme 9 Pro Plus

### Other details

It still does add it in the library even if it doesnt appear.
proven by:
1. After exiting the series page, even if the label doesnt appear, when you long press/ hold the series cover, it give you a popup that says the series was removed from library. So by that, it should still have been added regardless of the lable being present. 
2. When you go to your library regardless of the lable being present in the source/extention at that time, the series will be present in your library. 
3. When you exit out of the source/extension and open it again, it will appear as labled. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Fixed for next release
