### ISSUE TITLE
Double pages are not well paginated after screen rotation

### ISSUE THREAD

**Issue by zatenzu** [Jays2Kings/tachiyomiJ2K#1654]
### Steps to reproduce

1. Go to reader setting and set "Page layout" to auto
2. Rotate your device in landscape position
3. Open a book
4. Go to a double page in that book (the double page is displayed properly (see [picture 1](https://image.noelshack.com/fichiers/2023/43/3/1698228383-1.jpg))
5. Rotate your device in portrait position
6. Rotate back your device in landscape position (the double page is not displayed properly (see [picture 2](https://image.noelshack.com/fichiers/2023/43/3/1698228383-2.jpg) and [picture 3](https://image.noelshack.com/fichiers/2023/43/3/1698228382-3.jpg))

### Expected behavior

Double pages are properly displayed after screen rotation

### Actual behavior

Double pages are not properly displayed after screen rotation

### TachiyomiJ2K version

1.7.2

### Android version

Android 13

### Device

TCL NXTPAPER 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
There's a button right beside the double page button to manually fix that, shift the double pages
