### ISSUE TITLE
Add option to switch back to old screen switching animation and page save behavior.

### ISSUE THREAD

**Issue by pseudokawaii** [Jays2Kings/tachiyomiJ2K#1655]
### Describe your suggested feature

Firstly, I am always appreciative of J2K for their active maintenance of this fork. TachiyomiJ2K remains one of my most beloved open-source projects. The recent v1.7.2 update introduced some changes that I personally find undesirable:
>- Updated animation for switching between screens (older devices will still see the old animations)
>- Covers and pages of library entries are now always saved in subfolders

I find the new sliding animation somewhat bothersome, and I am not fond of the application creating numerous folders for saving images, as I frequently save images. If it's not too much to ask, I would appreciate the ability to revert to the previous screen transition animation and the previous behavior of using a single folder for saving individual pages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfly** [comment]
Agreed, I feel like the new animation doesn't smooth. I prefer the old one.

**Comment by Jays2Kings** [comment]
The animation I'm still looking into but the saved image structure isn't returning, as main tachi has removed it for the bugs it caused, I'm doing the same
