### ISSUE TITLE
Tachiyomi 1.7.2 broke browser mode

### ISSUE THREAD

**Issue by ZFranz** [Jays2Kings/tachiyomiJ2K#1656]
### Steps to reproduce

Select a source protected with cloudflare that requires confirmation, instead of showing the cloudflare page it shows nothing, because it appends "blob" in the url and doesn't load the correct page. 

### Expected behavior

Loading cloudflare page to confirm and load the desired manga

### Actual behavior

Cant confirm cloudflare beacuse link is incorrect when "blob" is appended in the url. 

### TachiyomiJ2K version

1.7.2

### Android version

Andoird 13

### Device

Asus rog 6

### Other details

![Screenshot_20231025-192557_TachiyomiJ2K_1](https://github.com/Jays2Kings/tachiyomiJ2K/assets/16793189/b59b698a-0093-4370-8e26-3914d00a5ab5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/1657
