### ISSUE TITLE
Erreur Blob:url

### ISSUE THREAD

**Issue by Kiwi-ma** [Jays2Kings/tachiyomiJ2K#1657]
### Steps to reproduce

Bonjour,

J'ai un gros soucis depuis plusieurs jours. L'ouverture de webview sur des extensions pour passer la barrière Cloudflare me renvoie un une URL "Blob:" qui rend la page innacessible.

Qu'est-ce que ce problème et comment y remédier ?

En vous remerciant par avance !

![SmartSelect_20231025_214001_Tachiyomi](https://github.com/Jays2Kings/tachiyomiJ2K/assets/139688732/d0029fdd-028c-4ef3-ae2e-13f77154aca6)

### Expected behavior

...

### Actual behavior

.
.

### Crash logs

...

### TachiyomiJ2K version

Stable 0.14.6

### Android version

Android 15

### Device

Fold 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.2](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Alors déjà deux choses : 
1) N'ouvre pas des issues spécifiques à Tachiyomi en général sur le repo J2K, cette issue a été fix sur le Tachiyomi stable aujourd'hui ; donc je te recommande vivement d'utiliser Tachiyomi stable pour le moment
2) Après c'est le classic Cloudflare.
3) Quand tu ouvres des issues sur GitHub, essaie d'écrire en anglais
4) N'hésite pas à passer sur le Discord Tachiyomi si besoin ; on pourra t'aiguiller sur comment fix ce problème.
Est-ce que tu peux fermer cet issue ? Merci !

**Comment by Jays2Kings** [comment]
im closing this either way since its already fixed for next j2k release
