### ISSUE TITLE
Migrating Broke the Interface

### ISSUE THREAD

**Issue by paressz** [Jays2Kings/tachiyomiJ2K#1661]
### Steps to reproduce

1. Select a manga to migrate
2. Migrate the manga

### Expected behavior

Migrating shouldn't show the selected manga as background

### Actual behavior

Migrating manga from the manga page make the manga page as background and will bring me to reader if I selected a chapter

### TachiyomiJ2K version

1.7.2

### Android version

13

### Device

Xiaomi Poco M5

### Other details

![Screenshot_2023-10-28-06-51-25-613_eu kanade tachiyomi j2k](https://github.com/Jays2Kings/tachiyomiJ2K/assets/95536754/3ccd2de2-7567-4b71-a90e-1224114d5933)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Redownload 1.7.3 from the releases page. There's a few other screens that have the issue but those are already known
