### ISSUE TITLE
Manually saved images now show up in subfolder omg

### ISSUE THREAD

**Issue by fieldhouse** [Jays2Kings/tachiyomiJ2K#1662]
### Steps to reproduce

Previous behavior was when an image was long pressed an option would show to save it.  The location was a folder under Pictures named TachiyomiJ2K. Since 1.7.3 this behavior has changed to be a subfolder under TachiyomiJ2K using the title of the manga. 

### Expected behavior

Not sure why it was switched but now I have a ton of empty folders to clean up... One for each image I save. 
The subfolder is unnecessary. The name of the manga is already included in the images file name.

Can we get it back to saving images in Pictures/TachiyomiJ2K or maybe add an option to not add the subfolder for each image.?

### Actual behavior

long pressing an image shows an option to save it.  The location now has changed to be a subfolder under Pictures/TachiyomiJ2K using the title of the manga. 

### TachiyomiJ2K version

1.7.3

### Android version

Android 13

### Device

Samsung Galaxy tab S8

### Other details

Pretty please?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Checked the 🤡 box for you
