### ISSUE TITLE
Edit categories page wouldn't open new page

### ISSUE THREAD

**Issue by Hikarikun42** [Jays2Kings/tachiyomiJ2K#1663]
### Steps to reproduce

1. Open menu
2. Settings
3. Library
4. Edit categories

### Expected behavior

Edit categories open

![Screenshot_20231029_145858_TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K/assets/110003583/2ed327b4-6a79-457a-9f37-e0771f0504f9)

### Actual behavior

Edit categories just drawer over library setting

![Screenshot_20231029_145912_TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K/assets/110003583/e925a88f-270c-413e-9ed4-5f150fff8b92)

### TachiyomiJ2K version

1.7.3

### Android version

Android 13

### Device

Samsung A04e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by e-shl** [comment]
I thought it was a special feature.
It looked beautiful and appropriate.
