### ISSUE TITLE
Toggle to disable manually saved pages from being saved in different sub-folders

### ISSUE THREAD

**Issue by XxJibril** [Jays2Kings/tachiyomiJ2K#1665]
Hello, 

I don't remember since which update but i recently noticed that saving a page from a manga automatically creates a sub-folder named after the manga at .../pictures/TachiyomiJ2K/NameOfManga and saves the picture there, i don't like that because it spawns dozens of new albums in my gallery that i have no use for because it makes it very cluttered extremely fast.

I'd love a toggle option to be able to revert that back to how it was = saved pictures automatically go to .../pictures/TachiyomiJ2K and not a sub-folder there, so they all stay in the same album in my gallery, just like it was before.

Thank you for everything!

### Other details

i saw someone mentioned the same thing as a "bug" here https://github.com/Jays2Kings/tachiyomiJ2K/issues/1662  but the ticket was closed, maybe because it's not a bug but a feature someone asked for ? 
Anyway, i think the picture's name having the name of the Manga it's from and even the Chapter's Number and Page is absolutely amazing and more than enough reference, no need for a sub-folder.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] If this is a request for a feature in the original Tachiyomi, i am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.
![Screenshot 1](https://github.com/Jays2Kings/tachiyomiJ2K/assets/61125414/0a3257ef-dc5b-4192-86cd-f9251d812f0f)
![Screenshot 2](https://github.com/Jays2Kings/tachiyomiJ2K/assets/61125414/e8b6d96d-5bdc-47d6-9f61-a39050191cb4)
![Screenshot 3](https://github.com/Jays2Kings/tachiyomiJ2K/assets/61125414/53b9f509-2a4d-4510-9009-89f29031713e)

**Comment by KingDrofd** [comment]
Same issue here, having too many folders clutters the Gallery.

**Comment by Jays2Kings** [comment]
🤡

**Comment by XxJibril** [comment]
what is that supposed to mean ?

**Comment by Jays2Kings** [comment]
It means properly read the acknowledgements and don't try to hide the fact you're a 🤡
