### ISSUE TITLE
Search in Settings

### ISSUE THREAD

**Issue by xFerZx** [Jays2Kings/tachiyomiJ2K#1666]
### Steps to reproduce

1) will launch the application
2) opened the settings
3) clicked on the settings search

### Expected behavior

Must be a clean background

### Actual behavior

and there was a bug with pictures

### Crash logs

there was a crash and shows manga cards instead of a clean background

### TachiyomiJ2K version

1.7.3

### Android version

13

### Device

PIXEL 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by e-shl** [comment]
As an image
![Screenshot_2023-11-04-11-18-00-82_5901a79de973a50c74cff4cbb6149856.jpg](https://github.com/Jays2Kings/tachiyomiJ2K/assets/35057681/a084cf1e-480f-4c4d-9d4e-5db9807cb9bb)
