### ISSUE TITLE
Migration & Categories page is overlapping with other pages.

### ISSUE THREAD

**Issue by iLikeCake10** [Jays2Kings/tachiyomiJ2K#1674]
### Steps to reproduce

Open / tap and hold a entry, tap on the ellipsis and select migration. The migration page is bugged out and overlaps library and manga details page.

Tap and hold a category and tap on edit and the categories page overlaps with the library page.

### Expected behavior

Migration and categories page should open in a sub page like before.

### Actual behavior

The migration page overlaps with the manga details page and library page.

### TachiyomiJ2K version

1.7.3

### Android version

Android 12

### Device

OnePlus Nord

### Other details

![IMG_20231105_213212](https://github.com/Jays2Kings/tachiyomiJ2K/assets/122379215/87731a1d-6b73-4b80-b0b5-46d2eae5d5a5)
![IMG_20231105_213156](https://github.com/Jays2Kings/tachiyomiJ2K/assets/122379215/aca0405f-7412-445d-a5cc-b908199b09c3)
![IMG_20231105_213138](https://github.com/Jays2Kings/tachiyomiJ2K/assets/122379215/060a83a2-9f78-4fd6-8a0f-245533940e24)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by iLikeCake10** [comment]
For some reason GitHub isn't allowing me to post media, so here's an example of what I'm talking about. https://streamable.com/w4oodx

**Comment by Jays2Kings** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/1663
