### ISSUE TITLE
Translate image

### ISSUE THREAD

**Issue by WEPOXS** [Jays2Kings/tachiyomiJ2K#1677]
### Describe your suggested feature

If possible, add translation for the image 
![Screenshot_20231108_155746_TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K/assets/146017577/512112a8-cdf5-4cdc-8f24-818cf84a773a)

### Other details

![Screenshot_20231108_155913_TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K/assets/146017577/f9f02416-02a6-427c-be9d-af2b27a7bd4e)
when pressed it will translate the image (if possible) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
ill be nice and say this is strike #2 instead 🤡
