### ISSUE TITLE
TachiyomiJ2K Is Virus

### ISSUE THREAD

**Issue by amineziat** [Jays2Kings/tachiyomiJ2K#1678]
### Steps to reproduce

I Just scanned TachiyomiJ2K in VirusTotal website and find TROJ_GEN.R002V01J9 in TachiyomiJ2K
Maybe it Just an issue I hope you fix it soon because I removed TachiyomiJ2K until you fix it

### Expected behavior

I expect no virus

### Actual behavior

I Find TROJ_GEN.R002V01J9 in TachiyomiJ2K

### TachiyomiJ2K version

last one

### Android version

13

### Device

redmi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by e-shl** [comment]
🤡
![Screenshot_2023-11-08-18-05-15-34_ffb2f5e1b976ff98cfc94f359fbce8de.jpg](https://github.com/Jays2Kings/tachiyomiJ2K/assets/35057681/eab6521e-c871-4bde-a456-135cdcd9caa9)

**Comment by amineziat** [comment]
> 🤡 ![Screenshot_2023-11-08-18-05-15-34_ffb2f5e1b976ff98cfc94f359fbce8de.jpg](https://user-images.githubusercontent.com/35057681/281411411-eab6521e-c871-4bde-a456-135cdcd9caa9.jpg)

what can't you see TROJ_GEN.R002V01J9

**Comment by amineziat** [comment]
__

**Comment by e-shl** [comment]
> what can't you see TROJ_GEN.R002V01J9

find an application where this antiaitrus will not find this ершы the same virus

**Comment by amineziat** [comment]
> > what can't you see TROJ_GEN.R002V01J9
> 
> find an application where this antiaitrus will not find the same virus

I don't know what you talking about man I'm Just asking what is "TROJ_GEN.R002V01J9" is it a virus? or just an issues

**Comment by CarlosEsco** [comment]
> > > what can't you see TROJ_GEN.R002V01J9
> > 
> > 
> > find an application where this antiaitrus will not find the same virus
> 
> I don't know what you talking about man I'm Just asking what is "TROJ_GEN.R002V01J9" is it a virus? or just an issues

It's an issue with the scan itself, especially if all the other scans are not finding this so called virus.

**Comment by amineziat** [comment]
> > > > what can't you see TROJ_GEN.R002V01J9
> > > 
> > > 
> > > find an application where this antiaitrus will not find the same virus
> > 
> > 
> > I don't know what you talking about man I'm Just asking what is "TROJ_GEN.R002V01J9" is it a virus? or just an issues
> 
> It's an issue with the scan itself, especially if all the other scans are not finding this so called virus.

ok thanks man 👍
