### ISSUE TITLE
Date format didn't get changed after the setting changed

### ISSUE THREAD

**Issue by Hikarikun42** [Jays2Kings/tachiyomiJ2K#1679]
### Steps to reproduce

1. Menu
2. Settings
3. General 
4. Date format

![Screenshot_20231108_205802_TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K/assets/110003583/befca42f-d69f-4770-b711-bf30bc3ed1db)

### Expected behavior

![Screenshot_20231108_205740_Tachiyomi](https://github.com/Jays2Kings/tachiyomiJ2K/assets/110003583/e85bdd70-873b-4d7a-b917-175cb7fadf98)

### Actual behavior

![Screenshot_20231108_205819_TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K/assets/110003583/b060aabf-0f3f-4c34-b805-121cc335530a)

### TachiyomiJ2K version

1.7.3

### Android version

13

### Device

Samsung A04e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Date format doesn't change the date on this screen, it's barely used in fact and I'll likely remove the setting in the future if I bother
