### ISSUE TITLE
[Bug] In migration Screen background glitch 

### ISSUE THREAD

**Issue by kanniprab03** [Jays2Kings/tachiyomiJ2K#1681]
### Steps to reproduce

See Bottom near fab you can see chapter lists and my device is 6.7inch display 

![Screenshot_2023-11-09-16-10-42-310_eu kanade tachiyomi j2k](https://github.com/Jays2Kings/tachiyomiJ2K/assets/132337697/7d77f7cf-660e-4255-8775-8903bccc3550)

### Expected behavior

It should be same background as above 

### Actual behavior

It's transparent below and color above

### TachiyomiJ2K version

1.7.3

### Android version

13

### Device

Mi Redmi Note 12 4G non NFC model 

### Other details

I tried all theme same behaviour 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Read the acknowledgements again
