### ISSUE TITLE
Per series Reading mode & Page layout.

### ISSUE THREAD

**Issue by iLikeCake10** [Jays2Kings/tachiyomiJ2K#1687]
### Describe your suggested feature

Some sources have split double pages for some series, and it's very inconvenient to switch the layout from "Double Pages" to "Automatic" (or vice versa) everytime for series that have doesn't have split pages and those that does have split pages. To fix this, I suggest to implement per series reading mode and page layout (j2k exclusive) like Tachiyomi main preview.

### Other details

![Screenshot_2023-11-23-20-37-44-70_79aa9bf7c61e266c5f841e42245e214b](https://github.com/Jays2Kings/tachiyomiJ2K/assets/122379215/a61df344-a3db-4f33-aca3-c962e7d9536d)
![Screenshot_2023-11-23-20-53-34-77_79aa9bf7c61e266c5f841e42245e214b](https://github.com/Jays2Kings/tachiyomiJ2K/assets/122379215/8e0df889-6527-4a91-8a38-31649163ad48)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
Per series reading mode already esists in j2k, its literally the first thing you see when you open the settings sheet. Page layout is not going to be a thing since I have no idea what use case you want to sometimes combine pages and sometimes don't but the use case isn't widespread enough to make that a feature
