### ISSUE TITLE
Won't Download

### ISSUE THREAD

**Issue by isekhai** [Jays2Kings/tachiyomiJ2K#1715]
### Steps to reproduce

1. Manga/Manhwa is from Bato.to
2. The comic updates without issues
3. When I try to download a chapter, the download won't work

### Expected behavior

The download should proceed. 

### Actual behavior

The download is paused and it shows a message
![IMG_20240111_133046](https://github.com/Jays2Kings/tachiyomiJ2K/assets/111270028/888ebaba-5759-402b-84dd-561cbdb069be)

### TachiyomiJ2K version

1.7.3

### Android version

Android 13

### Device

Oppo A96

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by StudentSerai1181201811** [comment]
Can you detail which manga/manhwa in particular? Is it just Bato.to or is it all sources?
If it's not a specific one but all manga/manhwa and only for Bato.to, it could be just the extension that's the problem.
My Bato.to extension works fine but I only tested on one and have a more updated version from another repo compared to the one taken down from the original repo.
You might need to uninstall the extension and reinstall it from the new community repo, if the problem still persists, try opening up an issue over there instead.

**Comment by isekhai** [comment]
ooooh this is noted. thank you !!
