### ISSUE TITLE
Categories tab like official tachiyomi

### ISSUE THREAD

**Issue by Hiirbaf** [Jays2Kings/tachiyomiJ2K#1718]
### Describe your suggested feature

I would like to be able to have the categories tab like in the official tachiyomi, it would look more aesthetically pleasing, if not by default there would at least be an option to activate it.
I leave an image as an example.
![Screenshot_20240112_044241_Tachiyomi](https://github.com/Jays2Kings/tachiyomiJ2K/assets/42479509/592722fd-40d3-4b40-9f02-8ae401a85c41)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Xeiv** [comment]
This is kind of already a thing, you just have to press the library button twice or swipe up twice to show the display options, open that, go to the categories tab and untick show all categories. You can now swipe left and right to switch categories

**Comment by Hiirbaf** [comment]
My request is to make it look like the official one, and it doesn't have that option

**Comment by nonproto** [comment]
Search the issues this was denied before

**Comment by Hiirbaf** [comment]
I hadn't seen it, so I'll have to change the fork.
