### ISSUE TITLE
Plz Update Tachij2k quickly

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [Jays2Kings/tachiyomiJ2K#1720]
### Describe your suggested feature

add options to make categories list like original tachiyomi

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [ ] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Xeiv** [comment]
As I posted on #1718 
> This is kind of already a thing though they don't all show up on top. You just have to press the library button twice or swipe up twice on the bottom bar to show group library by and display options. Touch display options then the categories tab, and untick Show All Categories. You can now swipe left and right to switch categories. If you want the number of items you can tick Show number of items in the badges tab.
