### ISSUE TITLE
Will J2K continue or also joever?

### ISSUE THREAD

**Issue by Azim** [Jays2Kings/tachiyomiJ2K#1721]
### Describe your suggested feature

with tachi discord locked down, i cant really ask anywhere else

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by mechagomizilla** [comment]
I try not to mention anything directly, so I will only use abbreviations. While I don't know about J2K yet, the SY fork has confirmed it's not dead yet and it's also helping a long term contributor set up a successor to the main Tachiyomi branch. You should be able to find more info by looking at SY's patch notes from version 1.10.1. As for J2K, updates trend to be a bit slow even though they're consistent. You should wait a bit before giving up.

**Comment by DisasterInbound** [comment]
> I try not to mention anything directly, so I will only use abbreviations. While I don't know about J2K yet, the SY fork has confirmed it's not dead yet and it's also helping a long term contributor set up a successor to the main Tachiyomi branch.

I read the announcement but I prefer J2K UI. I hope this fork continues but if not I guess that's another option.

**Comment by Azim** [comment]
Yeah i also prefer this fork's UI approach (and migrating everything would be a pain) so i'd rather stay here

**Comment by radry** [comment]
Tachiyomi has been relaunched as [Mihon](https://github.com/mihonapp/mihon), so the question is if J2K will continue independently or become a fork of Mihon.

**Comment by nonproto** [comment]
> Tachiyomi has been relaunched as [Mihon](https://github.com/mihonapp/mihon), so the question is if J2K will continue independently or become a fork of Mihon.

No it hasn't. That an unrelated project
