### ISSUE TITLE
Can't install extensions, more likely that i can't find any extensions to install.

### ISSUE THREAD

**Issue by Hitharth13** [Jays2Kings/tachiyomiJ2K#1724]
### Steps to reproduce

1.Opening the app.
2.Go to browse.
3.Click on extensions to install new extensions.

### Expected behavior

The list of extensions should have opened so that we can install the new extensions that we want.

### Actual behavior

The list of extensions opened but i had only the extension that we previously installed and no new extensions were to be found to install.
![6c845836-8f36-479e-8cd8-5e83b80913b3](https://github.com/Jays2Kings/tachiyomiJ2K/assets/114826617/7bb78eb6-720f-4715-acc0-c19b38b386f3)

### TachiyomiJ2K version

1.7.3

### Android version

Android 13

### Device

Nothing Phone 1.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by copurxia** [comment]
My guess is that the official plug-in source is closed
Tachiyomi just said goodbye
[https://tachiyomi.org/news/2024-01-13-goodbye](https://tachiyomi.org/news/2024-01-13-goodbye)

**Comment by Hitharth13** [comment]
@copurxia yea saw that too late I'm gonna delete this issue.
