### ISSUE TITLE
Change the name and launch animation 

### ISSUE THREAD

**Issue by Sadwhy** [Jays2Kings/tachiyomiJ2K#1737]
### Describe your suggested feature

The main app in Mihon now so the app could be renamed to MihonJ2K and the launch animation could be changed to the new Mihon logo. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
As [az4521/tachiyomiAZ](https://github.com/az4521/tachiyomiAZ/) and [jobobby04/TachiyomiSY](https://github.com/jobobby04/TachiyomiSY) does, this project won't be renamed as it is a trademark* of this project and its derivatives.

Not specifically a trademark but its something we know and live. Also, MihonJ2K sounds worse to me personally.

**Comment by Sadwhy** [comment]
Stubborn old people fr. The future is now old man.

**Comment by pokewizardSAM** [comment]
> Stubborn old people fr. The future is now old man.

UNSTABLE new generation fr. Tachiyomi name should be kept as a tribute
