### ISSUE TITLE
Cannot update extensions after setting new extension repo

### ISSUE THREAD

**Issue by anikoiau** [Jays2Kings/tachiyomiJ2K#1738]
### Steps to reproduce

1. Set new extension repo to https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json
2. Click on "Update" for any extension
3. Observe

### Expected behavior

Extension should get installed correctly

### Actual behavior

Installation fails. A toast pops up saying "Could not install extension"

### TachiyomiJ2K version

1.7.4

### Android version

Android 14

### Device

Samsung Galaxy A34

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by anikoiau** [comment]
Closing since this is resolved

**Comment by mitch030504** [comment]
What did you do to solve it?

**Comment by anikoiau** [comment]
It was a signature issue. The signature of the extensions already installed were different from the ones installed via the keyoushi repo. So I had to uninstall the existing extensions first before
