### ISSUE TITLE
Myanimelist not connecting after clicking allow

### ISSUE THREAD

**Issue by kmlkmljkl** [Jays2Kings/tachiyomiJ2K#1763]
### Steps to reproduce

1. in tracking menu select myanimelist
2. log in, then click allow
3. wait for the spinner
4. ???

### Expected behavior

3 should not take very long, and after 4 there should be a check to show it's logged in

### Actual behavior

the loading spinner stays there for a solid 30 seconds, after which there is no checkmark next to myanimelist. I do not get an error message.

### TachiyomiJ2K version

1.7.4

### Android version

10

### Device

samsung a51

### Other details

the site loads just fine, but tracking stopped working, so I removed it, and now this happens after trying to add it again.

i've tried removing cache, cookies, and webview data, but it looks like tracking login is separate from the webview you get on manga titles as I don't have to login again to myanimelist,

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by kmlkmljkl** [comment]
also I just noticed the browser said powered by firefox so I figured I'd try changing my default browser to chrome to see if it's related to that - but still have the same issue

**Comment by kmlkmljkl** [comment]
reinstalled and now it works... I'd hoped being able to avoid this considering backups don't save custom covers, and my library is pretty big... oh well

**Comment by kmlkmljkl** [comment]
Actually, it has connected again - seemingly. the checkmark is there, but it's not working. attempts to change the tracking info, for instance the last read chapter, or searching MAL to add new tracking to an entry, results in either a 503 error (on searching) or a 403 error (on changing), despite the site being up, and the API page saying what's listed above. unsurprisingly manually changing anything on the site also isn't displayed, though without any sort of error message.

**Comment by Jays2Kings** [comment]
Closing as it's on MAL's end
