### ISSUE TITLE
[Feature Request] In Vertical reader, allow scrolling.

### ISSUE THREAD

**Issue by MinitotheMax1** [Jays2Kings/tachiyomiJ2K#177]
### Why/User Benefit/User Problem
In the vertical reader, it shows page by page which in my opinion, somewhat ruins the experience. Although there is the webtoon mode which allows for scrolling, the lack of gaps between pages makes it confusing sometimes where the previous page ends and the new page begins. I think that many readers like myself would be really happy if this option was added to the app.

### What/Requirements
I have no technical knowledge, but the idea is to have small gaps inbetween pages to differentiate them like in MangaRock or MangaDex.
![Screenshot_20200403-010806_Chrome](https://user-images.githubusercontent.com/45908027/78326149-9ddf3400-7547-11ea-97b2-1ad865447f90.jpg)

And this is it in Mangarock:
![Screenshot_20200403-010850_Manga Rock](https://user-images.githubusercontent.com/45908027/78326170-b18a9a80-7547-11ea-99a9-9a5a43da9745.jpg)

I hope its not too difficult to implement.

P.S.

This is probably a stupid question, but for a landscape page why does smart fit zoom in. Should it not fit the width so the reader can see the whole image since the point of smart fit is to fit the longest side?

**Comment by joseph619** [comment]
So you basically want continious scrolling in Vertical reading mode with some padding between the pages?

**Comment by CarlosEsco** [comment]
if you exclusively use mangadex i have this in Neko, if not if this is added it should be as another viewer not replace the vertical one.

**Comment by joseph619** [comment]
New viewer could be labelled **Vertical (with padding)** with the 10% from Neko as the default.

**Comment by joseph619** [comment]
This is now can be cherry picked from Dev

https://github.com/inorichi/tachiyomi/commit/38ceaf5253e10101a19146487f321589e9b761f4
https://github.com/inorichi/tachiyomi/commit/dd59748bf082b2c2a236061d1cf9357b95791493
https://github.com/inorichi/tachiyomi/commit/05fd8e2a38c9ff7c140ce676a8dd361cfb89ea1e

**Comment by MinitotheMax1** [comment]
Thanks a lot, but how do I download the J2K dev version?

**Comment by MinitotheMax1** [comment]
Also does tachiyomi recognize the difference between webtoons and manga and
change the reading mode accordingly, like in MangaDex or MangaRock?

**Comment by joseph619** [comment]
Ask questions on Discord server, Github is only to report bugs or request new features.

**Comment by Jays2Kings** [comment]
Added as of 1.0.0
