### ISSUE TITLE
MyAnimeList tracking/ searching stopped working in the app

### ISSUE THREAD

**Issue by kalinduss** [Jays2Kings/tachiyomiJ2K#1770]
### Steps to reproduce

For manga that have not been connected to MAL tracking:
1. Tap on any manga
2. Tap on tracking
3. Tap add tracking for MAL

For manga that have been connected to MAL tracking in the past before this bug:
1. Finish reading a previously unread chapter

### Expected behavior

For manga that have not been connected to MAL tracking:
- A list of search results that correspond to the title of the manga you are currently on should appear

For manga that have been connected to MAL tracking in the past before this bug:
- The finished chapter should update the tracking number (e.g. from chapter 56 to 57) in the background without visual interruption

### Actual behavior

For manga that have not been connected to MAL tracking:
- A "no results found" error shows up now. A couple of days ago it was an "http error 503" error message.
![2](https://github.com/Jays2Kings/tachiyomiJ2K/assets/99096297/87dc7f09-c260-49b6-bfaa-5ac4783e31f1)

![1](https://github.com/Jays2Kings/tachiyomiJ2K/assets/99096297/f38b8f36-bc41-431f-b160-a5abb1357809)

For manga that have been connected to MAL tracking in the past before this bug:
- A blank box appears at the bottom of the screen and the tracker does not update.
![4](https://github.com/Jays2Kings/tachiyomiJ2K/assets/99096297/c02a1b26-2bdc-4b96-9566-1488d63c451a)

### TachiyomiJ2K version

1.7.4

### Android version

Android 8

### Device

Samsung Galaxy S9

### Other details

I have tried logging out and back into MAL in the app to no avail. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by kalinduss** [comment]
Also, as a side note, Mihon and Yokai seem to have fixed the bug according to their changelogs. I don't want to insinuate that those forks are better, just that it might be helpful to look for a fix there if it hasn't been found already. Delete this comment if you find it inappropriate

**Comment by kalinduss** [comment]
Sorry, I misclicked. This issue is still open.
Also, as a side note, Mihon and Yokai seem to have fixed the bug according to their changelogs. I don't want to insinuate that those forks are better, just that it might be helpful to look for a fix there if it hasn't been found already. Delete this comment if you find it inappropriate

**Comment by null2264** [comment]
> Sorry, I misclicked. This issue is still open. Also, as a side note, Mihon and Yokai seem to have fixed the bug according to their changelogs. I don't want to insinuate that those forks are better, just that it might be helpful to look for a fix there if it hasn't been found already. Delete this comment if you find it inappropriate

Not the same issue, those fixes are to fix login issue and unintentional spam, this issue however is from MAL side and IS affecting both Mihon and Yokai.

REF:
- https://myanimelist.net/forum/?topicid=2143705
- https://github.com/mihonapp/mihon/issues/298

**Comment by GeorgyDesign** [comment]
I have the same issue. Tried to reconnect MAL account a few times, but it did not help. Shikimori tracker works though.

That being said, both MAL and Shikimiori do not work for me in Aniyomi fork right now, so, maybe, MAL has some API issues, and it is not forks’ fault, at least.

**Comment by kalinduss** [comment]
> Not the same issue, those fixes are to fix login issue and unintentional spam, this issue however is from MAL side and IS affecting both Mihon and Yokai.
> 
> REF:
> 
>     * https://myanimelist.net/forum/?topicid=2143705
> 
>     * [Cannot add MyAnimeList tracking  mihonapp/mihon#298](https://github.com/mihonapp/mihon/issues/298)

I see, sorry about that then. Guess we'll just have to wait until MAL resolves the API issues on their end.

**Comment by kalinduss** [comment]
The issue seems to have resolved itself on MAL's side.
