### ISSUE TITLE
Extension Nettruyen changed domain

### ISSUE THREAD

**Issue by QuangTKD** [Jays2Kings/tachiyomiJ2K#1771]
### Steps to reproduce

Can't access Nettruyen extension

### Expected behavior

Access normally

### Actual behavior

Website not avaiable.

### Crash logs

New domain: https://www.nettruyenss.com/

Old domain: https://www.nettruyenclub.com/

### TachiyomiJ2K version

v1.7.4

### Android version

Android 15

### Device

S21+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
This is not extension repo.

**Comment by QuangTKD** [comment]
> This is not extension repo.

Sorry for posting here but do you know where I can summit this prob ?

**Comment by kyoyacchi** [comment]
> > This is not extension repo.
> 
> Sorry for posting here but do you know where I can summit this prob ?

Np, if you added Keiyoushi's repo in J2K, you can open an issue on https://github.com/keiyoushi/extensions-source
