### ISSUE TITLE
Manatoki / Newtoki reader doesn't work

### ISSUE THREAD

**Issue by Judeisbad** [Jays2Kings/tachiyomiJ2K#1782]
### Steps to reproduce

1. Download manatoki or newtoki
2. open a manga from those sources.

### Expected behavior

The manga is downloadable and readable.

### Actual behavior

The mangas show up on the list of mangas, but when opening a chapter or attempting to download, the reader doesn't work. 

### TachiyomiJ2K version

1.7.4

### Android version

Android 14

### Device

Samsung A52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by GuPuSi7ff** [comment]
This seems related to domain changes.
I found updated info here:
https://manatoki.site/

**Comment by NaeemaliSEO** [comment]
I tried following your steps, but they don’t seem to be working for me. Currently, I’m accessing Manatoki through this website: [https://manatoki.click/](https://manatoki.click/)
