### ISSUE TITLE
[Feature Request] Data Saving for downloads

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#18]
Currently, Tachiyomi does not provide an option for data saving for downloading chapter. Some sources use a lot of data and takes up a lot of storage space. Data saving would resolve both of these issues. Currently, Manga Rock offers this feature on their app.

A PR has already been made for this feature, it might be helpful to check out it

https://github.com/inorichi/tachiyomi/pull/1526

**Comment by joseph619** [comment]
This might be too complex at the moment, so I request to look at it after implementing other feature requests.

**Comment by Xeiniac** [comment]
TachiyomiSY has a feature like this that uses bandwidth hero, that could be ported to J2K 👀

**Comment by CarlosEsco** [comment]
I'm gonna close this for now.  There are no plans to convert images (as you see the main app wip never got implemented). As for bandwidth hero, requiring someone to setup their own server to compress images is also not ideal
