### ISSUE TITLE
[Beta] [Bug] Open tracking then back twice causes weird ui

### ISSUE THREAD

**Issue by CarlosEsco** [Jays2Kings/tachiyomiJ2K#181]
1.  open a manga
2.  click tracking 
3.  dismiss sheet either with back or clicking outside
4.  immediately click back.
5.  screen jumps to middle of chapter list then backs out

**Comment by Jays2Kings** [comment]
It's more because of how the fast scroller works (which is why I wanna replace it too), since the fast scroll jumps to somewhere else on touch down (even if its hidden) so when you swipe back it jumps.

I'm going to see if I can replace that fast scroll with something better
