### ISSUE TITLE
Hiding spaces between images

### ISSUE THREAD

**Issue by Daviid81** [Jays2Kings/tachiyomiJ2K#1823]
### Describe your suggested feature

An option in the reader settings to remove black spaces between images when reading in a cascade continues.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Change your reading mode to Webtoon?

Either change it per-series, while in Reader > Settings button > Series: Reading mode, or change the default reading mode in J2K Menu > Settings > Reader > Default reading mode

**Comment by Daviid81** [comment]
That's not what I'm referring to, look at the image I'm going to send you to see if there's a way to add an option to remove the spaces between images when reading.
![IMG_20240825_133059](https://github.com/user-attachments/assets/673e3d14-09f9-4f78-adef-b62a04bbb8c6)

**Comment by Smol-Ame** [comment]
@Daviid81 That's literally what the setting I told you does

Try it for yourself

https://github.com/user-attachments/assets/3d834b7a-0191-4436-9814-756e6d9b25db

**Comment by Daviid81** [comment]
Okay, thank you very much. I got confused when you said default reading mode and the black didn't go away, thanks. 😁

**Comment by Smol-Ame** [comment]
Close out the issue if that resolved your issue
