### ISSUE TITLE
[Feature Request] ability to prioritize sources for migration

### ISSUE THREAD

**Issue by Mechanical-sanity** [Jays2Kings/tachiyomiJ2K#183]
### Why/User Benefit/User Problem
Some sources are better than others. this will allow for faster and better source migration

### What/Requirements
(explain how this feature would behave)
This feature will allow source migration to prioritize the better sources, and only then, if there are no options from them, the app will find the manga or mangas through the other sources. 

Also, if there are multiple sources with the same number of chapters, allow an option for the user to choose the source.

**Comment by joseph619** [comment]
What do you mean by 'prioritize'? Tachiyomi has over 350 sources in 15 languages, the app has no way to know which source has most chapters or least without checking all of them (which would make the search extremely long). You can already disable unwanted sources by crossing them out. Recommended sources are mentioned on Website and Discord FAQ.

The feature already exists, explore the app.
