### ISSUE TITLE
Very Slow loading of chapter list with 500+chapters

### ISSUE THREAD

**Issue by Crzyadian** [Jays2Kings/tachiyomiJ2K#185]
App version:.9.81 , .9.82 , beta1 , beta 2
Android version/Device: Honor Holly ; Android Nougat 7.1.2

The chapter list loads very slows 
And sometimes crashes the app 

Tried using another device (vivo 1803)  same bug
 
Works fine with stable/dev

**Comment by CarlosEsco** [comment]
crashes app?  what is your android device and version?

**Comment by Crzyadian** [comment]
@CarlosEsco 
Honor Holly (Hol U19)
Android version 7.1.2

**Comment by Crzyadian** [comment]
![@CarlosEsco](https://i.imgur.com/U2NJNWH.png)

**Comment by Jays2Kings** [comment]
Can you provide details about which manga is causing crashes or issues. I gave yet to see anyone have a crash for loading that many chapters before

**Comment by Crzyadian** [comment]
@Jays2Kings 

Mousou telepathy

I've uploded a gif on discord channel 
 By the name "hoodie_pikachu"
Before

**Comment by Crzyadian** [comment]
@Jays2Kings ![](https://i.imgur.com/Jbjny0J.png)

**Comment by Crzyadian** [comment]
Apparently it's source/extension related problem

Source:mangaonl

Switched over to Mangahasu works fine now
Sorry for disturbance :relieved:

**Comment by Crzyadian** [comment]
I tried other manga with more and less chapters than Mousumi telepathy with same sources as mentioned in above comment

It seems the problem is just with the specific manga(mousou telepathy)

Sorry for the trouble
