### ISSUE TITLE
[Feature Request] Categories for sources in Browse

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#189]
### Why/User Benefit/User Problem
Now that there are so many sources with various types of content (aggregator, scanlator, manhwa, hentai etc), it would be useful if users could categorize sources in Browse. 

### What/Requirements
Similar to how categories are implemented in Library. Users would be able to categorize their favorite sources manually naming and placing the sources. The category order should also be changeable.

**Comment by vipzzx** [comment]
1.0.7 has it. You can close this.
