### ISSUE TITLE
[Feature Request] Custom title aliases. 

### ISSUE THREAD

**Issue by mrcory** [Jays2Kings/tachiyomiJ2K#19]
I personally prefer english titles for my manga. My suggestion is the ability to have an editable title for each manga. For the sake of matching up for syncing the original title should be used by default.

**Comment by joseph619** [comment]
#70 will cover this as well, I think

**Comment by mrcory** [comment]
> #70 will cover this as well, I think

I believe so. #70 would already require the feature I asked for.

**Comment by Jays2Kings** [comment]
Added as of 0.9.75, as well as modifying the other parts of the metadata
