### ISSUE TITLE
[Feature Request] Add universal default option for Display and Sorting Mode.

### ISSUE THREAD

**Issue by IAMNOTRANA** [Jays2Kings/tachiyomiJ2K#192]
Hey, can we add some kind of universal default option for display and sorting mode?
[https://cdn.discordapp.com/attachments/657923584811073566/700364408542461982/Screenshot_20200416-204745.png](url)
Currently its only available as per manga and it become rather pain if you have over 200+ manga in your library. 
Having some kind of option that set display and sorting mode option by default would be great.

**Comment by lmj0011** [comment]
@IAMNOTRANA 
There was talk about this feature in the main Tachiyomi [discord channel](https://discord.com/channels/349436576037732353/694092459839455243/737024214665789533). Apparently this fork is suppose to have some implementation of this. 

This may be what you're looking for? https://github.com/Jays2Kings/tachiyomiJ2K/issues/92

**Comment by CarlosEsco** [comment]
I don't think a global filter will be added at this time but please make a new ticket just for that.

Default option for global filtering of chapters


the global sorting already exists.  when you change a manga's sort it gives an option to change set that as global default
