### ISSUE TITLE
[Feature Request] access internal browser from chapter reader menu 

### ISSUE THREAD

**Issue by clombion** [Jays2Kings/tachiyomiJ2K#194]
Would it be possible to open the internal browser directly from a chapter? It would make it easy to see the comments of the chapter on the source website. It would also be a shortcut to browse the source website using the internal browser, as I sometimes want to do after reading a chapter.

**Current workflow**

I read chapter 3 of a manga uploaded on Mangadex. At the end of the chapter I want to see the comments on the chapter but also check out other works by the author. Currently I would have to 
1. exit the chapter, 
2. change pane, 
3. open the internal browser
4. scroll down to the specific chapter on Mangadex
5. Click on the chapter comments button
6. Do other steps to check out other works by the author.

I've seen the mockups for the next version of the app so I know that there won't be panes anymore, which will streamline one step but not remove it (instead of changing panes we would scroll up). But being able to launch internal browser from the reader interface would streamline another step (instead of having to exit the chapter we would just need to tap the reader to display the internal browser button alongside the usual reader menu options). And if the internal browser opened directly on the relevant chapter in the source website, it would remove yet another step (no need to scroll down to the chapter).

**Expected UX**

1. Tap on manga page to display reader options
2. Tap on "open chapter in browser" button
3. Scroll to comments/tap comments button (depends on the website)
4. Do other steps to check out other works by the author

**Comment by CarlosEsco** [comment]
This is very specific to mangadex though. How many other extensions would you want to view the chapter in browse

**Comment by clombion** [comment]
> This is very specific to mangadex though. How many other extensions would you want to view the chapter in browse

1. Just a quick check showed me that Leviantan Scans, Hatigarm Scans and Zero Scans also have (Disqus) comments enabled on their chapters
2. Even if the website doesn't have a comments per chapter, being able to quickly access the internal browser would be useful for other situations like when a chapter page is not loading in Tachiyomi due to a DDOS check for example. Or simply when you want to browse the website after finishing the latest chapter, for whatever reason (check author's other works, check other series TLed by the group...).

**Comment by Jays2Kings** [comment]
Can't happen because the url to view a chapter and the url to get the list of chapter pages are two different links. Tachi doesn't get the former link so this is impossible to implement with the current way extensions work
