### ISSUE TITLE
[Feature Request] Display chapter count when doing source search

### ISSUE THREAD

**Issue by clombion** [Jays2Kings/tachiyomiJ2K#195]
Most of the time a manga is available from different sources. Very often some of those sources do not have the latest chapters. Sometimes some sources have the latest chapters but not early chapters. 

**Current UX**

The current UX requires us to tap on each source (and potentially wait for manga info to load) to check the number of chapters hosted by each source. 

**Expected UX**

A better UX would have the chapter count being displayed on top of each result allowing at-a-glance source comparison. 

Implementation may be tricky as it may slow down further the fetching process. So it could be proposed as an option activated by a toggle, putting the responsibility on the user to choose between faster result displaying or faster result comparison.

**Comment by CarlosEsco** [comment]
#57

**Comment by clombion** [comment]
Rate limiting is an issue yeah. But right now, when I search for "Otoyomegatari" I find 5 sources with the title. If I want to check the number of chapters held by each source, I have to:

1. Click on an individual source's result
2. Wait for it to load the manga info
3. (soon to be removed if in the next update) go to the chapter pane
4. Check that there are no chapters missing in the middle or at the end (because the chapter list does not necessarily make it obvious if some chapters are missing)
5. Go back to the search result view
6. Repeat steps 1-5 for the other sources

In this situation that's a total of 20 steps to get 1 info (which sources hold the most chapters) and I run the risk of forgetting the chapter count of the first source by the time I can visualise the chapters of the last one. So it's super cumbersome AND does not prevent an additional HTTP request to be made.

So what if we do that HTTP request but in a single step per source? We could have a "fetch chapter count" button displayed on the covers in search View. The same use case that I outlined above would be solved in 5 steps: 1 button click per source. Even if the search loaded multiple results per source, I would only click on mangas that are of interest for me.

I reckon that it could be challenging to add a button on each cover without making the UI feels too busy, but source comparison is a such a common (and currently cumbersome) scenario, I feel that it's worth exploring.

**Comment by CarlosEsco** [comment]
steps with new build are now 
click into result, wait for it load see total number above chapter list.
if you did this with http requests you would still have to wait for all of them to download the manga info and parse it then count the chapters.  so no plans to add this at this time
