### ISSUE TITLE
[Bug] Chapters Looping when reading in webtoon mode

### ISSUE THREAD

**Issue by Ninjistix** [Jays2Kings/tachiyomiJ2K#196]
### Device information
* Tachiyomi version: 9.82
* Android phone & version: 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
The chapter should continue

### Actual behavior
https://streamable.com/kw2apx
Uploaded video

![Screenshot_20200417-034022](https://user-images.githubusercontent.com/12572974/79545157-3c968500-805e-11ea-927f-b00ef4b342a0.png)
Even if you read to the end of the duplicate chapter it still repeats

### Other details
Additional details and attachments.

Happens once in awhile on different Manga's

**Comment by Ninjistix** [comment]
It seems like the problem is with the source, I tired migrating the manga to a different source and it works,


BTW by time I made it to chapter 36 on the previous source (manganelo) it started to loop back chapter 30 no matter how I skipped

**Comment by Jays2Kings** [comment]
Can you provide which source this is happening on?

**Comment by Ninjistix** [comment]
it was mentioned to be Manganelo, I have since moved some of them to Readm, but it seems to have an issues loading the chapters.

**Comment by joseph619** [comment]
Does this still happen?

**Comment by Ninjistix** [comment]
I haven't noticed it happening in a long time maybe it got fixed already
with one of the updates
