### ISSUE TITLE
[Feature Request] allow to migrate a manga to another source from manga info

### ISSUE THREAD

**Issue by panslothda** [Jays2Kings/tachiyomiJ2K#197]
**App version:**
0.9.82
**Android version:**
10
**Issue/Request:**

Currently if I have lets say 200 entries in a source and i want to migrate just one of those entries i need to go to source Migration and then select --> the source --> and select the entry from a list.

It would be much nicer to have the option to simply open the entry in my library and use the 3 dots to then directly get a list of possible new sources. So a migrate this entry to other source button. 

As most of times i am already on the entry in my library when i want to migrate just that one.

**Comment by Ninjistix** [comment]
I second this being able to migrate form the manga info page is better than doing it from the library (for individual cases)

**Comment by DuccinatorAlpha** [comment]
Press the title on the info tab of a manga :/

**Comment by panslothda** [comment]
Ah. Well that is good to know. And very very not intuitive.......

But yes seems to work

**Comment by Ninjistix** [comment]
I didn't know about that, good to know tho, I thought it would have been a menu like from in the library

**Comment by Jays2Kings** [comment]
Added as of 1.0.0
