### ISSUE TITLE
[Bug] some Pages are bugged

### ISSUE THREAD

**Issue by Yogchan** [Jays2Kings/tachiyomiJ2K#198]
### Device information
* Tachiyomi version: J2K
* Android phone & version: android 9 samsung galaxy s8 plus

## Steps to reproduce
1. When you go through a new updated chapter

### Actual behavior
One or two pages don't load and are stuck with the refresh button in the middle

### Other details
When I try to download the chapter with the bugged pages the app force closes

**Comment by joseph619** [comment]
Mention source, manga name and chapter number.

**Comment by Jays2Kings** [comment]
> Tachiyomi version: J2K
Dude....
Please add more details like the what joseph619 said above

**Comment by Yogchan** [comment]
Sorry for the late reply it was hataraku maou-sama on mangaonl source chapter 82 specifically page 19 but it resolved itself after a few days
