### ISSUE TITLE
[Feature Request] let source auto set manga as webtoon (to change reading mode)

### ISSUE THREAD

**Issue by Light-Wing** [Jays2Kings/tachiyomiJ2K#199]
### Why/User Benefit/User Problem
Having to choose for each webtoon to read it as a webtoon gets old... So I thought if extensions would be able to add a category (like manga.webtoom = true), and then the main app reads that and sets the reading mode to webtoon automatically would be great...

### What/Requirements
When the source is setting the info of the genres, usually webtoons have a genre to indicate it (long-strip, webtoon, web comic etc.). And by checking for that genre the source can set the type of reading mode... (I think Neko (the mangadex fork) already does this...)
(I also put this request on the main tachi app fork, but I think things get done faster here, so I'm putting it here as well (though it might not be possible without the extensions-lib being updated to support it))

**Comment by loocool2** [comment]
This feature exists in beta 2, so if you wanna get that now, install that.

**Comment by Light-Wing** [comment]
For the beta, I need to create the apk myself, correct? I couldn't find
anywhere to download it, but it shouldn't be a problem to create it
myself... Thanks

**Comment by CarlosEsco** [comment]
Please don't switch to the beta. It will not get future updates just wait for the next stable release. And don't ask for ETA for that

**Comment by Light-Wing** [comment]
I won't switch to the beta, just checking out what it has, or what it's missing (it's missing a filter to remove manga that you read all chapters, so if it doesn't have any chapters to read it can be hidden... I always have that filter on, and it's one of the first things I found missing... I'm not sure if I should open a bug report or something... So I'll just mention it here and close this request as you already have it planned for the next release. Thank you.)
