### ISSUE TITLE
[Beta] [Bug] "Reset All Chapters" Being a Necessary Prerequisite To Remove Titles From History 

### ISSUE THREAD

**Issue by Zolcry** [Jays2Kings/tachiyomiJ2K#202]
### Device information
* Tachiyomi version: Tachiyomi j2k r2170 (beta 2)
* Android phone & version: Honor Play, EMUI 9.1.0.370

## Steps to reproduce
1. Go to Recents, History, select any manga to Remove. 
2. Upon clicking remove, you will be greeted with the remove screen which gives you the option to remove a title with or without resetting the chapters. 
3. Try to remove without selecting to "Reset chapters for this manga". 

### Expected behavior
Ideally the title would be removed without any chapters being removed. 

### Actual behavior
The title just stays in the history without being removed, unless you tick the option to reset chapters. 

### Other details
Tested on 3 sources, MangaSee Toonily (Under Madara) and MangaDex.
![Screenshot_20200421_192709_eu kanade tachiyomi debugJ2K](https://user-images.githubusercontent.com/58501451/79877876-678c2a80-840a-11ea-971c-593e70d89a7a.jpg)

**Comment by Jays2Kings** [comment]
It will stay if you read chapters back to back, it'll just update to the next last read chapter. If the chapter in the card isn't being updated as well then there's a bug here.

**Comment by Zolcry** [comment]
Ah yes, I tested it and it works. Didn't realise that; thank you.
