### ISSUE TITLE
[Bug] Chapters not updating for series transferred from Manga Rock

### ISSUE THREAD

**Issue by Vedat-Ozkan** [Jays2Kings/tachiyomiJ2K#204]
### Device information
* Tachiyomi version: 0.9.82
* Android phone & version: Pixel 3 XL, Android 10

## Steps to reproduce
1. Migrate Sources
2. Update Library or Update a Manga

### Expected behavior
All manga(s) should update newer chapters.

### Actual behavior
Only manga added manually updates chapters.

### Other details
Most manga migrated from Manga Rock don't work although some do (All of WSJ). 
The new chapters can be accessed through webview.
When you try to manually update a single manga, who you know should update, Tachiyomi gives the error [Attempt to invoke virtual method 'java.lang.Stringorg.jsoup.nodes.Element.text()' on a null object reference] and if you try to manually update a manga that isn't problematic this message doesn't pop up and the manga updates accordingly.
If you remove a manga that doesn't work from the library and re-add it, from the same source, the new chapters are available and the error above doesn't occur when manually updating.

**Comment by CarlosEsco** [comment]
1st off this sounds like a source issue so i would open the issue here.

https://github.com/inorichi/tachiyomi-extensions

**Comment by Jays2Kings** [comment]
2nd you need to mention what source it is or manga that's not working. Plenty of people have migrated without issue. Check the discord faq if the site is working and submit an issue to the link above if its not mentioned
