### ISSUE TITLE
Kissmanga source doesn't work

### ISSUE THREAD

**Issue by medoria0** [Jays2Kings/tachiyomiJ2K#205]
### Device information
* Tachiyomi version: r2170
* Android phone & version: 8.0.0

## Steps to reproduce
1. Download kismanga soure
2. Try to open it

### Expected behavior
Open like normal sources

### Actual behavior
It doesn't load

### Other details
Nothing much

**Comment by Jays2Kings** [comment]
Go to discord and read faq
