### ISSUE TITLE
[Bug] Download queue needs to be started manually

### ISSUE THREAD

**Issue by Caagr98** [Jays2Kings/tachiyomiJ2K#207]
### Device information
* Tachiyomi version: J2K 0.9.82
* Android phone & version: Nokia 8, Android 8.1.0

## Steps to reproduce
1. Choose "download" on any chapter
2. Go to download queue screen

### Expected behavior
The download should start immediately.

### Actual behavior
The download doesn't start until I manually press the resume button.

### Other details
The same happens when new chapters are set to be automatically downloaded.

This all works fine in upstream.

There is also no notification on new chapters or anything, which I suppose should go into its own issue.

**Comment by CarlosEsco** [comment]
closing if this is still an issue on 1.0.7 open a new ticket
