### ISSUE TITLE
[Feature Request] Show manga count in My library 

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#21]
Request feature to have an option to show manga count  for each Category in My Libraries (besides the category name, maybe).

For Category example, it could be-

> Harem (10) Webtoons (15) Action (6)

And option could be added on the sidebar menu, either above or under Download Badges, that's for you to decide.

**Comment by Jays2Kings** [comment]
For library that can be an option. For sources, not so much. Each of the extensions would have to support that feature and not every website has an api to get the total manga count they have

**Comment by joseph619** [comment]
I see, could it be possible to implement for those select sources only which provide the API?

**Comment by Jays2Kings** [comment]
That's more on the extension maintainers + tachi main devs to decide, since they would have to add a new function to each of the extensions to support that, and if that's the case the sources part of this should be made an issue in the main tachi repo

**Comment by CarlosEsco** [comment]
Yea that catalog count will be a hard no.  I don't know of any site that provides a 1 request here's everything we have.  So you are talking multiple http requests just to get a number that will change often

**Comment by joseph619** [comment]
Ok I will remove Catalog from title and description then, just library.

**Comment by pranavtifr** [comment]
It would also be nice to have an unread notification along with the library names. Maybe a setting to choose this number to be the unread manga or a small dot.

**Comment by joseph619** [comment]
New update fixed it somewhat, dont need it anymore
