### ISSUE TITLE
[Feature Request] Auto Webtoon Detectet

### ISSUE THREAD

**Issue by 0kolya0** [Jays2Kings/tachiyomiJ2K#212]
Add
Auto Webtoon Detectet
1) If it is detected, display a window in which you can confirm the presence of Webtoon or leave normal mode and continue reading. (Recommend)
2) Automatically switch the mode when Webtoon is detected without confirmation.

You can search Webtoon on the x and y axes or for example, on tags in the manga.

**Comment by 0kolya0** [comment]
You can search Webtoon on the x and y axes or for example, on tags in the manga

**Comment by joseph619** [comment]
This is already added on Beta and will be available for next release.
