### ISSUE TITLE
[Feature Request] Pull to Refresh 

### ISSUE THREAD

**Issue by fpschubert** [Jays2Kings/tachiyomiJ2K#213]
Request for Pull to Refresh Manga updates on the library. 

Like in Chrome and any other apps when you want to see updates. Clicking the Refresh button is a bit jarring specially if you previously used MR.

**Comment by CarlosEsco** [comment]
Will be in next release

**Comment by Jays2Kings** [comment]
Closing because
1) stable has this already
2) beta is a beta
3) ^ read above
4) You didn't list a version or any info
5) You didn't read the message when installing the beta which said:
6) Don't make feature request for the beta because:
7) read point 2
