### ISSUE TITLE
[Beta] [Bug] White on White Text vice versa

### ISSUE THREAD

**Issue by itoffie** [Jays2Kings/tachiyomiJ2K#215]
### Device information
* Tachiyomi version: 0.9.82
* Android phone & version: Oppo a3s 1803 Android 8.1.0

### Expected behavior
Text on white or light themes should have black text color and Text color on dark or black themes should be white

### Actual behavior
Text on white or light themes has white text and Text on dark or black themes should have white text color 

### Other details
https://m.imgur.com/a/OMxNuYF

okay so after 30 mins of doing things on my phone i found the problem. the OpenGL skia is the one causing the bug

**Comment by Jays2Kings** [comment]
As you've already said it's an issue with your phone, not the beta
