### ISSUE TITLE
[Feature Request] Allow ability to see all the pages in a chapter then choosing one

### ISSUE THREAD

**Issue by DKTsubasa** [Jays2Kings/tachiyomiJ2K#219]
### Why/User Benefit/User Problem
Basically, like what the title say, a feature to see all the pages of a chapter at the same time and picking whichever specific page you want. Like say you are trying to remember a certain scene or image in a chapter, but you dont have the time to go through the pages one by one to find it. 

### What/Requirements
Not sure, maybe add an option in how you view a chapter/manga, like call it a Gallery option and insert it with the options like Read Left to Right, Vertical, and so on.

**Comment by joseph619** [comment]
Duplicate of #200 I think

**Comment by DKTsubasa** [comment]
> Duplicate of #200 I think
Ah, yes, I think it might. Though I'm thinking the feature should be allowed for the chapters in general, not just downloaded?
