### ISSUE TITLE
java.io.IOException error on opening some webtoons.com chapter

### ISSUE THREAD

**Issue by da123rrell** [Jays2Kings/tachiyomiJ2K#220]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
MD2 version 0.9.82
**Android version:**
Android 10
**Issue/Request:**
I've been using the webtoons.com extension for some of my webtoon, but for some reason several chapters cannot be opened, it keeps saying java.io.IOException note that it does not happen in the stable j2k version nor in the official tachiyomi app.
**Steps to reproduce (if applicable)**

 1. Open the "The Gamer" webtoon from the webtoons.com source
 2. Open Ep. 76 CH. 76
 3. A "java.io.IOException" error will occur

**Other details:**
Not all the chapters will experience this, as far as i know, the other webtoon that is also affected by this is "sweet home" on the latest chapter.
Honestly i have no idea wether to post it here or the tachiyomi extension github since  it is only happening in the j2k md2 version, so im sorry if this is the wrong issue page.

**Comment by Jays2Kings** [comment]
Closing because you didn't follow any template here, but it's already fixed for the future
