### ISSUE TITLE
[Feature Request] Ability to use headphone button(s) to navigate in reader

### ISSUE THREAD

**Issue by namelessguy121** [Jays2Kings/tachiyomiJ2K#222]
### Why/User Benefit/User Problem
- This feature will make it easier to read manga while having the phone docked on a table or somewhere further away from the user

### What/Requirements
- For 3 buttons headphones, the volume up and down buttons will behave as next and previous page with the ability to invert them
- For 1 button headphones, clicking the button once will go to next page while clicking it twice will go to previous page
-This feature should behave similarly to volume key navigation

**Comment by Jays2Kings** [comment]
Nah. Use a keyboard
