### ISSUE TITLE
[Feature Request] Includes reverse portrait as an option for the reader 

### ISSUE THREAD

**Issue by namelessguy121** [Jays2Kings/tachiyomiJ2K#223]
### Why/User Benefit/User Problem
- Make some phones easier to hold while charging
- Make it possible to dock the phone while having headphone plugged in for plebs like me that still have a headphone jack 

### What/Requirements
- When flipping phone upside-down, the reader will rotate to reverse portrait

**Comment by arkon** [comment]
You should just use something like this: https://play.google.com/store/apps/details?id=org.crape.rotationcontrol&hl=en

**Comment by Jays2Kings** [comment]
Yeah because it's not being added here
