### ISSUE TITLE
[Feature Request] Favorite sources

### ISSUE THREAD

**Issue by clombion** [Jays2Kings/tachiyomiJ2K#224]
**Problem**
Most of the times I search a limited number of trusted sources that I have filtered from the full list of possible sources available with the extensions I've installed. But 

1. Sometimes I'm not finding anything in my favorite sources and I want to be able to quickly search all the sources then go back to my selection of favs
2. When extensions are updated it is common for a source to be added. But those sources end up selected by default, requiring me to deselect them when I notice them.

**What/Requirements**

A favorite system for sources would allow for quickly switching (using a toggle for example) between the fav sources and all sources for searching, and would avoid new sources popping up among the favorites as they would need to be specifically starred as favorite to be there.

**Comment by KraXen72** [comment]
just uninstall the sources you don't use while you migrate the manga from unused sources to your trusted sources

**Comment by Jays2Kings** [comment]
Basically added with the addition of pinned sources

**Comment by clombion** [comment]
So after getting used to pinned sources, it's really handy but doesn't fully address the feature request.

I think a good way to visuale the idea is to think about the difference in terms of sources for manga and manhwa. 

When searching for Manga, sources like Eldegarde Scans, Leviathan Scans, Manwha Club, Mangazuki... are mostly useless. But they would be my main sources when looking for up to date manhwa. The same distinction exist for manhua. 

The current pinned source system is good to avoiding searching every time across 100 sources when I know that my main 10 sources should have the title. But if you search regularly for manga, manhwa and manhua, you end up having to pin 20+ sources instead, leading to longer search times and cluttered results. 

If I could have preset list of sources, I would switch to the manga, manhwa or manhua preset depending on what I'm searching for. It would even make it possible to include more obscure sources (on top of the 4-5 top ones) within each preset without cluttering the search. 

Maybe I should create a new issue?
