### ISSUE TITLE
[Feature Request] feature to migrate title from categories (not entire library).

### ISSUE THREAD

**Issue by akzn** [Jays2Kings/tachiyomiJ2K#228]
Possibly related to feature [Batch Auto-Source Migration]
### Why/User Benefit/User Problem
there is often some manga site got down (either because of maintenance or they r gone for good), curently its mangaonl.com

if i have a lot of library from that site (50++), migrating would be really slow and painful. 

I make some categories from my libraries to easier the sort and reading.
if there is a feature that can migrate just from the said categories (not from all title on library) that would be good.

### What/Requirements
feature to migrate title from categories (not entire library).
 - if we have multiple categories on the library, migration only fetch title from selected category only.

**Comment by Jays2Kings** [comment]
I'm not really clear on what your saying but you can long press a manga in your library, and long press another, and it will select the manga in between it, then there's a button on the top right to migrate what you selected

**Comment by akzn** [comment]
sorry, english is not my native language
fyi i've updated the app on my phone to 1.0.1
yep pretty much what u r described can fullfill my need for now. But because  on the library page, there is no information about the manga source, I still need to open the manga one by one to know which one to migrate. 
---
If u think that this request is not really interesting, you can close this issue, thanks for this great app

**Comment by CarlosEsco** [comment]
You can type the name of the source in the search bar to filter all manga by that source. Then you know which to migrate

**Comment by akzn** [comment]
whow that is a feature that i dont know, Thanks :D
