### ISSUE TITLE
[Bug] Can't change local manga image cover

### ISSUE THREAD

**Issue by hjdrm** [Jays2Kings/tachiyomiJ2K#232]
### Device information
* Tachiyomi version: 1.0.0
* Android phone: Redmi Note 5 Ai
* Android Rom: Ion OS
* Android Version: 10

### Other details
So, I tried changing the image cover of my local manga and it starts out fine, I can choose different images but the problem is it won't change. Right now my local manga image cover is non-existent.

**Comment by bairagyakushal4** [comment]
My cover is not showing at all, even after doing refresh library metadata, re-add the title but no avail.

**Comment by Jays2Kings** [comment]
This is fixed now
