### ISSUE TITLE
[Feature Request] Filter for unread manga

### ISSUE THREAD

**Issue by ardittristan** [Jays2Kings/tachiyomiJ2K#234]
### Why/User Benefit/User Problem
in version 1.0.0 there is a filter for not started, in progress and read, but before 1.0.0 unread would show what started and in progress now shows.

### What/Requirements
a filter for manga with unread chapters
or
the possibility to select both in progress and not started filters at the same time

**Comment by sirfog** [comment]
Please add this feature.

Unread was my default previous to the upgrade

**Comment by hjdrm** [comment]
Toggle "in-progress" that should sort it to unread.

**Comment by ardittristan** [comment]
> Toggle "in-progress" that should sort it to unread.

in progress doesn't show unread that you've not started reading yet, I have a category with a mix of currently reading and yet to start reading manga and want to see unread for both of those options.

**Comment by DeKleineKobini** [comment]
Would love to see this back.

**Comment by ardittristan** [comment]
Got added back
