### ISSUE TITLE
[Feature Request] Make download button for each individual chapter optional on Recents and Recent Updates View

### ISSUE THREAD

**Issue by serankua** [Jays2Kings/tachiyomiJ2K#236]
**App version:**
1.0.0

**Android version:**
10

**Issue/Request:**
Since not everybody using the app intends to download manga, would it be possible to put a switch in the settings to disable the download buttons attached to every single manga chapter in the Recents and Recent Updates view? The button is kinda obtrusive and repetitive for those of us who do not care about always downloading and instead only read once. 

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
Sexy new looks btw

**Comment by joseph619** [comment]
Downloads button is now made optional for Recents
