### ISSUE TITLE
[Feature Request] bring back original categories

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#237]
Can you please bring the original category system back? I find it much easier to swipe and be able to see which category I'm going to than to pull from the side of the screen.

**Comment by ChestieBooBoo** [comment]
I agree, the new categories, while sleek, is considerably more cumbersome to use.

I use categories extensively and it's way harder for me to switch between categories with the new system.

**Comment by CarlosEsco** [comment]
use regular tachiyomi.  They arent coming back

**Comment by Jays2Kings** [comment]
No

**Comment by joseph619** [comment]
Tachiyomi 0.9.0 has tabbed categories, fyi

**Comment by vongdong** [comment]
Not sure why you guys are against bringing it back as it makes it much easier to navigate through categories. I see that I can have the fast scroll always shown but it doesn't look nice. Don't need to bring tabs back, just swiping is enough.
