### ISSUE TITLE
[Feature Request] Make covers slightly larger in libraries and move badges.

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#238]
Can you please make it so the covers in the libraries are slightly larger? It would make it look nicer with smaller gaps between the covers. I know that would sort of interfere with the badges but if you could also move them more to the right so they stay on the cover rather than overhang then that would be nice.

**Comment by CarlosEsco** [comment]
No plans to change padding between covers at this time
