### ISSUE TITLE
[Feature Request] Fast Scroll Toggle Button

### ISSUE THREAD

**Issue by TheWalkyrian** [Jays2Kings/tachiyomiJ2K#239]
## Default Device Information
**Application Version:** 1.0.0
**Android Version:** 10
**Android Skin:** Samsung One UI 2.1

## Feature Request
**[1]** I personally use Samsung's Scheduled Dark Mode. During scrolling, the fast scroll tab pops out in the dark theme, looking completely off and not falling in the same theme as with the rest of the application's look. This leads to the Library screen looking a lot more cluttered than it should be.
**[2]** I manage a small library of manga with 3 categories, separating them from types rather than genres. Because of having a small library, having a fast switch with only 3 letters popping up, two of them the same (Manhwa and Manga) it's more of an annoyance than actually helping.

### Requirements
I personally have two ideas in my mind of how to implement it. Personally, I'd be fine with either of them, whatever would be easier to implement.

Have a Toggle for Fast Scroll under "Display Options", in case it would only edit it for Library.
OR
Have a Toggle for Fast Scroll under "Settings -> General", in case it would be omitted across the entire application.

## Side Note
Because the touching area for Fast Scroll is small and put to the edge of the device, people utilizing Samsung's One Handed Operation+ have a higher chance of triggering their edge function buttons by accident rather than actually being able to use the fast scroll.

**Comment by KraXen72** [comment]
+1 this would be a good feature to hide the quickscroll
or add a setting to only show if we swipe from the side
or be able to hide it with swiping right until you go back from reader or restart app

**Comment by Paul-Tra** [comment]
Hello, 

we are two people interested in manga and we find your application interesting. We propose to solve this problem.

Can we take it?
And any other suggestions regarding the problem?

We are two guys (@LeoPaulC & me).
Kinds regards.
