### ISSUE TITLE
[Bug] Sorting Preference Resets

### ISSUE THREAD

**Issue by ChestieBooBoo** [Jays2Kings/tachiyomiJ2K#241]
### Device information
* Tachiyomi version: 1.0.0
* Android phone & version: Pixel 2 - Android 10

## Steps to reproduce
1. First step: Go into manga
2. Second step: Return

### Expected behavior
Sorting Preferences Saved

### Actual behavior
Sorting Preferences Resets

If this was a change, please also refer to #240

**Comment by Jays2Kings** [comment]
Fixed as of 1.0.1
