### ISSUE TITLE
[Feature Request] add horizontal categories option

### ISSUE THREAD

**Issue by ImRyley** [Jays2Kings/tachiyomiJ2K#245]
### Why/User Benefit/User Problem
(explain why this feature should be added)
As someone that collapses categories, the previous horizontal library was technically the same except it was more convenient and auto collapsed and uncollapsed making it smoothe.
### What/Requirements
(explain how this feature would behave)
You could have an option under library display options called horizontal categories and when the option box is ticked it would make the library categories horizontal with the auto collapse like previous tachiyomi.

**Comment by CarlosEsco** [comment]
No. Use stable if you want categories
