### ISSUE TITLE
Webtoons reading

### ISSUE THREAD

**Issue by Yukkun** [Jays2Kings/tachiyomiJ2K#246]
**App version:**
1.0.0
**Android version:**
7.1.2
**Issue/Request:**
Unable to switch reading style of webtoons to anything else.
**Steps to reproduce (if applicable)**

 1. Select webtoon you want to read
 2. From settings try to change the reading style to anything else and it refuses to do it
 3. Get frustrated and complain here

**Other details:**
I hate webtoons reading style and some of them work way better in manga style when it comes to reading them so let me choose

**Comment by Jays2Kings** [comment]
You hate the webtoon reading style....on a webtoon?

**Comment by Yukkun** [comment]
Yes, very much. Good example of this is ""My Wife Is A Man" in Mangakakalot. It has the webtoon tag, but it reads lot better in manga-style rather than webtoon-style. And either way, not being able to change the style how you read it, is a bug.

**Comment by CarlosEsco** [comment]
if you are not a fan you can easily use the main app that doesn't do this.

**Comment by Yukkun** [comment]
I had to switch over from the main app due to Kissmanga's hunt on Tachiyomi-users, and trying to migrate everything to this one was very painful. I'd rather not go through similar process again. I'd just much rather see this bug get fixed and provide any information needed for fixing it.

**Comment by AlphaCentauri** [comment]
Well, for starters, how about you use a better source considering "My Wife Is A Man" is definitely _not_ a webtoon. Works as expected using MangaDex as the source.

**Comment by Natsulus** [comment]
Also getting this bug. It's nice that the app detects webtoon tags, but sometimes its a case of the tag not actually fitting the series. Trying to read "God of Martial Arts" from Mangadex Source, but pages are clearly made to be read by page and not in webtoon format.
Would be good for it to auto detect webtoons a single time so the viewer can be changed.

**Comment by CarlosEsco** [comment]
@Natsulus with dex you should report on their website that it has wrong tags.  I just did that for you but for future reference

**Comment by joseph619** [comment]
This appears to be a source issue, app is not responsible for sources with wrong tags.

**Comment by Yukkun** [comment]
> This appears to be a source issue, app is not responsible for sources with wrong tags.

Its just not Mangakakalot I had this issue with. This also doesnt happen with just webtoon-tag either. It can happen also with manhua (or manhwa, I always mix the two)-tag

**Comment by RyuFive** [comment]
Same case with me that i can't change reading style. I understand that _most_ manhwas/webtoons are meant to be read top to bottom.
The manhwa i am reading is "The Breaker" and this one is not really a top to bottom read. Would be nice if i could change it but nothing serious. 
[Link to a screeshot](https://media.discordapp.net/attachments/349436576037732355/712879743829147679/Screenshot_20200521-090846.png?width=297&height=475)

**Comment by jendralcox** [comment]
Get this bug too. Im on manga "Rainbow" and it must be horizontal to read it. I read it in Mangahub latest version, but the view mode is webtoon, can't change it to horizontal (left right )

**Comment by CarlosEsco** [comment]
See above. Edit the tag if you want to change the reading mode.
