### ISSUE TITLE
[Bug] a mass unread button or rereading option missing when all is read

### ISSUE THREAD

**Issue by fakeee722** [Jays2Kings/tachiyomiJ2K#247]
It would be nice to just click one button to set all on the chapters of one series unread instead of swiping each chapter 

It could work like the "Mark previous as read" button, just have a second one that says "Mark previous as unread"

Thanks for the great app and sorry if this isn't well said I don't know how this kind of thing works

**Comment by ChestieBooBoo** [comment]
There is a button my guy...
Check the three dots at the top.

**Comment by EasilyEntertained** [comment]
> There is a button my guy...
> Check the three dots at the top.

I have clicked it and it's not there
![Screenshot_20200501-164219_TachiyomiJ2K](https://user-images.githubusercontent.com/64665636/80843782-c2700f80-8bca-11ea-80ad-9d0df1ee6c3d.jpg)

**Comment by Jays2Kings** [comment]
It's a bug, if you make a single chapter as unread the option appears
