### ISSUE TITLE
[Bug] Latest Chapter Sorting not working as intended

### ISSUE THREAD

**Issue by ChestieBooBoo** [Jays2Kings/tachiyomiJ2K#248]
#152 # Device information
* Tachiyomi version: 1.0.0
* Android phone & version: Pixel 2 Android 10

### Expected behavior
All newer updates chapters are at the top when sorting by latest chapter

### Actual behavior
Some newer updates are being pushed to bottom when sorting by latest chapter

**Comment by Jays2Kings** [comment]
As you've said it's working now
