### ISSUE TITLE
[Feature Request] Snap the zoom around the screen width.

### ISSUE THREAD

**Issue by m-vlad** [Jays2Kings/tachiyomiJ2K#250]
### Why/User Benefit/User Problem
Previously you couldn't zoom out further than the max page width. Now you can zoom out further and that's cool, that's fine, but you can't get back to that perfect 1:1 page width to screen width ratio other than closing the chapter and opening it back.

### What/Requirements
have the zoom snap when the zoom is around that value so it's not slightly zoomed in/out.

**Comment by Jays2Kings** [comment]
You can by double tapping
