### ISSUE TITLE
[Bug] Viewer stuck in webtoon mode

### ISSUE THREAD

**Issue by danwill2000** [Jays2Kings/tachiyomiJ2K#251]
### Device information
* Tachiyomi version: 1.0
* Android phone & version: OnePlus 6, android 10

## Steps to reproduce
1. View webcomic
2. Try to change viewer from webtoon to any other.
3. Page refreshes
4. Webtoon viewer remains selected.

### Expected behavior
Should change viewer

### Actual behavior
Gets stuck in webtoon viewer

### Other details
Tried clearing cache, didn't resolve issue.

**Comment by Jays2Kings** [comment]
Which webcomic and which source

**Comment by danwill2000** [comment]
@Jays2Kings Solo Leveling -mangakakalot, however the bug is effecting all the webtoons in my library, regardless of source or title. For instance tower of god from webtoons is also affected.

**Comment by danwill2000** [comment]
Another user with the same issue here ---> https://github.com/Jays2Kings/tachiyomiJ2K/issues/246

**Comment by danwill2000** [comment]
Video showing issue here --->  https://drive.google.com/file/d/1q86HvDJwNVvH1tOKK1cJt10aOwfMKbzE/view?usp=drivesdk

**Comment by Jays2Kings** [comment]
Right this is a duplicate so it's closed
