### ISSUE TITLE
[Feature Request] Category UI proposal

### ISSUE THREAD

**Issue by m-vlad** [Jays2Kings/tachiyomiJ2K#254]
Transcripts were added after the images for readability and search reasons

**Why/User Benefit/User Problem**
![export-0002](https://user-images.githubusercontent.com/22298459/80847919-4943dd00-8c09-11ea-85e3-410cce502759.png)
Both filter systems affect the library at the same level. Many users find this confusing as categories lose their sandboxing purpose and instead get the same importance as filters, however users have different categories for different purposes and use-cases, some of which are used less than others. Compacting the unneeded ones is a temporary solution, but it only treats the symptom.

### What/Requirements
![export-0003](https://user-images.githubusercontent.com/22298459/80847924-4ea12780-8c09-11ea-91d6-ddae14901a91.png)
My suggested solution would be to move the category in place of the "Library" text, similar to how instagram allows you to change profiles if you are logged into more than one at the top of the profile page. The solution meets the old design halfway. This allows both filters and compartmentalisation to work concomitantly (big words i know) and it makes the transition between categories be a more conscious decision instead of the app making the decision for you. Different categories, different usage, different mindsets.
The user should be in control of such changes. Spotify doesn't put all your playlists one after the other in a huge home screen, it gives you the option to go to them individually.
Finally, compartmentalisation helps with organisation, while the current system does try to some degree to make it easier to filter the library, the categories losing their function makes it seem like you're trying to move away from the concept of categories alltogether, and that's fine for some reasons, but at the moment the filters aren't powerful enough by themselves and they lack functionality categories had (like only letting certain categories get updated). Until such issues are fixed, categories are still a must needed feature (and might still be after, who knows) for easier organisation.

**Comment by m-vlad** [comment]
It was brought to my attention that this is how it worked in one of the betas but the speed scroll was considered instead of this. I hope you can reconsider the decision, the fast scroller is not a good navigation device, using the first letter of the category doesn't always work properly especially if one has categories that start with the same name. the scroller is also very small and this still doesn't solve the issue of having everything dumped in the same screen and filtered by both categories and filters at the same time.

**Comment by eternalcakes** [comment]
Agree. I used the category function as a sandboxing option, as I have over 500 manga titles saved (lots of old manga kept on 'to read' list). 

Additionally, current 'collapsed' categories have way too much space even when collapsed. Like, I could collapse 4 categories and my screen is filled up? 

Need some way to hide categories and to jump to categories as desired, especially as _everything_ appears in the default category so you can't avoid it...

**Comment by clombion** [comment]
+1 Would love this. Simple and efficient, nothing in the current UI would need to change, at the exception of the added dropdown. But it would make navigating my 8 categories less straining mentally as I have 1k+ manga sorted across these and categories starting with the same letter. Also my categories are functional (completed but unread, completed and read, ongoing but not reading etc) and not thematic, so scrolling through all of them doesn't match my mental map of the feature.

**Comment by m-vlad** [comment]
The newest 1.0.2 version implemented something similar that makes both workflows of having categories one after another and having a single active category work without much hassle. I think that satisfies the issues brought up and I will close this Issue now that it's no longer a problem.
