### ISSUE TITLE
[Feature Request] Smaller Grid option 

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#255]
### Why/User Benefit/User Problem
For users who wish to have smaller sizes grid options. It would benefit users who have smaller screens or wish to be able to view more manga on the screen. The current choices (small, medium, large) are still too big. (2,3 and 4 columns respectively.)
![Screenshot_20200502-010703_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/80855702-68df0380-8c11-11ea-9af5-f5fb53e84221.jpg)
![Screenshot_20200502-010707_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/80855703-68df0380-8c11-11ea-9f14-b29c7426257c.jpg)
![Screenshot_20200502-010712_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/80855704-69779a00-8c11-11ea-8cc1-07033b91a533.jpg)

### What/Requirements
Have an additional option where it is 5 columns (size xsmall) it is the perfect size in my opinion where I can see the cover page and the title page all at once and more on the screen. 
Screenshot taken from stable
![Screenshot_20200502-014059_Tachiyomi](https://user-images.githubusercontent.com/59638889/80856259-51eee000-8c16-11ea-854c-43a18566ba72.jpg)

**Comment by eternalcakes** [comment]
Agree. I also have 500+ manga listed (some read, many to-read). Would also suggest having a list as in the past.
