### ISSUE TITLE
[Bug] Library Fast scroll

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#256]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Note 9, Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Letters, number, and emojis are to be displayed on the library fast scroll.

### Actual behavior
Letters and numbers are being displayed but only 2 emojis are displaying. The rest are question marks.

### Other details
Additional details and attachments.
![Screenshot_20200501-193547_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/80849085-a75dc980-8be3-11ea-9825-dd281401d8fa.jpg)

**Comment by CarlosEsco** [comment]
Jay I assume it's the custom system font..

**Comment by vipzzx** [comment]
There is no problem in the library.  Only on the quick scroll.

![Screenshot_20200501-195422_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/80849548-9615bc80-8be5-11ea-88d8-bed172aa1ec9.jpg)
![Screenshot_20200501-195413_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/80849549-96ae5300-8be5-11ea-8404-cd4fb129cade.jpg)
