### ISSUE TITLE
[Feature Request] Add an option to use the old UI

### ISSUE THREAD

**Issue by Buexta** [Jays2Kings/tachiyomiJ2K#257]
App version: 1.0.1

Android version: 9

Request: Please add an option to use the old UI from the previous build. I found it way better to navigate and generally more user-friendly than the new UI version. Also, it makes categories obsolete, as you can't navigate them properly.

**Comment by CarlosEsco** [comment]
Nah dog. Use stable 0.9.0

**Comment by Jays2Kings** [comment]
No
