### ISSUE TITLE
Dedicated Updates Button at the bottom

### ISSUE THREAD

**Issue by TheTabbingman** [Jays2Kings/tachiyomiJ2K#259]
Dedicated updates button at the bottom of the screen so you can get to the updates faster like the normal tachiyomi

**Comment by Jays2Kings** [comment]
Regular tachiyomi has a dedicated update button at the bottom? That's news to me

Anyway long press the library icon

**Comment by TheTabbingman** [comment]
Button for listing updates not for starting an update

**Comment by TheTabbingman** [comment]
I found a way to do it if you use the filter button at the top and select only updates but the icons are too big so it would be nice if you could make them smaller
