### ISSUE TITLE
[Feature Request] (Manually) merge iterations of the same manga from different sources

### ISSUE THREAD

**Issue by MxFlix** [Jays2Kings/tachiyomiJ2K#26]
Why/User Benefit/User Problem
- To save space in My Library
- To be able to see all sources' chapters for a single manga close to each other.

What/Requirements
A manga would have a "Link" button, allowing the user to select another manga from their library. Upon linking, the two (or more) manga would take up only one spot in the library. When looking at the details, switching between the sources could be done in a manner of different ways. I'm imagining a bar at the bottom with the different sources, which can maybe be reordered. This bar could also have badges for the numbers of new chapters, based on the most recent refresh.
The Tracking part of each manga should maybe be source-independent.

**Comment by joseph619** [comment]
This sounds like a big UI change to me.

**Comment by MxFlix** [comment]
Not necessarily, on the UI-side, it could be as small as a source-switcher on the manga page, and an additional button to select other manga to link.

**Comment by Doomsdayrs** [comment]
*steals notes for shosetsu*

**Comment by joseph619** [comment]
This already exists kind of on TachiyomiAZ

**Comment by az4521** [comment]
> I think this exists kind of on TachiyomiAZ, but it crashes
the crashing is fixed on tachiAZ now, btw. i'm pretty sure jay just doesnt want to add this because it's a pain in the ass

**Comment by Jays2Kings** [comment]
Correct az, so it's not getting added. I wanted to see how az/eh does it and it's not worth the headache
