### ISSUE TITLE
[Feature Request] Option to swap chapter title and manga title for updates in recents section

### ISSUE THREAD

**Issue by Th3N3rdyGam3r** [Jays2Kings/tachiyomiJ2K#261]
### Why/User Benefit/User Problem
When using the "Recents" section either with "Group all" or "Only updates", the manga title is in a smaller font and is below the chapter title. I prefer the manga title on top like how it is in the "Recent updates" section since the manga title is more important to me than the chapter title.

### What/Requirements
Have an option in the settings that swaps the chapter title and the manga title for the updates in the recents section

**Comment by joseph619** [comment]
Chapter and manga title are now swappable in Recents
