### ISSUE TITLE
[Feature Request] Side swipe gesture in library to jump down category lists

### ISSUE THREAD

**Issue by anonymousUsers1** [Jays2Kings/tachiyomiJ2K#263]
I really like the new look of the app, but I'm not great at clicking the tiny jump between different category options on the right hand side of the screen. An option to swipe left or right to jump forward or back across that list would be helpful. Similar to how apple laptops let you use three fingers to switch apps.

### Why/User Benefit/User Problem
(explain why this feature should be added)
Navigating between categories requires a lot of vertical movement or fine control to select the desired option. A single swipe is more natural and offers more fine control.

### What/Requirements
(explain how this feature would behave)
While on the library screen a swipe left to right takes you to the previous category, a swipe right to left takes you to the next one.

**Comment by Jays2Kings** [comment]
You know after closing the same thing so many times I might just consider it now
