### ISSUE TITLE
[Bug] "Open in App" not working from Firefox Mobile

### ISSUE THREAD

**Issue by clombion** [Jays2Kings/tachiyomiJ2K#264]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Google Pixel 3 Android 10

## Steps to reproduce
1. Open mangadex manga page on Firefox Mobile 
2. Try to use the "open in app" option either via the little icon in the address bar or via long click on the manga image (which displays the "open in Mangadex" option, which refers to the Tachiyomi-installed Mangadex extension).

### Expected behavior
Tachiyomi should open the manga's overview page

### Actual behavior
Version 1.0.0: Tachiyomi crashed right away and would keep crashing if reopened from recent app menu. Needed to force quit the app
Version 1.0.1: Nothing happens when tapping the "open in app" option. 

### Other details
Works in Chrome Mobile or Firefox preview, just not Firefox Mobile stable (haven't tested on any other browser). Firefox preview/beta (which uses the same engine as preview)  has very limited support for extensions so "use firefox preview/beta instead" is not an option.

![Screenshot_20200502-060417](https://user-images.githubusercontent.com/8268300/80855083-326bad80-8c3e-11ea-9306-ef928eae3541.png)

**Comment by myrul0225** [comment]
Nhentai suffer from the same problem. Also not working if someone sent the mangadex or nhentai link in any messaging apps (Discord, WhatsApp, Telegram, etc..). Link open correctly with tachiyomi stable v0.90

**Comment by Jays2Kings** [comment]
Fixed for next release
