### ISSUE TITLE
[Bug] Clicking on manga name not launching source search

### ISSUE THREAD

**Issue by clombion** [Jays2Kings/tachiyomiJ2K#265]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Pixel 3 Android 10

## Steps to reproduce
1. Go to any manga overview page
2. Click on manga title

### Expected behavior
It should launch a source search using the manga title

### Actual behavior
Nothing happens. 

### Other details
Worked until 1.0.0 update

**Comment by CarlosEsco** [comment]
#252
