### ISSUE TITLE
[Bug] Incomplete application language change on app restart

### ISSUE THREAD

**Issue by MusicOnline** [Jays2Kings/tachiyomiJ2K#267]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Samsung Galaxy A20s on Android 10

## Steps to reproduce
1. Set device language to Japanese
2. Install the app
3. Open the app to find that the app language is set to System Default
4. Change app language to English (United States)
5. Get expected behavior.
6. Kill and restart app
7. Get actual behavior.
8. Change app language to English (United States) (select the same option despite already selected)
9. Get expected behavior.
10. Repeat steps 6 to 9.

### Expected behavior
All strings change to English.

### Actual behavior (on restart of app)
Most strings change to English, except the "Sources" title in the Browse tab as 出典 and the "Installed" header in the unpulled Extensions sheet as インストール済. When the Extensions sheet is pulled up, the "Extensions" title then turns into 拡張機能. However, other areas which have localized strings (as can be seen when changing the language into Japanese) show English strings correctly (eg. each section name in Settings).

### Other details
The localization is not good... (eg. "About" in settings as 約, but unrelated to the bug)
(I now realize localization is from the original Tachiyomi app, however the bug described above still stands.)

**Comment by CarlosEsco** [comment]
This isn't really a bug the application changed from main app and main app has all the localiaztions

**Comment by MusicOnline** [comment]
I have updated the bug details and am able to reproduce the issues every time. The "Other details" section is unrelated to the actual bug and I have edited it to state as such.
