### ISSUE TITLE
[Bug] App Crashed & Not responding when deleting downloaded chapter

### ISSUE THREAD

**Issue by xSteins** [Jays2Kings/tachiyomiJ2K#268]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Mi Pad 4 Android Pie

## Steps to reproduce
* Open 3 dots on the top left manga and select remove all download manga

### Expected behavior
* With the old version (0.9.2)  deleting chapter is much faster even with more chapter downloaded.

### Actual behavior
* When remove button is pressed, there's a slight delay and some manga with more downloaded chapter often makes the app crashed.
![Screenshot_20200502-132138](https://user-images.githubusercontent.com/42110361/80857022-0a4d7000-8c79-11ea-8787-62d48dacb190.jpg)
![Screenshot_20200502-132111](https://user-images.githubusercontent.com/42110361/80857052-3ec12c00-8c79-11ea-9889-34c830748230.jpg)

### Other details
*I used the old download directory which is /storage/emulated/0/Tachiyomi/downloads

**Comment by CarlosEsco** [comment]
Should be fixed in #537
