### ISSUE TITLE
[Bug] Blank name category crashes app

### ISSUE THREAD

**Issue by GrenadeSpamr** [Jays2Kings/tachiyomiJ2K#269]
### **Technical Information:**
**App version:** 1.0.1

**Android version:** Android 9, One UI 1.0 (Galaxy S8)

### **Issue:**
App crashes after giving a category with a blank name and refuses to open after the fact.

### **Steps to reproduce**

 1. Edit a category.
 2. Change the category's name into a blank space.
 3. The app should have crashed once entering Library view. 

**Other details:**
Already had blank name categories prior to this version (0.9.8.1) which carried over and the app worked, only after creating a new blank name instance did the app crash. Modifying said existing blank name categories also crashes the app. This happens on categories with or without content in it.

Clearing the app's data makes for a workaround.

**Comment by CarlosEsco** [comment]
Realistically I feel blanks shouldn't be an option

**Comment by GrenadeSpamr** [comment]
Bug has been fixed by commit cdf2a16731da6c1ffa3dcdeabae6d9d64d2521c0 and blank name categories are now possible again via version 1.0.2.
