### ISSUE TITLE
[Bug] Reader bottom panel stretched too large for Android 10 Gesture Navigation 

### ISSUE THREAD

**Issue by geominorai** [Jays2Kings/tachiyomiJ2K#271]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Samsung Galaxy S9+, Android 10

## Steps to reproduce
1. Enable Android 10's gesture navigation rather than the default navigation bar buttons
2. Open a manga to read
3. Tap to show controls in reader

### Expected behavior
The slider should be at the bottom of the screen.

### Actual behavior
There is unnecessary extra space under the slider due to the lack of an Android on-screen navigation bar.  This also affects phones that have physical navigation buttons.

### Other details
[Screenshot](https://i.imgur.com/P7xtcjo.jpg)

**Comment by CarlosEsco** [comment]
Thats by design so you when you do the recents gesture on a10 you don't trigger the slider on accident like previous versions of app

**Comment by Jays2Kings** [comment]
How do you know it affects phones with physical buttons if you have an s9? the space isn't random it's padded because that's how much space the gesture to go home or swap apps takes up. If you turn off gesture navigation and use traditional navigation you will notice there isn't extra padding because there isn't a gesture area.

The space is necessary to swipe up.

**Comment by geominorai** [comment]
I presumed it was an overlooked issue since the amount of space seemed similar with gesture and traditional navigation buttons, but on closer inspection I see the gesture ones have slightly smaller space -- albeit large enough to still be aesthetically displeasing.

I later checked a device with hardware buttons and found it did not have this space, so my apologies for the assumption there.

**Comment by geominorai** [comment]
I also have not been able to accidentally trigger the page scrollbar or buttons on that panel while using navigation gestures on the original Tachiyomi 0.9.2, which does not have this lower panel stretched.

**Comment by CarlosEsco** [comment]
it has happened before and this is not going to be configurable
