### ISSUE TITLE
[Bug] Inconsistent page-order behavior within downloaded chapters that have missed(?) pages

### ISSUE THREAD

**Issue by Jerrk** [Jays2Kings/tachiyomiJ2K#272]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Galaxy Note 8, Android V9

## Steps to reproduce
1. Open a downloaded chapter
2. Scroll down until you reach a blank(?) page

### Expected behavior
The chapter should navigate as expected

### Actual behavior
The chapter will jump around between pages not consistent with their actual numbering.

### Other details
I took a screen recording of the issue, might be easier seeing the behavior rather than me trying to explain it. where you can see how it skips between a bunch of pages, deloading the entire chapter.

The video shows best at the end where you can see as i reach a blank page, i immediately scroll back to the previous page but that page has now changed to some other page.
**God Of Blackfield ch. 19 spoilers**
https://streamable.com/kohtkh

**Comment by CarlosEsco** [comment]
can you check it file explorer that all images are present
