### ISSUE TITLE
[Bug] Reader pinch-zoom acceleration can yeet manga pages off screen

### ISSUE THREAD

**Issue by geominorai** [Jays2Kings/tachiyomiJ2K#273]
### Device information
* Tachiyomi version: 0.9.81 ***and*** 1.0.1
* Android phone & version: Samsung Galaxy S9+, Android 10

## Steps to reproduce
1. Enable webtoon view mode.
2. Pinch to zoom in/out quickly, but this also happens occasionally even if not done in quick succession.

### Expected behavior
Pinch-zooming should keep pages on screen.

### Actual behavior
All manga pages can get yeeted partly, or fully into oblivion.

### Other details
[Video](https://i.imgur.com/zjPG9S7.mp4)

This is possibly related to the same bug behind #115.

**Comment by geominorai** [comment]
This can also be very reliably reproduced by double-tapping to zoom out, but the second tap is a bit away from the first tap.

[Video 1](https://i.imgur.com/kLUbA77.mp4)
[Video 2](https://i.imgur.com/R77Ac5v.mp4)

**Comment by CarlosEsco** [comment]
#115
