### ISSUE TITLE
[Bug] Inconsistent global default view settings and individual series settings

### ISSUE THREAD

**Issue by Bombonfun** [Jays2Kings/tachiyomiJ2K#274]
Xiaomi Redmi Note 7 SD660 4GB/64GB
* Tachiyomi version: 1.0.1
* Android phone & version: MIUI11.0.7Global Android 9PKQ

## Steps to reproduce
1. If you change the viewer settings (Left to Right, Webtoon...) in a specific series or comic, only the view setting for that series changes, and remains the default for all other series.
 But, if you change the rotation settings (Lock Portrait, Lock Landscape...) in a series, it also changes the default rotation setting in the entire app.

### Expected behavior
Instead, some series should be landscape, and some portrait. Changing the rotation setting of a series should only change the setting for that series, like the viewer setting, and not change the default for all series.

### Actual behavior
It changes the default rotation setting in the main reader setting, even though it's only changed inside a series.

**Comment by Jays2Kings** [comment]
That's not a bug, the wording is "viewer for series" and "rotation" not "rotation for series". It is intended and theres already a feature request for it
