### ISSUE TITLE
[Bug] when opening a new manga from any source it will start downloading automatically

### ISSUE THREAD

**Issue by vzvoz** [Jays2Kings/tachiyomiJ2K#275]
### Device information
* Tachiyomi version: latest 
* Android phone & version: note 9 v10

## Steps to reproduce
1. First step: enter any source 
2. Second step: open any manga that hadn't been added to your library 

### Expected behavior
This should happen.
the manga shouldn't start downloading automatically 
### Actual behavior
This happened instead.
the manga started downloading automatically upon opening 
### Other details
Additional details and attachments.

**Comment by vipzzx** [comment]
this has been fix. can close this issue
