### ISSUE TITLE
[Feature Request] Pressing title of manga within manga details page searches for title in sources

### ISSUE THREAD

**Issue by GreatestFool** [Jays2Kings/tachiyomiJ2K#279]
### Why
In the older version before v1.0.1, up-stream Tachiyomi had this neat little hidden feature of letting you press the title (and authors I think) of a manga within the manga details page to search for it with all your selected sources. It is really, *really* nice to have for users, simply because it saves a lot of time when you need to check if you already have it added through another source. It has since been removed with the MD2 redesign.

Please consider adding this again. It's such a nice little feature to have!

**Comment by CarlosEsco** [comment]
#252
