### ISSUE TITLE
[Bug] Chapter Unloading?

### ISSUE THREAD

**Issue by Natsulus** [Jays2Kings/tachiyomiJ2K#284]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: OnePlus 5 & Android 9

## Steps to reproduce
1. Read manga and swipe to the next page

### Expected behavior
Page should be loaded and displayed normally

### Actual behavior
This happens instead
<img src="https://user-images.githubusercontent.com/7202306/80868514-8cbc4b00-8cde-11ea-8b7e-36a129b36692.png" height="400" />
and all subsequent and previous pages appear blank like that too. I've tried various manga from different sources, downloaded and not, fiddled with a couple of reader settings, but I always end up getting the blank pages.
If you immediately swipe back to the previous page when you get an unloaded page, it will still be loaded, but pages further back are unloaded. If you go further than 2 pages from the loaded page, it also seems to unload.

### Other details
Only way I've figured how to deal with this is exiting the chapter and opening it back up, though most of the time I'll be put back to the first page instead of where I exited the chapter from and would soon run into the blank pages again.
I also have the same issue as #272 with webtoons and suspect it might be an issue that stems from a similar or the same problem.

**Comment by Wrath6** [comment]
I'm also facing the same it's even showing like this in the downloaded chapters it's really annoying 
![IMG_20200502_213739](https://user-images.githubusercontent.com/64690856/80869331-7baf1200-8cbd-11ea-93ff-67f72032b797.jpg)

**Comment by Jerrk** [comment]
I also have this issue, i've noticed if i zuum out allt the way and scroll up/down that SOMETIMES fixes it.

I also use an external sd card for the downloaded storage, is that something the two of you use as well?

**Comment by Wrath6** [comment]
Nope I'm just using internal storage to download the chapter but still happening. This is really ruining my manga reading.

**Comment by Jays2Kings** [comment]
Closing as its fixed for next release

**Comment by melink14** [comment]
Still seeing this in the new version but much less. Saw it in a couple regular rtl manga

**Comment by Jerrk** [comment]
I still get this issue as well, it is much less frequent though. 

I can always fix the issue by pulling down the quick settings and then going back to tachiyomi.

It's like tachiyomi losing the focus will fix the issue for some reason.

I'll see if i can get a demonstration of the issue..
