### ISSUE TITLE
[Bug] Recents tab gets broken when opening manga

### ISSUE THREAD

**Issue by xlbobby** [Jays2Kings/tachiyomiJ2K#285]
**App version:** 1.0.1

**Android version:** Android 10

**Device**: Xiaomi Mi 9T

**Issue/Request:** Manga stuck on background

**Steps to reproduce (if applicable)**

 1.  Open manga title (not chapter from "Continue reading"
 2. Open a chapter
 3. Go back to recents tab

**Other details:**

video and pictures: (imgur album) https://imgur.com/a/ewq1mdO

**Comment by yul-oh895** [comment]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Motorola One Vision w/ Android 10 and security update April 1, 2020.

This also happened to me with the same steps to reproduce the bug.
In my case, the last read manga (Killing Bites) was duplicated and left at the top on the background.

[https://imgur.com/a/V0CntNm](url)

**Comment by xlbobby** [comment]
Seems to be fixed in latest update(s). Thanks!
