### ISSUE TITLE
[Bug] crash at chapter end on specific chapters

### ISSUE THREAD

**Issue by m-vlad** [Jays2Kings/tachiyomiJ2K#286]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Poco F1 MIUI 11 (Android 10)

## Steps to reproduce
1. Get Adventures of God (webtoons source) 
2. Get to the end of either of the last two chapters
3. Crash

### Expected behavior
Not crash

### Actual behavior
Crash lol

### Other details
Here's a logcat if it's helpful: https://drive.google.com/file/d/1IVjJV-gLpRg2AsNzPM6gvPjPSwQveFE6/view?usp=drivesdk

**Comment by Fredddi43** [comment]
Same issue l, reproducable crash at the end of certain chapters.
Devuce: Samsung T-835 Android 9
Logcat: https://drive.google.com/file/d/19dgsTbPK4t9td8B6QEIXLPlXYDAjBDWt/view?usp=drivesdk
Crashes occur on the most recent chapters of Sono Bisque Doll wa Koi wo Suru on Mangadex or The Story Between a Dumb Prefect and a High School Girl with an Inappropriate Skirt Length also ob Mangadex.

**Comment by m-vlad** [comment]
This seems to have been fixed in the newest version. If @Fredddi43 isn't encountering issues anymore we can safely close this issue.

**Comment by Fredddi43** [comment]
Yes, seeme to be fixed.
