### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by laurentlbm** [Jays2Kings/tachiyomiJ2K#287]
This is a great fork. Any plans to submit it to F-Droid?

**Comment by joseph619** [comment]
Why? Tachiyomi now has it's own website.

https://tachiyomi.org/forks/TachiyomiJ2K/

**Comment by Jays2Kings** [comment]
No plans

**Comment by momobobe** [comment]
> No plans

@Jays2Kings sorry for bothering, but could you plz reconsider it? It doesn't take too much time and most stuff would be done by their team, so the most important thing is your approval (or non-opposition) as well as cooperation (like slightly modifying some files and code, and again mostly they'll help). Also usually after the initial setup, they could automatically catch up later updates of the app, if the file structure and code were not corrupted. The original tachiyomi has been listing there and successfully work for years, so no worry there might be any big problem. Thanks for your attention.

**Comment by RokeJulianLockhart** [comment]
@Jays2Kings, perhaps https://gitlab.com/fdroid/fdroid-website/-/blob/6c145c9584cc064acef770de4077d874c465f97e/_docs/Reproducible_Builds.md#publish-both-upstream-developer-signed-and-f-droid-signed-apks and, of course, https://github.com/tachiyomiorg/website/blob/ea69277fbf146b69210e5e10a04f1deaf98fb79a/website/src/news/2024-01-13-goodbye.md?plain=1#L11, shall cause you to reconsider.
