### ISSUE TITLE
[Bug] Crashes, not responding, serious lag

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#288]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Galaxy Tab S6, Android 10

Had these issues since the 1.0.0 update, thought the 1.0.1 would fix them.

1. Getting serious lag when removing manga from categories. I would remove 1 then do a 2nd and the app freezes for about 10secs. Get the worse lag (~20secs) when changing to any kind of page in the UI, sometimes even crashes

2. Touching a title/cover from a source and sometimes library will cause the app to not respond. I close the app, retry and it happens again. Repeat several times until it works properly again

I've got it on my Galaxy S10 too but it's not as bad.

**Comment by CarlosEsco** [comment]
Is your library on an SD card?

**Comment by vongdong** [comment]
> 
> 
> Is your library on an SD card?

No, all on internal memory. Had no problems before updating to this new UI.

**Comment by Mitia99** [comment]
@CarlosEsco My library is in SD card and I'm also facing some serious lags.Improve the performance please.

**Comment by CarlosEsco** [comment]
@Mitia99 easy. Don't use an SD card they are second class citizens on Android

**Comment by Mitia99** [comment]
@CarlosEsco Thus,I haven't faced not responding issue with the inorichi's tachiyomi(library in SD)

**Comment by CarlosEsco** [comment]
Even in regular tachiyomi sd card libraries are slow af when very large. Just search through closed issues on the repo

**Comment by Mitia99** [comment]
@CarlosEsco Yes library in SD are slower but in TachiJ2K,it is too slower.Anyway,please add a "loading icon" when opening a manga cause I sometimes I don't even know if the app is crashung or not.

**Comment by CarlosEsco** [comment]
#537 should fix this whenever it gets released
