### ISSUE TITLE
Insert scroll bar for library inside categories

### ISSUE THREAD

**Issue by harshwasan** [Jays2Kings/tachiyomiJ2K#289]
**App version:**1.0.1

**Android version:**10

**Issue/Request:* *
It is difficult to get to the get to the middle of the category if the category is very big please add a scroll bar

**Other details:**

**Comment by CarlosEsco** [comment]
May I ask how big your categories care that once you are you the category you can swipe scroll as normal

**Comment by harshwasan** [comment]
I have around 500 in the default one and some more in another category
