### ISSUE TITLE
[Feature Request] Back button goes back to library

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#290]
### Why/User Benefit/User Problem
Every time I am in Recents or Browse, when I press the back button it exits the app. Most users usually will be wanting to go back to the library page after looking through Recents or Browse. 
Once in Library, the back button would exit the app.

### What/Requirements
When the user is viewing Recents or Browse, when the press the back button it will return them back to the Library. When the user press the back button in Library, it will exit the app.

**Comment by vongdong** [comment]
Ah, I've accidentally done it a few times too. I would like it see a 'tap back again to exit' so you'd need to press back twice to close the app.

**Comment by CarlosEsco** [comment]
I'm pretty sure jay and I discussed this once but this was by choice. For reference google apps aren't even consistent. Google Maps does what you want as does main tachiyomi. Google Photos does what this app does.

My argument is if each bottom button is of equal importance like the ones here why I expect a back out of a top level screen to go to another top level screen.

**Comment by vipzzx** [comment]
Sure all 3 are top level screen but unlike Google Photos, I feel like this app should act more like Google Maps because Library is the one that people will be using the most often.

If a user is in Browse, and in an extension, they add a few to their library, then press back, it will go back to the source list and most likely will be going back to the library to read the ones they just added or read another manga.

If a user goes into Recent, it shows New Chapters, Continue Reading and Newly Added. If they don't see the manga they are looking for they will be going back to the Library.

So my case is that while all 3 are top level screens, the probability of a user going to back to the Library from the other 2 pages is higher.

**Comment by CarlosEsco** [comment]
You also are just used the old way. Your muscle memory will change

**Comment by Riztard** [comment]
or maybe add this #168

**Comment by CarlosEsco** [comment]
This will not be added.  your best hope is #168
