### ISSUE TITLE
[Feature Request] add category select when adding a manga to your library via popup when downloading

### ISSUE THREAD

**Issue by winneratwin** [Jays2Kings/tachiyomiJ2K#291]
### Why/User Benefit/User Problem

Saves time so we don't need to hold down the" in library" button 

### What/Requirements

Add a menu to select a category in the add Manga to library popup

**Comment by vongdong** [comment]
I'm pretty sure what you want is already available. If the manga is not in your library and you download a chapter or multiple chapters, a popup appears at the bottom asking if you want to add it to your library. Besides you don't need to hold the add to library button, so hardly saving time.

**Comment by winneratwin** [comment]
Yes that popup appears but it will automatically put it in the "default" category even if the setting is set to ask first

**Comment by CarlosEsco** [comment]
Click into the manga click the heart.
