### ISSUE TITLE
[Feature Request] Add ability to collapse library sorting options when an option is selected.

### ISSUE THREAD

**Issue by AlphaCentauri** [Jays2Kings/tachiyomiJ2K#292]
### Why/User Benefit/User Problem
Currently, tapping the library icon (while inside your library) will bring up a filter list. This list can be collapsed by swiping down. However, if an option or options are selected the list is now fixed in place. If a user plans on browsing/reading with filters applied for an extended period of time this menu is now wasting screen space.

### What/Requirements
Easy fix, just enable the ability to swipe down on the menu to close it regardless of the current filter state.

**Comment by CarlosEsco** [comment]
What would you propose since a user won't know they have a filter set if they come back into the library a day or two later

**Comment by AlphaCentauri** [comment]
Well, since the filter already shows you what options you have selected when you kill and reopen the application, all that would be needed to solve that problem is to have the filter open by default (this is how the filter works in 1.0.1 already, so functionality wise nothing changes). There should be no doubt that a user would have a filter active at that point.

**Comment by Jays2Kings** [comment]
Well it can hide now, it will just always show when you first go to that page if theres a filter on
