### ISSUE TITLE
[Feature Request] Mark as read should update tracking

### ISSUE THREAD

**Issue by Ninjistix** [Jays2Kings/tachiyomiJ2K#295]
### Why/User Benefit/User Problem
if you read a chapter elsewhere, online etc, and you mark it as read in it the app, it does not update the current chapter read in tracking.

### What/Requirements
marking a chapter as read should also update the tracking to the highest read chapter.

**Comment by CarlosEsco** [comment]
This is also missing in the main app so when one of them finally gets it then they both will

**Comment by CarlosEsco** [comment]
#102 and opinion on this has changed
