### ISSUE TITLE
1.0.1 version moved downloads folder

### ISSUE THREAD

**Issue by melink14** [Jays2Kings/tachiyomiJ2K#297]
**App version:**
1.0.1

**Android version:**
8.0
**Issue/Request:**
Md2 update notes say that downloads folder won't be moved for preexisting users but mine was causing it to seem like my downloads were gone.

**Steps to reproduce (if applicable)**
1. Update to new version from pre 1.01
2. Notice all downloads are gone until moving download folder back to tachiyomi.

**Comment by CarlosEsco** [comment]
Unfortunately it was a bug you need to copy your content of the initial folder to the new one

**Comment by melink14** [comment]
Thanks. For confirmation, is copying necessary? Instead, I changed the
setting to point to the old folder which seemed to work. Will that cause
problems later.

**Comment by CarlosEsco** [comment]
nope thats fine too
