### ISSUE TITLE
[Feature Request] Search by long pressing navigation tab

### ISSUE THREAD

**Issue by KeiznKlei** [Jays2Kings/tachiyomiJ2K#299]
### Why/User Benefit/User Problem
This would extremely benefit users with long screen aspect ratio and would eliminate the need to reach the search icon high above the screen.

### What/Requirements
The feature would behave by doing a long press in the navigation tabs and automatically enabling search like just when you click it normally. 

It can be expanded more. For example, when in navigation tab 'library' and then the user long presses the navigation tab 'browse', it'll automatically navigate to 'browse' and search of that particular tab. 

If the above is not possible due to already existing keybind, it can then be implemented just by enabling the long press when your on that particular navigation tab. This'll mean that long pressing other navigation tab will open tabs such as 'downloads' or 'extension'. But when your already in the 'browse' tab for example, long pressing it will just open the search field for it. It will also be like that when your in the 'extension' tab where it will open the search field. This may complicate things a bit but one can hope.

**Comment by CarlosEsco** [comment]
While the idea is not bad, you would lose long press on library as being update library.   Them being inconsistent is a deal breaker
