### ISSUE TITLE
[Feature Request] Migration/shared storage from/with Inorichi:Tachiyomi

### ISSUE THREAD

**Issue by narfanar** [Jays2Kings/tachiyomiJ2K#301]
### Why/User Benefit/User Problem
As a user coming from the main app, I could really use a streamlined migration (or shared library) experience with the main Tachiyomi.

Currently backup+restore works for most things.

Except downloaded manga. I don't want to re-download entire titles that are just sitting there already in Tachiyomi storage.

### What/Requirements
Migrate titles, status and downloads automatically from the main Tachiyomi.

OR share the download storage.

**Comment by CarlosEsco** [comment]
point your downloads to the same folder and make sure you download with regular app only as the chapter download folder names are different, but j2k can read original tachiyomi

**Comment by CarlosEsco** [comment]
there are no plans to sync between main app and forks

**Comment by narfanar** [comment]
What guarantees are there for migration compatibility?

Can I for example depend on backups always being both ways compatible between the main app and the J2K fork? I'd be hesitant to leave a fork (main) that I know works and has significant momentum otherwise :/ If that makes sense.

**Comment by CarlosEsco** [comment]
Considering we all talk no one's planning on breaking things like backup.  A shared system would be even more potential for breaking because what if this work put something of the share and it breaks the main app
