### ISSUE TITLE
Library manga sources merged

### ISSUE THREAD

**Issue by heksagen** [Jays2Kings/tachiyomiJ2K#313]
### Why/User Benefit/User Problem
(I happen to have favorited a manga with different sources and sometimes other source dont update frequently than the other 
But sometimes it's vice versa so that's why I use multiple sources on one manga. This benefits so our library looks more clean because sometimes having one manga with multiple sources (sorted by latest chapter) it gets messy and the manga is all over the placeand it's kinda confusing and you don't remember that you've already read the current chapter )

### What/Requirements
( how this works is basically one manga is merged with all the other sources favorited ( ( kinda similar to how mangapark fox,duck,panda, and rock does).)

**Comment by CarlosEsco** [comment]
I won't close this and let jay decide. But highly and I mean highly doubt this wi be implemented. It will be a nightmare to maintain

**Comment by Jays2Kings** [comment]
Yeah Carlos is right in this one, it will be a pain to maintain so this is a pass. TachiAZ has this feature i believe so you can move to there if you wish you use it

**Comment by asdkant** [comment]
@Jays2Kings do you still think it'd be troublesome to support this kind of feature
