### ISSUE TITLE
Grey shade above while reading

### ISSUE THREAD

**Issue by heksagen** [Jays2Kings/tachiyomiJ2K#314]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Y6 2018, android 8.0

## Steps to reproduce
1. Read any chapter on any manga
2. Wait for the page to load
3. Click the center of the page then the navigation bar( the one you navigate with pages and chapters not the system navigation bar) below and the title of the manga above pops.
4.Closing the navigation bar and the title of the mangaby tapping the center of the page

### Expected behavior
The navigation bar and the title of the manga should disappear.

### Actual behavior
The navigation bar and the title of the manga disappeared but there is a grey shade above the reader same location as the title of the manga appears.

### Other details
It can be fixed by scrolling the notification bar down but the bug doesnt disapper it just clears the reader but once you click the center of the page again to open the navigation bar it reappears again
![Screenshot_20200504-122430](https://user-images.githubusercontent.com/64727699/80936125-5546bf00-8e02-11ea-8364-b9585a488e97.jpg)

**Comment by Jays2Kings** [comment]
Closing as its fixed for next release
