### ISSUE TITLE
[Bug] The downloads are really broken in this fork

### ISSUE THREAD

**Issue by KraXen72** [Jays2Kings/tachiyomiJ2K#315]
### Problem
I have noticed this yesterday when i wanted to download 10 chapters of one manga.
The downloading is super unstable. I pressed download on then chapters, went to sleep. Should download overnight, right? i wake up and chapter one is downloaded on 90% chapter 2 on 70% chapter 3 on 50% and chapter 4 on 30% and they are not moving.   
  
### Workaround - not ideal
The temporary solution i use it every time there is a new chapter, i have to pause, unpause and tap on the chapter for it to start "force downloading." I highly, highly doubt this is intended behaviour for the app, so please make downloading in the backgrounds stable, without me having to force it every chapter.  
  
### Suggestion for solution?
Every time, that a chapter is being downloaded for too long, pause and resume it, or something like i did manually.  I've also tried reordering the first and second, this seems to also force download.
  
Even better solution would be making a stable backend thing that could download the chapters reliably. I have seen apps that can reliably run in the  background when they're supposed to even on my phone. My very rough idea of how it would work is that you would give the downloader process high priority, and every time it freezes or is killed, just restart it. I know this is easier said than done, but i still don't think this is undoable. Please fix downloading.

### Specs
android 7, xiaomi redmi note 4, miui 11,
app permissions: autostart: on, all other permisions: on, app has the lock to not clear it from ram.

**Comment by joseph619** [comment]
Could've just mentioned the issue and manga source only. There's a lot of unnecessary wall of text.

**Comment by KraXen72** [comment]
it happens to every manga source i tried. It sometimes works with Webtoons source, but im guessing that is just because it is fast

**Comment by CarlosEsco** [comment]
Pretty sure most of your issues are your phone. See here 

https://github.com/inorichi/tachiyomi/issues/2975

**Comment by narfanar** [comment]
I'm seeing this and another bug related to downloading. Happens with J2K only. Upstream works fine.

I'll mention the other bug once I submit it.

**Comment by KraXen72** [comment]
i opened #321 check the comment for my idea of fixing the thing
