### ISSUE TITLE
[Feature Request] auto-hide library-recents-browse bar when scrolling down

### ISSUE THREAD

**Issue by 29988122** [Jays2Kings/tachiyomiJ2K#316]
First: this is just an ordinary feature request, no pressure. I'm not a native speaker, so please bear with my attitude if there's any. I absolutely admire your effort on maintaining this app - I also have a repo, so I feel you. Thank you.

### Why/User Benefit/User Problem
For a library-like screen, it's crucial to maximize viewable area, and at the same time minimize visual clutter. This is to make that particular app screen cleaner, thus users can focus on the important things.

Together, the topmost bar and the library-recents-browse bar took about 15~20% of viewable screen size, and it's not ideal if you ask ppl doing UI prototyping.

You can see that in Chrome, the address bar will be automatically hidden when scrolling down, but immediately reappear when scrolling up. This is the behavior I mentioned.

However, the navigation bar (back, home, recent apps), unlike the behavior in Chrome, should not be hidden (so don't just implement immersive mode), for usability reasons.

Whether to hide topmost bar or not should be optional via options or developer's choice, again, for usability reasons.

### What/Requirements
1. Add an option to toggle auto-hide of library-recents-browse bar, when scrolling down.
1.a. Add an option to toggle auto-hide of the title bar(topmost bar), when scrolling down.
2. Make them default enable, to enhance app UX experience. 
(It's a fucking giant leap from upstream Tachiyomi, tremendous job btw!)
3. They should be in effect for (not exhaustive) the following Activity/Context: 
```
Library
Recents(history/updates), downloading
Browse, sources, extensions
```
Reason: they're list-like(well, literally lists..), people are reading. So abundant elements should be auto-hide.

4. As a "temporary" solution, you can just implement immersive mode when users scrolling down, I guess. No idea how hard this behavior is to be implemented.

***
Again, thank you for this magnificent work.

**Comment by Jays2Kings** [comment]
The top bar will scroll away but the bottom nav is there to stay
