### ISSUE TITLE
[Feature Request] Option for "Category Tabs Bar" & Swiping laterally to switch between category.

### ISSUE THREAD

**Issue by Gallardo26** [Jays2Kings/tachiyomiJ2K#318]
Feature 1: Additional option for displaying a categories tab bar similar to before v1.0.1.
Feature 2: (and maybe swiping laterally, similar to android homescreen pages)

Before the major UI update, there was a category tab bar where we could quickly select the category we want to read. Previously in v1.0.1, the library shows everything in a single page. But thanks to v1.0.2 update, we can select without display all categories.

### Why/User Benefit/User Problem
1. Faster, quick single tap to switch between categories.
2. Where people have many categories eg... split between on-going, reading, completed, western-comics, all split with different types, genres etc... with a tab bar, it allows quick switching between them instead of going "in and out" of a drop-down menu.

### What/Requirements
For Feature 1:
- A checkbox to turn on and off the category tabs bar in category options.
- Ability to scroll the bar laterally if too many categories to display.
- The bar would be on top of the library page like a "sticky" menu when you scroll downwards, like a frozen 1st row in excel. (Could also include a checkbox option whether to sticky or not)

For Feature 2:
- Additional 'always-on' feature for swiping laterally to switch between categories.
- Or could also have an on/off option in category options

**Comment by KraXen72** [comment]
this was a thing in beta2 which i personally liked, you had a list but swiping horizontally changed categories. it got removed because it didn't make sense. I would still bring it back tho.

**Comment by CarlosEsco** [comment]
Don't know why you opened this when its been discussed in discord tabs are not coming back, and horizontal swipe to move down a vertical list is not being readded. 
If you want tabs, stable has a new ui but keeps tabs.
https://github.com/inorichi/tachiyomi

**Comment by Gallardo26** [comment]
@CarlosEsco I opened this before we've chatted in Discord.

**Comment by Poopooracoocoo** [comment]
For those of us not on Discord, what was the verdict? Why are you guys not going with tabs?

**Comment by Gallardo26** [comment]
It's not gonna happen. No tabs.

**Comment by joseph619** [comment]
New drop down option has been added in latest update, which is an alternative to switching categories.

**Comment by Poopooracoocoo** [comment]
@Gallardo26 but why?

**Comment by CarlosEsco** [comment]
go to stable Tachiyomi this isn't coming back
