### ISSUE TITLE
[Feature Request] Range selection for chapters

### ISSUE THREAD

**Issue by Vincentvibe3** [Jays2Kings/tachiyomiJ2K#319]
It would useful to be able to select a range of chapters and then mark them as read or unread rather than only being able to do so for downloading.

Long pressing on the chapter title would select the chapter rather than showing mark previous as read and then long pressing on another chapter would select all chapters in between.

**Comment by fiestorra** [comment]
This would be extremely useful, as it is right now if you start a manga in x chapter it always directs you to read the first chapter as it is not yet red, making it really tedious to scroll until you find the last chapter you red, allowing a range selection to mark as read would solve this problem.

**Comment by Jays2Kings** [comment]
Is there an actual case when you need to mark a large group of chapters as read in the middle of a manga, but not the chapters before it?

**Comment by fiestorra** [comment]
There are certain extensions that unify various sources in one manga.
For example, if it has 100 chapters it goes from 1 to 100, then back to 1 from another source and to 100 again and so on.
Hope this helps.
![Screenshot_2020-05-23-09-34-20-965_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/65175643/82724743-a4cd2c00-9cd8-11ea-98e8-b20b51c629d3.jpg)

**Comment by joseph619** [comment]
You can fix the duplicate issue in MangaPark easily, go to Extension > MangaPark > Chapter list source then choose a version

Try to find a better usecase
