### ISSUE TITLE
[Bug] Recently read bugs

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#32]
### Device information
* Tachiyomi version: 0.9.5
* Android version: 9.0

There are two bugs, first is when an entry in Recently read is removed, it works but doesn't show visually. 

Also, sometimes duplicate entries might appear in Recently read. 

![Tachiyomi-2_Screenshot_2020 01 05_15 01 41](https://user-images.githubusercontent.com/34897862/71785447-9b635180-2fcd-11ea-82ec-3fe54b1da19f.jpg)

**Comment by Jays2Kings** [comment]
Both of those issues should be fixed as of .69, let me know if there's issues before I close this

**Comment by joseph619** [comment]
I couldn't find any for now, will bump this again when I find one

**Comment by Jays2Kings** [comment]
Nah if there's currently no issues, we're closing it, but feel free to make a new issue for any new bugs
