### ISSUE TITLE
[Bug] Reader Not Going Full Screen

### ISSUE THREAD

**Issue by RoxTheVile** [Jays2Kings/tachiyomiJ2K#322]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: MIUI 11.0.5

## Steps to reproduce
1. Read any manga in portrait mode

### Expected behavior
The whole screen should show the manga page. 

### Actual behavior
The screen shows the manga page but there's a section it doesn't cover where the navigation bar used to be. 

### Other details
![Screenshot_2020-05-04-20-48-40-971_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/63662346/80987739-e8f0ad80-8e4b-11ea-9c29-6e82f32e415c.jpg)

![Screenshot_2020-05-04-21-03-11-560_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/63662346/80987753-eee68e80-8e4b-11ea-9898-bcacbc2ba04f.jpg)

**Comment by Jays2Kings** [comment]
Closing as its fixed for next release
