### ISSUE TITLE
[Bug] Null instead of an author

### ISSUE THREAD

**Issue by e-shl** [Jays2Kings/tachiyomiJ2K#323]
### Device information
* Tachiyomi version: v1.0.2
* Android phone & version: 10

## Steps to reproduce
1. Install the Readmanga source:
2. Open the manga "A Returner's Magic Should Be Special" or another without an author

### Expected behavior
Only an artist without an author and other information is displayed

### Actual behavior
Instead of author Null
![2020-05-04 21-13-20](https://user-images.githubusercontent.com/35057681/80988445-f8bcc180-8e4c-11ea-92a0-85bea947ea5c.JPG)
In the manga where the artist is not indicated, everything is displayed normally.
The problem is not in the extension, in Tachiyomi there is a substitution
![2020-05-04 21-14-29](https://user-images.githubusercontent.com/35057681/80988772-649f2a00-8e4d-11ea-8573-bd08c154f01c.jpg)

**Comment by cantunborn** [comment]
@Jays2Kings Now instead of null, it starts with the string `", "`, replacing null with empty string. Two sources in which this can be seen is allporncomic and e-hentai.

The correct way should be only showing the artist instead.
