### ISSUE TITLE
[Bug] Black page bug v2

### ISSUE THREAD

**Issue by exudis** [Jays2Kings/tachiyomiJ2K#327]
Device information
* Tachiyomi version: 1.0.2
* Android phone & version: 
J2 prime 2016
6.0.1
Systemless root using Magisk

Steps to reproduce
1. Open TachiJ2k
2. Click on any manga (library or from source)
3. Tap screen to remove from fullscreen mode to show Manga name and chapter
4. Tap screen again to go back into fullcreen
5. Scroll down/up

Expected behavior
Manga pages should remain visible with no black pages and able to see each panel

Actual behavior
Every page turns black starting from the page you tapped on. Only page number remains visible

Other details
Not able to send screen rec

**Comment by heksagen** [comment]
Try disabling secure screen so you can send a screenshot

**Comment by littlemagehero** [comment]
I think i got the same bug
![Screenshot_20200506-002113](https://user-images.githubusercontent.com/51184069/81090722-c08eaf00-8f30-11ea-88ce-2e1788c16823.jpg)

**Comment by exudis** [comment]
> 
> 
> ![Screenshot_20200506-002113](https://user-images.githubusercontent.com/51184069/81090722-c08eaf00-8f30-11ea-88ce-2e1788c16823.jpg)
> 
> I got this bug on update 1.0.2

whats ur disc?

**Comment by Jays2Kings** [comment]
You can confirm this bug is fixed now, and will be for the next release
