### ISSUE TITLE
[Feature Request] Hide chapter from specific scanlator

### ISSUE THREAD

**Issue by null2264** [Jays2Kings/tachiyomiJ2K#329]
### Why/User Benefit/User Problem
Prevent confusion, sometime on certain source such as MangaDex, they have 2 different people that working on the exact same manga and the exact same language... 

### What/Requirements
I'm hoping to have the ability to hide future chapter from specific scanlator, or even just simply the ability to hide doubled chapter...

**Comment by null2264** [comment]
Nevermind i checked someone already requested it and mark as wont-fix... my bad..

**Comment by CarlosEsco** [comment]
If you use dex for a lot of your manga i have that in Neko and you can use it side by side with J2K.  But that obviously won't solve your issue if you only want to use J2K

**Comment by null2264** [comment]
Yeah that is a good idea, but i want to have only 1 app for manga reader... I tried to blocking the group but that didn't fix the problem if the chapter uploaded by 1 person scanlator (no-group), so i guess there is no other way other than ignoring it...

It would be great if that's a feature but i guess that's gonna cause other trouble (?), thanks for the suggestion btw... i'll check out Neko later.
