### ISSUE TITLE
[Bug] Date Format

### ISSUE THREAD

**Issue by Riztard** [Jays2Kings/tachiyomiJ2K#330]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Xiaomi Redmi 4X Android 9

## Steps to reproduce
1. go to setting
2. general
3. change date format

### Expected behavior
the date format should change.

### Actual behavior
date format stay MM/dd/yy.

### Other details
maybe because the month number changed to text.

**Comment by Jays2Kings** [comment]
correct the setting applies only where the month is a number, (which might not be anywhere anymore so if anything the setting should be removed)

**Comment by Riztard** [comment]
but it can changed to ddMMyy by chance to English uk like before
