### ISSUE TITLE
[Bug] sort by source isn't actually sorting by source

### ISSUE THREAD

**Issue by yusernemu** [Jays2Kings/tachiyomiJ2K#331]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Redmi note 4x & Android 10 

## Steps to reproduce
1. Select any manga from mangadex with multiple sources
2. Tap the sort button below the read button to the right
3. Choose sort by sources order

## Expected behavior
The chapter would sort by the sources
Example:
Ch 1 by source1
Ch 2 by source1
Ch 1 by source2
Ch 2 by source2

### Actual behavior
Just switching the sources 
Example if you choose sort by sources:
Ch 1 by source1
Ch 1 by source2
Ch 2 by source1
Ch 2 by source2.
Example if you choose sort by chapter number:
Ch 1 by source2
Ch 1 by source1 --swtiched
Ch 2 by source2
Ch 2 by source1 --swtiched
### Other details
Notice the chapter number, it's really annoying to skip a chapter after finished reading one. 
Im sorry, I'm not really good at explaining things

**Comment by CarlosEsco** [comment]
you are misunderstanding it is working as designed.  It sorting by the sources order.  In this case the order mangadex provided was
Ch 1 by source1
Ch 1 by source2
Ch 2 by source1
Ch 2 by source2

its not a sort by scanlator/group setting
