### ISSUE TITLE
[Feature Request] Start with hidden filter(on)

### ISSUE THREAD

**Issue by Riztard** [Jays2Kings/tachiyomiJ2K#334]
### Why/User Benefit/User Problem
user doesn't need to manually hide (if rarely scroll) the filter

### What/Requirements
work just like "start with hidden filter" start with hidden filter but with selected filter

**Comment by Riztard** [comment]
oh forgot to add if you open recent/source then back to library, the filter showup again

**Comment by AlphaCentauri** [comment]
To quote @CarlosEsco when I opened a similar issue (#292)
> What would you propose since a user won't know they have a filter set if they come back into the library a day or two later

With what you're suggesting I don't see a way to avoid this if the filter has the ability to be permanently hidden other than to just hope that the user just doesn't forget. I'm perfectly fine with the current operation where the filter bar is shown by default if a filter is selected, but can still be dismissed.

**Comment by CarlosEsco** [comment]
closing since jay already commented on a similar issue

**Comment by Riztard** [comment]
> To quote @CarlosEsco when I opened a similar issue (#292)
> 
> > What would you propose since a user won't know they have a filter set if they come back into the library a day or two later
> 
doesnt the old one like that too? when filter on or off we need to open the filter setting

**Comment by AlphaCentauri** [comment]
> doesnt the old one like that too? when filter on or off we need to open the filter setting

I'm having a hard time understanding what you're trying to say here, but when "Start with filters hidden" is checked in the display options, if no filter is applied the list will remain hidden. This makes sense as there's no reason for the user to care about the filter until they want to apply one. However, if a filter is applied and a user exits, if the filter is automatically hidden on application startup then my earlier comment applies.

The only QoL change I could see being added is removing the need for the filter to show back up when you switch off of the library view and come back. I don't think it's that much of an issue to expect the user to remember they manually collapsed the filter in this case. As a counter that point though, you have people who keep applications open on their phone almost indefinitely, what about them?

**Comment by CarlosEsco** [comment]
@Riztard  doesn't the old app change the color of the filter icon on top when a filter is enabled?

**Comment by Riztard** [comment]
at least that not taking so much space :(
