### ISSUE TITLE
[Bug] Slight delay/freeze when removing download 

### ISSUE THREAD

**Issue by arkediaz** [Jays2Kings/tachiyomiJ2K#336]
Hello,

I'm experiencing a slight but noticeable delay/freeze whenever i'm deleting a downloaded chapter,the pause/delay will be longer if i'm deleting multiple chapters at once

similar problems also occur whenever i press "cancel all" on download queue page

this problems didnt exist before the app redesign 

my download folder is on the internal storage,not on the sdcard

here's the video capture of the problem

https://streamable.com/hxunhp

Device : Samsung Galaxy S8+
* OS : Android 9.0
* Tachiyomi version: 1.0.2

sorry for bad grammar,i hope i communicated this problem clearly

Thanks

**Comment by CarlosEsco** [comment]
This is fixed with #537
