### ISSUE TITLE
[Feature Request] Filter by tracked or not

### ISSUE THREAD

**Issue by loocool2** [Jays2Kings/tachiyomiJ2K#34]
### Why/User Benefit/User Problem
Many new manga come out all the time and a lot of the time they don't have entries on any of the tracking websites yet. This would make it easier to find which titles haven't been tracked rather than tapping on each title and seeing if there's a checkmark.

I'm not sure if there's anything in tachiyomi that returns if a title is tracked or not though.

### What/Requirements
There's two ways I'm thinking of doing it: Just a is tracked and not tracked box. Then more complicated you could have the first part then have another filter by the service it's filtered by, and hide the checkboxes for the tracking services that have not been logged into yet. Like how it's laid out here https://github.com/inorichi/tachiyomi/issues/1899

It would probably be in the my library sidebar

**Comment by Jays2Kings** [comment]
In as of 0.9.7
