### ISSUE TITLE
[Feature Request] Manga count for each library category

### ISSUE THREAD

**Issue by codewalk3r** [Jays2Kings/tachiyomiJ2K#341]
### Why/User Benefit/User Problem
Helps make sure that restoring the library is complete. And advance option to quickly view the error logs would be nice as well.

### What/Requirements
On the Library dropdown, add the total number of manga on each category.

**Comment by CarlosEsco** [comment]
You can just long click a manga in the category then click the dot by the category name to get the count.
As for view error log of restore there is the option in the notification
