### ISSUE TITLE
[Feature Request] Add more than 1 search filter category while exploring sources.

### ISSUE THREAD

**Issue by rAgnaAA** [Jays2Kings/tachiyomiJ2K#347]
*Explain why this feature should be added.

Right now you can only use a single category filter while exploring sources.

![Screenshot_20200506-174241_TachiyomiJ2K](https://user-images.githubusercontent.com/64928522/81227088-3d1d9e00-8fc2-11ea-98a1-95f3af7dff21.jpg)

*Explain how this feature would behave.

Adding multiple category filters would make searching for mangas more accurate on what the user is looking for.
The user should be able to select multiple individual category (Action + Seinen + Comedy + etc).
Thanks

**Comment by Jays2Kings** [comment]
"If this is an request for an extension/source, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions"

Read the template next time
