### ISSUE TITLE
Visual popup randomly appears when changing pages.

### ISSUE THREAD

**Issue by Aithey** [Jays2Kings/tachiyomiJ2K#349]
**App version:**
1.0.2
**Android version:**
Samsung Galaxy S10 / Android 10
**Issue/Request:**
Video of the issue I posted in the Discord #support
https://cdn.discordapp.com/attachments/349436576037732355/707638165263089805/Screen_Recording_20200506-125828_1.mp4

Image of my reader settings:
https://cdn.discordapp.com/attachments/349436576037732355/707638493676961792/Screenshot_20200506-130228_TachiyomiJ2K.jpg
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
Nobody in support seems to know what's causing this, some people said it could just be an issue related to the Samsung Galaxy S10 series of phones.

**Comment by Jays2Kings** [comment]
if you enable "show touches" in android developer settings you can see you're swiping near the edge of the screen (but maybe samsung over calibrated it). When swiping on any edge of the screen with gestures enabled, it will show the status/nav bar and when that shows the top bar shows as well

**Comment by Aithey** [comment]
I thought that's what it was too, but even if I hold my phone in a way where I'm not touching the edges it does this.
