### ISSUE TITLE
[Bug] Attempting to Multiple Chapters Lands at End Page

### ISSUE THREAD

**Issue by aznchronos** [Jays2Kings/tachiyomiJ2K#350]
## Device information
Tachiyomi version: 1.0.2
Android version: 10
Device: Samsung Note 10+
## Steps to reproduce
1. Download multiple chapters of any manga
2. Read through chapter
3. Proceed to next chapter via swiping right
4. (Next chapter starts at "There's no next chapter")
## Expected behavior
Start the next chapter page 1

## Actual behavior
Starts next chapter end page at "There's no next chapter"

## Other details
Started reading from 2nd last chapter. This also occurs on other chapters as well

Reproducible with any manga under same circumstances, except webtoons.

**Comment by CarlosEsco** [comment]
Do you still have this issue?

**Comment by aznchronos** [comment]
No. Looks like part of the update from 1.0.2 to 1.0.7 solved it.
