### ISSUE TITLE
[Bug] Empty page bug still persists in newest version

### ISSUE THREAD

**Issue by VielenKaat** [Jays2Kings/tachiyomiJ2K#351]
### Device information
* Tachiyomi version: 1.02
* Android phone & version: MHA-L29, Android 8.0

## Steps to reproduce
Reading manga occasionally produces a white page, can be fixed by going back to the library, but appears again after a few pages

### Expected behavior
No empty pages should appear

### Actual behavior
Empty pages still appear

### Other details
Additional details and attachments.

**Comment by Murasakinoe** [comment]
I have the same problem.

Was working fine up until I updated actually, and then my entire library has empty pages. I use mangakakalot, which is entirely unusable at the moment. MangaDex still works though without any problems

**Comment by Jays2Kings** [comment]
Fixed in next release, see #327 

I'll leave this open so others can see

**Comment by rijan72** [comment]
I've been use this app since i like it ui better.
But the above mentioned bug has made the app unusable which is sad.It been 6 day but the fix hasn't been rolled out.

**Comment by CarlosEsco** [comment]
Don't start asking for ETAs

**Comment by Murasakinoe** [comment]
> I've been use this app since i like it ui better.
> But the above mentioned bug has made the app unusable which is sad.It has been almost 6 day but the fix hasn't been rolled out.

I updated Mangakakalot's extension and it seemed to iron out my problems. In fact, it has never worked better, for some reason I download it a lot faster, on top of, while reading manga some of the pages no longer load for super long times

**Comment by rijan72** [comment]
> 
> I updated Mangakakalot's extension and it seemed to iron out my problems. In fact, it has never worked better, for some reason I download it a lot faster, on top of, while reading manga some of the pages no longer load for super long times

The blank pages and top bar shadow are still relevant in my device, though the pages do load faster.

**Comment by Jays2Kings** [comment]
Fixed as of v1.0.3
