### ISSUE TITLE
[Bug] Can't load the chapters uploaded before this date

### ISSUE THREAD

**Issue by b1cco** [Jays2Kings/tachiyomiJ2K#352]
Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Galaxy J6+ & Android 9

Steps to reproduce
1. Open any manga/manhwa
2. Open any early chapters (like chapter 1)

Expected behavior
Chapters loaded as usual.

Actual behavior
Dosen't load and kept on asking to 'retry'

Other Details
I've tried opening the newest chapters and it does open
Happens on mangas i've read and haven't read

**Comment by CarlosEsco** [comment]
this is more than likely an extension issue
https://github.com/inorichi/tachiyomi-extensions
