### ISSUE TITLE
[Bug] Installer Crashes while uninstall

### ISSUE THREAD

**Issue by dfrost16** [Jays2Kings/tachiyomiJ2K#353]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version:  Redmi Note 5 pro, Running Android 10

## Steps to reproduce
1. Install App
2. Uninstall it
![Screenshot_20200507-195105_Lawnchair](https://user-images.githubusercontent.com/24663673/81305948-8e9a5b80-909c-11ea-9006-1567dd8fd28f.png)
[Logs](https://files.catbox.moe/bmknta.zip)

**Comment by arkon** [comment]
Remove your SD card first.

**Comment by dfrost16** [comment]
Is there any issue with the SD card?

**Comment by CarlosEsco** [comment]
a10 bug

**Comment by dfrost16** [comment]
> a10 bug

Not to sound rude 😅 if I may ask why specifically it happens with Tachiyomi and its fork ( I tried official app and J2k ) other apps works fine

**Comment by arkon** [comment]
Because we use a feature that allows app data to be retained after uninstalling on Android 10+. Certain apps like WhatsApp also have the same issue.
