### ISSUE TITLE
[Bug] Jumps to the last page of the next chapter

### ISSUE THREAD

**Issue by iSpaghetti** [Jays2Kings/tachiyomiJ2K#355]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Samsung J7 Pro Android 9 & Note 9 Android 10

## Steps to reproduce
Just happens randomly

### Expected behavior
Just go to first page of the next chapter

### Actual behavior
Jumps to the last page of the next chapter, on Note 9 it happens a little to no issue at all but happens most of the time in J7 Pro

### Other details
Happens randomly so i cant really get any other details

**Comment by Jays2Kings** [comment]
Duplicate of #350
