### ISSUE TITLE
[Feature Request] Please add selection range in source migration

### ISSUE THREAD

**Issue by rohezu** [Jays2Kings/tachiyomiJ2K#358]
Good day 
I think that selection range should be added to source migration. I, for example, have a 2500+ manga library. Using the auto option for migrating everything takes a really long long time, way too many hours. Individual selection would be longer. So i think, migrating in batches like from 300 to 300 would make things faster and more manageable.

---

### Why/User Benefit/User Problem
I think this feature would be useful when migrating a really long manga library.

### What/Requirements
We would enter the select mode from source migration, then select the start manga or comic; then the final one. Then press a button that says selection range. Then migration would proceed with the selected range.

**Comment by Jays2Kings** [comment]
1. Go to library
2. Press the search icon
3. Search _source name_
4. Long press one manga
5. Long press another and it'll select everything in between
6. Press source migration

**Comment by rohezu** [comment]
Thank you for the response and solution.
