### ISSUE TITLE
[Bug] Dark bar on top when reading

### ISSUE THREAD

**Issue by Itsfurqan1337** [Jays2Kings/tachiyomiJ2K#359]
### Device information
* Tachiyomi version: v1.02
* Android phone & version: Huawei P10 Lite (android ver 8.0.0)

## Steps to reproduce
1. First step: open the reader and tap to pull down the details windows dropping down from top and bottom. 
2. Second step: Tap again to see the whole page and remove the drop downs. 

### Expected behavior
The full screen should be shown with equal brightness on the whole screen. 

### Actual behavior
A dark shadow is seen of the drop down on the top part of the reader. 

### Other details
The error is fixed when you go back and open the chapter again. It opens the cjapter without those drop downs. The problem is not with the page as the size of the shadow remains the same even though you zoom in. 
![Screenshot_20200508-131821](https://user-images.githubusercontent.com/65011832/81386562-a28e9d80-912e-11ea-8f03-5400162214dd.jpg)
![Screenshot_20200508-131827](https://user-images.githubusercontent.com/65011832/81386571-a5898e00-912e-11ea-967c-e9875277dd1e.jpg)
![Screenshot_20200508-131830](https://user-images.githubusercontent.com/65011832/81386579-a7ebe800-912e-11ea-8b8e-909e6e9834a1.jpg)

**Comment by CarlosEsco** [comment]
#314
