### ISSUE TITLE
[Bug] Acra reports to Inorichi's server

### ISSUE THREAD

**Issue by CarlosEsco** [Jays2Kings/tachiyomiJ2K#36]
formUri = "http://tachiyomi.kanade.eu/crash_report"

should have it send to your own server or a free backend.
I ended up going with tracepot for the time being.

**Comment by Jays2Kings** [comment]
Oof, I was sure I left some stuff pointing to main tachi but oops. Yeah tracepot looks like a good choice as well, I'll use that

**Comment by Jays2Kings** [comment]
Using tracepot now, thank again
