### ISSUE TITLE
[Bug] App Crash Upon/During Search

### ISSUE THREAD

**Issue by ElemBeast** [Jays2Kings/tachiyomiJ2K#364]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Samsung Galacy J6+, Android Version 9

## Steps to reproduce
1. Open TachiJ2K.
2. Open any saved manga in the Library page.
3. Click manga name (note: the one with the Author name right below).

 OR

1. Open TachiJ2K.
2. Browse (Sources) -> Search.
3. Write any manga name in Global Search.

### Expected behavior
Search page appears, several sources load introduced term/name matches.

### Actual behavior
App crashes immediately.

### Other details
Bug doesn't seem to exist with either the base app or Neko fork (both ways given to reproduce the bug were reproduced in said apps, worked fine).

**Comment by ElemBeast** [comment]
Note: Several other things caused the app to crash (reading any chapter, for example, two or three times the app just crashed when opening).
Uninstalling and reinstalling seems to have solved all issues.

**Comment by Jays2Kings** [comment]
Since you said that your issues are resolved, this is being closed
