### ISSUE TITLE
[Feature Request] Remove Firebase Analytics from the app

### ISSUE THREAD

**Issue by DrizztFR** [Jays2Kings/tachiyomiJ2K#365]
More like "unfeature" request.

### Why/User Benefit/User Problem
Google Firebase Analytics is a tracking feature giving informations to Google about user behaviour. User privacy is compromised when a developper uses this framework.

### What/Requirements
Maybe a replacement for the push notifications will be needed, like the ongoing project [OpenPush](https://bubu1.eu/openpush/). I guess it's not a real problem since the app doesn't need to notify the user every other minute like a messaging app would.

**Comment by arkon** [comment]
Firebase Analytics doesn't have anything to do with push notifications, that's Firebase Cloud Messaging.

Analytics allow us to make informed decisions, such as dropping support for older versions if there aren't many users, or how to make improvements to the app to better retain users.

**Comment by Jays2Kings** [comment]
Exactly it's not going anywhere, this project is open source so if you want to make a fork w/o firebase analytics you're free to
