### ISSUE TITLE
[Feature Request] Move to different category + location 

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#366]
Can you please add a move/change library button somewhere of added titles? Would be helpful to show what category it is in on the page too.

Looks like I wasn't clear with my request. I'd like a button on the title's page so if I decided I wanted to move it I can without having to remove it first. I know I can do this from the library but it's useful if we want to do it while browsing in an extension.

**Comment by Riztard** [comment]
@vongdong try long press "in library" is that what you ask?

**Comment by vongdong** [comment]
> @vongdong try long press "in library" is that what you ask?

No, sorry I wasn't clear with what I requested. I've updated the post.
