### ISSUE TITLE
[Bug] Sometimes chapters are skipped when transitioning to the next chapter 

### ISSUE THREAD

**Issue by iecg** [Jays2Kings/tachiyomiJ2K#367]
**App version:** 1.0.2

**Android version:** 10

**Issue/Request:** Issue

**Steps to reproduce (if applicable)**

 1. Finish a chapter 
 2. Continue reading the next chapter 
 3. Sometimes a whole chapter will be skipped

**Other details:** Sometimes whole chapters are skipped while going to the next chapter

**Comment by CarlosEsco** [comment]
Are they read chapters and you have skip read enabled?

**Comment by iecg** [comment]
They are unread chapters and I don't have skip enabled

**Comment by iecg** [comment]
Looks like it might be related to #350 and #355

**Comment by CarlosEsco** [comment]
Do you still have this issue?

**Comment by iecg** [comment]
No, this was fixed a few versions ago
