### ISSUE TITLE
[Bug] Daily Automatic backups not working

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#368]
## Steps to reproduce
1. Set Backup frequency to **Daily**
2. Set Max automatic backups to **3**

### Expected behavior
Auto backups should be created

### Actual behavior
Last Auto backup was created nearly 3 days ago (May 6th)

### Other info

12 hour backup works, as does 6. Only Daily is broken apparently.

**Comment by CarlosEsco** [comment]
still an issue on 1.0.7 ?

**Comment by joseph619** [comment]
Yeah it was never fixed, I changed frequency it to 12hr to make it work

**Comment by joseph619** [comment]
closing this since i haven't used daily backup for a year
