### ISSUE TITLE
[Feature Request] Select & Deselect all sources

### ISSUE THREAD

**Issue by Riztard** [Jays2Kings/tachiyomiJ2K#369]
### Why/User Benefit/User Problem
it would be easier for people with many sources so people would not do it one by one. 

### What/Requirements
if people want to check majority source they only need to select all and deselect the minority, and if after that they want to migrate to mangadex only, they just do deselect all and then just select mangadex.  

![Screenshot-20200509-152748-Tachiyomi-J2-K 1](https://user-images.githubusercontent.com/16263232/81468762-c1169680-920b-11ea-99c8-7f065af5e45c.png)

**Comment by joseph619** [comment]
You forgot to mention this is for Auto migration only.
