### ISSUE TITLE
[Feature Request] Thumbnail zoom-in

### ISSUE THREAD

**Issue by m-vlad** [Jays2Kings/tachiyomiJ2K#37]
### Why/User Benefit/User Problem
(explain why this feature should be added)
It makes sense. Maybe I'm the only one but I keep tapping on the thumbnails when I want to take a closer look at them but it doesn't do anything. I can't think of any other apps that do it at the moment but it's been often enough that I've got the habit now.

### What/Requirements
(explain how this feature would behave)
it would maybe open it in full screen with an option to save the thumbnail.

**Comment by joseph619** [comment]
We don't need it to be full screen, just an expanded view of the thumbnail in original resolution. Not zoomed in though (zooming would make it blurry)

**Comment by Jays2Kings** [comment]
It's in now, 0.9.7
