### ISSUE TITLE
[Feature Request] ability to Expand hidden categories

### ISSUE THREAD

**Issue by Raidou13** [Jays2Kings/tachiyomiJ2K#370]
### Why/User Benefit/User Problem
Whenever I have a Filter enabled, and I have category collapsed, the library will then hide that category, it's a hassle to disable the filter and Expand that category, it's more convenient to be able to Expand hidden categories while a filter like show only Downloaded/unread filter(s) are enabled,.

### What/Requirements
While a filter is enabled, When a category that is currently hidden is selected in the category Dropdown, and if it has manga that fits the filter, that category will reappear and be expanded.

**Comment by AlphaCentauri** [comment]
This should be fixed as of 1.0.3
