### ISSUE TITLE
[Bug] Downloads to SD card fail with getMangaDirName(manga) must not be null error

### ISSUE THREAD

**Issue by Fredddi43** [Jays2Kings/tachiyomiJ2K#372]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Samsung SM-T835, Android 9

## Steps to reproduce
1. Select download folder on SD card (android/data/... or other) 
2. Try to download any Manga chapter

### Expected behavior
Manga downloads correctly

### Actual behavior
Manga does not download, error notification pops up

### Other details
It seems that downloads to SD cards do not work in this release. They worked fine before 1.0, using the standard android/data path selectable in options. If I change the download path to internal memoery they work again. Selecting SD card means the downloads fail and an error like "... getMangaDirName(manga) must not be null" (first part of notification is cut off) or like [this](https://photos.app.goo.gl/kL69WimKBKpXEmWE6) pops up. Logcat: https://drive.google.com/file/d/1WdW2Py-yX9SMsfxNZKEWzM53X5T7Jyvj/view?usp=drivesdk

**Comment by WH1T3No1SE** [comment]
Downloading To SD card works for me,
TachiJ2K Version: 1.0.2
Phone: OPPO AX7 Android 8.1

**Comment by Fredddi43** [comment]
It seems this wasn't actually a Tachiyomi error but just bad timing for my SD card to go read-only before dying. Got a new SD card and now downloading to SD card works again.
