### ISSUE TITLE
[Feature Request] Similar Manga

### ISSUE THREAD

**Issue by Aldrichyl** [Jays2Kings/tachiyomiJ2K#373]
Hello,
It would be very nice to have on `Tachiyomi J2K` a function that can give you similar manga or like manga suggestions for each manga depending on the genre,format,community recommendations... I think there is a similar feature in the Neko app. 
Thanks

**Comment by CarlosEsco** [comment]
Neko's similar is not coming here cause it only works for mangadex

**Comment by C0nvert** [comment]
@CarlosEsco I thought your app says "This recommendation System is outside of Manga Dex"...
So how exactly is it working from a technical Point of view ?

Is it possible to implement similar Mangas over a Service like anilist e.g?

**Comment by CarlosEsco** [comment]
Outside meaning it's not provided by mangadex but it uses mangadex IDs and everything to generate it. Anilist is possible but then you are relying on a 3rd party source to be up and their recommendations at times are suspect. Join discord and look at tachiyomi Az build that has it

**Comment by C0nvert** [comment]
i checked the discord server and didn't find the proper az version.
So i downloaded it from Github https://github.com/az4521/TachiyomiAZ/releases/download/v8.5.0-AZ/app.apk
Hope it's the right version.
But unfortinatly i didn't find any Similar Manga function in there.
Maybe i'm searching in the wrong place..

**Comment by joseph619** [comment]
You need the Dev version of AZ for Similar manga

**Comment by Aldrichyl** [comment]
So there is no way to have this feature someday on J2K ? Because it would very helpful.

**Comment by CarlosEsco** [comment]
I'll let @Jays2Kings  answer but I think no. Relying on anilist to be up and be reliable is suspect

**Comment by Jays2Kings** [comment]
Yeah looking at Anilist recs I'll pass on it. And aside from it I don't think there's going to be a better method for it until major changes in base tachi and its extensions happens
