### ISSUE TITLE
[Feature Request] Better Background pictures for Manga descriptions

### ISSUE THREAD

**Issue by Aldrichyl** [Jays2Kings/tachiyomiJ2K#374]
Hello,
I would like to request a small change that is purely and strictly esthetical. `TachiyomiJ2K` has a prettier UI in my opinion, and the thing is when you go to see the description of a manga (Where you also find the chapters and everything related to it) You see a background picture that is the the cover of the Manga itself. My suggestion comes here, I think that it would nice to have have a different one (Different background picture) and to be more precise, to have the same presentation as Anilist.
Thanks

**Comment by CarlosEsco** [comment]
Where do you suggest these image come from?

**Comment by she11sh0cked** [comment]
Maybe you could grab a random page from the source. But then I would suggest blurring it to avoid spoilers.

**Comment by Aldrichyl** [comment]
I suggest Anilist but I don't know if it's possible. Here is the exemple https://anilist.co/manga/105398/Na-Honjaman-Level-Up

**Comment by she11sh0cked** [comment]
Isn't Anilists content user submitted? I don't think that would be possible. Also, I don't think the devs want to rely on Anilist for features other then tracking.

**Comment by CarlosEsco** [comment]
What shell said. Also a random image might be okay but then a chapter would need loaded and there's no guarantee what the random image would be

**Comment by she11sh0cked** [comment]
If you are not ok with loading a random image from all chapters, you could load a random image from already downloaded chapters and fallback to the cover if none are downloaded.

**Comment by CarlosEsco** [comment]
no plans to add this at this time
