### ISSUE TITLE
[Feature Request] Auto find / migrate for title's changed url

### ISSUE THREAD

**Issue by fivesoul1** [Jays2Kings/tachiyomiJ2K#376]
Hello. First and foremost, thank you very much for the app.

I think it will be easier for the user in having this feature, where the app can tell us which titles are having an invalid / changed url. Sometimes the extensions changed the manga title's url without the user knowing. This occurs to me when some titles are not updating for quite a while, and it may be a hassle for users with 400+ titles, because i have to go through each title and refresh them, to know their url is still valid or not.

Personally, i would like the feature to find the changed / invalid url of manga titles, and then 'migrate' to the same extension (the title still exist, but under different URL).

I hope i got my message across.

Regards.

**Comment by vongdong** [comment]
I 2nd this. Mangakalot changed their URL some weeks ago and it screwed up a majority of my library (talking 1000+). I primarily use TachiyomiJ2K on a tablet and didn't want to risk migrating so I tried it on my phone and it didn't migrate to the new URL at all, infact some manga actually went missing.

**Comment by Jays2Kings** [comment]
As kakalot breaks more and more, this idea becomes pointless as time goes on. My recommendation is just to migrate to a better source
