### ISSUE TITLE
[Feature Request] Limit migration to individual categories

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#377]
I believe this was mentioned before but I'll just make another incase it hasn't.

It would be great if migration could be limited to categories instead of just extensions. It becomes tedius when one is looking to change sources for a library but have to sift through an entire list of one source. For example, I have 3 categories. 1. ongoing 2. stalled 3. completed

Mangakalot recently changed their URL so I have quite a lot of manga to changeover and I can't rely on the auto migration system so I need to manually do it.

**Comment by Jays2Kings** [comment]
#358
