### ISSUE TITLE
[Bug] "Mark as read" crashes/freezes app

### ISSUE THREAD

**Issue by Jerrk** [Jays2Kings/tachiyomiJ2K#378]
### Device information
* Tachiyomi version: 1.0.2
* Android phone & version: Galaxy Note 8, Android V9

## Steps to reproduce
1. navigate to a page where you can mark multiple chapters as read by dragging them to the left.
2. mark multiple as read in quick succession.
3. app either hangs for several seconds and/or crashes

### Expected behavior
all chapters should be marked as read without issue

### Actual behavior
the app freezes and/or crashes

### Other details
[video of the issue](https://streamable.com/udk86y)

**Comment by Jerrk** [comment]
I still have this issue every single day.

**Comment by CarlosEsco** [comment]
Are you on 1.0.6?

**Comment by Jerrk** [comment]
Yes, i've updated to the latest version every time

**Comment by Jerrk** [comment]
Still have the issue in 1.0.7

**Comment by Jerrk** [comment]
It appears to only be an issue when marking a DOWNLOADED chapter as read with the "remove when marked as read" option enabled. my storage is on an "external" SD card as well which might be contributing to the slowdown.

I did not have this issue with the old app (pre 1.0.0).

**Comment by Jerrk** [comment]
Until this issue is fixed i'll just disable the "remove when marked as read" option which is gonna be a pain with a bunch of stray chapters about after a while.

**Comment by CarlosEsco** [comment]
You can also enable remove after read and it will delete them after you read

**Comment by Jerrk** [comment]
> 
> 
> You can also enable remove after read and it will delete them after you read

that is the cause of my issue.

**Comment by CarlosEsco** [comment]
Are your downloads on an SD card?

**Comment by CarlosEsco** [comment]
Also there are two different options remove when marked as read and remove after read. Which one is causing the issue. Marked as read is when you swipe a chapter to mark it read. After read is after you exit the reader it deletes all that were read

**Comment by Jerrk** [comment]
Yes my downloads are on an SD card.

Both options exhibit the issue of the entire app freezing after a chapter is being deleted from storage.

**Comment by CarlosEsco** [comment]
This sounds like an SD card issue.  What class is it?

**Comment by Jerrk** [comment]
As i said, i did not have this issue in pre 1.0.0

the SD card is the "Samsung MicroSDXC EVO Plus 256GB Class 10"

**Comment by CarlosEsco** [comment]
this should be resolved with #537
