### ISSUE TITLE
[Feature request] Disable topbar pop up in reader if 'Always show chapter transition' is disabled

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#379]
### Device information
* Tachiyomi version: 1.0.3
* Android phone & version: Android 10, Galaxy S10+

Requesting feature to remove the topbar pop up in reader when  'Always show chapter transition' is disabled, as it breaks immersion (especially in webtoon/continuous vertical mode)

**Comment by Jays2Kings** [comment]
Fixed
