### ISSUE TITLE
MangaDex Domain Address Change

### ISSUE THREAD

**Issue by Karma2424** [Jays2Kings/tachiyomiJ2K#38]
Could you change the manga dex domain address from MangaDex.org to MangaDex.cc
Fast plss

**Comment by CarlosEsco** [comment]
Does not belong here at all this fork uses tachiyomi's extensions and any issue with an extension belongs there
https://github.com/inorichi/tachiyomi-extensions

**Comment by Karma2424** [comment]
@CarlosEsco Thanks I did no that

**Comment by orangpelupa** [comment]
@Karma2424 there's a modded mangadex extension for tachiyomi https://www.reddit.com/r/manga/comments/el67r5/release_mangadexcc_fix_for_tachiyomi_android/

**Comment by arkon** [comment]
The official extension has been updated.
