### ISSUE TITLE
[Bug] Can't change reading style on auto detected webtoons

### ISSUE THREAD

**Issue by KraXen72** [Jays2Kings/tachiyomiJ2K#383]
If a manga auto switches to another reading style than default based on its tag (like webtoons), you can't switch it to something else. This is a problem if some manga isn't a webtoon but accidentally has a webtoon tag, you can't read it like a normal manga.

## Steps to reproduce
1. search for manga R402 or Room 402 (this case)
2. start reading, but open the options.
3. try to switch the style to left to right, but when you return, it will still be webtoon
4. if you go to the options again, you will see it switched back to webtoon

## Device information
* Tachiyomi version: J2K 1.0.4
* Android phone & version: xiaomi redmi note 4. Android 7 miui 11

**Comment by e-shl** [comment]
It was https://github.com/Jays2Kings/tachiyomiJ2K/issues/246

**Comment by KraXen72** [comment]
ok
