### ISSUE TITLE
[Feature Request] Uniform covers in everywhere if uniform cover is on

### ISSUE THREAD

**Issue by KraXen72** [Jays2Kings/tachiyomiJ2K#384]
### Why/User Benefit/User Problem
if you decide you want to have covers uniformed, it only makes sense they are uniformed everywhere (i noticed they are not in updates tab, i don't know if somewhere else)

### What/Requirements
if uniform covers is on, then uniform covers everywhere.. (updates tab etc.)

**Comment by joseph619** [comment]
Updates tab is planned to look like List view of Library for consistency.

**Comment by KraXen72** [comment]
ok

**Comment by KraXen72** [comment]
covers are still not uniformed in updates view
