### ISSUE TITLE
[Bug] category switcher border radius isn't full circle

### ISSUE THREAD

**Issue by KraXen72** [Jays2Kings/tachiyomiJ2K#386]
this is really hard to explain, but:
![image](https://user-images.githubusercontent.com/21956756/81535154-96425480-9369-11ea-87fd-a4b949b787c1.png)
these borders should complete a full circle sides.
like this: 
![image](https://user-images.githubusercontent.com/21956756/81535254-c38f0280-9369-11ea-8cf2-1cff8001dc73.png)

**Comment by CarlosEsco** [comment]
phone?

**Comment by KraXen72** [comment]
xiaomi redmi note 4 android 7 miui 11

**Comment by KraXen72** [comment]
this also happens if you have download labels on and you have some unreads on that manga
