### ISSUE TITLE
[Feature Request] Comments for each title and chapter

### ISSUE THREAD

**Issue by NaeemBolchhi** [Jays2Kings/tachiyomiJ2K#389]
### Why/User Benefit/User Problem
Being able to hold discussions about a certain title or chapters, see reviews and interact as a community.

### What/Requirements
If native comments can be implemented, that's great. If not, Disqus could be used instead. The app [NovelReader](https://apkpure.com/novelreader-read-novel-offline-online/ns.free.light.novel.reader) had such an implementation. Making it that the comments section can be turned on and off from settings would be nice. Thank you.

**Comment by CarlosEsco** [comment]
There are no plans to add comments for manga and chapters.
