### ISSUE TITLE
[Bug] Switch category FAB doesn't update correctly

### ISSUE THREAD

**Issue by pranau97** [Jays2Kings/tachiyomiJ2K#390]
### Device information
* Tachiyomi version: 1.0.4
* Android phone & version: Nokia 7 plus, Android 10

## Steps to reproduce
1. Make 2 or more categories
2. Disable "Show all categories" checkmark
3. Switch between the categories by pressing the up or down arrow
4. Notice that the up and down arrows don't update correctly although the buttons still work as expected

### Other details
I have 2 categories - "Planning / On-hold" is the bottom category. The down arrow is still active even though it's the last category on the list. The up arrow appears disabled even though there are categories above it.
![image](https://user-images.githubusercontent.com/12474765/81579350-af7aed80-93c9-11ea-940c-36001d27f189.png)

![image](https://user-images.githubusercontent.com/12474765/81579424-c7eb0800-93c9-11ea-8f48-fad7eb37ae7d.png)

**Comment by Jays2Kings** [comment]
This should be fixed now
