### ISSUE TITLE
Ability to switch to other tabs by swiping the screen

### ISSUE THREAD

**Issue by heksagen** [Jays2Kings/tachiyomiJ2K#392]
### Why/User Benefit/User Problem
(explain why this feature should be added)
This makes it easier to those who hold their phone with one hand to switch to other tabs, because most of smartphones are long and maybe your thumb might not reach the icon below to switch to other tabs.

### What/Requirements
(explain how this feature would behave)
You can switch to the library, recents, and browse tabs just by swiping your screen left and right.

**Comment by joseph619** [comment]
This is not happening, use the category hopper or the dropdown. Or use Stable.

**Comment by KraXen72** [comment]
there is a bottom nav. It couldn't be physically easier to switch to those tabs.

**Comment by CarlosEsco** [comment]
no plans to add swipe to the navigation
