### ISSUE TITLE
[Feature Request] RECOMMENDATIONS

### ISSUE THREAD

**Issue by yatodummy** [Jays2Kings/tachiyomiJ2K#395]
### Why/User Benefit/User Problem
Having these kind of features helps to find similar manga you've like andalso especially when you don't have any friends to look for recommendations :)

### What/Requirements
Adding a recommendation button like SY or Neko 
![Screenshot_20200512-193944_TachiyomiSY](https://user-images.githubusercontent.com/65228623/81683461-bddc0e80-9488-11ea-8467-cf44e985b3f6.png)
![tmp-cam-6904118528068130659](https://user-images.githubusercontent.com/65228623/81683530-cc2a2a80-9488-11ea-8f5b-2c181fb92dda.jpg)

**Comment by CarlosEsco** [comment]
#373
