### ISSUE TITLE
[Bug] BGM tracking error

### ISSUE THREAD

**Issue by lemako** [Jays2Kings/tachiyomiJ2K#396]
---

### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: MI9PRO Android 10

## Steps to reproduce
1. First step serch manga title
2. Second step select and enter track

### Expected behavior
nothing

### Actual behavior
![Screenshot_20200512-200745921](https://user-images.githubusercontent.com/38862056/81688864-6f307380-948c-11ea-9e5f-435cbc7b15a0.jpg)

### Other details
The original  tachiyomi 0.92 don't have this problem, maybe you need to merge request.

thanks for you great work.

**Comment by CarlosEsco** [comment]
This should be resolved now on 1.0.7 .  Please open a new issue if it is not
