### ISSUE TITLE
[Feature Request] Add category name to saved manga's page

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#398]
### Why/User Benefit/User Problem
Let's us know which category the manga is added to without having to manually check

### What/Requirements
Currently all saved manga display a heart with 'in library'. What I'd like to see is the same but have the category it's saved to next to 'in library'

**Comment by Jays2Kings** [comment]
Not happening. that would take up too much space, and the manga can be in multiple categories. You can long press the in library button to see what categories they're in
