### ISSUE TITLE
[Bug] Download queue gets cleared randomly

### ISSUE THREAD

**Issue by Raidou13** [Jays2Kings/tachiyomiJ2K#399]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Redmi K20Pro/MiUI 11/Android 10

Since updating to 1.0.x my download queue is always being cleared for no reason, the first time it was cleared was right after updating to 1.0.0, i thought it was normal after updating to md2, but it happened again for a second time after some time, but then it happened after the app crashed. Now it happened again earlier but this time  the app did not crashed it just cleared for no reason After launching the app i just checked the queue and it was cleared again.

**Comment by Jays2Kings** [comment]
Please add a proper title or this will be closed

**Comment by CarlosEsco** [comment]
Do you still have this issue?

**Comment by Raidou13** [comment]
Well not anymore I guess
