### ISSUE TITLE
[Bug] Cover not showing for GetManhwa

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#405]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Note9/Android 10

Source: Mandara
Version 1.2.92

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Cover image should show

### Actual behavior
Bookmarked manhwa's covers are not displaying in library or in browse. 

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
sounds like a bug should be posted here.  unless you are saying it doesn't work in stable either
https://github.com/inorichi/tachiyomi-extensions

**Comment by vipzzx** [comment]
Not sure if it is just in j2k or in stable also. Like I am unable to edit the cover image either. Ainz said to post it here.

**Comment by vipzzx** [comment]
![Screenshot_20200512-215140_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/81812778-9884ea00-94f4-11ea-9c9f-eacc9ff3d2ba.jpg)
#
![Screenshot_20200512-214947_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/81812799-a0dd2500-94f4-11ea-8c91-d01e76dfede8.jpg)

**Comment by vipzzx** [comment]
think its more extension issue. i opened an issue there
