### ISSUE TITLE
[Bug] Mangaowl images wont open

### ISSUE THREAD

**Issue by mmyucel** [Jays2Kings/tachiyomiJ2K#408]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Xiaomi Mi A1 Android 9
* Mangaowl version 1.2.5

## Steps to reproduce
1. Choose a manga from mangaowl
2. Open any chapter

### Expected behavior
Should open image

### Actual behavior
Shows retry button

### Other details
Same addon version on original tachiyomi app works fine. Thats why im posting this here.

**Comment by Jays2Kings** [comment]
Mangaowl seems to be working fine, it could've have just been the server having issues at the time, can you provide which manga and chapter isnt working?

**Comment by mmyucel** [comment]
For instance Isekai Meikyuu de Harem o chapter 0. And i checked and there is a server issue on Mangaowl but im not sure if its related.

**Comment by Jays2Kings** [comment]
So it was only a server issue, so I'm closing this. Always check on webview as well to make sure the site is running.
