### ISSUE TITLE
[Feature Request] Improved Sort by Sources in My library

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#41]
Currently, the Sort  by sources feature in My library is useless, since there's no way to know what titles belong to which source before clicking it.

Manga Rock has the same feature but much better implemented. Here's an example in screenshot below. 

It shows the thumbnails under the Source name (which also shows the manga count).

![20200108_031254](https://user-images.githubusercontent.com/34897862/71961503-70dbe900-31c5-11ea-8d99-485206052dcf.jpg)

An exact copy of this is not necessary, something similar that just shows the source name so that we can directly know what manga belongs to what source.

Also for the post title, can the bug label be changed? I put it bug by mistake.

**Comment by Jays2Kings** [comment]
Yeah this can't happen the way the library is implemented. At best there could be a label on each entry say what source it's from, but having it grouped with a header is way to heavy a workload for this

**Comment by joseph619** [comment]
Label on each entry might look ugly, but it's still better than nothing I suppose. All up to you to decide whether it's worth it.

**Comment by CarlosEsco** [comment]
@Jays2Kings   a couple hacking workaround
1.  A dummy manga for the source  that is placed in front of the other manga in that source.  
2.  label you can hide or show like you mentioned
3.  remove option to sort by source but allow filter by source so only the selected source or sources are shown

**Comment by joseph619** [comment]
I did't understand what Carlos suggested for option 1, but option 3 is acceptable for me. Not as I wished originally but it should work well.

**Comment by CarlosEsco** [comment]
Option 1 would basically look like a manga cover that says the source.  but would be unclickable.  it would be the first entry for the source.  so when you saw that entry you would know everything after is part of that source.  if that makes sense

**Comment by joseph619** [comment]
I understand now, it would look pretty weird though. I like your idea of removing the useless sorting entirely and replace it with filter (option 3).

**Comment by Jays2Kings** [comment]
Option 3 would be best, I attempted 1 and the result isn't pretty

**Comment by Jays2Kings** [comment]
And now option 3 is in 0.9.61
