### ISSUE TITLE
[Feature Request] Automatic start and end dates.

### ISSUE THREAD

**Issue by Eggroley** [Jays2Kings/tachiyomiJ2K#410]
Automatic start and end dates can let you know when you first started and finished your manga. This is a feature that MyAnimeList has, I'm sure Anilist also has this.

Similar to the app [MALClient](https://play.google.com/store/apps/details?id=com.drutol.malclient)  start dates can be added as soon as chapter 1 is marked as read, and end dates once you have read the last chapter. 

Seen here in the MALClient app, the start date reads "not set"
![SmartSelect_20200513-192253](https://user-images.githubusercontent.com/58383883/81879102-60f75b80-954f-11ea-892f-6a3c2620b8e6.jpg)

Once I press the plus icon at the top right corner and tap yes.
![SmartSelect_20200513-192330](https://user-images.githubusercontent.com/58383883/81879173-a1ef7000-954f-11ea-92ce-bd89179d0397.jpg)

The start date is then set.
![SmartSelect_20200513-192347](https://user-images.githubusercontent.com/58383883/81879223-c64b4c80-954f-11ea-8638-0007b6c47606.jpg)

**Comment by Jays2Kings** [comment]
Added a while ago
