### ISSUE TITLE
[Bug] App freezing/ not responding when opening manga in extension for 1-2mins

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#412]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Galaxy Tab S6

## Steps to reproduce
Looking/ searching on extension, touch desired manga to be opened and it freezes for about 1-2mins then opens the info page

### Expected behavior
Info page should immediately open

### Actual behavior
Selected manga is highlighted but the whole app freezes for 1-2mins

### Other details
It randomly happens. I've attached a screenshot. As you can see, I tried to open Jagaaaaan and it froze like that. If I leave it like that then it eventually opens the page and everything returns to normal.
![Screenshot_20200514-143900_TachiyomiJ2K](https://user-images.githubusercontent.com/60080780/81893601-52fa1700-95f1-11ea-869f-7a13b68b2b8f.jpg)

**Comment by CarlosEsco** [comment]
What source and were you having issues with their site in webview. This is more than likely an issue withe source just being slammed.

**Comment by vongdong** [comment]
> What source and were you having issues with their site in webview. This is more than likely an issue withe source just being slammed.

Its happens in all my sources (mangadex, mangakalot and mangasee). I don't use the Web view.

**Comment by CarlosEsco** [comment]
well you should use the webview to verify the source is working when you are having issues like this

**Comment by vongdong** [comment]
> well you should use the webview to verify the source is working when you are having issues like this

Never happened in the older version but I'll check it out anyway. I can hold and add just fine though.

**Comment by vongdong** [comment]
> well you should use the webview to verify the source is working when you are having issues like this

Can confirm it's not the source. It just happened on my S6, tried it with my S10 and it works fine there.

**Comment by CarlosEsco** [comment]
This should be fixed with #537
