### ISSUE TITLE
[Feature Request] Reverse sort button for Recent history

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#413]
# Why/User Benefit/User Problem
Currently, it's very hard to access the last read manga on Recent history, as it's located at the very top. 

# What/Requirements
A sort button that can reverse the order of manga on Recently read, to make the last read manga easier to access.

**Comment by CarlosEsco** [comment]
couldnt you just go to library, show all categories, sort by last read reverse?

**Comment by joseph619** [comment]
I sort Library by Latest chapter mostly, Recently read is for when I want to read something irrespective of the categories. 

It's a 3 year old habit at the point lol

**Comment by Yronk** [comment]
my search and filter genre button in browse section missing...what happen..

**Comment by Yronk** [comment]
> I sort Library by Latest chapter mostly, Recently read is for when I want to read something irrespective of the categories.
> 
> It's a 3 year old habit at the point lol

does your search button and filter genre button there in browse section..please help

**Comment by Yronk** [comment]
> couldnt you just go to library, show all categories, sort by last read reverse?

my search and filter genre button in browse section missing...what happen..

**Comment by joseph619** [comment]
@Yronk You can discuss that on Discord, doesn't sound like a bug to me.

**Comment by joseph619** [comment]
This isn't how mobile UI is supposed to work, so closing
