### ISSUE TITLE
[Feature Request] adjust zoom value when double tapping screen

### ISSUE THREAD

**Issue by Raidou13** [Jays2Kings/tachiyomiJ2K#417]
### Why/User Benefit/User Problem
Double tap zoom just zooms in too much, and will just show less of the whole specifically for landscape double-pages and maybe webtoon too. I would like to have feature to customize how much zoom double tapping will do.
This will really help for one-handed use for the app specially when reading while standing (Tachiyomi™️ LOL)

Here's the fit-screen view
![Screenshot_2020-05-14-23-20-27-572_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/13474745/81954342-51edd780-963b-11ea-89f8-f1da1b259833.jpg)

Here's what I expect it to do after double tap
![Screenshot_2020-05-14-23-22-09-142_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/13474745/81954453-734ec380-963b-11ea-9c20-3dd5fa195394.jpg)

Here's what it will actually do:
![Screenshot_2020-05-14-23-21-22-370_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/13474745/81954540-8feafb80-963b-11ea-8bff-200db3ddef33.jpg)

### What/Requirements
Put an option to change zoom value percentage via slider or multiple choice somewhere in the reader settings.

**Comment by CarlosEsco** [comment]
#137
