### ISSUE TITLE
My search and filter genre button missing in browse section

### ISSUE THREAD

**Issue by Yronk** [Jays2Kings/tachiyomiJ2K#418]
---

### Why/User Benefit/User 
Easier finding manga genre

### What/Requirements
Search and genre button in browse section
![Screenshot_20200515-014505_TachiyomiJ2K](https://user-images.githubusercontent.com/65336081/81968554-1fe67080-964f-11ea-8ac1-7705cb18db31.jpg)

**Comment by CarlosEsco** [comment]
Click the title of the source not the latest button

**Comment by Yronk** [comment]
> Click the title of the source not the latest button

Omg thank you...now im gonna use it as my daily reader app
