### ISSUE TITLE
[Bug] Inconsistence in library filter

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#419]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
List of tracking sites should show to the right of tracking in filter.

### Actual behavior
When I filter Tracked, the list of tracking sites will show on the right, but if another filter is used first and then tracking is in addition to, the list will appear on the left

### Other details
Additional details and attachments.

[Screen_Recording_20200514-222400.zip](https://github.com/Jays2Kings/tachiyomiJ2K/files/4631930/Screen_Recording_20200514-222400.zip)

**Comment by Jays2Kings** [comment]
Fixed in commit bc8ed36
