### ISSUE TITLE
[Bug] Zooming Out cuts out parts of last page of webtoon

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#421]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Note9/Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Show the whole page.

### Actual behavior
If I zoom out then zoom back in, it doesn't show the rest of the page.

### Other details
Additional details and attachments.
[Screen_Recording_20200514-230606.zip](https://github.com/Jays2Kings/tachiyomiJ2K/files/4632033/Screen_Recording_20200514-230606.zip)

**Comment by Jays2Kings** [comment]
This is an issue in base Tachiyomi as well, please make an issue there since the dev responsible for adding zooming out (not me) can fix the issue

**Comment by vipzzx** [comment]
Got it. See an issue was made 15 days ago. Guess just have to wait and dont accidentally trigger zoom out
