### ISSUE TITLE
[Feature Request] Faster transition of sorting by tapping arrows

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#425]
### Why/User Benefit/User Problem
Faster transition for sorting manga in ascending/descending order.

### What/Requirements
Make it instantly sort by ascending/descending order by tapping the up/down arrows instead of opening the full list and selecting the sorting type again.

**Comment by Jays2Kings** [comment]
closing this since the behaviour has changed in 1.0.6

**Comment by vipzzx** [comment]
Still want the same feature. The behavior is a bit different from 1.0.6 but in 1.0.7 it still opens to the full menu.
