### ISSUE TITLE
[Feature Request] Add Tag Categories filter & Edit Tag Features

### ISSUE THREAD

**Issue by yatodummy** [Jays2Kings/tachiyomiJ2K#427]
### Why/User Benefit/User Problem

Adding tag filter in the categories can easily distinguish and find the genre without typing the tags above andalso in editing tags can help to replace wrong tags (for e.g. most of the manwha/manhua doesn't have a label or the tags of it and it considered as a manga type)

![Screenshot_20200516-201446_TachiyomiJ2K](https://user-images.githubusercontent.com/65228623/82119804-f72bbb80-97b3-11ea-9654-3c93fd222c92.png)

### What/Requirements
![tmp-cam-9109321023536580476](https://user-images.githubusercontent.com/65228623/82119774-c21f6900-97b3-11ea-9975-a5c8d61927ab.jpg)
Here's my edit to visually imagine it, in addition the edit tags in local manga I hope it can be done to the library manga too. Ps. Sorry for my wrong english&grammar 

![Screenshot_20200516-203343_TachiyomiJ2K](https://user-images.githubusercontent.com/65228623/82119902-bf714380-97b4-11ea-8a4d-e2ae2633715e.png)

**Comment by CarlosEsco** [comment]
Editing non local manga is not coming back

**Comment by yatodummy** [comment]
> Editing non local manga is not coming back

: (
Why editing non-local manga isn't coming back?

**Comment by Jays2Kings** [comment]
As carlos said it's not happening
