### ISSUE TITLE
[Feature Request] Suggest similar Manga/manhua

### ISSUE THREAD

**Issue by kolla47** [Jays2Kings/tachiyomiJ2K#429]
Suggest similar Manga/mangia/webtoon on the end of the discription page form similar source or different source.

### Why/User Benefit/User Problem
Engages Users to spend more time on reading rather than browsing for Manga since there are a lot of sources.

### What/Requirements
When a Manga/mangia/webtoon is opened there has to be section in the bottom of the page for similar Manga from same source or different sources.

**Comment by CarlosEsco** [comment]
#373
