### ISSUE TITLE
add languages ​​in sources in auto migration

### ISSUE THREAD

**Issue by MakuSensei** [Jays2Kings/tachiyomiJ2K#43]
Hello, I wanted to ask that the corresponding language be in parentheses in each auto-migration source. In the menu where the sources to search are enabled and disabled. I hope you understand what I explain. I use google traductor.
I'm using octodroid on android so it doesn't let me upload a screenshot to show

**Comment by MakuSensei** [comment]
![Screenshot_20200108-174700](https://user-images.githubusercontent.com/16900914/72015098-e2587d80-323f-11ea-8f3f-6eb2df25b6c9.png)

**Comment by MakuSensei** [comment]
In that capture, what I ask for is something like this: E-hentai (Ja), E-hentai (En)

**Comment by joseph619** [comment]
This seems like a feature request for TachiEh or AZ.

**Comment by Jays2Kings** [comment]
It's a valid concern for this fork. With multiple languages enabled there isn't a way to distinguish which source is for which language. It applies to all multi-langauge source

**Comment by Jays2Kings** [comment]
This has been added as of 0.9.6
