### ISSUE TITLE
[Feature Request] Add downloadLock button / Comic

### ISSUE THREAD

**Issue by xlixAxilx** [Jays2Kings/tachiyomiJ2K#431]
### Why/User Benefit/User Problem
My preferred options are:
--- Remove after read: Last read chapter
--- Download new chapters

Now because this will download the new chapters and delete them as soon as I read them it works perfectly, but there is manga I do want to keep.
The problem is that if I want to reread a comic after the chapter is read it will be deleted, currently if I were to deactivate "remove after read" and activate "remove when marked as red" the chapters wouldn't get deleted, but then the new chapters that I'm reading wouldn't get deleted and I'd have to manually delete them. 
xD

### What/Requirements
So if we had a new button that looks like a "lock" placed besides the download button or anywhere that makes sense, we could lock that comic from having any automatic changes made on them regarding downloads.
It would be something like:

comic has property { lock: true/false } // gets updated when we tap the button
if comic.lock not true { then do automatic }

**Comment by joseph619** [comment]
You could just bookmark the chapters you like and download those chapters manually.

**Comment by xlixAxilx** [comment]
I don't understand how that solves the problem, since they would get deleted after I read them.
The idea is to keep the ones that I don't want to be deleted ever, download the new chapters of a comic when they come out, and delete the ones that I've read.
The problem is that u can't have the "remove after read" option active and download at the same time since everything u read will get deleted.
Either way give it a thought, and if u think it's useless then we can drop it.

**Comment by CarlosEsco** [comment]
Move the ones you want permanent to a local manga.  There is no guarantee the site doesn't update and removes those chapters anyways.  Then you have to make a local manga anyways with the orphaned downloads

**Comment by joseph619** [comment]
Local manga isn't affected by that setting yes

**Comment by xlixAxilx** [comment]
ight, u can close the issue then.
:)
