### ISSUE TITLE
[Bug] When in landscape Webtoon or Continuous Vertical mode, upper ~half of the screen doesn't register input for scrolling after opening the upper drawer

### ISSUE THREAD

**Issue by Nocifer** [Jays2Kings/tachiyomiJ2K#434]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Mi 9T, Android 10

## Steps to reproduce
1. Open manga in Webtoon or Continuous Vertical mode.
2. Switch to landscape.
3. Try to scroll the manga, everything works properly.
4. Scroll down from upper edge to open the upper drawer (displaying manga info and settings buttons).
5. Return to the manga and try to scroll it from the upper half of the screen towards the lower half.

### Expected behavior
The manga scrolls normally.

### Actual behavior
The touch input doesn't register and the manga doesn't scroll.

### Other details
"Clicking" once on the upper half (thereby scrolling the manga half a page up) gives you a window of about half a second to put your finger on the screen and then scroll the manga normally, then reverts to the broken behavior.

Having the upper drawer open allows you to scroll the manga normally.

Input works properly in portrait mode.

**Comment by Jays2Kings** [comment]
Can you record a video of this, I'm not able to replicate it

**Comment by Nocifer** [comment]
Sure can, [here's the link](https://streamable.com/jtiz0y). A short explanation of what's happening in the video (the white dot at the upper right part of the screen is my touch input):

- At first, scrolling works properly, both by tapping and by touching & dragging the screen.
- At the 0:08 mark I touch & drag the top edge to reveal the drawer and then wait until it hides itself.
- At the 0:12 mark I again try to scroll by touching & dragging the upper part of the screen, but now the content won't scroll. But as you can hopefully see, if I touch & drag at a slightly lower part of the screen, then I'm able to scroll.
- At the 0:24 mark I tap the upper part of the screen and the content scrolls up by a half page. As soon as I've tapped, and before the content has finished scrolling, I tap again and hold my finger on the screen, and now I'm once more able to scroll by dragging the screen.
- At the 0:28 mark I release my finger, and when just a second later I try to tap the screen again and scroll by dragging, it has already stopped working.

If I had to guess, based on the point in time this happens and the area of the screen that is affected, I'd say that when the app drawer is revealed and then hidden, for some reason the app thinks it's still present on the screen and thus tapping and dragging doesn't work because it thinks I'm tapping and dragging not on the content but on the drawer that supposedly still overlays the content. Tapping the screen momentarily "fixes" this behavior, but it regresses as soon as the scrolling stops.

Also, contrary to what I said in the first comment, this also happens in portrait mode.

**Comment by Nocifer** [comment]
It seems that the problem has been fixed in 1.0.6, so this report can be closed.
