### ISSUE TITLE
[Bug] Sorting in sources crashes

### ISSUE THREAD

**Issue by e-shl** [Jays2Kings/tachiyomiJ2K#436]
# Device information
* Tachiyomi version: r2608
* Android phone & version: 6.0 (Flyme 6.3.1G)

## Steps to reproduce
1. Source launch (e.g. mangadex)
2. Attempt to select sort

Video from 1.0.5:
https://drive.google.com/open?id=1_rP-zAM6AtkVOFPR_EyQHff0IvR9mQ2z

### Actual behavior 
Show message:

Application: eu.kanade.tachiyomi.debugJ2K
Manufacturer: Meizu
Model: M5s
Brand: Meizu
Device: M5s
Board: M5s
Hardware: mt6735
Product: meizu_M5s
Android Version: 6.0

java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f04000a a=-1}
androidx.core.content.res.TypedArrayUtils.getNamedColorStateList(TypedArrayUtils.java:172)
androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:765)
androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719)
androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:664)
eu.kanade.tachiyomi.ui.source.filter.SortItem$bindViewHolder$1.invoke(SortItem.kt:38)
eu.kanade.tachiyomi.ui.source.filter.SortItem.bindViewHolder(SortItem.kt:45)
eu.kanade.tachiyomi.ui.source.filter.SortItem.bindViewHolder(SortItem.kt:16)
eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1772)
androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1897)
androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:414)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:896)
android.view.Choreographer.doCallbacks(Choreographer.java:698)
android.view.Choreographer.doFrame(Choreographer.java:630)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:882)
android.os.Handler.handleCallback(Handler.java:815)
android.os.Handler.dispatchMessage(Handler.java:104)
android.os.Looper.loop(Looper.java:207)
android.app.ActivityThread.main(ActivityThread.java:6009)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)

**Comment by joseph619** [comment]
Wrong repo? J2K latest version is 1.0.5, you're using something else

**Comment by e-shl** [comment]
@joseph619 collected by the latest commits.  In 1.0.5, as you can see from the video, it just crashes.

**Comment by joseph619** [comment]
Why are you posting bug report for an unreleased version?
