### ISSUE TITLE
[Bug] Only Installed Extensions Shown

### ISSUE THREAD

**Issue by iecg** [Jays2Kings/tachiyomiJ2K#437]
#325 # Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Samsung Galaxy Note 9, Android 10

## Steps to reproduce
1. Go to the browse tab
2. Pull up the extension drawer

### Expected behavior
I expect to see installed and not installed extensions. 

### Actual behavior
Only installed extensions are displayed. 

### Other details
![Screenshot_20200520-011643_TachiyomiJ2K](https://user-images.githubusercontent.com/8894160/82407825-2f433080-9a38-11ea-8dbe-ac312a90fa0d.jpg)

**Comment by geraldlnj** [comment]
+1

**Comment by CarlosEsco** [comment]
This was a bug with extensions github it should be resolved now
