### ISSUE TITLE
[Feature Request] Confirmation before using clean up options

### ISSUE THREAD

**Issue by Crzyadian** [Jays2Kings/tachiyomiJ2K#438]
Just wanted an confirmation option for downloaded chapter option 
because you can accidentally delete all your read downloads in advanced settings

Why this is required: - CAN PREVENT ACCIDENTAL LOSS OF DOWNLOADS

**Comment by CarlosEsco** [comment]
it says this deletes read chapters...  its not like its a hidden delete

**Comment by Crzyadian** [comment]
o once accidentally clicked it and without any confirmation saw all my read downloads vanish unable to stop it 
that's what I'm saying

**Comment by Crzyadian** [comment]
Fixed
