### ISSUE TITLE
[Feature Request] Double page viewer

### ISSUE THREAD

**Issue by fighuass** [Jays2Kings/tachiyomiJ2K#439]
### Why/User Benefit/User Problem
Viewing single pages as is the default in Tachiyomi wastes a lot of screen space on tablets when in the default orientation (landscape), the other option is viewing them fullscreen in portrait mode which fills the entire screen but if the scans are low quality (often the case with older scans and crappy reader sites) this will cause the manga to look blurry and crappy, so this is not a 100% foolproof method. A double page layout will allow tablet users to fill their screen space in landscape mode, while not stretching the pages like in portrait mode, making good use of the screen space, and allowing for a more authentic way of reading manga. This will also prevent problems with 2-page spreads and display them like they were meant to.

### What/Requirements
Add an option that allows you to pick between single pages (for people on phones) and double pages (for people on tablets). Default will probably be single pages since the majority uses a phone, for tablet users they can switch it to double pages and this will cause pages to be neatly shown like [this](https://i.imgur.com/FnAdcLq.jpg) instead of the default, which is [this](https://i.imgur.com/jbM1OA7.jpg).

**Comment by Jays2Kings** [comment]
It's been discussed many times before but it's not going to happen since the tablet audience is small, and there's tablet users who have said they wouldn't use/need it.
