### ISSUE TITLE
[Bug] Automatic migration does not find manga

### ISSUE THREAD

**Issue by e-shl** [Jays2Kings/tachiyomiJ2K#440]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: 10

## Steps to reproduce
Perform manga migration.

### Actual behavior
The manga not search automatic, but is in manual mode without changing the request.
https://drive.google.com/open?id=1bWCcj0LiV8ZqmuvMO5az3rHCX0Y2ILgL

**Comment by Jays2Kings** [comment]
Automatic migration wouldn't work in this case because the title you're searching for is in russian and the results are an english and a romanji title. Because there's multiple results the auto migration tool has no idea which manga to use, which is why the manual search exists
