### ISSUE TITLE
Inclusion of mangaupdates in web view option of manga screen

### ISSUE THREAD

**Issue by sukhijapiyush** [Jays2Kings/tachiyomiJ2K#441]
In manga details screen, inclusion of mangaupdates link similar to Neko fork of tachiyomi as it will help in managing as a tracker.

### Why/User Benefit/User Problem
It will help in managing the updates of mangaupdates as normally i login in chrome and i update using open in browser.

### What/Requirements
It can be as simple as that and it would be possible to import it from neko fork.

Thanks a lot and stay safe 😄😄😄😄

**Comment by CarlosEsco** [comment]
Not really possible unless it just opened a generic search to manga updates.

The reason Neko has it is mangadex returns the url for mangaupdates when you query their api
