### ISSUE TITLE
Bug with readm view latest

### ISSUE THREAD

**Issue by medoria0** [Jays2Kings/tachiyomiJ2K#447]
### Device information
* Tachiyomi version: v1.0.5
* Android phone & version: version 8.0.0

## Steps to reproduce
1. Download readm source
2. Click view latest

### Expected behavior
You should see the latest uptaded mangas (each one) in a separate folder

### Actual behavior
The manga is in a folder with complete chapters but the covers doesn't load unless you click on it and also the latest updated chapters are in a seperate folder too

### Other details
An example, also I clicked on the mangas so the cover could load, normally it wouldn't load alone, plz fix this
![Screenshot_20200523-034707_TachiyomiJ2K](https://user-images.githubusercontent.com/64145746/82729549-bb837b00-9cf8-11ea-97c7-f480000a2d36.jpg)

**Comment by joseph619** [comment]
This is likely a source/extension issue, not app. Try on Stable 0.9.2 as well.

**Comment by Riztard** [comment]
this happened on preview as well, so source/extension issue
