### ISSUE TITLE
[Bug] Can't reorganize category list

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#448]
### Device information
* Tachiyomi version: 1.0.5
* Android phone & version: Note9/Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Be able to reorganize categories smoothly.

### Actual behavior
Unable to move categories lower in list where it requires to scroll down.
When i scroll down to move it, the screen will scroll back up

### Other details
Additional details and attachments.
[Screen_Recording_20200523-100053.zip](https://github.com/Jays2Kings/tachiyomiJ2K/files/4671875/Screen_Recording_20200523-100053.zip)

**Comment by Jays2Kings** [comment]
Fixed in 7c034f0
