### ISSUE TITLE
[Feature Request] Add Cancel all download queue for a single title

### ISSUE THREAD

**Issue by Raidou13** [Jays2Kings/tachiyomiJ2K#449]
### Why/User Benefit/User Problem
whenever I find a new title to read I always add all the chapters to download queue in advance, but there are times that I want to cancel all the downloads for that specific title but it's hard to do that if it has more than 50 chapters and without clearing the other chapters from other titles in the download queue .and swiping them each manually is a bad idea lol, specially for titles with 100+ chapters

### What/Requirements
Place an "cancel download" inside the title to clear download queue, next to or inside the "remove downloads"
![IMG_20200523_232546](https://user-images.githubusercontent.com/13474745/82734304-c536ce00-9d4c-11ea-9d79-56ef02d94036.jpg)

**Comment by Caio99BR** [comment]
@Jays2Kings issue fixed

---

On Download Queue > 3-dots of title > Cancel all for this series (or something like this, mine is translated)
