### ISSUE TITLE
[Feature Request] Ranged page download

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#45]
### Why/User Benefit/User Problem
The user can download a certain amount of pages, for example 30-60, instead of the entire chapter. Some manga chapters can be ...very large. There are many series on 18+ sites which have 500-1000+ pages, and it's either impossible or pointless to download entirety of it. Users can download only select pages in range and read those offline.

### What/Requirements
When the triple dot besides a chapter is click, we will see an option called ranged chapter download, under download. Clicking on ranged will give us an option to download pages within the range.

Screenshots below to show how it might work

![viber_image_2020-01-09_10-56-2 (1)](https://user-images.githubusercontent.com/34897862/72086918-b982c780-32d5-11ea-9bef-3ace8ad01260.jpg)
![viber_image_2020-01-09_10-56-2](https://user-images.githubusercontent.com/34897862/72086922-bb4c8b00-32d5-11ea-931d-c5fa71823b39.jpg)

**Comment by joseph619** [comment]
Not really needed for regular Tachi, and requires a lot of work. Closing

**Comment by CarlosEsco** [comment]
side not why would a source put 500+ images in one chapter lol.

**Comment by joseph619** [comment]
@CarlosEsco Those are mostly on Ehentai, usually it's Western porn who don't release comics in chapter format, rather a single page/group of pages every week, which keeps incrementing.
