### ISSUE TITLE
[Bug] Tags merging with other library's

### ISSUE THREAD

**Issue by bloodkingBk** [Jays2Kings/tachiyomiJ2K#451]
(https://streamable.com/83ltbg)

I'm not sure how to explain it but the tags ie. Unread/not started. For some reason they merge with the other library's instead of the library I'm in. The way I have to update it is to go to the library tab and tap on it again. All my unread I finished reading, I think it should be a empty page in my reading library instead of showing my default library that's unread (Video will be attached above)

**Comment by Jays2Kings** [comment]
This is intended behavior, categories do not have seperate filters
