### ISSUE TITLE
[Library] Auto-generate catalog per source

### ISSUE THREAD

**Issue by quangkieu** [Jays2Kings/tachiyomiJ2K#453]
**App version:**
1.0.5
**Android version:**
Android 10
**Issue/Request:**
Request
**Steps to reproduce (if applicable)**

 1. User add new comic to library
 2. If this comic from a new source
 3. Create new catalog for that source and auto tag the source to comic

**Other details:**
I only request this solution as time of writing, 1st Kiss source having problems and down for fews hours. During that time the app keep trying to sync to this source. If we have this, I could temporarily disable one source from global update

Best regard

**Comment by quangkieu** [comment]
And the app used lots of battery to hot and keep trying to update from a down source

**Comment by Jays2Kings** [comment]
Closing because its not the newest version
