### ISSUE TITLE
[Feature Request] Option to use old tachiyomi chapter navigation bar

### ISSUE THREAD

**Issue by anonmagnon** [Jays2Kings/tachiyomiJ2K#454]
**Why/User Benefit/User Problems**
Some users find it hard and counter-intuitive to navigate through chapters using the new navigation bar. It would be better to add an option to change back to the old navigation bar, or to simply add forward and backward buttons.
![IMG_20200525_123122](https://user-images.githubusercontent.com/65882506/82778327-b0a92180-9e83-11ea-96ca-645f19fe11d2.jpg)

**What/Requirements**
Add forward and backward buttons to navigate through chapters forward and backward.
![IMG_20200525_115654](https://user-images.githubusercontent.com/65882506/82778177-324c7f80-9e83-11ea-8d1c-d928f1e2297a.jpg)

**Comment by CarlosEsco** [comment]
Not coming back.
