### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by CerealKiller7** [Jays2Kings/tachiyomiJ2K#455]
### Device information
* Tachiyomi version: 1.0.6
* Android phone & version: Samsung Galaxy J5

### Problem
When you open the Renascence Scans(Renascans) on Tachiyomij2k it say that there is a http error 404 but when you open it on web view it works fine.

**Comment by CarlosEsco** [comment]
Sounds like an extension issue that should be opened in the tachiyomi extensions repository
