### ISSUE TITLE
[Feature Request] Download Unread Chapters Button

### ISSUE THREAD

**Issue by allandck123** [Jays2Kings/tachiyomiJ2K#457]
### Why/User Benefit/User Problem
Sometimes when I find a new title to read I'll just read it normally without downloading the chapters, but there are times that I dont have the time to read it all in one go, and want to download the unread chapters to read it later without any problem. So instead of putting the chapters one by one to download queue, it would be easier to have download unread chapters button to put all unread chapters to download queue in one go. Tachiyomi stable ver. also have this button inside the 3 dots dropdown menu

### What/Requirements
Place a "Download Unread Chapters" Button in this dropdown menu
![Screenshot_20200526-171204_TachiyomiJ2K](https://user-images.githubusercontent.com/46028608/82889025-55a32780-9f74-11ea-9dfb-54587fac8bf8.jpg)

**Comment by CarlosEsco** [comment]
There's a download button at the top menu already to the left of the 3 dot..
