### ISSUE TITLE
[Bug] Can't download or remove chapters not in filtered list

### ISSUE THREAD

**Issue by tAzO8596** [Jays2Kings/tachiyomiJ2K#459]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: POCO F1 Android 10

## Steps to reproduce
1. Set chapters filter to downloaded or anything else
2. Download unread chapter/s or Remove read chapters

### Expected behavior
Chapter/s should start downloading or read chapters be removed

### Actual behavior
Nothing happens

**Comment by CarlosEsco** [comment]
Can you provide a video or gif of the issue
