### ISSUE TITLE
[Bug] Update Library Fail

### ISSUE THREAD

**Issue by Mano5JP** [Jays2Kings/tachiyomiJ2K#460]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Note 10 + android 10

### Expected behavior
Should update manga's without error.

### Actual behavior
manga's doesn't update & has error.

### Other details
source: mangabox (manganelo)

Error receive
**java.net.UnknownHostException: Unable to resolve host "manganelo.com": No address associated with hostname**

**Comment by CarlosEsco** [comment]
That means you are unable to connect o mangnelo.  Either migrate your manga from it.  Or wait until you can access.
