### ISSUE TITLE
[Feature Request] Show what manga i have in a specific extension

### ISSUE THREAD

**Issue by Arthur-o-b** [Jays2Kings/tachiyomiJ2K#464]
Why/User Benefit

When i go to a specific extension i would like to be able what manga i'm currently reading from there so i can know if i want do uninstall it or not.

What/Requirements

When looking at a extension show what titles from my library are from this extension, in the same place as the preferences show.

**Comment by CarlosEsco** [comment]
In your library search the source name.  It wilo show just those manga
