### ISSUE TITLE
[Bug] Refresh tracking metadata closes app and signs out of MAL

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#465]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Note9/Android 10

## Steps to reproduce
Settings > Advanced > Refresh tracking metadata

### Expected behavior
Refresh tracking metadata, app doesn't crash and close and does not get signed out of MAL

### Actual behavior
App closes and force signed out of MAL

### Other details
Additional details and attachments.

Issue occurs in Neko too

**Comment by CarlosEsco** [comment]
My guess is Mal was having issues. I just tried and am unable to replicate are you able to?

**Comment by vipzzx** [comment]
actually.... not too sure, that might be the case

**Comment by Jays2Kings** [comment]
Fixed in recent PR
