### ISSUE TITLE
[Bug] Reader bottom chapter list panel clickable even when minimized

### ISSUE THREAD

**Issue by geominorai** [Jays2Kings/tachiyomiJ2K#469]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Samsung Galaxy S9+, Android 10

## Steps to reproduce
1. Enable Android gesture navigation
2. Open a manga to read
3. Tap page to toggle bottom panel
4. Tap anywhere in the vertical gap under the page slider

### Expected behavior
Nothing should happen.

### Actual behavior
Skips ahead between 1 to 3 manga chapters depending vertical position of the tap within this gap.

### Other details
[Video](https://i.imgur.com/ZVDNsH0.mp4)

The slide-up panel with the chapter list appears to still register the tap despite being minimized, so chapters can be accidentally skipped if one tries to use the page slider or press anywhere in this area really.

**Comment by CarlosEsco** [comment]
Must be a Samsung issue I can't emulate jay

**Comment by arkon** [comment]
Happens on my OnePlus 5T too, running Android 10 and using gestures with the bar enabled.

**Comment by geominorai** [comment]
This also happens on Android Studio's emulator with Pixel XL running Android 10.

**Comment by geominorai** [comment]
Thanks for the fix!
