### ISSUE TITLE
[Bug] Unexpected Status Line : 0

### ISSUE THREAD

**Issue by thegodgame** [Jays2Kings/tachiyomiJ2K#47]
### Device information
* Tachiyomi version: 0.96.1 (Latest of now)
* Android version: Pie

## Steps to reproduce
I opened Mangahere, Mangareader, Mangastream and choose a manga's chapter

### Expected behavior
This should happen.

### Actual behavior
all of them shows up that error

### Other details
What is the problem? I can open Scanlations catalogue (package) fine though

**Comment by Jays2Kings** [comment]
Mangastream has shut down, and the other 2 are working fine on my end, can you make sure you have the latest extensions for the other 2?

**Comment by thegodgame** [comment]
> Mangastream has shut down, and the other 2 are working fine on my end, can you make sure you have the latest extensions for the other 2?

I already refreshed to check whether the extension is the most updated or not, but there's no update button, so I'm assuming both are already the latest version.

**Comment by joseph619** [comment]
Update your extensions again
