### ISSUE TITLE
[Feature Request] Automatically(?) add trackers for sources with tracker links on webview

### ISSUE THREAD

**Issue by Jerrk** [Jays2Kings/tachiyomiJ2K#470]
### Why/User Benefit/User Problem
It would make it much easier to track the reading progress of all your manga titles

### What/Requirements
Certain sources (thinking specifically Mangadex here) have a link on their title page to their respective tracking providers, and i thought instead of having to go to each manga individually and add any/all of the trackers would be very tedious (i track well over 1000 manga/manhwa titles), and doing it in a more automatic way would be much less of a headache. 

It's a bit in the vein of #152 where the matching of titles is so horrible it could take you minutes scrolling down the page and trying different spelling of the name, and then caving and having to go into the webview anyway and find the exact title string from the respective tracker, and sometimes having to do DIFFERENT titles for the same manga on different trackers which just seems bizarre.

Not sure if this would be at all feasible but one can hope.

**Comment by CarlosEsco** [comment]
Not something feasibile in j2k with the current structure. I do plan to add the feature to Neko at some point but it's too specific to mangadex for a regular tachiyomi
