### ISSUE TITLE
[Feature Request] Add Custom Range Selection for Read/Unread Chapters

### ISSUE THREAD

**Issue by borkception** [Jays2Kings/tachiyomiJ2K#474]
### Why/User Benefit/User Problem
This feature existed before to my knowledge...

### What/Requirements
Allow us to select a span of chapters to be marked as un/read which currently works the same way as how you can multi-select chapters to download which makes it easier for the end-user. Currently we have to swipe left on a per chapter basis which if you got a title with say 500 chapters and 4-5 different scanlators (dropped or not) it takes considerably longer as to how I remember it being before the rework.

Regardless if said aggregator site splits its chapters as 1-100 depending on the group (or not like MD) this feature should be highly sought after by anyone not reading current chapters.

**Comment by Jays2Kings** [comment]
#319
