### ISSUE TITLE
[Bug] small bug about webtoon viewing

### ISSUE THREAD

**Issue by yusernemu** [Jays2Kings/tachiyomiJ2K#477]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Redmi note 4x & Android 10

## Steps to reproduce
1. Read any webtoon/webcomic that would make the viewing type webtoon as default
2. Tap the setting button
3. In the 'viewer for this series' dropdown, choose any 
   other than webtoon

### Expected behavior
It should change to selected viewing type

### Actual behavior
It just kept viewing as webtoon

**Comment by CarlosEsco** [comment]
working as designed.  Webtoons are for webtoons.  if your source is mislabeling then edit the tag and remove the tag that is causing the auto webtoon to.
