### ISSUE TITLE
[Bug] Cover images dont always load from backup

### ISSUE THREAD

**Issue by ardittristan** [Jays2Kings/tachiyomiJ2K#48]
### Device information
* Tachiyomi version: 0.9.62
* Android version: 8.0

## Steps to reproduce
1. First step make a backup
2. Second step load the backup on a new tachiyomi instance

### Expected behavior
All cover images should load.

### Actual behavior
Some cover images (xkcd for example) don't load

**Comment by ardittristan** [comment]
The current way to get around this is to remove the manga from the library, then clear the database in adv options and then add the manga back, so maybe something like a reload this manga option would help

**Comment by Jays2Kings** [comment]
Pulling to refresh on manga should restore the cover if it doesn't, you can try this is .69 to see if it still happens

**Comment by ardittristan** [comment]
On .69 refreshing the manga does not fix the missing images on none of the extensions that got them after loading a backup

**Comment by bairagyakushal4** [comment]
I did encounter this but only on local manga.

**Comment by ardittristan** [comment]
This seemingly fixed itself when auto updating of thumbnails got added
