### ISSUE TITLE
[Bug] Various bugs with category and hopper after restoring backup to an existing library

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#485]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Note9, Android 10

## Steps to reproduce
1. Backup from different fork or stable with everything selected
2. Restore backup in J2K (Neko has the same issue) with an already existing library 

### Expected behavior
Categories should transfer over.

### Actual behavior
Hopper doesn't move past the transferred over category. (Up and down arrows)

When all categories are expanded, the categories that was transferred over are split up and also splits the categories that were previously in the library.

Can only see the full category when all categories are collapsed and only expand the one category.

### Other details

[Screen_Recording_20200612-175046.zip](https://github.com/Jays2Kings/tachiyomiJ2K/files/4773445/Screen_Recording_20200612-175046.zip)

**Comment by SynderBlack** [comment]
Can confirm this, and will add that after collapsing all categories, and then expanding only a few, the app can crash. Couldn't really figure out what exactly caused the crash, but I assume something about displaying the categories gets corrupted, because the app will keep crashing.
