### ISSUE TITLE
[Feature Request] Migration option similar to 1.0.5

### ISSUE THREAD

**Issue by Camo260** [Jays2Kings/tachiyomiJ2K#487]
Is it possible to configure the source migration to function like it did in 1.0.5?
I haven't had luck playing with the migration settings in 1.0.7 to get it to function similarly.

---

### Why/User Benefit/User Problem

I'm not sure about other people but for migration I found it handy being able to search my select preferred sources for a quick find and if that failed or I wanted to search all other enabled sources, that was an option I could do through the search manually function which I can't figure out how to do in 1.0.7.

Also using the manual search as it was before, we were able to see if the manga had become unlinked since it had the in library tag. I used that quite a bit to migrate to new links for the same source when they became broken. Now in 1.0.7 it just doesn't show the source you are migrating from under manual.

It would be great to be able to configure it through the migration settings to function like that again as I used it quite a bit.

### What/Requirements

How it functioned in 1.0.5

Select preferred sources which I think is still functioning the same in 1.0.7

![TachiJ2K_Screenshot_2020 06 08_01 01 01](https://user-images.githubusercontent.com/13219873/84571425-26e7d680-ade7-11ea-9b35-d1c1d6468eb3.jpg)

Then when using the search manually option, it used to do a global search using all enabled sources and show the source you are migrating from at the top, along with it's library status.

![TachiJ2K_Screenshot_2020 06 08_01 01 25](https://user-images.githubusercontent.com/13219873/84571428-294a3080-ade7-11ea-8e40-8b9ca12e81bb.jpg)

Searching manually in 1.0.5

![TachiJ2K_Screenshot_2020 06 08_01 01 37](https://user-images.githubusercontent.com/13219873/84571431-2c452100-ade7-11ea-9ab4-4a7d84232a2e.jpg)

**Comment by clombion** [comment]
Search manually works the same in 1.0.7

**Comment by Camo260** [comment]
> Search manually works the same in 1.0.7

How do you get it to search like 1.0.5?
This is what I get in 1.0.7, it only shows inital selection rather than all enabled in global search and doesn't show the source it is currently on.

![SmartSelect_20200619-112345_TachiyomiJ2K](https://user-images.githubusercontent.com/13219873/85081322-c100b200-b21f-11ea-9c3a-028e17fd5eda.jpg)

**Comment by clombion** [comment]
I think I understand your issue.

You have two options to search manually. Either you use the three dots → search manually then you're presented with a search that only includes the sources you selected for the migration. 

But if you want to search all enabled sources, you can also click on the manga picture, then click on the title. As long as you have "search only pinned sources" deactivated in the settings, it should launch a full search across all your sources. 

But using that second workflow means that you'll end up adding the manga manually from the new source before having to remove it from your old source. It's doesn't really use the migration feature. With that said, it doesn't interfere with it either: once you have done your selecting/de selecting, you can return easily to the migration screen by using your phone's back button. So if you're doing a mass migration you can review the other mangas. 

I agree that the fact that feature where the source currently being used in the library is a the top of the search is nice, and it would be good to have it back.

**Comment by Camo260** [comment]
I didn't realise how frequently I actually used it that way to migrate in 1.0.5 until it was removed haha
At the moment I've been searching globally via the title and adding/re-adding the new and removing the old manga manually.

I hope they can add it back in as an option in settings in a future update.
Some sources just frequently break manga and require re-adding xD

**Comment by XxJibril** [comment]
use popular sources such as MangaDex/MangaPark/MangaHere/MangaNelo
those are pretty much always up to date with a slight difference in update time but you wont have to change sources as often as with little unknown sources

**Comment by Jays2Kings** [comment]
This isn't changing, if the source isnt intended for migration it shouldn't show up. You can use the option in the top right on the pre migration screen to search through all enabled sources
