### ISSUE TITLE
[Bug] Can't change cover image when there is none

### ISSUE THREAD

**Issue by ardittristan** [Jays2Kings/tachiyomiJ2K#49]
### Device information
* Tachiyomi version: 0.9.62
* Android version: 8.0

## Steps to reproduce
1. First step have a manga without a cover image
2. Second step try to change the cover image

### Expected behavior
The cover image should change 

### Actual behavior
The cover image stays black and the app throws an error

### Other details
Error: Failed to update cover

**Comment by arkon** [comment]
Also see https://github.com/inorichi/tachiyomi/issues/1663
