### ISSUE TITLE
[Bug] Crash during mass migration 

### ISSUE THREAD

**Issue by clombion** [Jays2Kings/tachiyomiJ2K#494]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Google Pixel 3 Android 10

## Steps to reproduce
1. Start mass migration of multiple mangas selected from the library 
2. For the first manga, select "search manually", long press an entry from any other source to open the manga's overview page then tap on the internal browser button
3. Go back to the mass migration screen and repeat the previous the same for the next manga until the crash

### Expected behavior
Nothing

### Actual behavior
At some point the app crashes when opening the internal browser while in the middle of the mass migration. 

### Other details
Happened 3 times in 1 hour today, and also happened before.

**Comment by cpang6** [comment]
I may have had a similar issue but I've only seen it during individual migration. My bug is triggered when I go to "search manually", I long press a manga to see it, and then try to read it where it crashes seconds into opening a chapter.

**Comment by the-reverbcs** [comment]
I also have the same issues as @cpang6 . Issue ( #529 ).

[https://youtu.be/wdL_R0A1Vd0](https://youtu.be/wdL_R0A1Vd0) - here is a video demonstrating the issue.
