### ISSUE TITLE
[Feature Request] Remember library selection / search when switching away from J2K

### ISSUE THREAD

**Issue by clombion** [Jays2Kings/tachiyomiJ2K#496]
### Why/User Benefit/User Problem
Multitasking on smartphones is very common, but when doing a search or a selection in the J2K library it becomes impossible to switch apps or the search / selection is lost. 

### What/Requirements
The state of the search / selection should be remembered even if the user switch to another app.

**Comment by CarlosEsco** [comment]
No plans to change this.  It falls under https://material.io/components/bottom-navigation#behavior
