### ISSUE TITLE
[Bug] Stopping backup restore causes loss of progress 

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#50]
### Device information
* Tachiyomi version: Latest
* Android version: 9

Not exactly a bug report, since it behaves as intended, but it feels like a bug due to poor execution.

Currently in Tachiyomi, if a backup is stopped in the middle of restoring, it cancels completely and all progress it's lost, and we have to start over. This is a huge waste of time if the backup file is very big, and users aren't always have the time to restore everything in a single attempt.

Thus I am requesting a fix the issue so that all backups are restored upto what's shown on the progress bar, and not lose all progress when Stop is clicked and start over. When restore is resumed, backups will also resume from where it's left off.

If all users don't like this option by default, it could be added as a toggle under Backup menu.

The label tag can be changed enhancement, I can't manually tag it as enhancement so I chose bug.

**Comment by Jays2Kings** [comment]
Added Neko's backup via notification as of .69, cancelling it will keep what you already have
