### ISSUE TITLE
[Bug] Downloaded chapters not auto-deleting after being read

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#500]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Galaxy S10+, Android 10

## Steps to reproduce
1. Enable 'Remove when marked as read'
2. Set it to 'Second to last chapter'

### Expected behavior
Downloaded chapters should be deleted.

### Actual behavior
Downloaded chapters don't get deleted.

**Comment by CarlosEsco** [comment]
@Jays2Kings  this needs merged in https://github.com/inorichi/tachiyomi/pull/3320
