### ISSUE TITLE
Downloaded chapters deleting without permission. 

### ISSUE THREAD

**Issue by EmmaKhan3** [Jays2Kings/tachiyomiJ2K#502]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

Itel P32

8.1

My downloaded chapters are deleting without my turning on any auto-delete permission

**Comment by plW0lf** [comment]
Are you using any cleaning application? The cause may be that application if it detected downloaded pictures as trash files as the files aren't stored in Android/Data folder.

**Comment by CarlosEsco** [comment]
closing for lack of info
