### ISSUE TITLE
[Bug] Icon for downloaded chapters show up as blue instead of green.

### ISSUE THREAD

**Issue by zamansakib** [Jays2Kings/tachiyomiJ2K#503]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Xiaomi mi A2 lite (Android 10)

## Steps to reproduce
1. Download a chapter 
2. Close the app
3. Open the app later when offline

### Expected behavior
The icon for the download chapter should be green

### Actual behavior
The icon for the downloaded chapter is blue (but still readable without connection)

### Other details
Here's a screenshot. I can read the unread chapter without WiFi or data because it was downloaded before but the download icon suggests it's not downloaded. 
![Screenshot_20200623-185145](https://user-images.githubusercontent.com/67324649/85407241-c98d1b80-b584-11ea-8e9d-44ef77eed530.png)

**Comment by CarlosEsco** [comment]
if you swipe the app away from recents.  does the download button show green when you open up again

**Comment by zamansakib** [comment]
> if you swipe the app away from recents. does the download button show green when you open up again

It does not. Even after restarting the device and with wifi connection. It's still blue

**Comment by zamansakib** [comment]
I forgot to mention in the post that the icon was green when the actual download completed. But when I came back it was blue. This has happened multiple times before on different mangas

**Comment by arkon** [comment]
Just realized this is probably because of https://github.com/inorichi/tachiyomi-extensions/issues/3536

**Comment by SBence** [comment]
Same here, the app sometimes forgets to remove the _tmp suffix from the chapter folders, leading to all sorts of weird behaviour later on, especially when trying to redownload those chapters. When in this state, a redownload attempt results in instant download followed by the chapter download button turning red and a stuck entry in the queue. Tapping the red download button sometimes displays a notification with a full progress bar, at other times it's an Android system notification that says "TachiyomiJ2K is running in the background". The latter notification disappears shortly after, the former stays until clearing the queue. Clearing the queue deletes the files of the stuck chapters, allows redownload, button turns green but after a restart it's back to blue and to the same broken state. Happens across sources (tested MangaDex and Guya) and across manga. Some are perfectly fine while others exhibit this behaviour, but never on all of their chapters. The broken chapters seem to be always the same when retrying but after deleting all chapters and redownloading them the number of broken chapters increases. Tested on a Google Pixel 2 running Android 11 Beta 1.5.
