### ISSUE TITLE
[Bug] The reading mode is impossible to change

### ISSUE THREAD

**Issue by Kyrela** [Jays2Kings/tachiyomiJ2K#505]
**App version:**
1.0.7

**Android version:**
8.1

**Issue/Request:**
I can't change the reading mode - it's blocked in the webtoon mode.

**Steps to reproduce (if applicable)**

 1. Add a manga to library that is automatically considered as a webtoon and the reading mode is automatically configured (personally, "JoJo's Bizarre Adventure Part 7: Steel Ball Ru lon Colored" from Bato.to (en).
 2. Open it, and open the parameters of the manga
 3. Try to change the reading mode
 4. Close the parameters
 5. Re-open it. The reading mode is re-set to "Webtoon"

**Other details:**
None

**Comment by CarlosEsco** [comment]
Edit it to remove the tag causing the forced webtoon.
