### ISSUE TITLE
[Feature Request] Use white as automatic background color instead of gray

### ISSUE THREAD

**Issue by she11sh0cked** [Jays2Kings/tachiyomiJ2K#51]
### Why/User Benefit/User Problem
The "automatic" mode for the background color sets the color to gray if the page is predominantly white. I think it would make more sense to set it to white as thats what surrounds the background (the page).

### What/Requirements
The background color would be set to white if a predominantly white page is detected.

You could also have an option to define what color values to use for white and black.

**Comment by she11sh0cked** [comment]
Now that i re-read it, i don't actually know if this would be a feature request or a bug. But i think that's for you to decide.

**Comment by Jays2Kings** [comment]
I was thinking of adding an option to pick between automatic following the library theme (which it currently does) and what you're suggesting. I will try to add it in the next release

**Comment by Jays2Kings** [comment]
Aaaand added as of .69
