### ISSUE TITLE
[Bug] Can't download chapters if chapter list filter is on

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#513]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Galaxy S10+, Android 10

## Steps to reproduce
1. Go to a manga chapter list and enable 'Show downloaded chapters' filter 
2. Try to download a chapter for the manga 

### Expected behavior
Chapter should download 

### Actual behavior
Chapter doesn't download 

### Other details
This issue also existed on TachiSy before Syer fixed it.

**Comment by tAzO8596** [comment]
#459
