### ISSUE TITLE
[Feature Request] Block repetitive credit images by selecting the image in a chapter to create a filter

### ISSUE THREAD

**Issue by anonymousUsers1** [Jays2Kings/tachiyomiJ2K#514]
### Why/User Benefit/User Problem
Credit pages can prove incredibly intrusive in series with smaller chapters (e.g. there are 1-2pg series with 1-2 pages of end credits each chapter). Adding an a function that lets you select one of these pages once and ignore it when loading subsequent chapters would considerably improve user experience. 

It may also save on storage space considerably depending on the exact way in which this is applied. 

### What/Requirements
UI Journey:
1. User reads a chapter
2. User comes across an end credits page
3. User long presses the page to select it
4. User clicks a block page button at the top with the options:
 a. Block on all chapters in this series
 b. Block globally across all series
5. Any exact duplicates of this page in the rest of the series are deleted or ignored when loading chapters. 
5b. One optional approach here is that the image is collapsed into a small grey rectangle one page width across that can be clicked to expand into the full image.

Logic:
There are a few ways in which this could work:

- Hash all chapter images when downloading them and just not load images with the same hash
- For something a bit easier with fewer hashes- When loading the next chapter: Check for images with the same dimensions -> same file size -> date edited (?) / hash -> only block those
- Very hit or miss but if  end credit page titles are unique (not numbered per usual pages / with differing metadata - it may be able to go by image name or date created)

**Comment by CarlosEsco** [comment]
Fall under this and jay can reopen if he disagrees

https://github.com/inorichi/tachiyomi/issues/1451

**Comment by CarlosEsco** [comment]
forgot to close
