### ISSUE TITLE
[Feature Request] Differentiate complete status on mangadex

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#515]
### Why/User Benefit/User Problem
There should be a difference between Publication Complete and Complete in uploads. Some are marked as unknown while some are marked as complete when it's only publication complete

### What/Requirements
How Neko does it. 
![Screenshot_20200701-022229_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/86210249-49495600-bb42-11ea-9351-286402ed8961.jpg)

![Screenshot_20200701-022645_Neko](https://user-images.githubusercontent.com/59638889/86210272-52d2be00-bb42-11ea-9151-6d9def2ba41f.jpg)

**Comment by CarlosEsco** [comment]
So publication complete is more than likely not coming.  That's very specific to mangadex and the manga status values are stored in main app.

I would open a ticket in extensions repo though cause this shouldnt say complete by the extension.  As it wont get auto updates (when dont update completed manga is enabled)  and is actively being scanned.

**Comment by vipzzx** [comment]
Ty :)
