### ISSUE TITLE
[Feature Request] Prevent chapters of newly added favorites flooding Library updates

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#52]
When a new manga is added to My library, or a backup is restored, all its chapters show up in Library updates, which buries all manga which got actual chapter updates recently. This can be very annoying if the new favorite has a lot of chapters, it's can become hard to see actual chapter updates on Library updates because of this. The new feature would prevent chapters of newly added favorite manga from showing up on Library updates.

**Comment by Jays2Kings** [comment]
Added
