### ISSUE TITLE
[Bug] AsyncSocket

### ISSUE THREAD

**Issue by Mano5JP** [Jays2Kings/tachiyomiJ2K#526]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Note 10 + Android 10

### Other details
Additional details and attachments.

I have been receiving this error every time when i open tachiyomi app. It does every often when i open app or read magnas or updating libraries. 

If i uninstall app there's no error and its back when i install again.

I have no idea what that error does but expect for that pop up error, it hasn't affected me on normal uses. 

![20200708_164816](https://user-images.githubusercontent.com/64928088/86927449-08ea6900-c13c-11ea-9456-41456935e9ff.jpg)

**Comment by CarlosEsco** [comment]
Does this happen with a specific source?

**Comment by Mano5JP** [comment]
I only have 2 source installed.

Mangabox 
ReadMangaToday

I don't know if it's a issues with any of these source.

**Comment by joseph619** [comment]
Try on regular Tachioymi. If it doesn't work there, uninstall an extension to see which one is causing issue.

**Comment by Mano5JP** [comment]
I had installed and uninstalled j2k.It's was solved for a day but its back again.
My apps are on sleep mode so, when i open it its shows same pop up again. It less frequent from before but it still persist there.

**Comment by joseph619** [comment]
Install main Tachiyomi (0.9.2) to troubleshoot, not J2K.

**Comment by Mano5JP** [comment]
Yea i did say i had installed 0.9.2 standard tachiyomi, and uninstalled j2k.

Also I am putting app on sleep coz i don't want to keep receiving popup
So, now when i open apps to read manga, I am been bombarded with pop up (asyncsocket)

**Comment by CarlosEsco** [comment]
please verify if you still have this issue.  Am closing for now as its likely a source issue.

**Comment by Mano5JP** [comment]
I haven't found any issues as of moments

Thx
