### ISSUE TITLE
[Feature Request] Missing chapter warning

### ISSUE THREAD

**Issue by plW0lf** [Jays2Kings/tachiyomiJ2K#528]
### Why/User Benefit/User Problem
Sometimes while reading there may be situation when there is a gap between chapters (like ch30 and next is ch50)

### What/Requirements
Warning before starting reading next chapter while gap is detected with optional confirm popup. Also maybe alert icon in chapters list

**Comment by CarlosEsco** [comment]
That is what the transition page is for

**Comment by plW0lf** [comment]
The problem is when you are reading with webtoon mode or continuous vertical.

**Comment by CarlosEsco** [comment]
The transition page still shows there

**Comment by plW0lf** [comment]
Sure there is, but it's easier to miss it. Also there are situations when someone will publish chapter making a gap in some series. You get notification that new chapter is out and you start reading it without knowing that there is a gap (had this situation few times in some mangas that hasn't been updated for months)

**Comment by XxJibril** [comment]
usually you can detect that the story skipped a part and think about checking the chapters number
the option you are asking for wouldnt be 100% reliable imo bec you might be reading chap 12 and then move to chap 13, but the source you are reading is missing chap 12.5 (some mangas have chapter numbers going up by decimals)

**Comment by Schadows** [comment]
I agree with the opening post.
Although there wouldn't be a reliable solution for this as @XxJibril said, I think it's better than nothing to be warned when there is an obvious gap (ch.88 -> ch.90).
