### ISSUE TITLE
[Bug] App crashes when loading chapters in auto-migration.

### ISSUE THREAD

**Issue by the-reverbcs** [Jays2Kings/tachiyomiJ2K#529]
### Device information
* Tachiyomi version: v1.0.7
* Android phone & version: Samsung Galaxy S9/Android 10/One UI 2

## Steps to reproduce
1. Select one manga
2. Proceed to auto-migration
3. Once sources have loaded with results, open a result and load a chapter

### Expected behavior
It should show the chapter for reading

### Actual behavior
The app fully crashes and exits out. Does this every time

### Other details
Additional details and attachments.
[https://youtu.be/wdL_R0A1Vd0](https://youtu.be/wdL_R0A1Vd0) 
Here is a video describing the issue.

**Comment by CarlosEsco** [comment]
Can you paste this information into #494
