### ISSUE TITLE
[Bug] Connection closed by peer canceling backup restore

### ISSUE THREAD

**Issue by ardittristan** [Jays2Kings/tachiyomiJ2K#53]
### Device information
* Tachiyomi version: 0.9.62
* Android version: 8.0

## Steps to reproduce
1. Make a backup with most years from the dilbert extension

2. Restore the backup

### Expected behavior
After 2 or 3 years scannes, dilbert will temp ip ban you, the backup should skip all following years

### Actual behavior
When the connection gets closed by peer it fully cancels the backup recovery.

### Other details
When removing the extension so it doesn't try to connect, it skips over them

**Comment by Jays2Kings** [comment]
There's nothing that can be done about temp ip bans, but restores have been updated recently. Update to 0.9.69 and see if the restore continues

**Comment by ardittristan** [comment]
Update fixed it
