### ISSUE TITLE
[Feature Request] Tracker Badge

### ISSUE THREAD

**Issue by qwerty017** [Jays2Kings/tachiyomiJ2K#531]
### Why/User Benefit/User Problem
This would allow a user to see if a given Manga is being tracked, and by what websites. This would be helpful for times when a given manga is not in any tracker when initially released, but is later, and a user wants to go through their library and make sure their stuff is being tracked without needing to go into every manga and verify it is not only being tracked, but also tracked by their chosen trackers if multiple.

### What/Requirements
A badge on the image, like the downloaded badges. Maybe different colors for each tracker for easier viewing of which trackers are enabled on a given manga in case a user wants to use multiple trackers for a given title?

**Comment by CarlosEsco** [comment]
This wouldn't look good at all.  You can also filter by tracker or group by tracking status.
