### ISSUE TITLE
[Feature Request] Always hide "unread-read/Not started-in progress" bar

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#532]
### Why/User Benefit/User Problem
Cleaner design

### What/Requirements
Add a feature to always hide unread-read/Not started-in progress bar in display options![Screenshot_20200717_104548.jpg](https://user-images.githubusercontent.com/56766778/87762081-3067c280-c81b-11ea-9ad1-645c502aff7e.jpg)

**Comment by CarlosEsco** [comment]
Why?  If it bothers you you can reorder it and put it in a different spot

**Comment by CarlosEsco** [comment]
And if it's about hiding the bar completely.

https://github.com/Jays2Kings/tachiyomiJ2K/issues/400

**Comment by Mitia99** [comment]
@CarlosEsco I just figured out that the app already have the feature.Thanks
