### ISSUE TITLE
[Feature Request]Display current category name in top bar(when switching categories)

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#533]
Why:
Better UI and categories management

Requirements:
-Display category name in top bar inside a rounded box

**Comment by Mitia99** [comment]
![AddText_08-05-02.01.02.jpg](https://user-images.githubusercontent.com/56766778/89409724-d0ca4c00-d722-11ea-93e9-73b100259926.jpg)![AddText_08-05-02.03.04.jpg](https://user-images.githubusercontent.com/56766778/89409741-d58f0000-d722-11ea-8a89-1290a78a4500.jpg)

**Comment by Mitia99** [comment]
*Updated post

**Comment by CarlosEsco** [comment]
This already exists.  Enable always show current category in the display options

**Comment by Mitia99** [comment]
@CarlosEsco Thanks,I didn't know.It will be more modern if you could consider changing the UI like the concept(rounded box) I made.
