### ISSUE TITLE
[ISSUE] Hide Chapter Titles Bug

### ISSUE THREAD

**Issue by vanessabluellie** [Jays2Kings/tachiyomiJ2K#538]
**App version:** TACHIJ2K 1.0.7

**Android version:** 8.0.0

**Issue/Request:** The feature 'Hide Chapter Titles' only visibly works when you click on the manga in your favourites tab. For the other tabs; history, recent, downloads, updates; it shows the original chapter names (i.e. chapter 6 - read online ---> chapter 6, stays as read online rather than just chapter 6)  

**Steps to reproduce (if applicable)**

 1. First screenshot, in the favourites tab

![20200727_155355](https://user-images.githubusercontent.com/55352222/88510321-eacca600-d021-11ea-972c-7273f51bb434.jpg)

 2. Click 'Hide chapter titles' to only see the chapter number so it looks less cluttered

![20200727_155931](https://user-images.githubusercontent.com/55352222/88510461-31ba9b80-d022-11ea-85ae-1f9956c22127.jpg)

 3. In the favourites tab, it works and the manga chapter titles only shows the chapter name, but in the other tabs it doesn't change. This is the history tab:

![20200727_155459](https://user-images.githubusercontent.com/55352222/88510546-629ad080-d022-11ea-9f44-bee382db5afb.jpg)

4. Under group all, this is the continue reading tab:

![20200727_160204](https://user-images.githubusercontent.com/55352222/88510635-983fb980-d022-11ea-9e66-a1df755d0f8c.jpg)

5. Downloads

![20200727_160323](https://user-images.githubusercontent.com/55352222/88510727-bdccc300-d022-11ea-84a5-b8a0580c5107.jpg)

6. Updates

![20200727_155433](https://user-images.githubusercontent.com/55352222/88510753-d046fc80-d022-11ea-9daf-b49039dc2dd3.jpg)

7. But it should all look like this :D (Without manga title, just chapter number)~

![20200727_155523](https://user-images.githubusercontent.com/55352222/88510844-fc627d80-d022-11ea-808d-13c458c93340.jpg)

I hope my explanation was okay! Thank you so much for all the work, I absolutely love Tachiyomi! 

**Other details:**
I hope this issue can be fixed sometime, when you can! Thanks!

**Comment by CarlosEsco** [comment]
This is by design. The setting is for thwt chapter list not for the other screens.
