### ISSUE TITLE
[Feature Request] Manual option for "Download new chapters" feature

### ISSUE THREAD

**Issue by MagnesG** [Jays2Kings/tachiyomiJ2K#54]
### Why/User Benefit/User Problem
More robust options for the users.

### What/Requirements
Instead of going by the categories, user can have the option to automatically download new chapters from the manga itself.

**Comment by CarlosEsco** [comment]
Why wouldn't you just make a category that you add the manga to that is just so things are downloaded?

**Comment by Jays2Kings** [comment]
As mentioned this functionality exists via categories, doing it on a manga basis overly complicates things
