### ISSUE TITLE
[Bug] Extensions screen bug

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#540]
Don't remember how to reprdouce sadly

![Screenshot_20200729-234022_TachiyomiJ2K](https://user-images.githubusercontent.com/34897862/88879036-5156ed00-d1f7-11ea-9b9a-972509ff2e21.jpg)

![Screenshot_20200729-234046_TachiyomiJ2K](https://user-images.githubusercontent.com/34897862/88879182-a561d180-d1f7-11ea-820f-af6632e27bd5.jpg)

**Comment by CarlosEsco** [comment]
maybe the extension list wasnt downloaded yet?

**Comment by joseph619** [comment]
Haven't seen this in a while so closing
