### ISSUE TITLE
[Bug] Auto-migrating mangas with apostrophe in the title yields no results

### ISSUE THREAD

**Issue by d4rky-pl** [Jays2Kings/tachiyomiJ2K#541]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: OnePlus 7 Pro, Android 10

## Steps to reproduce
1. Grab a manga/mangwa/manhua with apostrophe in the title (for ex. `I'll Do That Marriage`)
2. Try to migrate it

### Expected behavior
The man(g|hw|hu)a should be found in other sources

### Actual behavior
The man(g|hw|hu)a is not found.

### Other details
If you go into manual search and remove the part containing the apostrophe (for ex. just search for `Do That Marriage`), everything works fine

**Comment by fightmesun** [comment]
Im having the same issue

**Comment by Jerrk** [comment]
This is still an issue.

**Comment by Jays2Kings** [comment]
Not sure why this was open for so long but this is an extension issue that doesn't accept certain characters. Try the extensions website with the same query and if it doesn't work, then nothing can be done, if it does, then open an issue on the extensions repo instead of here
