### ISSUE TITLE
[Bug] next chapter for read chapters is broken

### ISSUE THREAD

**Issue by Ninjistix** [Jays2Kings/tachiyomiJ2K#545]
### Device information
* Tachiyomi version: version 1.0.7
* Android phone & version: Pixel 4XL Android 10

## Steps to reproduce
1. Go to a previously read chapter
2. Finish the chapter and try to read the next chapter you will get a no new chapter error 

### Expected behavior
The check should be for a next chapter not new chapter, when re-reading old chapters the reader only checks for new chapters.

### Actual behavior
New chapter is 118.3 I went back to 113.1 to re-read the story, it went from 113.1 to 118.3, decided to read the new chapter and then go back to 113.2 when changing to 113.3 it said there's no new chapter

I always have to exit the reader and go manually select the next chapter

### Other details
![Screenshot_20200804-025904](https://user-images.githubusercontent.com/12572974/89263135-b0a16c80-d5fe-11ea-891a-2579274a972b.png)
![Screenshot_20200804-025923](https://user-images.githubusercontent.com/12572974/89263145-b5662080-d5fe-11ea-944b-0f153cd699e1.png)
![Screenshot_20200804-030009](https://user-images.githubusercontent.com/12572974/89263156-bbf49800-d5fe-11ea-8997-dfc9a9fe6898.png)

**Comment by CarlosEsco** [comment]
Can you verify you don't have skip read enabled in the settings.

**Comment by Ninjistix** [comment]
I didn't even know such a setting existed, and It was, I disabled it and it works now.
