### ISSUE TITLE
[Feature Request] Change Disable Zoom to Disable Zoomout

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#548]
### Why/User Benefit/User Problem
Having disable zoomout fixes the bug that happens when zoom out and the last page doesnt show, and also allows zoom in for webtoon view

also add it to reader setting so it is easy to find

### What/Requirements
Like in Neko and SY

**Comment by CarlosEsco** [comment]
This is already merged in. I took it from j2k for Neko. It's just waiting a release
