### ISSUE TITLE
[Bug] No OK button when setting manga status

### ISSUE THREAD

**Issue by mrskizzex** [Jays2Kings/tachiyomiJ2K#55]
### Device information
* Tachiyomi version: 0.9.69
* Android version: 9

## Steps to reproduce
1. In tracking tab select Status

### Expected behavior
There should be OK button to confirm tracking status change. 

### Actual behavior
No OK button

### Other details
![Screenshot_20200113-081002_Tachiyomi](https://user-images.githubusercontent.com/11503128/72237981-aa08c480-35dc-11ea-9402-edb5987b9539.jpg)

**Comment by CarlosEsco** [comment]
if you select one does it auto select it and close the chapter?

**Comment by mrskizzex** [comment]
That's the first thing I tried of course. But nope, doesn't work. Not with status nor with any other options in tracking tab.

**Comment by Jays2Kings** [comment]
Fixed as of 0.9.7
