### ISSUE TITLE
[Feature Request] Ability to put manga shortcut on homescreen

### ISSUE THREAD

**Issue by KorayKaya** [Jays2Kings/tachiyomiJ2K#550]
### Why/User Benefit/User Problem
It would make it easier to quickly access your manga and showcase it on your home screen. 

### What/Requirements
There would be an option on the manga's page to add it to my home screen. An icon would appear on the home screen with the manga art and name, which when i press would open the app and instantly jump to where im currently reading. This would be awesome.

**Comment by CarlosEsco** [comment]
This was removed from all versions cause it is a hardily used feature and not worth supporting
