### ISSUE TITLE
[Feature Request] Badge for new chapters available

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#552]
### User Benefit
Easier new chapter tracking

### What/Requirements
_Exclamation badge for manga with new chapters out
_Auto remove badge after "x"(modifiable value) day!["New chapter out" badge.jpg](https://user-images.githubusercontent.com/56766778/89767835-02fcf480-dafb-11ea-8dbe-9e91c1d43f35.jpg)

**Comment by joseph619** [comment]
This is redundant as unread badge already exists

**Comment by Mitia99** [comment]
@joseph619  I don't think so.When I enable unread badge,there is too much badge on screens cause I don't read all my manga.I think it will be good to add a exclamation bagde when new chapter is out which auto disappear after "x" day.

**Comment by CarlosEsco** [comment]
sort by latest chapter then
