### ISSUE TITLE
[Bug] Crashes when asleep

### ISSUE THREAD

**Issue by squee666** [Jays2Kings/tachiyomiJ2K#556]
### Device information
* Tachiyomi version: 1.0.7
* Android phone & version: Samsung Galaxy Note 9 , Android 9 and Android 10

## Steps to reproduce
close the app, leave it in memory

### Expected behavior
It shouldnt tell me the app is frequently crahing and causing high batter usage.

### Actual behavior
Sometimes flashes a crash warning and gives warning on high battery usage

### Other details
This wasnt an issue before the samsung issues were fixed, it wasnt even crashing for me  at all before the fixes were made

**Comment by Caio99BR** [comment]
Should be fixed on latest releases or after https://github.com/Jays2Kings/tachiyomiJ2K/commit/9f4a6698bed291a282f1294d743ff73e9c120332

**Comment by Jays2Kings** [comment]
Commit is unrelated but I'll close it and leave for op to double check it
