### ISSUE TITLE
[Feature Request] Sort search results by...

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#557]
### Why/User Benefit/User Problem
More convenient catalog management

### What/Requirements
-Add sort icon 
-Add checkboxes:
   • Source with newest chapters
   • Source with the most numerous chapters 

![Sort search results by.jpg](https://user-images.githubusercontent.com/56766778/90475509-db73e080-e127-11ea-8ae5-762343b4d3cb.jpg)

**Comment by CarlosEsco** [comment]
#57
