### ISSUE TITLE
[Feature Request] Sub-sources search for multisource extensions

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#558]
### Why/User Benefit/User Problem
Better alternative to the multisource spreadsheet

### What/Requirements
-Display multisource extension when searching for a sub-source.
e.g: Searching "toonily" in extension menu displays "madara".

**Comment by CarlosEsco** [comment]
not possible at this time.

**Comment by Mitia99** [comment]
@CarlosEsco Oh I see.Maybe,adding the SnakeDoc83 link inside the extension tab will be convenient.
