### ISSUE TITLE
[Feature Request] Backup(export) library as a plain text

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#559]
### Why/User Benefit/User Problem
Sometimes sources are down and the manga won't appear in library when restoring a backup.

### What/Requirements
Backup(Export) library as a plain text

**Comment by CarlosEsco** [comment]
Are you saying you want a new backup created with manga that did not restore?

**Comment by Mitia99** [comment]
@CarlosEsco No,the plain text will be just needed to just make a list,not to restore.

e.g:

_Isekai:
 •Manga 1
 •Manga 2
 •Manga 3

_Romance
 •Manga 1
 •Manga 2....

**Comment by CarlosEsco** [comment]
So a list of of ones with errors? There are already an file created though?  What benefit does this format provide

**Comment by Mitia99** [comment]
@CarlosEsco A list of all manga(with and without error as well).

Plain text manga list backup:
Just categories and manga list,No source link,no number of chapters,no bookmarks...The simpliest

Benefits of plain text:
Simple text format that can be opened by majority of users who don't have knowledges with .json format(actually me)

**Comment by CarlosEsco** [comment]
yea that wont happen.  There would be no way to restore a manga to the actual source.  not to mention its provides nothing to the app as it would just be harder to parse and restore.  Also you would be maintaining 2 different backup restore systems

**Comment by Mitia99** [comment]
@CarlosEsco Here is a sample of the requested feature(maybe we won't call it backup but export my library)![List.jpg](https://user-images.githubusercontent.com/56766778/90509861-4c33f080-e15a-11ea-9d9a-3fb5ee6a28b3.jpg)
