### ISSUE TITLE
[Feature Request] Add a download unread button from library view

### ISSUE THREAD

**Issue by mrskizzex** [Jays2Kings/tachiyomiJ2K#56]
### Why/User Benefit/User Problem
When adding multiple new manga it's very annoying to have to go into each one of them individually, click 3 dots, click download, click unread. Adding a bulk download unread would save time and effort. 

### What/Requirements
When selecting manga in library view, add an option to 3 dot menu "Download unread". That will queue all unread chapters for download. 

![Screenshot_20200113-082159_Tachiyomi](https://user-images.githubusercontent.com/11503128/72238415-f0125800-35dd-11ea-8a62-35449e3068e6.jpg)

**Comment by Jays2Kings** [comment]
Isn't this functionality duplicated by setting a category to auto download. There's many ways to do this now, and this method would complicate the logic

**Comment by CarlosEsco** [comment]
tbf i think this is more when you add new manga.  Like if i add 3 new manga, You have to go into all 3 to initiate downloading.  The auto download won't affect it  since the chapters are not "new"

**Comment by mrskizzex** [comment]
Well it's not the same, the auto download only downloads new chapters, not already existing unread chapters.

**Comment by Fredddi43** [comment]
This would be really useful, especially when restoring from backup or migrating libraries. I just switched from main Tachiyomi and had to go into each unread manga and download unread chapters manually.
