### ISSUE TITLE
[Feature Request] Navigate chapter through pages thumbnails

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#564]
### User Benefits
Finding a specific page in a chapter will be more easier(especially for chapters with tons of pages)

### Requirements
_Add thumbnail navigation in navigation menu
_Display 3 columns thumbnails(like M library grid)
![Thumbnail navigation.jpg](https://user-images.githubusercontent.com/56766778/90737072-4bbc6680-e2ce-11ea-80a0-af5196ba5ebc.jpg)

**Comment by CarlosEsco** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/200

**Comment by CarlosEsco** [comment]
realize that ticket is missing some info.  This is a bit challenging to do and would only work on downloaded chapters.  Its a lot of work for what is a niche feature

**Comment by Mitia99** [comment]
@CarlosEsco That's a really must-have feature .It will replace the seekbar.
