### ISSUE TITLE
[Feature Request] Speech Bubble Zoom

### ISSUE THREAD

**Issue by AdityaAnand99** [Jays2Kings/tachiyomiJ2K#573]
Knew about this app just a few days ago and god it's brilliant but, before this I used to read all my comics on Google play books. There's only one thing that wish TACHIJ2K had and it's Google's BUBBLE SPEECH ZOOM. It uses machine learning to recognise speech bubbles and intelligently zoom into them for easier reading. Move from bubble to bubble one tap at a time, and still allows to keep the full-page experience. This vastly improves the reading experience and allows to enjoy the comic without zooming anywhere, especially on smaller phones. The difference is night and day. I got no idea how difficult it'd be port this feature back from Google play books but if you can please do it I'm practically begging you. https://www.theverge.com/platform/amp/2016/7/21/12229074/google-play-books-bubble-zoom-machine-learning-sdcc-2016
Bubble Zoom on Google Play Books: https://youtu.be/1v7dS8i5G9U
I already requested this feature on Tachiyomi github but they declined stating that they can't obtain the machine learning models and no one would maintain this feature.

**Comment by joseph619** [comment]
The speech bubble code is not open source, thus it's not possible to implement this. It's not worth to spend the massive amount of effort for such a niche feature.

**Comment by CarlosEsco** [comment]
Yea unless you can find an open source project that can provide this but its not something that will be attempted.  Just for the record i would love it also just not something feasible

**Comment by raul-lezameta** [comment]
Seems like the guys over at [Seeneva](https://github.com/Seeneva/seeneva-reader-android) have built an open source manga/comic reader with this feature. Maybe there is a way to work with them to include such features into Tachiyomi :)
