### ISSUE TITLE
[Bug] Webview not working correctly on VIZ Shonen Jump extension

### ISSUE THREAD

**Issue by Type-Ghost** [Jays2Kings/tachiyomiJ2K#575]
### Device information
* Tachiyomi version: 1.0.8
* Android phone & version: bq Aquaris M5.5, android 7.1.2

## Steps to reproduce
1. Install the VIZ Shonen Jump extension
2. Open it and tap on the webview

### Expected behavior
VIZ website loads, you swipe up the banner and you're able to log in

### Actual behavior
VIZ website loads but the banner is zoomed in and can't be swiped up, scrolling down the page just shows white background forever

### Other details
This is what it looks like immediately after opening the webview for VIZ
![Screenshot_20200827-041746](https://user-images.githubusercontent.com/70305574/91381689-e6adc700-e81f-11ea-830e-3bab123ec822.png)

**Comment by joseph619** [comment]
You mentioned that this works perfectly on Stable, and is an issue only on J2K, right?

**Comment by Type-Ghost** [comment]
Yes, I checked

**Comment by Jays2Kings** [comment]
This should be fixed in later versions
