### ISSUE TITLE
[Feature Request] Add "continue latest read manga" button in library page

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#579]
### Why/User Benefit/User Problem
Resuming manga will be more convenient

### What/Requirements
Option to display a resume(latest read) button in library main page in display settings![Resume.jpg](https://user-images.githubusercontent.com/56766778/91644416-67e5a380-ea44-11ea-8738-97fabc171799.jpg)

**Comment by CarlosEsco** [comment]
Just click recents and click the top one in the continue reading. A resume fab is not being added to the library view.
