### ISSUE TITLE
[Feature Request] Add "Show undownloaded chapters" in chapters display options

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#586]
### Why/User Benefit/User Problem
Downloading chapters which are not yet downloaded will be more convenient.

### What/Requirements
![AddText_09-12-11.24.37.jpg](https://user-images.githubusercontent.com/56766778/92991217-01a05c80-f4eb-11ea-8dcf-4cefec33ac39.jpg)

**Comment by joseph619** [comment]
Basically add negative/tri-state filter to chapter list as well

**Comment by Caio99BR** [comment]
@Jays2Kings fixed after tri-state filter?
