### ISSUE TITLE
[Feature Request] Option to download all undownloaded chapters

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#589]
### Why/User Benefit/User Problem
For users who want to download all chapters but can't download them at once.

### What/Requirements
![AddText_09-14-09.09.28.jpg](https://user-images.githubusercontent.com/56766778/93049876-92517680-f66a-11ea-94cb-2a2563e05e18.jpg)

**Comment by gloist** [comment]
Just click the "All Chapters", It'll download the undownloaded chapters by default since there's a restriction about this issue.

**Comment by Mitia99** [comment]
@gloist In that case, I think that it will be better to replace the text "All chapters" by "All undownloaded chapters"

**Comment by gloist** [comment]
It might be, but it will just add some unecessary work ('all' if all is downloaded, else 'undownloaded'). But it won't even change the function at all.

**Comment by Caio99BR** [comment]
Maybe it need to adding something like "All chapters ('x' missing)" and/or disabling the button when all chapters are downloaded (in both options)
