### ISSUE TITLE
Main page stays white on  theme change

### ISSUE THREAD

**Issue by Capocarlo23** [Jays2Kings/tachiyomiJ2K#592]
Phone: huawei p30 lite Android version 10
When I change my theme to a darker one, the main page will instead turn white. To correct this issue I can go to settings and change the language. After this everything the main page will assume the correct color. I can replicate this issue without problem

**Comment by Capocarlo23** [comment]
Phone: huawei p30 lite Android version 10
When I change my theme to a darker one, the main page will instead turn white. To correct this issue I can go to settings and change the language. After this everything the main page will assume the correct color. I can replicate this issue without problem

**Comment by CarlosEsco** [comment]
Can you attach a video or gif?

**Comment by Capocarlo23** [comment]
[https://drive.google.com/file/d/1zz8ThEtjBSJLiIFdBl4FMWYSACdAWMrd/view?usp=sharing](url)

**Comment by Capocarlo23** [comment]
[https://drive.google.com/file/d/1zz8ThEtjBSJLiIFdBl4FMWYSACdAWMrd/view?usp=sharing](url)

**Comment by Capocarlo23** [comment]
the file is too big. i cant post it here. i dont think the link i posted before works also.

**Comment by Capocarlo23** [comment]
[Uploading SVID_20200914_095317_1.zip…]()

**Comment by CarlosEsco** [comment]
can you attach a screen at least?

**Comment by Capocarlo23** [comment]
![Screenshot_20200914_093114_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/71254988/93608988-90b9e280-f9cb-11ea-9900-5ce0d0e783bd.jpg)

the thing is that the problem persisted for a couple of days, but now it seems like it fixed itself as i cant reproduce it anymore.

**Comment by Jays2Kings** [comment]
Closing since outdated. Reopen if this is still happening on latest version
