### ISSUE TITLE
[Bug] Default category not included in global update checklist

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#595]
### Device information
* Tachiyomi version: 1.0.8
* Android phone & version: A10, Note9

## Steps to reproduce
1. Setting > Library > Updates 
2. Select "categories to include in gonna updates"

### Expected behavior
Default category should be included in the selection. 

### Actual behavior
Default category is not included in the selection. 

### Other details
Additional details and attachments.

**Comment by jfcaraujo** [comment]
I think this has already been fixed in the latest update
