### ISSUE TITLE
Please add a feature where when you search in global or in specific manga site or searching manually in manga mirage it shows a manga's total chapters and latest chapter number

### ISSUE THREAD

**Issue by medoria0** [Jays2Kings/tachiyomiJ2K#600]
### Why/User Benefit/User Problem
When I am miraging manga's manually to find the best one or searching in global it is annoying to open each manga and wait for them to load just to see manga count and latest chapter number so it would be helpful and if someone doesn't like it then put an option in settings to turn it off

### What/Requirements
Show two circles above manga when you are searching for it in a specific source or in global or manual mirage to see manga chapter count and latest chapter count like in library when you see how many chapters you haven't read and how many you have downloaded

**Comment by CarlosEsco** [comment]
#195
