### ISSUE TITLE
[Bug] Library getting messed up while restoring the backup

### ISSUE THREAD

**Issue by Goku003** [Jays2Kings/tachiyomiJ2K#603]
### Device information
* Tachiyomi version: 1.0.9
* Android phone & version: OP6-A10

## Steps to reproduce
1. Library should have some manga with categories
2. Restore the manga (the backup also should have multiple manga with different categories which is not same as the existing one)

### Expected behavior
The library should be restored with the new manga and its category

### Actual behavior
Once the restore is completed, the new added manga will be present in the library but there will be multiple categories with same name and manga's gets splitted across. 
Attaching the discord link where I have posted the screen recording for better understanding.

### Other details
![image](https://user-images.githubusercontent.com/22503748/93707420-106ebb00-fb4c-11ea-8b8a-614feb34188b.png)

https://discordapp.com/channels/349436576037732353/657923584811073566/757152912647389266

**Comment by joseph619** [comment]
Does this still happen for you?

**Comment by Goku003** [comment]
I haven't tried this out in the latest build.
Let me try it

**Comment by Goku003** [comment]
Yeah that thing got fixed, i think i can close this issue
