### ISSUE TITLE
[Bug] Menu option "Delete chapters" doesn't work with filters

### ISSUE THREAD

**Issue by PedroG022** [Jays2Kings/tachiyomiJ2K#605]
### Device information:
- Tachiyomi version: 1.0.9 j2k
- Android phone & version: Moto G7 Plus, version 10

### Steps to reproduce:
1. Download any manga chapter
2. Mark it as read
3. Enable Only Non-Read filter (The downloaded and read chapter should disappear)
4. Use the menu option to delete downloads

### Expected behavior:
- A confirmation dialog should appear.

### Actual behavior:
- The dialog doesn't show up and the chapter is not deleted.

**Comment by Caio99BR** [comment]
Already fixed on latest release
