### ISSUE TITLE
Mangafast cover is black and you can't change it

### ISSUE THREAD

**Issue by medoria0** [Jays2Kings/tachiyomiJ2K#607]
**PLEASE READ THIS**

I acknow
### Device information
* Tachiyomi version:j2k 1.0.9
* Android phone & version: Samsung a71 and version 10

## Steps to reproduce
1. Back up manga from files and it should have a manga from manga fast, mine was the strongest anti m.e.t.a
2. Open it and try to edit the cover or try to let the cover load, it won't

### Expected behavior
Loading cover normally or you could change it
### Actual behavior
Cover is black and you can't edit it

### Other details
![Screenshot_20200928-131203_TachiyomiJ2K](https://user-images.githubusercontent.com/64145746/94425739-b8a80380-018c-11eb-9c9c-18511738a271.jpg)
![Screenshot_20200928-131208_TachiyomiJ2K](https://user-images.githubusercontent.com/64145746/94425750-bc3b8a80-018c-11eb-951c-2305c62d2245.jpg)

**Comment by Jays2Kings** [comment]
Closing since old
