### ISSUE TITLE
[Feature Request] Don't delete downloaded manga which are not available in source anymore

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#609]
### Why/User Benefit/User Problem
I've downloaded a manga but the source has removed the chapters(license issue) from site and all my downloads also dissapeared

### What/Requirements
Do not delete downloaded manga even if it is not available in source anymore

**Comment by CarlosEsco** [comment]
There already was an option to not delete them.

**Comment by Mitia99** [comment]
@CarlosEsco I can't find the option.

**Comment by CarlosEsco** [comment]
![Screenshot_20200930-102717.png](https://user-images.githubusercontent.com/2092019/94698706-938bd000-0307-11eb-90ca-f2ea348dde8b.png)

**Comment by Mitia99** [comment]
@CarlosEsco Thank you,I found it.Too bad that all my download chapters are already deleted..It will be great to enable(don't delete) this feature by default.

**Comment by CarlosEsco** [comment]
It prompts you the very first time it occurs. You must have clicked the other option
