### ISSUE TITLE
[Feature Request] Restore downloads

### ISSUE THREAD

**Issue by narfanar** [Jays2Kings/tachiyomiJ2K#613]
### Why/User Benefit/User Problem
Phone migration or restore after failure

### What/Requirements
1. Tachiyomi automatically detects existing downloads in the downloads folder (even when this installation of Tachiyomi wasn't the one that downloaded them), OR
2. Add an option to specify a download location and explicitly traverse it looking for existing downloads.

**Comment by CarlosEsco** [comment]
you can just copy the parent folder of the source over to the new download location.  Then force close the application to register it
