### ISSUE TITLE
can add support to lower Android versions like android 5.0

### ISSUE THREAD

**Issue by lostb053** [Jays2Kings/tachiyomiJ2K#615]
Well my request is that support with lower Android versions should be added.
Well this might seem quite unnecessary but many ppl still use old phones who are interested in manga
I too am using one with Android 5.0 and the app wont support tho i like the app
Sorry if i am giving insufficient info

**Comment by CarlosEsco** [comment]
This was a design choice as Android 5 was less than 5% of users. Either upgrade your phone, or use the main tachiyomi app
