### ISSUE TITLE
[Bug] App Crash

### ISSUE THREAD

**Issue by ve8rix** [Jays2Kings/tachiyomiJ2K#618]
I'm using j2k v1.0.9. Sometimes i see an extension update and i try to update it, the app starts crashing and won't open until i force stop it.

- Device : Pocophone F1
- Android version : 10
- ROM : MIUI 12.0.2 (stable)

**Comment by Caio99BR** [comment]
Should be fixed on latest release

**Comment by Jays2Kings** [comment]
Since this is pre 1.4.4 this isn't related to update all, but as a lot of reworks happened to the installer since 1.0.9

If the crash is still happening, I'll reopen this
