### ISSUE TITLE
Start and end dates in tracking menu

### ISSUE THREAD

**Issue by TheTabbingman** [Jays2Kings/tachiyomiJ2K#619]
The ability to add or change start and end dates in the tracking menu.
This would be a nice feature because then you wouldn't have to leave the app if you want to change start or end dates.
This is also already in the stock tachiyomi.
![Screenshot_20201027-125634](https://user-images.githubusercontent.com/51281790/97343176-2e1ef680-1855-11eb-8123-2f6b11035302.png)

**Comment by Umairuem** [comment]
I also wanted to request this. It was really great in Tachiyomi where we could manage these dates from the app itself. I transferred to j2k and am enjoying the app a lot but their are just some things missing.
Hope they add it soon.

**Comment by TheTabbingman** [comment]
Has been added In new update
