### ISSUE TITLE
[Feature Request] Category specific sort

### ISSUE THREAD

**Issue by ardittristan** [Jays2Kings/tachiyomiJ2K#62]
### What/Requirements
I have two main categories for example, one for current and one for planned, I'd like to have current on last updated and planned on alphabetical without having to switch it every time i change between the categories.

**Comment by Jays2Kings** [comment]
You can do this by using Drag & Drop and in the 3 dots button in the top right, the sorting now stays in version 0.9.7

**Comment by ardittristan** [comment]
If you could also add last read to the drag drop category sorting i would be very happy
