### ISSUE TITLE
[Feature Request] Add confirmation pop-up when trying to mark all as unread

### ISSUE THREAD

**Issue by undrewatre** [Jays2Kings/tachiyomiJ2K#623]
### Why/User Benefit/User Problem
Prevent users from accidentally marking all as unread if a miss-tap happens

### What/Requirements
Just like when tapping on "Mark all as read", there would be a similar pop-up for confirmation, with the buttons "Cancel" and "Mark as unread" below.

**Comment by Caio99BR** [comment]
@Jays2Kings already fixed on latest release (I will ping you to some closed/duplicated issues)
