### ISSUE TITLE
[Bug] Sort by Latest Chapter

### ISSUE THREAD

**Issue by LHuss** [Jays2Kings/tachiyomiJ2K#624]
### Device information
* Tachiyomi version: 1.0.9
* Android phone & version: Pixel 5, Android 11

## Steps to reproduce
1. First step
* Have a bunch of manga in your library
* Potentially from different sources? (I'm at like 250 manga, most from mangakakalot but not all so not sure on this one. No clean device to test this on)
2. Second step
* Sort by latest chapter

### Expected behavior
List should be in order of the latest chapter released regardless of source

### Actual behavior
List seems to have picked about 5 manga to sort by most recent, at which point it gave up and kept the rest sorting alphabetically.  Should note that the 5 that are ordered are not necessarily the most recent in the entire library, just that when compared to each other, they are sorted "properly"

**Comment by Powsin** [comment]
I think you mean sort?

**Comment by fightmesun** [comment]
Having this same issue as well

**Comment by Jays2Kings** [comment]
Closing since this is old. If it's still happening on newest version, reopen this with more details on manga and sources used
