### ISSUE TITLE
[Feature Request] Source Url Changed Indicator

### ISSUE THREAD

**Issue by Powsin** [Jays2Kings/tachiyomiJ2K#625]
---

### Why/User Benefit/User Problem
When source url changes , that library item will no longer update, it can take you months to a year before you realize why. Currently you will only know that the item's source url has changed when you manually try to update the cover. 

### What/Requirements
Maybe a red exclamation mark on the item cover , similar to the chapter count.

**Comment by Jays2Kings** [comment]
stale and has other solutions for this now
