### ISSUE TITLE
[Feature Request] Similar manga recommendations for each category

### ISSUE THREAD

**Issue by KraXen72** [Jays2Kings/tachiyomiJ2K#626]
### Why/User Benefit/User Problem
helps you to find similar manga

### What/Requirements
it would take the tags of the mangas from one cagerory and find some mangas with multiple of them - for example if you have mangas with tags: slice of life, comedy, ecchi or whatever in one category, it would serach for mangas with these tags and recommend them to you. some system of rating would be required, maybe from MaL or something so shit manga doesen't get recommended, only above certain rating threshold

**Comment by CarlosEsco** [comment]
#373

And if its just recommending library manga, just group by that the tags
