### ISSUE TITLE
[Bug] Login for MyAnimeList tracking doesn't work and only reports "Unknown Error"

### ISSUE THREAD

**Issue by falsefingolfin** [Jays2Kings/tachiyomiJ2K#629]
### Device information
* Tachiyomi version: J2K 1.0.9
* Android phone & version: Samsung Galaxy S10, Android 10

## Steps to reproduce
1. Go to tracking in settings
2. Try to login to MyAnimeList

### Expected behavior
Successfully login to MyAnimeList for tracking

### Actual behavior
Get "Unknown Error" report and don't login

### Other details
Is it possible this is a MAL API thing?

**Comment by Xeiniac** [comment]
This has been fixed
