### ISSUE TITLE
[Bug] back up created dialog %1$s

### ISSUE THREAD

**Issue by CarlosEsco** [Jays2Kings/tachiyomiJ2K#63]
Doesn't show the file location of the back up but the string that is supposed to be replaced

**Comment by CarlosEsco** [comment]
Also seems on Android 9+ it doesn't show the file path anymore from the uri

**Comment by Jays2Kings** [comment]
It seems like it still can but shared locations like "downloads" and "pictures" don't return a proper file name anymore

**Comment by Jays2Kings** [comment]
Fixed as of 0.9.7, for now I'll just hide the text when the path is null
