### ISSUE TITLE
[Feature Request] v3 backups from TachiyomiSY and Regular Tachiyomi

### ISSUE THREAD

**Issue by Xeiniac** [Jays2Kings/tachiyomiJ2K#633]
### Why/User Benefit/User Problem
It's the new backup system which can let you restore backups offline. Also unlike the json backup it'll tell you what sources are missing and if you aren't logged into tracking. Imo it's faster and usually has less errors since it doesn't have to get everything from the sources. 

### What/Requirements
When you create a backup .proto.gz backup files are created instead of json files that can be restored offline.
Also maybe another option to still create legacy backups

**Comment by KraXen72** [comment]
+1

**Comment by joseph619** [comment]
This can be closed
