### ISSUE TITLE
[Bug] Komiku extension not shown properly

### ISSUE THREAD

**Issue by AnggaraArif** [Jays2Kings/tachiyomiJ2K#635]
### Device information
* Tachiyomi version: J2K 1.0.10
* Android phone & version: Redmi 4x running in android 10

## Steps to reproduce
1. Open browse tab
2. Open Komiku extension

### Expected behavior
The list of manga appears as it should

### Actual behavior
The list of manga from komiku extension not shown

### Other details
if opened using the browser all normally without problems

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/
