### ISSUE TITLE
[Bug] Image in Color Filter in Reader is not showing up

### ISSUE THREAD

**Issue by dustter** [Jays2Kings/tachiyomiJ2K#64]
### Device information
* Tachiyomi version: 0.9.69
* Android version: 9

## Steps to reproduce
1. Open color filter option in Reader
2. See the bug being reproduced

### Expected behavior
It should show image as shown in this Dev screenshot.
![Screenshot_20200114-210707_Tachiyomi](https://user-images.githubusercontent.com/54286558/72378611-06b9cb80-3712-11ea-9e2f-f4b509bab56d.jpg)

### Actual behavior
It doesn't do so.
![Screenshot_20200114-205632_Tachiyomi](https://user-images.githubusercontent.com/54286558/72378655-189b6e80-3712-11ea-9f97-8ac20897b033.jpg)

### Other details
Nothing else, just solely the image doesn't show.

**Comment by happywillow0** [comment]
For reference: https://github.com/Jays2Kings/tachiyomiJ2K/blob/master/app/src/main/res/drawable/filter_mock.webp
