### ISSUE TITLE
What's the plan? Upstream/Regular and divergence.

### ISSUE THREAD

**Issue by munael** [Jays2Kings/tachiyomiJ2K#642]
The code base seems to have diverged quite a bit from Tachiyomi's master (based on the fork graph).

It should be clarified if the fork intends to sync up with the main build for non-UI components (and even some UI components?), like backup v3. Should help with logic and backend bugs as well (e.g. TachiyomiJ2K currently crashes often during migration).

Just putting this up for discussion :D

**Comment by joseph619** [comment]
You can open a ticket for migration crash now that J2K is active again

**Comment by CarlosEsco** [comment]
TachiyomiJ2K is a free and open source manga reader for Android 6.0 and above. **Based** on the original Tachiyomi
I would not expect every feature from main app to make it here.  At the end of the day it is whatever feature makes sense to Jays2Kings
