### ISSUE TITLE
[Feature Request] Download chapters on CBZ

### ISSUE THREAD

**Issue by KasukeLp23** [Jays2Kings/tachiyomiJ2K#645]
It would be a good option to be able to download the chapters in CBZ format, thus having a single file of each chapter with all the images, and would be feasible for the user.

I hope you will consider this option, and thank you in advance.

Greeting.

**Comment by CarlosEsco** [comment]
Its not possible to download as cbz, but is possible to convert the downloaded images to cbz after.

**Comment by KasukeLp23** [comment]
Oh, because I saw that they had that option in TachiyomiSY, I thought they could implement it here in TachiyomiJ2k

**Comment by CarlosEsco** [comment]
SY doesn't download them as CBZ he converts them after the fact

**Comment by KasukeLp23** [comment]
Oh ok, and how would it be possible to convert the downloaded images to cbz??

**Comment by Xeiniac** [comment]
Doesn't the zip just have to be renamed to cbz after the download since cbz is just zip file that only has images but with a different extension?

**Comment by Zaroz** [comment]
> > Oh ok, and how would it be possible to convert the downloaded images to cbz??
> 
> The downloaded folder just has to be zipped and the extension renamed to CBZ to make it into a CBZ file.
> Since CBZ is just a ZIP file that only has images but with a different extension.

well, there can also be other files in a .cbz, but it's usually metadata though.

**Comment by e-shl** [comment]
Very useful thing, especially for those who use a external reader.

**Comment by CarlosEsco** [comment]
if you are using an external reader, then you are using the wrong app and should probably be using a desktop downloader

**Comment by e-shl** [comment]
I and don't use a third-party reader, but some of them are familiar to me. But it can be useful both for saving space (https://github.com/Jays2Kings/tachiyomiJ2K/issues/773) and for hiding media files more strongly.

**Comment by CarlosEsco** [comment]
closing for the better named #773
