### ISSUE TITLE
[Bug] MyAnimeList doesn't sync chapters (Neither Automatically nor manually)

### ISSUE THREAD

**Issue by Umairuem** [Jays2Kings/tachiyomiJ2K#646]
### Device information
* Tachiyomi version: j2k 1.0.10
* Android phone & version: HTC One A9, Android 7

## Steps to reproduce
1. Open a manga entry
2. Read a chapter OR Open "Tracking" section in any entry and update the chapter

### Expected behavior
The chapter should be updated on MyAnimeList when I update it on Tachiyomi.

### Actual behavior
It shows on Tachiyomij2k that the chapter number increased, but after a refresh it's back to what it was before. And no changes to MAL site either.

### Other details
I've enabled the Tracking for both Anilist and MAL. Anilist works perfectly fine. But for the previous 3-4 days, MAL Tracking has been behaving this way even though it was working fine before that.

**Comment by CarlosEsco** [comment]
clear cookies and logout of mal, then relogin

**Comment by Umairuem** [comment]
> clear cookies and logout of mal, then relogin

Not working. I've also tried using "DNS over HTTPS", but the problem is still not solved.

**Comment by Umairuem** [comment]
version 1.0.11 fixed the issue.
