### ISSUE TITLE
[Bug] Extensions sometimes do not load

### ISSUE THREAD

**Issue by askolds11** [Jays2Kings/tachiyomiJ2K#648]
### Device information
* Tachiyomi version: ?
* Android phone & version: Poco F2 Pro Android 11 on xiaomi.eu MIUI 12

## Steps to reproduce
1. First step
Open Tachiyomi
2. Second step
Go to extensions
### Expected behavior
There should be installed extensions listed, library should update on refresh.

### Actual behavior
No extensions are shown to be installed and library doesn't/can't update.

### Other details
Since this happens randomly, I can't test it on the default Tachiyomi app.
Force closing the application seems to fix it (But it can still happen later).
I haven't linked any action I've done before to this behavior. This could be due to MIUI optimizations, but I can't check if disabling it works. I've now disabled it, and if it happens again, I'll post a comment here.
![Screenshot_2021-01-16-23-54-45-073_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/77554113/104824199-8106b980-5858-11eb-9021-129d33a1baa0.jpg)
![Screenshot_2021-01-16-23-55-42-667_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/77554113/104824201-819f5000-5858-11eb-9593-cd88882319d0.jpg)

Since this happens randomly, and I do not expect it to be reproducible, I'd like to know what to do if this happens again (get a log, or something else).

**Comment by CarlosEsco** [comment]
Click the filter at top and make sure you aren't filtering them out

**Comment by askolds11** [comment]
The next time this happens I will check, but I just checked (without the bug happening), and filtering all extensions out doesn't make the library not update, which happens if the bug happens, so it's probably not it.

**Comment by askolds11** [comment]
Happened again, the filters were empty, so it shouldn't be battery optimization.

**Comment by arkon** [comment]
See https://github.com/tachiyomiorg/tachiyomi/issues/4313

**Comment by askolds11** [comment]
As this is a Tachiyomi issue, do I close it here?

**Comment by arkon** [comment]
Up to you. J2K doesn't necessarily take fixes from the main app.

**Comment by CarlosEsco** [comment]
I would leave it open for now.  But watch the main app and if there is a fix link it here

**Comment by askolds11** [comment]
Forgot to link the fix, since I allowed the app to get info about installed apps always, as noted in [tachiyomiorg#4313](https://github.com/tachiyomiorg/tachiyomi/issues/4313), and that fixed it.
[fdcbc4c](https://github.com/tachiyomiorg/tachiyomi/commit/fdcbc4cffaed7a7e2656db3d206a5fa4c1f3c8d0)
