### ISSUE TITLE
[Bug] Not a JSON Object

### ISSUE THREAD

**Issue by VishalNikam1295** [Jays2Kings/tachiyomiJ2K#651]
---

### Device information
* Tachiyomi version: 0.10.7
* Android phone & version: OnePlus 5T & Android 10

## Steps to reproduce
1. Backup Created in Tachiyomi 0.10.7
2. Restore Backup in Tachiyomi J2K 1.0.10

### Expected behavior
Restore the backup in Tachiyomi J2K

### Actual behavior
Error shown "Not a JSON Object".

### Other details
N/A

**Comment by arkon** [comment]
You have to use the legacy backup if you're planning on restoring in J2K.
