### ISSUE TITLE
[Bug] Can't restore backup from Tachiyomi Beta to J2K

### ISSUE THREAD

**Issue by iamcrucial** [Jays2Kings/tachiyomiJ2K#652]
How do I transfer all the things I have to J2k? It says not a JSON object from Tachiyomi beta to J2K. Is there a workaround?

**Comment by iamcrucial** [comment]
Update: I tried Legacy backup and found these errors.

![Screenshot_20210206-130846](https://user-images.githubusercontent.com/78633099/107109575-96319f80-687c-11eb-9494-db35199dae36.jpg)

**Comment by Jays2Kings** [comment]
Betas are betas for a reason. Sources change and features break. Can't be helped
