### ISSUE TITLE
[Bug] My Library Can't Update Latest Chapter

### ISSUE THREAD

**Issue by dimanawaifuku** [Jays2Kings/tachiyomiJ2K#658]
### Device information
* Tachiyomi version: 1.0.10
* Android phone & version: Vivo V7 Funtouch OS 4.0 Android 8.1.0

## Steps to reproduce
1. Open TachiJ2K
2. Update library

### Expected behavior
Latest chapter from my library will appear

### Actual behavior
My library update were stuck from 7 days ago update only

### Other details
This is for example. "Blue Hearts" only shown until ch 61, even though in mangadex it's already updated for ch 62. I tried to update manually for one title too (ex. only refresh on Blue Hearts), but still not worked.

![PhotoCollage_1613105327846](https://user-images.githubusercontent.com/78945235/107731713-3aa65c80-6d29-11eb-9127-62c10a619e0a.jpg)

Another example with "Enen no Shouboutai", if I open mangadex from chrome and I choose read the chapter with tachij2k, it says chapter not found.

![PhotoCollage_1613105425653](https://user-images.githubusercontent.com/78945235/107731700-3417e500-6d29-11eb-8fc2-cdd7babdf638.jpg)

**Comment by KaniDev** [comment]
Same issue here, all sources stopped updating 5 days ago and I also get the "chapter not found" thing when I try opening a new chapter externally

**Comment by DARKFLAMEMASTA** [comment]
See https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5780
They can fix it temporally but don't want to do it, because if Neko is working now the extension can be fixed.
Just use Neko https://tachiyomi.org/forks/Neko/

**Comment by dimanawaifuku** [comment]
> The extensions are maintained by others.
> See [tachiyomiorg/tachiyomi-extensions#5780](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5780)
> They can fix it temporally but don't want to do it, because if Neko is working now the extension can be fixed.
> Just use Neko https://tachiyomi.org/forks/Neko/

Thank you so much! I hope the issues will be fixed as soon as possible
