### ISSUE TITLE
[Feature Request] Connection to sites library with proxy

### ISSUE THREAD

**Issue by Divaltor** [Jays2Kings/tachiyomiJ2K#659]
### Why/User Benefit/User Problem
Some sites block requests from certain IP addresses, so it would be nice to add the ability to connect a proxy (HTTPS or SOCKS5)

### What/Requirements
The ability to connect a proxy in the settings: the host, username, password, port and type (https or socks5) fields

**Comment by arkon** [comment]
You can just do that at your system-level networking settings.

**Comment by Divaltor** [comment]
> You can just do that at your system-level networking settings.

I don't want to constantly switch the system proxy, but if there is no other option, then ok. You can close the topic
