### ISSUE TITLE
[Bug] Editing tracker for one manga opens keyboard by default

### ISSUE THREAD

**Issue by WH1T3No1SE** [Jays2Kings/tachiyomiJ2K#66]
### Device information
* Tachiyomi version: J2K 0.9.70
* Android version: 8.1 Color OS

## Steps to reproduce
1. Select any manga
2. Go to track section
3. Edit tracker to add to tracking
4. Window opens and keyboard automatically with it by default.

### Expected behavior
No keyboard should open by default, just selection window.

### Actual behavior
Keyboard opens along with selection window

### Other details
Keyboard takes screen real estate. I should only open keyboard there manually for edits if necessary.

**Comment by Jays2Kings** [comment]
Pretty sure this one is fixed
