### ISSUE TITLE
Taking too long to load

### ISSUE THREAD

**Issue by aoiaoiaoi1** [Jays2Kings/tachiyomiJ2K#660]
**App version:** latest v.1.0.10

**Android version:** 6.0

**Issue/Request:** 
the contents are taking too long to load on new chaps and the chapter itself.

**Other details:**
Checked my internet connection and it's fine and stable, cleared cache and cookies, cleared download chapters, refreshed library and metadata, etc. Kindly please fix it thank you

**Comment by CarlosEsco** [comment]
Sounds entirely source related. You should follow the general troubleshooting provided on the discord channel and if an issue still exists open one on the tachiyomi-extensions repo
