### ISSUE TITLE
[Bug] TachiyomiJ2K cannot open downloaded chapter from other tachiyomi apps

### ISSUE THREAD

**Issue by CaptainHalflife** [Jays2Kings/tachiyomiJ2K#661]
### Device information
* Tachiyomi version: 1.0.10
* Android phone & version: 8.1.0

## Steps to reproduce
1. Having an another tachiyomi app (e.g tachiyomi or tachiyomiSY)
2. Add the exact same manga from the same source on both apps library
3. Make sure they both have the same download directory 
4. Download a chapter from tachiyomi (not tachiyomiJ2K)
5. Restart tachiyomiJ2K (need to force stop)

### Expected behavior
TachiyomiJ2K detect that there is a downloaded manga and can open it offline

### Actual behavior
The download badge appear on the library but when opening the manga it says it is not downloaded and can't open it offline.

![20210221_110913](https://user-images.githubusercontent.com/65003109/108618188-61eddf80-7435-11eb-95ac-9301635980b5.jpg)
![20210221_110930](https://user-images.githubusercontent.com/65003109/108618190-6619fd00-7435-11eb-9523-a6ce762a521f.jpg)

### Other details
The other way around work. If i download a chapter on tachiyomiJ2K it will work on tachiyomi.

**Comment by Jays2Kings** [comment]
You'll have to provide an example folder chapter name, since the logic is the same for both apps

**Comment by CaptainHalflife** [comment]
The bug is fixed with the 1.10.11 update.
