### ISSUE TITLE
Pages do not load

### ISSUE THREAD

**Issue by Westerrr** [Jays2Kings/tachiyomiJ2K#665]
After the update of mangasee I did earlier I've been unable to read manga from mangasee, the pages do not load and it keeps asking to retry it. But nothing happe.s once I click it

**Comment by CarlosEsco** [comment]
This a mangasee extension issue not a j2k issue.

**Comment by Westerrr** [comment]
Ic, thank you for your reply.... uhm, is there anything I can do?

Op do 11 mrt. 2021 om 18:14 schreef Carlos ***@***.***>:

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6136

no either migrate or wait, the owner said they probably will unblock tachi after dex is more stable.

**Comment by Westerrr** [comment]
Ok, thanks for the update.

Op vr 12 mrt. 2021 om 13:27 schreef Carlos ***@***.***>:
