### ISSUE TITLE
[Bug] manga life is broken

### ISSUE THREAD

**Issue by medoria0** [Jays2Kings/tachiyomiJ2K#668]
### Device information
* Tachiyomi version: 1.0.10
* Android phone & version: A71, version 10

## Steps to reproduce
1. Download manga life
2. Open a manga, the one I choose was "the gamer", it is a webtoon

### Expected behavior
It should load normally

### Actual behavior
The pages are all retry and I open it in web view and there wasn't a problem with the site or the actual pages, so I think it is a problem with the extension itself

### Other details
Can you please fix it ASAP, it is my main extension that I use

**Comment by CarlosEsco** [comment]
This is a tachiyomi extension issue.  Which is known. Has nothing to do with j2k

**Comment by medoria0** [comment]
Ops my bad just read the announcement in the discord server
