### ISSUE TITLE
[Feature Request] Add change log for extensions

### ISSUE THREAD

**Issue by parthspatel** [Jays2Kings/tachiyomiJ2K#669]
### Why/User Benefit/User Problem
Many times we are seeing updates to extensions and have no idea why I should update?  And what features/bug-fixes are being added.  

### What/Requirements
When an extensions has an update when you click install it should list out the change log.
Also when you click on an extension where there are extension preferences, we should also be allowed to see the change log.

**Comment by CarlosEsco** [comment]
extensions don't have a change log.  Your best bet would be to look at 

https://github.com/tachiyomiorg/tachiyomi-extensions/commits/master

to see the commit history
