### ISSUE TITLE
Create a "migrate bookmarks" option on migration

### ISSUE THREAD

**Issue by James-Yuji** [Jays2Kings/tachiyomiJ2K#670]
Why/User Benefit/User Problem
(when migrating a manga/manhwa/webtoon there is no option to migrate bookmarks, hence whenever a title is migrated, all bookmarks are deleted)

What/Requirements
(A option in the migrating menu with such feature would help, put it beside the "tracking" "chapters" "categories" as a data to choose to migrate with the title)

**Comment by GreatestFool** [comment]
#671 is identical to this, and also one of yours, so this can be deleted or closed so that attention is not split between Issue threads.

**Comment by joseph619** [comment]
Duplicate of #151
