### ISSUE TITLE
[Bug] Bacakomik ID Empty Page List

### ISSUE THREAD

**Issue by Username778** [Jays2Kings/tachiyomiJ2K#672]
![160957785_3994606827271961_2123048522497333963_o](https://user-images.githubusercontent.com/32461041/111484292-3629f500-8768-11eb-9d53-af606eb9567e.jpg)

**Comment by CarlosEsco** [comment]
extension issues go https://github.com/tachiyomiorg/tachiyomi-extensions/issues
