### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#673]
### Device information
* Tachiyomi version: 1.0.10
* Android phone & version: note 9. Android 10

## Steps to reproduce
1. Select manga
2. Expand description by taking description
3. Tap again to collapse

### Expected behavior
Description should collapse when reading description area

### Actual behavior
Does not happen

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Jay here's the line from neko if you decide to address this
https://github.com/CarlosEsco/Neko/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaHeaderHolder.kt#L58
