### ISSUE TITLE
[Feature Request] Able to choose Accent Color

### ISSUE THREAD

**Issue by IshaqIqbalRick** [Jays2Kings/tachiyomiJ2K#675]
### Why/User Benefit/User Problem
I know it's totally optional or unnecessary. But it will give the tachiyomi-J2k an extra flex. Because I think tachiyomi-J2k is totally about flex where you can customise almost everything and anything....

### What/Requirements
![Screenshot_2021-03-19-19-42-36-011_com.bksapps.animezone.jpg](https://user-images.githubusercontent.com/72049567/111792734-bbd7ad00-88ee-11eb-8861-bc262f35dc9d.jpg)
It can be preferable....

![Screenshot_2021-03-19-20-07-20-259_com.kodarkooperativet.blackplayerex.jpg](https://user-images.githubusercontent.com/72049567/111792814-d27e0400-88ee-11eb-80f3-eb8c48bc6786.jpg)
It's much more like it......

**Comment by ramonGonzEdu** [comment]
This would be very interesting.

**Comment by ethanolamine** [comment]
I hope Jay adds this!

**Comment by joseph619** [comment]
This was rejected in #719, should be closed
