### ISSUE TITLE
[Feature Request] The continue reading button should be like the Tachiyomi's

### ISSUE THREAD

**Issue by IshaqIqbalRick** [Jays2Kings/tachiyomiJ2K#676]
### Why/User Benefit/User Problem
This issue is common between me and my friends who used both Tachiyomi-J2k and Tachiyomi.
We think that continue reading button (Tachiyomi style) was better because when we need to take look in a random previous chapter for understanding recent chapters materials after that we have to scroll all the way back up/down
To continue reading. It's a hassle when raeding big manga like:- Gintama , one piece, bleach etc

### What/Requirements
So it's would much better if it were to be like this
![Screenshot_2021-03-19-19-45-01-564_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/72049567/111795621-94361400-88f1-11eb-9889-133d59fe1442.jpg)

**Comment by CarlosEsco** [comment]
There are no plans to switch to the FAB.   FAB provides quicker access but provides less details compared to the button.
