### ISSUE TITLE
[Feature Request] Adding settings button beside each Source

### ISSUE THREAD

**Issue by hjdrm** [Jays2Kings/tachiyomiJ2K#677]
### Why/User Benefit/User Problem
(explain why this feature should be added)

Put a settings button beside the source, and option where you can enable/disable specific language or source(from multiple sources). For someone like me who's still using WP Mangastream for certain sources which are removed in the newer versions of the source.

### What/Requirements
(explain how this feature would behave)

Like how TachiyomiSY has implemented. (See Screenshots)
![Screenshot_20210322-204135623](https://user-images.githubusercontent.com/64572536/111992872-df9a2d80-8b50-11eb-8d0c-5b976869ca2a.jpg)
![Screenshot_20210322-204128801](https://user-images.githubusercontent.com/64572536/111992920-eaed5900-8b50-11eb-9f3c-4d566562fc44.jpg)

**Comment by IshaqIqbalRick** [comment]
Bro there is triple line on conner click that _![Screenshot_2021-03-24-23-56-21-999_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/72049567/112360545-a4d4f880-8cfc-11eb-9f3f-2d3afea4b986.jpg)![Screenshot_2021-03-24-23-56-36-612_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/72049567/112360549-a69ebc00-8cfc-11eb-9a24-d52e92720f1d.jpg)_

**Comment by Jays2Kings** [comment]
Done in 9a220073b
