### ISSUE TITLE
[Feature Request] S-Pen support (from Neko)

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#678]
### Why/User Benefit/User Problem
Will allow users to navigate pages remotely for those who have a Samsung device with S pen 

### What/Requirements
Yoink from Neko

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/commit/53400b91c7708fc63675843b39f04bd8b9df647d

**Comment by CarlosEsco** [comment]
And 

https://github.com/CarlosEsco/Neko/commit/35330bf4d678d9e63079e5e05124a40ce2aa0ae8
