### ISSUE TITLE
[Bug] Chapter page returning to screen after changing apps

### ISSUE THREAD

**Issue by iAmPhilo** [Jays2Kings/tachiyomiJ2K#68]
### Device information
* Tachiyomi version: 0.9.7
* Android phone & version: 10

## Steps to reproduce
1. Go in to a Manga chapter, go to any page
2. Return to homescreen, go to another app
3. Go to multi task screen and click on tachiyomi
4. Not on the chapter page anymore

### Expected behavior
Should still be on the chapter page

### Actual behavior
Exits to previous screen

**Comment by bairagyakushal4** [comment]
No didn't happened to me, I tried to reproduce the problem but it's working fine.

**Comment by bairagyakushal4** [comment]
Could it be something to do with android version! BTW I am on android 7.

**Comment by iAmPhilo** [comment]
> Could it be something to do with android version! BTW I am on android 7.

Maybe, did you go to a chapter page like 3 in a manga, press your home button, go to another app, click multitask menu and back to tachiyomi app and it returns u to the previous menu instead of staying on the page? It does stay on the page when I do the swipe left or right to switch app, just when i manually click into it on the multitask screen it doesnt.

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi/issues/2054

**Comment by bairagyakushal4** [comment]
I see , it does happens but is this really bug ! Or just a function of the app maybe.

**Comment by Jays2Kings** [comment]
It's fixed as of 0.9.75
