### ISSUE TITLE
Can't open my Tachij2k app

### ISSUE THREAD

**Issue by Akev8** [Jays2Kings/tachiyomiJ2K#680]
Hi 
I was reading last night and this morning the application no longer opens, I made all the updates they asked but I do not understand why it no longer opens.  Is there a bug and we have to wait or I will lose everything and have to reinstall the application knowing that I have not made a backup 😭

**Comment by Akzyra** [comment]
Try to Update android system webview, it had a bug. Had to do it manually, quite bad that it didn't auto update.

**Comment by Akev8** [comment]
It worked , thanks 😅😭🙏
