### ISSUE TITLE
[Bug] TachiyomiJ2K can`t be uninstalled 

### ISSUE THREAD

**Issue by SoumickDeyArgha** [Jays2Kings/tachiyomiJ2K#681]
![Tachiyomi J2k](https://user-images.githubusercontent.com/81220532/112113912-6eed2280-8bdd-11eb-93ee-8a924e915ece.jpg)
### Device information
* Tachiyomi version: TachiyomiJ2K v1.0.10
* Android phone & version: Poco F1 (Beryllium) Official Lineage 17.1 Android 10

## Steps to reproduce
1. Uninstalling the app from the home screen
2. Uninstalling the app from within the app

### Expected behaviour
When uninstalling the app should be uninstalled.

### Actual behaviour
But instead, the phone package installer crashes every time.

### Other details
 I don't have any issue with other apps I can install and uninstall other apps just fine
It's just this app that has an issue.

**Comment by ramonGonzEdu** [comment]
Have you checked if the webview package is updated? The old version is causing many apps to crash on android.

**Comment by Jays2Kings** [comment]
https://tachiyomi.org/help/faq/#what-is-tachiyomi-preview 
Find "Why can't I uninstall Tachiyomi?" section

**Comment by SoumickDeyArgha** [comment]
> https://tachiyomi.org/help/faq/#what-is-tachiyomi-preview
> Find "Why can't I uninstall Tachiyomi?" section



> Have you checked if the webview package is updated? The old version is causing many apps to crash on android.

yeah I checked the webview I uninstalled the update too, but still the same result

**Comment by SoumickDeyArgha** [comment]
The problem was solved after flashing the ROM again.
