### ISSUE TITLE
[Feature Request] Large banner when there is a new version of the app.

### ISSUE THREAD

**Issue by ramonGonzEdu** [Jays2Kings/tachiyomiJ2K#682]
### Why/User Benefit/User Problem
I've been using a *very* outdated version of J2K for a very long time, and when it didn't work today, I tried to reinstall, and after fixing the actual issue, saw that J2K changed its UI completely. A large red banner at the top of the screen would help the users realize when an update comes out.

### What/Requirements
A large red banner (that you could disable in the settings) that says that there is an update. This should be very different than the regular notification banners as many people get so many notifs that an "update available" might be buried.
This could then use the same system as the sources apk updater to update the app when a button is pressed, or could open chrome on the gh releases page, so the user can manually install.

**Comment by Jays2Kings** [comment]
There's already been new measures to show theres a new update. Can't help fix that for older versions

**Comment by ramonGonzEdu** [comment]
Sorry, I didn't know and I couldn't find this info. May I ask what the new update thing is?
