### ISSUE TITLE
Switch to view binding

### ISSUE THREAD

**Issue by CarlosEsco** [Jays2Kings/tachiyomiJ2K#684]
Kotlin Synthetics are going away, should migrate to view binding
https://developer.android.com/topic/libraries/view-binding/migration

**Comment by arkon** [comment]
Technically not an issue if you never update Kotlin though.

**Comment by CarlosEsco** [comment]
True, i just assume Jays not abandoning the app since he's active now :smile:

**Comment by Jays2Kings** [comment]
Yeah this is planned after the next release, I was planning to do this even if synthetics didn't get deprecated
