### ISSUE TITLE
[Feature Request] Add the split seekbar in reader from Preview or Neko

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#685]
Basically the seekbar that's been split from bottom toolbar in reader , as available in Neko or Preview 

Also maybe yoink the vertical seekbar for vertical reading modes from SY (primary reason why the seekbar was split and would likely be added to Preview later anyway) 

Relevant commits 

https://github.com/jobobby04/TachiyomiSY/pull/216

https://github.com/jobobby04/TachiyomiSY/commit/d9b3b7b266217188d413f9cec6c4c36ba88ecc31

PS- Thanks a ton for adding SPen support Jay, now I can fully enjoy J2K on my Galaxy Tab S7 😁

**Comment by joseph619** [comment]
@Jays2Kings what's your plan for this? If you want to add this, I posted a screenshot on SY repo to move the View chapters button in reader to chapter name/number just to Manga Rock, to accomodate more buttons in the bottom toolbar, which I could post it here for reference.

**Comment by Jays2Kings** [comment]
It's only been a day have some patience lol. It's still the same as before: if something is still open, it's still in consideration. 

Either way, it's not a simple enough change that I'm willing to put into this upcoming release.

**Comment by joseph619** [comment]
haha, understandable. just wanted to let it out in case you vanished again 😛 

good to see J2K alive again 😄

**Comment by Jays2Kings** [comment]
Added for next version

**Comment by joseph619** [comment]
nicee, thanks a lot bruh ❤️ 

vertical seekbar is added too? since that was the main purpose of the split 👀
