### ISSUE TITLE
[Bug] Brightness problem

### ISSUE THREAD

**Issue by IshaqIqbalRick** [Jays2Kings/tachiyomiJ2K#686]
### Device information
* Tachiyomi version: 1.0.10
* Android phone & version: redmi note 9 (Android -10)

### Expected behavior
Actually the additional brightness settings in the is not working quite well because it doesn't showa the exact brightness changing like this![Screenrecorder-2021-03-26-06-24-05-672.mp4](https://user-images.githubusercontent.com/72049567/112559950-42632180-8dfc-11eb-8f6d-f9b5f7d29d95.mp4)

### Actual behavior
Instead it stays the same and the brighness drastically reduced or increases.![Uploading Screenrecorder-2021-03-26-06-29-26-370.mp4 …]()

### Other details
I think this whole part should excluding. Because it's quite annoying ![IMG_20210326_063025.jpg](https://user-images.githubusercontent.com/72049567/112560266-07152280-8dfd-11eb-8c5b-67641fbac649.jpg)
And show the actual page how it's brighting up or dim down
Like this![Screenrecorder-2021-03-26-06-35-42-939.mp4](https://user-images.githubusercontent.com/72049567/112560713-f6b17780-8dfd-11eb-9e6e-adc18ef93832.mp4)

**Comment by Jays2Kings** [comment]
Already done for next release

**Comment by IshaqIqbalRick** [comment]
Happy to know

**Comment by IshaqIqbalRick** [comment]
> Already done for next release

The didn't fix at all it doesn't show properly how bright the page until layout is down
