### ISSUE TITLE
[Bug] Download Queue cleared out but downloaded anyway

### ISSUE THREAD

**Issue by loocool2** [Jays2Kings/tachiyomiJ2K#69]
On behalf of Ducc

## Steps to reproduce
>I updated my Library
>Mangasee updated some manga which basically meant 30 new chapters
>They were queued for downloading
>I selected all of them [in the download queue], pressed delete and marked them as read(this should delete em)
>The chapter that was currently downloading stopped downloading
>After a minute, I notice 40 new downloaded chapters

### Expected behavior
The download queue should've been cleared and no chapters should have been marked as read so the downloaded chapters, even if they were downloaded, should've been deleted.
### Actual behavior
The chapters were still downloaded.

**Comment by DuccinatorAlpha** [comment]
The ducc thanks you.

**Comment by Jays2Kings** [comment]
This should be fixed now as of 0.9.75
