### ISSUE TITLE
[Feature Request] Show larger thumbnails (less manga per row) for L and XL grid on Tablets

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#690]
Us tablet users need some love 🥵 

On a Galaxy Tab S7, the thumbnails in gallery for L and XL grid options are too small in portrait mode 

For L grid option in Library, it currently shows 5 manga per row in portrait mode (on Tab S7). 

It would be nice if 4 manga per row for L, and 3 for XL grid option on Tablets in portrait mode.

Here is screenshot for example 

![Screenshot_20210326-191251_TachiyomiJ2K](https://user-images.githubusercontent.com/34897862/112701546-53954800-8e67-11eb-994e-04f39e950883.jpg)

**Comment by Xeiniac** [comment]
A new size could be added too which will be the current XL, let's say XXL and XL can be 4 per row. It would also make sense since M is 6 per row and L is 5 Per row but the current XL is 3 per row in portrait on tablets.

**Comment by joseph619** [comment]
This was added recently so closing
