### ISSUE TITLE
[Feature Request] Add Mangadex as a tracker (like MyAnimeList and Anilist) 

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#691]
### Why/User Benefit/User Problem
Since Mangadex is partially delegated already, requesting to add the feature to use Mangadex as a tracker in tracking sheet.

### What/Requirements
It should work for **both** Mangadex **and** non-Mangadex manga. 

Currently available as above in TachiyomiSY

**Comment by Zaroz** [comment]
In addition, I would also like to see MDList syncing (also in TachiyomiSY)
