### ISSUE TITLE
[Bug] Webtoon mode adds black bars between pages

### ISSUE THREAD

**Issue by jfcaraujo** [Jays2Kings/tachiyomiJ2K#692]
### Device information
* Tachiyomi version: 1.0.11
* Android phone & version: Huawei MediaPad M5 pro, android 9

## Steps to reproduce
1. Open Magic Emperor from the Manga kakalot or Read M source (the bug happens on both, there may be others but I didn't test more) 
2. Set reading mode to webtoon mode

### Expected behavior
All the images should be linked together vertically

### Actual behavior
Adds black bars/space between the pages

### Other details
This is the only title in my library for which the bug happens, other webtoons work fine
And I have checked on webview, on vertical and left to right reading mode and on regular/main tachiyomi, there are no black bars in the images of the chapter
The cause of the bug may be the pages having different widths or the long length of each page (dunno about this, just guessing) 
(First image is in webtoon mode, second is vertical, they both show the same page transition)  
![Screenshot_20210328_234428_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/20336458/112770744-0c9e8280-9020-11eb-89ce-6a5bb5259ef9.jpg)
![Screenshot_20210328_234610_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/20336458/112770745-0d371900-9020-11eb-97cb-6eada404c1d9.jpg)

**Comment by d4rky-pl** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/2736

**Comment by Discomforts** [comment]
> ### Device information
> * Tachiyomi version: 1.0.11
> * Android phone & version: Huawei MediaPad M5 pro, android 9
> 
> ## Steps to reproduce
> 1. Open Magic Emperor from the Manga kakalot or Read M source (the bug happens on both, there may be others but I didn't test more)
> 2. Set reading mode to webtoon mode
> 
> ### Expected behavior
> All the images should be linked together vertically
> 
> ### Actual behavior
> Adds black bars/space between the pages
> 
> ### Other details
> This is the only title in my library for which the bug happens, other webtoons work fine
> And I have checked on webview, on vertical and left to right reading mode and on regular/main tachiyomi, there are no black bars in the images of the chapter
> The cause of the bug may be the pages having different widths or the long length of each page (dunno about this, just guessing)
> (First image is in webtoon mode, second is vertical, they both show the same page transition)
> ![Screenshot_20210328_234428_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/20336458/112770744-0c9e8280-9020-11eb-89ce-6a5bb5259ef9.jpg)
> ![Screenshot_20210328_234610_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/20336458/112770745-0d371900-9020-11eb-97cb-6eada404c1d9.jpg)

Nah bro keep it like it is

**Comment by jfcaraujo** [comment]
> 
> 
> [tachiyomiorg#2736](https://github.com/tachiyomiorg/tachiyomi/issues/2736)

Like I said in the description, using regular/vanilla tachiyomi it works fine, there is no black bar.
Rechecked again, there is also no incorrect scalling

**Comment by Jays2Kings** [comment]
Closing this because it happens in main too and has be reported. If main fixes it I'll follow but there's no plans

**Comment by jfcaraujo** [comment]
> Closing this because it happens in main too and has be reported. If main fixes it I'll follow but there's no plans on my end for this

In main works fine for me, that's why I reported in this repo
Weird
