### ISSUE TITLE
[Bug] Manga not sorted in latest chapter update

### ISSUE THREAD

**Issue by fightmesun** [Jays2Kings/tachiyomiJ2K#702]
### Device information
* Tachiyomi version: 1.0.11
* Android phone & version: 11

## Steps to reproduce
1. Select manga to be sorted by the latest chapter update

### Expected behavior
Mangas that have recently been updated should show up at the top of the list/grid

### Actual behavior
Mangas are ordered in a bizzare manner where 9 or so mangas rotate order. Selecting the first manga and refresh it's page will cause it's last chapter upload time to change to "0 minutes ago"

### Other details
Would take screen shots but app prevents me from doing so.

**Comment by Jays2Kings** [comment]
Turn off secure screen in settings, and you can take screenshots.

There needs to be more details like what manga, what source(s), etc.

**Comment by fightmesun** [comment]
![Screenshot_20210409-191354_TachiyomiJ2K](https://user-images.githubusercontent.com/46666382/114255053-d0e0b280-9967-11eb-93b6-7e894b4dec0e.jpg)
All the ones with the notification are the ones that were just newly updated

**Comment by Jays2Kings** [comment]
You didn't mention the source but I'm guessing it CatManga, since the source doesn't have upload dates there's nothing that can be done. There's no real fixing that so you're out of luck for sources/extensions that change the upload date each time.

**Comment by Jays2Kings** [comment]
If the date's time in milliseconds being sent was 0, it would show in the correct order. TachiJ2K can handle this case, not sure about main Tachi. You can ask in the tachi-extensions repo if they'll change it.

**Comment by fightmesun** [comment]
Ergh sorry the source is from isekaiscans

**Comment by Jays2Kings** [comment]
Same issue as before, it being a source issue. Instead ask them to use a steady time for date upload (like UTC midnight), instead of refreshing the date upload to your current time

If on refresh the chapter date keeps changing then there's nothing I can do in my end

**Comment by fightmesun** [comment]
Ah alright. Thank you!
