### ISSUE TITLE
[Feature Request] Double page setting per reading mode

### ISSUE THREAD

**Issue by CrepeTF** [Jays2Kings/tachiyomiJ2K#705]
---

### Why/User Benefit/User Problem
Example: single page in portrait - optimum view for the largest page size, double page in landscape - as screen is wide enough to accommodate 2 pages without scaling down the other pages.

### What/Requirements
Add toggle under the reading modes in reader settings.

**Comment by CrepeTF** [comment]
In reference to: https://github.com/Jays2Kings/tachiyomiJ2K/tree/doublePages

**Comment by Jays2Kings** [comment]
...why are you making a request for something that's 
1) [already done](https://github.com/Jays2Kings/tachiyomiJ2K/commit/d997ca9d23d7b5be5c41d3844d5771f0990a31e8)?
2) still in progress?
