### ISSUE TITLE
[Bug] reader is a bit Glitchy

### ISSUE THREAD

**Issue by SanOtaku09** [Jays2Kings/tachiyomiJ2K#709]
### Device information
* Tachiyomi version: 1.0.11
* Android phone & version: xiaomi k20 & Android 10

Reader is being glitchy when webtoons are using very lengthy pages 
for example:-
Some webtoons are Divided into 100's of pages
And when reading those reader works smoothly
But when using webtoons with single or very few and long pages reader lags

[Here a video of the reader](https://cdn.discordapp.com/attachments/657923584811073566/827282385347411978/Screenrecorder-2021-04-02-02-01-34-577.mp4)

**Comment by Jays2Kings** [comment]
If you have 32-bit color on, turning it off will help, aside from that there's not much that can be done about it
