### ISSUE TITLE
[Feature Request] An All Category/Menu

### ISSUE THREAD

**Issue by DuccinatorAlpha** [Jays2Kings/tachiyomiJ2K#71]
### Why/User Benefit/User Problem
This would make searching manga in a user's library much easier. It would when a user for example is recommending manga to someone. 

### What/Requirements
This can be implemented either as a default category(togglable in settings) or as a menu in the left sidebar. If it's implemented as the latter, it needs to be searchable and the basic filters should ideally work. Simple statistics like the number of manga and the number of chapters(read) would be helpful. A mass recommendation feature where you select manga by long pressing and it copies the links(like the share button) to the clipboard which can be pasted somewhere else would be welcome(but optional).

**Comment by CarlosEsco** [comment]
This something at one time i opened as a pull request in the main app and got shot down.   I would definitely prefer this.  The code main app has since been refactored.
https://github.com/inorichi/tachiyomi/pull/960

**Comment by GreatestFool** [comment]
Can't you just make a category and add everything to that as well as the category you were supposed to add it to?

**Comment by MxFlix** [comment]
Just adding everything manually to some sort of "All" category would be pretty cumbersome, could be easily forgotten, and there's no way of finding out if and on what manga it has been forgotten.

**Comment by Jays2Kings** [comment]
Added under filters as of 0.9.8
