### ISSUE TITLE
[Feature Request] Add Long-Press Menu Back in Manga Page

### ISSUE THREAD

**Issue by LenKiMo** [Jays2Kings/tachiyomiJ2K#712]
### Why/User Benefit/User Problem
In 1.0.10, when reading manga, user can share the page by long press the page and using the share option in pop-up menu.
This share feature will add Manga title and page automatically, so it's very convenient for sharing, and others can know where this page from without ask.
1.0.11 delete this feature making share certain page harder than before, and can't add information about the manga and chapter information.  
Please consider add this feature back, or give option to enable/disable it.

### What/Requirements
Like 1.0.10, when reading manga in certain page, by long press will pop up a new menu to Save or Share this page. When sharing this page, app would adding Manga's name and chapter text together.

**Comment by Jays2Kings** [comment]
It's already added back for the next update a1e69e7194eb4bfe127be26158c5260dc5d25ffd
