### ISSUE TITLE
[Bug] Cover not showing on notification bar update

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#713]
### Device information
* Tachiyomi version: 1.0.11
* Android phone & version: Note9 Android 10

## Steps to reproduce
1. Update library
2. Look at update from notification bar

### Expected behavior
Show manga cover with the title and chapter

### Actual behavior
Does not show manga cover

### Other details
This has happened to an older version of j2k in the past too

**Comment by Jays2Kings** [comment]
Is this still happening on 1.0.13?

**Comment by vipzzx** [comment]
Yes still happening in 1.0.13

**Comment by vipzzx** [comment]
Looks like it's not happening anymore.... Should I close this for now and open another issue if it happens again?

**Comment by Jays2Kings** [comment]
Sure if it's not happening anymore you can leave a comment here and we can reopen

**Comment by vipzzx** [comment]
Well it's still happening. ![Screenshot_20210414-052829_TachiyomiJ2K.jpg](https://user-images.githubusercontent.com/59638889/114706451-f9b1d080-9cf6-11eb-85fa-90eaa27b7331.jpg)

**Comment by vipzzx** [comment]
It is happening again
