### ISSUE TITLE
[Bug] duplicate chapter for some source/manga

### ISSUE THREAD

**Issue by Riztard** [Jays2Kings/tachiyomiJ2K#714]
### Device information
* Tachiyomi version: 1.0.11 and 1.0.9
* Android phone & version: redmi 8 android 10

## Steps to reproduce
1. open flame scans
2. search `everlasting god of sword`
3. open it

### Expected behavior
chapter list just like the site

### Actual behavior
chapter list got duplicated

### Other details
<table>
<tr>
	<td>J2K
	<td>Stable
	<td>Preview
<tr>
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/828519762035343400/Screenshot_2021-04-05-13-40-54-890_eu.kanade.tachiyomi.j2k.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/828519762404311040/Screenshot_2021-04-05-13-40-50-548_eu.kanade.tachiyomi.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/828519761591140393/Screenshot_2021-04-05-13-41-12-447_eu.kanade.tachiyomi.debug.jpg">
</table>

**Comment by MCSilverMask** [comment]
I dunno if this helps or just different, but somw sources like MangaPark may have the same manga title from diffrent scanolations (diffrent translation inturpitation, or volum scans vs weekly scans)

**Comment by e-shl** [comment]
[RU] Mangalib also
![2021-04-07 21-45-20](https://user-images.githubusercontent.com/35057681/113903833-d95fae80-97ea-11eb-8ede-9a4e8fb2e9a1.PNG)
![2021-04-07 21-44-43](https://user-images.githubusercontent.com/35057681/113903840-d9f84500-97ea-11eb-9a1a-18556be7d459.PNG)
