### ISSUE TITLE
[Feature Request] Please re-add press and holding a page to save it

### ISSUE THREAD

**Issue by GreatestFool** [Jays2Kings/tachiyomiJ2K#717]
### Why/User Benefit/User Problem
Before the newest update, it was possible to save images by merely clicking and holding to save images, which is much faster than it is now. Now you have to click on the page to get up the full menu, then press the three dots up in the right corner and then press save. It might not seem like a lot, but before, it was still faster even with the occasional accidental page flip.

It is a nice way to save parts that you want to remember, since bookmarks are more or less useless as they are considering they do not transfer between source migrations (which could simply be done by enabling a setting to make the end user do so manually).

### What/Requirements
Press and hold the center of the page, or something like that, to save the image.

**Comment by CarlosEsco** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/712
