### ISSUE TITLE
[Feature Request] Split long webtoon images (from upstream)

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#718]
The PR is a WIP but yoink it as soon as it's finished

https://github.com/tachiyomiorg/tachiyomi/pull/4791

**Comment by 29988122** [comment]
I'd also like to know if https://github.com/tachiyomiorg/tachiyomi/pull/4252
is compatible to J2K, as I have a ton of early scan which are double faced, this hard to read on cellphone.
