### ISSUE TITLE
[Feature Request] Add Midnight Dusk dark theme (from SY)

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#719]
### Why/User Benefit/User Problem
Tachiyomi blue looks too bland and boring, the Midnight Dusk theme is 🔥 🔥

**Comment by joseph619** [comment]
the pull request for reference

https://github.com/jobobby04/TachiyomiSY/pull/183

**Comment by Mitia99** [comment]
@joseph619 How about a complete customizable app theme?It will be more rich

There will be:
_custom accent color
_custom app background color
_custom top and bottom bar color.

**Comment by joseph619** [comment]
adding a single theme is easier than creating theme engine

**Comment by IshaqIqbalRick** [comment]
Not everybody has same preference so it more like it👌

**Comment by Mitia99** [comment]
@IshaqIqbalRick 
Yes,personnaly I prefer the amoled black and blue theme rather than this midnight one(a black and red will be better in my opinion)That's why I said that customizable will be pretty cool.

**Comment by IshaqIqbalRick** [comment]
@Mitia99
Bro same here in my oppion black and red is the best color combination😍

**Comment by CarlosEsco** [comment]
This isn't a chat stop using it like it

**Comment by Jays2Kings** [comment]
Full customization isn't going to happen without a full rewrite (which no), so we'll stick to a single theme
