### ISSUE TITLE
[Bug] Downloaded sources do not check if there are already existing source folders with different capitalization and create unusable duplicates

### ISSUE THREAD

**Issue by GreatestFool** [Jays2Kings/tachiyomiJ2K#720]
### Device information
* Tachiyomi version: v1.0.11
* Android device: Samsung Galaxy S5e, SM-T720
* Android version: v10, kernel v4.9.186-20003519; OneUI 2.5

## Steps to reproduce
1. Download chapter locally
2. Open chapter after download complete

### Expected behavior
Chapter pages should load faster than downloading each page from the internet as you're reading.

### Actual behavior
Pages load about as slowly as reading it on an internet connection as opposed to from a local file. It takes about 2-4 or 5 seconds for each page to load.

### Other details
It seems to happen regardless of if the app has been open for a while and regardless of how soon it was downloaded. For example, I downloaded a chapter from One Punch Man was newly released, but pages still load slowly. Likewise, the problem also occurs on chapters that have been downloaded for a long time.

This has not happened in the past, but recently this slow page load has started appearing. It may be something that comes from an update, I can't say for certain.

**Comment by CarlosEsco** [comment]
Are you downloading to an sd card?

**Comment by GreatestFool** [comment]
I am, but this should not have much of an effect considering it has worked perfectly fine for years, unless Android has once again mucked something up on their side of course.

**Comment by CaptainHalflife** [comment]
Which source are you using ? If its Mangasee they change the name recently so go to your download folder and make sure if it written "MangaSee"

**Comment by CarlosEsco** [comment]
Easiest way to test.  Move the downloads off sd card. Force close app.  Then see if loads instantly

**Comment by GreatestFool** [comment]
> Which source are you using ? If its Mangasee they change the name recently so go to your download folder and make sure the folder name is "MangaSee"

Thanks for the heads up @CaptainHalflife, that appears to have been the problem. Every time a new chapter was downloaded, a "MangaSee (EN)" folder was created, but due to "Mangasee (EN)" existing it appended a number on the end like "(1)". This let it successfully download the chapter, but when opening it, the application can't find it and defaults to loading the chapter like normal. Amusingly enough, after deleting all but one, I found you apparently can't rename a folder to the same name with different capitalization- talk about Android being stupid.

Anyway, not sure if this is proper decorum, but hopefully this is nothing too disastrous. @Jays2Kings, there should probably be some sort of logic to check for this. If a source is requesting a specific folder name that is case-sensitive, the application should also check if there are any folders with the same name with different capitalization and either rename that or move the contents out into a temporary location and then into the new folder once the old is deleted. I ended up having to rename the folder to something else and then to the correct one, so that may work, but I am not familiar with Android so this is probably something you'd be able to answer better I think.

**Comment by CaptainHalflife** [comment]
I think its not the correct place for this kind of issue. Do it on the tachiyomi extention github

**Comment by arkon** [comment]
@CaptainHalflife This is an app issue, not an extension issue.

**Comment by CaptainHalflife** [comment]
Ok my bad

**Comment by Jays2Kings** [comment]
Fixed in f9a724ee7b9d89b26cb4d2c91363a0954e5b1cf6
