### ISSUE TITLE
[Feature Request] recommendation and extension latest option from SY

### ISSUE THREAD

**Issue by IshaqIqbalRick** [Jays2Kings/tachiyomiJ2K#721]
### Why/User Benefit/User Problem
Help us to know similar kinds of manga.....
![Screenshot_2021-04-11-00-49-45-968_eu.kanade.tachiyomi.sy.jpg](https://user-images.githubusercontent.com/72049567/114281394-f650e780-9a5f-11eb-8aac-1bc587943f85.jpg)
### What/Requirements
![IMG_20210411_002539.jpg](https://user-images.githubusercontent.com/72049567/114280948-7590ec00-9a5d-11eb-88aa-7458aac84b80.jpg)
But it would be much better if it(the recommendation) weren't here..

**Comment by Jays2Kings** [comment]
Closing this because I have different plans for latest, and sy's implmentation wouldn't work in this ui
And just straight up not doing recs
