### ISSUE TITLE
Options in Recents not working properly.

### ISSUE THREAD

**Issue by ShaddaiSchelin** [Jays2Kings/tachiyomiJ2K#726]
**App version:**
1.0.13
**Android version:**
10
**Issue/Request:**
The new "options" for recents don't seem to work properly. Once I toggle the "history" or "updates" it wouldn't show anything. Sometimes it would display, but then once I toggle the other options nothing happens.
Now I can see only the four most recent updates and not all of the list.
Reverting back to version 1.0.11 for the time being.

Thanks for such a great app.
Cheers

**Comment by Jays2Kings** [comment]
Can you create a backup of your library and either post it here, or dm me on discord it?

There's not enough info here to try to solve this issue

**Comment by ShaddaiSchelin** [comment]
> Can you create a backup of your library and either post it here, or dm me on discord it?
> 
> There's not enough info here to try to solve this issue

Sure man here ya go

[tachiyomi_2021-04-12_11-00.proto.gz](https://githu#718 .com/Jays2Kings/tachiyomiJ2K/files/6295115/tachiyomi_2021-04-12_11-00.proto.gz)

**Comment by ShaddaiSchelin** [comment]
> Can you create a backup of your library and either post it here, or dm me on discord it?
> 
> There's not enough info here to try to solve this issue

[tachiyomi_2021-04-12_11-00.proto.gz](https://github.com/Jays2Kings/tachiyomiJ2K/files/6295162/tachiyomi_2021-04-12_11-00.proto.gz)

Here ya go,
Cheers
