### ISSUE TITLE
[Bug] Long-Press to Clear History Does Not Work

### ISSUE THREAD

**Issue by LenKiMo** [Jays2Kings/tachiyomiJ2K#727]
### Device information
* Tachiyomi version: 1.0.13
* Android phone & version: 10

## Steps to reproduce
1. Enable clear history button in Recent page
2. Long press the clear history button

### Expected behavior
Long press should back a real action, like confirm to clear history, or clear all history for this manga entirely.

### Actual behavior
Only raise a "Reset chapter hisory" toast

### Other details

* I am not using English interface so the text of the button/toast might be not match the original.

**Comment by Jays2Kings** [comment]
There is no bug here, long-pressing buttons pop up a tool tip on what a button does. You'd want to short tap on it instead.
