### ISSUE TITLE
[Bug] Library Updates Rearranging even after being read

### ISSUE THREAD

**Issue by SecretiveBastard** [Jays2Kings/tachiyomiJ2K#729]
Earlier, I tried updating to the latest version of J2K but still the same problem occured and in addition, there have been problems in my Recents Tab as mentioned from the one who posted a similar issu earlier so I reverted it to 1.0.11 to have a more stable interface.

### Device information
* Tachiyomi version: 1.0.11
* Android phone & version: Samsung J7 Pro 2017; Android Pie

## Steps to reproduce
1. Open Recents Tab
2. Click View All Updates

### Expected behavior
The library should be updated either alphabetically or last updated as selected from the settings while not including the previous library updates which I set hourly. 

### Actual behavior
The updates from the same series got connected to its recent update, breaking the order of how it should have been updated especially when the chapters have aready been read.

### Other details
All the updates got scrambled up within the day making it unorganized and it randomly occurs every library update. I tried both setting the library update order to alphabetically and last updated but the problem just worsened.

First library Update After reading all the updates:
![Screenshot_20210412-000708_TachiyomiJ2K](https://user-images.githubusercontent.com/81961756/114406667-4ce23100-9bda-11eb-9493-7939734b7cde.jpg)

Second updates and until now: 
![Screenshot_20210412-215645_TachiyomiJ2K](https://user-images.githubusercontent.com/81961756/114406798-671c0f00-9bda-11eb-946d-478d3bd3c662.jpg)

**Comment by CarlosEsco** [comment]
Posting bugs for old versions of the app is not something that will be addressed
