### ISSUE TITLE
[Feature Request] add detailed description in multi source extensions

### ISSUE THREAD

**Issue by MakuSensei** [Jays2Kings/tachiyomiJ2K#73]
Hello, I wanted to propose that within the menu of an extension I have the information of the multiple sources that you have. 
This is because since the last update they show obsolete extensions. Where one of the ones I use is DoujinHentai (Spanish)
While trying to migrate to another source, it occurred to me to look at the Excel document where it details the corresponding sources in each extension, to see if by chance DoujinHentai was in another Extension and there I found it in all.madara 
That's how it occurred to me to ask for some way to simplify that detail to make it easier to find. Since if a previous extension is also in another multi-source extension nobody notices. There is nothing in sight of the user. That's why I ask for something like this or any viable alternative to provide this information. Thanks and regards from Argentina.

**Comment by Jays2Kings** [comment]
This isn't possible from my end, this request is better redirected at the base tachiyomi or tachiyomi-extensions
