### ISSUE TITLE
[Feature Request] Ability to swipe left/right in recents tab

### ISSUE THREAD

**Issue by hjdrm** [Jays2Kings/tachiyomiJ2K#730]
---

### Why/User Benefit/User Problem
(explain why this feature should be added)
Ability to swipe left/right in recent page to seamlessly switch from "grouped, all, history, and updates" tabs. So instead of clicking the aforementioned tabs, users  can just swipe left or right to switch  from history to updates.

### What/Requirements
(explain how this feature would behave)
When you swipe left or right in recents page, it takes you to different tab (i.e. from history tab to updates tab or vice versa)

**Comment by Jays2Kings** [comment]
no they're not tabs

**Comment by CrepeTF** [comment]
@Jays2Kings make them tabs
