### ISSUE TITLE
[Feature Request] Category specific Reading Mode

### ISSUE THREAD

**Issue by volkanturkut** [Jays2Kings/tachiyomiJ2K#731]
I use tachiyomij2k to read comics and manga and I have 2 categories for those.  but since manga and comics don't have the same reading mode, I just use it either from right to left or left to right.  Can you add a category-specific reading mode for this?

**Comment by joseph619** [comment]
You can manually add comics tag to your comics, this way they will automatically switch to the proper reading mode

**Comment by volkanturkut** [comment]
> You can manually add comics tag to your comics, this way they will automatically switch to the proper reading mode

I added comics tag to a comic, but the reading mode did not change to left to right

**Comment by volkanturkut** [comment]
> You can manually add comics tag to your comics, this way they will automatically switch to the proper reading mode

wow i didn't know that, thanks

**Comment by volkanturkut** [comment]
> You can manually add comics tag to your comics, this way they will automatically switch to the proper reading mode 
not worked :(

**Comment by volkanturkut** [comment]
> You can manually add comics tag to your comics, this way they will automatically switch to the proper reading mode 

Not worked :(
