### ISSUE TITLE
[Feature Request] crop border button request

### ISSUE THREAD

**Issue by jafri-jahan-s** [Jays2Kings/tachiyomiJ2K#732]
---

### Why/User Benefit/User Problem

Since webtoon type series breaks when crop is on I have to **constantly** switch the crop feature on and off depending on if I read a 'manga' or a webtoon type series and that's kind of annoying.
( I use 'webtoon' viewer for manga as well and probably more people also) 

### What/Requirements

a button for crop in the bottom bar to toggle on or off crop and remember its position. This is implemented in the original tachiyomi in the latest release.
![Screenshot_20210413-111908__01.jpg](https://user-images.githubusercontent.com/56589554/114505687-61f8a780-9c4e-11eb-984f-653ca2f41a00.jpg)

Or consider issue#621 which is a similar request. But I think the button will be better.

**Comment by Jays2Kings** [comment]
Not sure why you wouldn't just use continuous vertical for manga instead, but there's space for it in webtoon mode anyway

**Comment by Jays2Kings** [comment]
Done in https://github.com/Jays2Kings/tachiyomiJ2K/commit/cdc7f64637ffef9a853f3eee31ad9ade03ff39f2

**Comment by jafri-jahan-s** [comment]
> Done in https://github.com/Jays2Kings/tachiyomiJ2K/commit/cdc7f64637ffef9a853f3eee31ad9ade03ff39f2

Thanks 👍

**Comment by jafri-jahan-s** [comment]
> Not sure why you wouldn't just use continuous vertical for manga instead since that obeys the crop for paged viewer, but there's space for it in webtoon mode anyway

😅
