### ISSUE TITLE
[Feature Request] Bookmark page

### ISSUE THREAD

**Issue by Mitia99** [Jays2Kings/tachiyomiJ2K#734]
### Why/User Benefit/User Problem
My issue is that some sources packed chapters(+100) and open bookmarked packed ain't really convenient

### What/Requirements
Bookmark page inside chapter![AddText_04-13-05.16.59.jpg](https://user-images.githubusercontent.com/56766778/114567621-165cf280-9c7c-11eb-993f-57e8ce32125d.jpg)

**Comment by joseph619** [comment]
Duplicate of #630
