### ISSUE TITLE
[Feature Request] Add a sorting feature to show chapters that are not downloaded

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#736]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Some sources have missing chapters so when I download the chapters that are available I have to manually scroll through hundreds of chapters to see the chapters that are not downloaded so I can download them on another another source 

### What/Requirements
(explain how this feature would behave)
1) go to manga
2) click on the filter
3) click on show downloaded chapter once will a show ✔️ and click on it again it will show ✖️ and you will be able to see the chapters that are not downloaded ( I also suggest you do this for the read and unread)

**Comment by Jays2Kings** [comment]
Why not just tap on download > all?

**Comment by FireNation323** [comment]
> Why not just tap on download > all?

The problem is that there are some chapters that I cannot download so I use another source to read those chapters and I just want a way to see what those chapters are without scrolling through hundreds of chapters

**Comment by FireNation323** [comment]
> Why not just tap on download > all?

The chapters won't download and having to go back and forth between downloads and Library to see the chapters that can't be downloaded is not ideal and not efficient
