### ISSUE TITLE
[Bug] cannot restore backup

### ISSUE THREAD

**Issue by laqyx** [Jays2Kings/tachiyomiJ2K#737]
Android 11, MIUI 12.0.2
Xiaomi Poco F3
when I try to restore a backup it simply doesn't work, here's a short video: https://youtu.be/fNFnr_XuUnc

**Comment by Jays2Kings** [comment]
Can you post your backup either here or message me on Discord

**Comment by laqyx** [comment]
So I've solved this issue thanks to the tachiyomi discord, it's related to MIUI. You have to enable MIUI optimizations in developer options for backup restore to work. I don't know how it is related, but that fixes it for me. Maybe add a disclaimer somewhere in the settings if the app detects that you are using MIUI would help some people that will face the same issue.
