### ISSUE TITLE
[Bug] In reader menu settings missing

### ISSUE THREAD

**Issue by RingingInMyEars** [Jays2Kings/tachiyomiJ2K#738]
### Device information
* Tachiyomi version: v1.0.13
* Android phone & version: OnePlus 7 Pro: Android 10, Samsung S6 Tablet: Android 10

## Steps to reproduce
1. Open a chapter and bring down the top menu
2. The reader settings are missing

### Expected behavior
In the previous version there is a button that will allow for settings to come up for the individual chapter that is currently being read.

### Actual behavior
There is no button so there is no way to bring up the bottom chapter menu.

### Other details
See attachments between version 13 (Missing in red box) and version 11 (Present in red box)
![Screenshot_20210414-095724_TachiyomiJ2K](https://user-images.githubusercontent.com/82531044/114750236-4ae7b180-9d43-11eb-8a21-8f9e8ca4b20b.png)
![Screenshot_20210413-235901](https://user-images.githubusercontent.com/82531044/114750237-4b804800-9d43-11eb-8e1b-eb72aa4c876d.jpg)

**Comment by Jays2Kings** [comment]
When you tap on the screen does the bottom bar not show?

**Comment by RingingInMyEars** [comment]
It does not. Tapping the middle of the screen pops the top bar where it says the title and chapter number. I can try on my tablet after I reinstall v13. I reverted to v11 last night.

**Comment by Jays2Kings** [comment]
If you're on discord, send me a friend request because I dont have a oneplus and trying to mock it works fine

**Comment by Omicroon** [comment]
I have the same bug on my Samsung galaxy tab. I got the menu to appear two times (one time I got it to work when I switched to horizontal mode), but most of the times it's impossible to get up.

**Comment by Jays2Kings** [comment]
Try this test version of the app, it should be fixed with this, but let me know
[tachij2k-test.zip](https://github.com/Jays2Kings/tachiyomiJ2K/files/6313617/tachij2k-test.zip)

**Comment by RingingInMyEars** [comment]
It works now on both my devices. I did a complete uninstall and reinstall rather than just upgrading from v11 if that makes a difference.

**Comment by Jays2Kings** [comment]
closing this since this is stale now with the new update, comment back if it issue still happens on 1.0.15
