### ISSUE TITLE
[Feature Request] Catalogue search sorting/filtering

### ISSUE THREAD

**Issue by WH1T3No1SE** [Jays2Kings/tachiyomiJ2K#74]
### Why/User Benefit/User Problem
While searching first time for a manga we don't see amount of chapters it has available, that makes search for source what is up to date tedious as you open and close results to check what one is most up to date.
### What/Requirements
**- Option 1:**
Catalogue search would behave more similar to auto migration for one manga, will go down the list of sources in search which one has most chapters and present result

**- Option 2:**
Sources in catalogue search could have option be sorted not alphabetically but by what source has most chapters at the top and least chapters at the bottom.

**- Option 3:**
Just show amount of chapters as a plaque on manga title card on search

**Comment by CarlosEsco** [comment]
#57

**Comment by joseph619** [comment]
Also #21 , this won't likely be added

**Comment by Jays2Kings** [comment]
As the issues mentioned above say, this isn't possible
