### ISSUE TITLE
[Bug] Updates tab doesn't show multiple updates for same manga, only the most recent

### ISSUE THREAD

**Issue by Husbug** [Jays2Kings/tachiyomiJ2K#740]
### Device information
* Tachiyomi version: 1.0.13
* Android phone & version: Honor View 10,  Android 10

## Steps to reproduce
1. First step: Find manga with multiple chapters released at once
2. Second step: Go to 'Updates' tab in 'Recents'

### Expected behavior
Multiple chapters show up

### Actual behavior
Only the latest chapter showed up

### Other details
The notification of updated manga shows multiple new chapters released, but not the Updates tab
![Screenshot_20210415_223345_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/74500093/114941225-c9734a80-9e3a-11eb-917e-bf7e8e946562.png)
![Screenshot_20210415_223321_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/74500093/114941228-ca0be100-9e3a-11eb-93fc-393183d76833.png)

**Comment by FireNation323** [comment]
I have been having this glitch on a lot of my manga too

**Comment by FireNation323** [comment]
I can't even access updates in the recents tabs T_T

**Comment by FireNation323** [comment]
> I can't even access updates in the recents tab T_T

**Comment by Jays2Kings** [comment]
Both are already addressed for the next update
