### ISSUE TITLE
Significantly slower loading

### ISSUE THREAD

**Issue by R-N** [Jays2Kings/tachiyomiJ2K#742]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 1.0.13

**Android version:** 11

**Issue/Request:** After updating to 1.0.13, it takes a long time to load the app. Maybe around a minute. By loading I meant the first one where it only shows tachiyomi logo. Previously it only took few seconds.

**Steps to reproduce (if applicable)**

 1. Open the app

**Other details:** The updates tab is empty for around 10 seconds after the loading I mentioned. The old updates tab (prior to 1.0.13) would've had contents almost immediately.

**Comment by joseph619** [comment]
Is it still slow after 1.0.15 update?

**Comment by R-N** [comment]
Sorry for the very, very late response. I didn't try 1.0.15 since I just switched to TachiyomiSY. I really didn't expect it to be so unbearable. 

I'll just close this issue.
