### ISSUE TITLE
[Bug] updates not in proper order

### ISSUE THREAD

**Issue by vipzzx** [Jays2Kings/tachiyomiJ2K#743]
* Tachiyomi version: 1.0.13
* Android phone & version: note 9, Android 10

## Steps to reproduce
1. Go to recent
2. Go to updates tab

### Expected behavior
Update should go from newest to oldest starting from the top

### Actual behavior
Update time and dates not in order

### Other details
![Screenshot_20210416-202038_TachiyomiJ2K.jpg](https://user-images.githubusercontent.com/59638889/115096116-e028a880-9ef1-11eb-99f7-b5ef3bc5de6c.jpg)

**Comment by Jays2Kings** [comment]
"Fixed" in new release
