### ISSUE TITLE
[Feature Request] Reader menu changes

### ISSUE THREAD

**Issue by DishankJ** [Jays2Kings/tachiyomiJ2K#746]
### What/Requirements
1. The chapter list icon from the reader's bottom menu can be removed and a **down arrow beside the chapter title and chapter number can be put to access the chapters list**.
2. Custom filter menu icon can be replaced where the chapters list icon used to be for quickly turning on and off filter and the ease of use.

**Comment by CarlosEsco** [comment]
I feel people are using the chapter list more than changing filters.  Moving the chapter list button to the top seems to be moving a more frequently used icon to the top.  

If anything I would say make the sheet have 4 buttons, but even then are you using the color filter so often that two button taps is too many?

**Comment by Jays2Kings** [comment]
I'm closing this because number 1 is an option for the next release, and point 2 is pointless. 

Like Carlos said it's already 2 button taps away, there's a preview button of the changes you make so you don't need to constantly in and out of filter settings.
