### ISSUE TITLE
Cache is closed error while downloading new chapter

### ISSUE THREAD

**Issue by m-a-hannan** [Jays2Kings/tachiyomiJ2K#747]
App version: 1.0.13

Android version: 8.0.0

Issue: Cache is closed error while downloading new chapter

Other details:
I am getting "Cache is Closed" error while trying to download new chapter, I am getting this error from all the sources i am currently using, when it happens download gets paused and to start the download again sometime i have to close the app and re-open, sometime changing the download order fixes it but after downloading 2/3 chapter I get the error again.

**Comment by joseph619** [comment]
is this still happening?

**Comment by joseph619** [comment]
Update your app, this should be fixed in latest update

**Comment by m-a-hannan** [comment]
It got fixed after updating to latest version.
