### ISSUE TITLE
[Feature Request] Use different strings for the different trackers

### ISSUE THREAD

**Issue by she11sh0cked** [Jays2Kings/tachiyomiJ2K#75]
### Why/User Benefit/User Problem
Anilist has the following status modes:
- Reading
- Plan to read
- Completed
- Rereading
- Paused
- Dropped

Tachiyomi has the following status modes for the anilist tracker (in corresponding order):
- ✔️ Reading
- ✔️ Plan to read
- ✔️ Completed
- ❌ Re-reading
- ❌ On hold
- ✔️ Dropped

As you can see by the ones marked with "❌" some of them don't line up.

### What/Requirements
I'm guessing all trackers use the same strings and that's why these don't line up.
If so than there would need to be different strings for the different trackers.

**Comment by Jays2Kings** [comment]
Added as of 0.9.75
