### ISSUE TITLE
[Feature Request] Custom Extension Repositories

### ISSUE THREAD

**Issue by Xeiv** [Jays2Kings/tachiyomiJ2K#753]
### Why/User Benefit/User Problem
It will allow people to get extensions from custom repositories and not just the official one

### What/Requirements
The ablity to add custom repositories in the settings, probably under Settings>Sources>Extensions.
It's currently in TachiyomiSY so that could probably be imported (In Settings>Browse>Extensions>Edit repos)

**Comment by ArjixWasTaken** [comment]
Nice idea!
+1

**Comment by Xeiv** [comment]
Closing this as it's been added.
