### ISSUE TITLE
[Feature Request] please support x86!

### ISSUE THREAD

**Issue by AimerEGOIST** [Jays2Kings/tachiyomiJ2K#754]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (latest J2K is v1.0.13)
- I will not repeat a request for a feature already requested
- If this is an request for an extension/source, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Why/User Benefit/User Problem
(explain why this feature should be added)

### What/Requirements
(explain how this feature would behave)

**Comment by AimerEGOIST** [comment]
I have a x86 pad(Android 5) and I cannot install the app on it.

**Comment by arkon** [comment]
Your architecture has nothing to do with it.

> TachiyomiJ2K is a free and open source manga reader for Android 6.0 and above.
