### ISSUE TITLE
[Bug] Name of the comics are getting chopped off.

### ISSUE THREAD

**Issue by PrithirajN** [Jays2Kings/tachiyomiJ2K#755]
### Device information
* Tachiyomi version: 1.0.13
* Android phone & version: 8.1.0

## Steps to reproduce
1. Open the library

### Expected behavior
The name of the comics should show properly without getting chopped off.

### Actual behavior
The name of the comics of the comics are getting chopped off.

![Screenshot_20210419_211912.jpg](https://user-images.githubusercontent.com/60390549/115267232-92f94080-a156-11eb-8cc7-4950577d4f82.jpg)

**Comment by joseph619** [comment]
Does this also happen on 1.0.15?

**Comment by PrithirajN** [comment]
> Does this also happen on 1.0.15?

yes.

**Comment by PrithirajN** [comment]
> Seems to be a side effect of not using the default font.

Is there an option to change to default font?

**Comment by PrithirajN** [comment]
Changing the fonts helps a bit but I couldn't find a single font which show but the name of the comic and author properly.
![Screenshot_20210420_223749.jpg](https://user-images.githubusercontent.com/60390549/115436839-0ec3bd80-a229-11eb-9b0c-2c1d6d444113.jpg)

**Comment by Caio99BR** [comment]
Should be fixed on #1198

**Comment by Jays2Kings** [comment]
closing this since there hasnt been an update from OP
