### ISSUE TITLE
[Bug] Trying to open any chapter crashes the app

### ISSUE THREAD

**Issue by weebkent** [Jays2Kings/tachiyomiJ2K#757]
### Device information
* Tachiyomi version: 1.0.14
* Android phone & version: Samsung Galaxy J2 Prime/6.0.1

## Steps to reproduce
1. Open chapter

### Expected behavior
The reader opens

### Actual behavior
The app crashes

### Other details
There's also noticable lag than the previous version where the app is unresponsive when opening manga for a few seconds

**Comment by Jays2Kings** [comment]
Install 1.0.15
