### ISSUE TITLE
[Feature Request] smb reader and storage]

### ISSUE THREAD

**Issue by Gweenteaneko** [Jays2Kings/tachiyomiJ2K#758]
[Feature Request] smb reader and storage]

(When you have fast internet, good powered smartphone downloading manga here and there those will pile up in your storage in no time. With that tons of data in your storage, the performance of rom will takes its toll in frequent scrubbing

In solution smb shared folder will solve the lack of storage 

(In the current app there is a (local source) which is linked in directory of tachiyomi in its folder contains the manga folders that you've "move into it". 
Then Adding smb (folder) will give more flexibility and option, capability to move manga after download into there)

**Comment by CarlosEsco** [comment]
Why not just use an extension that supports your computers manga.

Mango, lanraragi, komga

**Comment by Gweenteaneko** [comment]
I have no know how to use that

**Comment by CarlosEsco** [comment]
They are pretty easy to set up and solve your problem now.  Instead of hoping jay adds niche support for smb

**Comment by Gweenteaneko** [comment]
Ok i will try for how it works for now. 
I just always use smb when i watch anime in vlc's smb support just looking same function for manga reading

**Comment by Gweenteaneko** [comment]
Mango, komga is hard to set-up its also involve some coding and minimal tutorial for those cant code,
I install lanraragi because it has no coding with more tutorial but it itself is useless
manga must be in archive state in able to use.
