### ISSUE TITLE
[Feature Request] Sort the sources settings by extension

### ISSUE THREAD

**Issue by DuccinatorAlpha** [Jays2Kings/tachiyomiJ2K#76]
### Why/User Benefit/User Problem
When installing multiextensions, it's a pain to disable sources by trying to find all sources alphabetically.

### What/Requirements
 Sorting sources should be by extensions and subsorted alphabetically ideally. It could also be done in a way that each extension has its own menu which can be expanded to reveal its sources.

**Comment by joseph619** [comment]
Sorting for sources already exists, the enabled ones are grouped together. The search exists so that you don't have to go though all of them.

**Comment by Jays2Kings** [comment]
Like @joseph619 said, you can sort by enabled, so when you install a multi they will all show up on the top. Sources don't save the extension apk they come from so sorting by that wouldn't be possible
