### ISSUE TITLE
Submit the app to fdroid??

### ISSUE THREAD

**Issue by bluecheeser** [Jays2Kings/tachiyomiJ2K#764]

**Comment by CarlosEsco** [comment]
Considering the normal tachi got taken down from fdroid. This will probably be a no too.

**Comment by bluecheeser** [comment]
> Considering the normal tachi got taken down from fdroid. This will probably be a no too.  
Tachiyomi is still on fdroid![IMG_20210422_062029.jpg](https://user-images.githubusercontent.com/81776134/115639689-d90afb80-a332-11eb-8fca-0fee1e53341c.jpg)

**Comment by CarlosEsco** [comment]
Interesting I figured they took it down 

https://gitlab.com/fdroid/admin/-/issues/195

**Comment by CarlosEsco** [comment]
Either way their is no benefit to using fdroid as a repo owner when this app already has auto updates.
