### ISSUE TITLE
[Feature Request] add independent filters in each category

### ISSUE THREAD

**Issue by MakuSensei** [Jays2Kings/tachiyomiJ2K#77]
I would like to propose that different filters be available in each category. For example, in one category of read sleeves it remains visible while in other categories only show the no Read

Greetings from Argentina

**Comment by Jays2Kings** [comment]
Sorry but this won't happen, I'm not sure how to implement that in the first place, and it would add too much complexity to categories (which there already is thanks to drag and drop sorting and more)
