### ISSUE TITLE
[Feature Request] More search features/filters

### ISSUE THREAD

**Issue by Murasakinoe** [Jays2Kings/tachiyomiJ2K#770]
Adding more filters and search options, I feel, would be a great addition to make; 

i.e. Being able to filter out Manga that is already in your library. This would help with finding new manga that you haven't read/seen before.

i.e. The ability to blacklist certain tags. I know depending on the source/extension you get many different filters and search options, but I don't think I've seen one that can get rid of manga of the genre one doesn't want to see. 

i.e. Probably the hardest one to implement, but for more universal search options. The difference in search options is pretty vast amongst the different sources. Mangakakalot has only 3 search options, while MangaDex has such a wide variety. 

As for how it'll be implemented, I don't quite know how it was programmed, but I can't imagine it'll be too hard? Maybe? There is already a check in the extensions that show if a manga is in your library or not, could possibly extend off of that or use that as some sort of signal. And as for the tags, every manga seems to have tags linked to them, I just thought it could some how filter using those.

**Comment by CarlosEsco** [comment]
1.  Possible to do, that's up to jay if he wants to add since it already adds a badge to the entry.
2.  Not happening, filters in search are based off what the websites themselves can do.  If a site can't filter by tags, that's not something we can add.  If a site does offer it and the extension is missing it. Open an issue on tachiyomi extensions repo

**Comment by asdkant** [comment]
@CarlosEsco a lot of sources provide tags, wouldn't it be possible to implement tag blacklist with a notice saying "this depends on tags being available in the sources"?
