### ISSUE TITLE
[Bug] Randomly closes when viewing Manga

### ISSUE THREAD

**Issue by qwerty017** [Jays2Kings/tachiyomiJ2K#776]
### Device information
* Tachiyomi version: 1.0.15
* Android phone & version: HUAWEI/SHT-W09 8.0.0

## Steps to reproduce
1. Open Manga and start reading

### Expected behavior
Nothing should happen.

### Actual behavior
Sometimes crashes after a few pages, a few chapters, or if I just leave it on a page for a while.
App does not crash all the way, but only to the last open tab.

### Other details
Attached debug logs from yesterday and today.
[tachiyomi_crash_logs (1).txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/6407282/tachiyomi_crash_logs.1.txt)
[tachiyomi_crash_logs.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/6407283/tachiyomi_crash_logs.txt)

**Comment by joseph619** [comment]
Does it still happen on latest update?

**Comment by qwerty017** [comment]
Nope. It has stopped happening. Thanks for fixing whatever caused it.
