### ISSUE TITLE
[Bug] Little visual glitch on opening most option settings

### ISSUE THREAD

**Issue by dustter** [Jays2Kings/tachiyomiJ2K#78]
### Device information
* Tachiyomi version: 0.9.7
* Android phone & version: Samsung Galaxy Note 8, Android 9.0

## Steps to reproduce
1. Go to Settings
2. Open pretty much any setting in there
3. Go to any setting that opens up the pop up window

### Expected behavior
The visual glitch shouldn't show up at all.

### Actual behavior
It shows up upon opening, BUT dissapears after a few seconds. Screenshots for examples.
![Screenshot_20200120-010041_Tachiyomi](https://user-images.githubusercontent.com/54286558/72690889-e4b0b680-3b20-11ea-863d-a7ae44d7ad21.jpg)
![Screenshot_20200120-010057_Tachiyomi](https://user-images.githubusercontent.com/54286558/72690890-ea0e0100-3b20-11ea-96cd-9514798682a6.jpg)
![Screenshot_20200120-010207_Tachiyomi](https://user-images.githubusercontent.com/54286558/72690893-eb3f2e00-3b20-11ea-835b-a3b6c3342f36.jpg)

### Other details
Doesn't happen say on Dev. Think it's the new rounded corners implementation that did it.

**Comment by Jays2Kings** [comment]
Fixed as of 0.9.75
