### ISSUE TITLE
[Bug] Backup restore doesn't work

### ISSUE THREAD

**Issue by ZED102** [Jays2Kings/tachiyomiJ2K#785]
---

### Device information
* Tachiyomi version: 1.0.16
* Android phone & version: mi note 10 lite - android 11

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
restore the Backup from the main tachiyomi app

### Actual behavior
doesn't restore the Backup

### Other details
when i make a backup from the main tachiyomi app and restore it on the tachij2k app it doesn't restore it

**Comment by Jays2Kings** [comment]
Closing as this was resolved
