### ISSUE TITLE
NSFW content in New search suggestions

### ISSUE THREAD

**Issue by yakau** [Jays2Kings/tachiyomiJ2K#786]
**App version:**

1.0.16

**Android version:**

MIUI 10.3.2 (Android 9 based I think)

**Issue/Request:**

You have a new feature: "Library will show search suggestions/tips after a day"

Can you please sanitize the list of search suggestions? I had "ecchi, anal" pop up as one of the suggestions. I'd rather not see clearly NSFW content like that by default. It'd be better as an opt-in if at all.

**Steps to reproduce (if applicable)**

 1. Open main library page
 2. Look at the search box at top of the page 
 3.

**Other details:**

I tried to screenshot the problem, but screenshots of the Tachiyomi app were blocked. I don't know if that's an intentional feature of the app or something from my Chinese Android OS. Other apps screenshot okay.

**Comment by dmswd** [comment]
To take a screenshot 
Open the settings 
Select security 
Turn off secure screen

**Comment by yakau** [comment]
> To take a screenshot
> Open the settings
> Select security
> Turn off secure screen

Thanks. I've deactivated it. Good to know.

**Comment by Jays2Kings** [comment]
There's no way to know what's a "nsfw" tag vs. a "sfw" tag.

**You also can turn off search suggestions in library settings.**

Alternatively use 2 tachi apps if you're going to use the same app for a wank and for work
