### ISSUE TITLE
Overlayed text over text

### ISSUE THREAD

**Issue by bloodkingBk** [Jays2Kings/tachiyomiJ2K#787]
### Device information
* Tachiyomi version: 1.0.16
* Android phone & version: Samsung s10 
* Android 11

## Steps to reproduce
1. Dubble tap library until display options is visible and tap on it 
2. Tap on reorder filters and you'll see some text overlayed over each other

### Expected behavior
 text overlayed with other text

### Actual behavior
Text is overlayed with other text

### Other details
Picture Attached*
![Screenshot_20210504-144540_TachiyomiJ2K](https://user-images.githubusercontent.com/65837094/117016367-8cd49980-acea-11eb-9be2-76b19a48dc20.jpg)

**Comment by CarlosEsco** [comment]
#780
