### ISSUE TITLE
[Bug] Empty Library

### ISSUE THREAD

**Issue by Aggiln** [Jays2Kings/tachiyomiJ2K#788]
### Device information
* Tachiyomi version: 1.0.16
* Android phone & version: Redmi Note 8 Pro MIUI 12.0.4 (Android 10)

## Steps to reproduce
1. Open TachiyomiJ2K

### Expected behavior
All of the Manga, Manhwa, Manhua that I've added should have shown.

### Actual behavior
It did not.

### Other details
https://streamable.com/rfnvqz

**Comment by CarlosEsco** [comment]
can you verify you don't have a filter enabled?

**Comment by Aggiln** [comment]
> can you verify you don't have a filter enabled?

https://streamable.com/7i1qh7

**Comment by CarlosEsco** [comment]
Did you clear app cache or anything?

**Comment by Aggiln** [comment]
> Did you clear app cache or anything?

Nope.

**Comment by Jays2Kings** [comment]
@Aggiln Can you send a backup of your library?
