### ISSUE TITLE
[Feature Request] Remove launcher icon long tap shortcuts menu

### ISSUE THREAD

**Issue by ratul0547** [Jays2Kings/tachiyomiJ2K#795]
**App version:**
1.0.16

**Android version:**
10

**Issue/Request:**
Please remove manga/comic list from the home screen launcher long press menu. Or add customizing options for these shortcuts. Keeping the shortcuts same as original Tachiyomi app is fine too. 
It is a major privacy issue.

**Steps to reproduce (if applicable)**

 1. Long press home screen launcher icon.
 2. A context menu will appear with extra shortcuts.

**Screenshot**
![Screenshot](https://i.imgur.com/BdMTwjJ.jpg)

**Comment by Jays2Kings** [comment]
Nothing about this is a privacy issue, since to see these in the first place your phone has to be unlocked. There are other apps such as your messaging apps (like sms or discord) that do the same.

Adding an option to disable is fine by me, but calling it a privacy issue is an exaggeration
