### ISSUE TITLE
[Bug] Cover does not persist when extension provides default

### ISSUE THREAD

**Issue by munael** [Jays2Kings/tachiyomiJ2K#798]
### Device information
* Tachiyomi version: 1.0.16
* Android phone & version: 10

## Steps to reproduce
1. Migrate MangaDex title
2. Cover is changed to the "default"
3. Try changing cover (directly from a chapter image or from local storage)

### Expected behavior
Cover changed.

### Actual behavior
Placeholder persists.

### Other details
Bug does not happen on the base Tachiyomi.

**Comment by Jays2Kings** [comment]
Fixed for next release in 491915aa22435d5c335426aa192afd9e7f8bd29b
