### ISSUE TITLE
[Feature Request] "Download X chapters ahead"

### ISSUE THREAD

**Issue by m-vlad** [Jays2Kings/tachiyomiJ2K#80]
### Why/User Benefit/User Problem
Right now you can do batch downloads of chapters, and sure, you can download like 50 chapters and that could cover you, but when you reach that 50th chapter you might lose internet connection or something, or you gotta go somewhere and you don't have any data. Anyway, my point is tachi could keep your downloads X number of chapters ahead, so you always have X amount of chapters downloaded ahead (would also help people with poor connection for whom streaming the chapters has a lot of buffering)

### What/Requirements
(explain how this feature would behave)
just a checkbox or something in the Download chapters menu that says "Keep downloading" or something clearer, or perhaps a global setting. or both (global setting overwritten manually)

**Comment by joseph619** [comment]
MD2 beta and Tachiyomi Dev nows preloads the next chapter once you reach the last 3 pages of a chapter.

**Comment by DuccinatorAlpha** [comment]
I was about to make an issue until github said that it was already a thing. I will post my draft:

`### Why/User Benefit/User Problem
A feature which let's say download the next 2 unread chapters of every manga in a category(ies) would be nice, especially when paired with auto deleting chapters.
(this feature basically means keeping the next x chapters in a cache which gets deleted after the chapter is read)

### What/Requirements
Any time a manga is added to the library, the next x chapters are downloaded, everytime a chapter is read from a manga in that category, the next chapter is downloaded.

This would obviously be a togglable thing. x=2 or 3 would probably be ideal if a variable chapter count isn't possible.`

**Comment by CarlosEsco** [comment]
are you so short on space that before you read you cant just click download however many.

**Comment by m-vlad** [comment]
> are you so short on space that before you read you cant just click download however many.

I've got two scenarios for you:
1. What if you've got a sketchy internet so you download 20 chapters so you don't have to sit through the loading icons? Every 20 chapters you have to get out, queue downloads again and wait for it to download again, while you could just have it download ahead of your reading so you don't get interrupted.

2. You download 10 chapters of a manga to see what it's like. You read on a commute, you don't have mobile data because that's expensive. You start reading a few chapters before the commute starts only to realise you've already burned through all the chapters you downloaded. Sure, you could've just downloaded 20 to begin with, but that kind of answer only works with hindsight in place.

**Comment by CarlosEsco** [comment]
#1.  Takes a 5s at worst to download more.
#2.  Doesn't help at all cause you don't have internet after your first few chapters so you blew through 13 chapters instead of 1p. And you still can't read after that.

**Comment by DuccinatorAlpha** [comment]
Here is how I read any new manga:

1. Download next 5 chapters
2. Read
3. Notice that suddenly each page is taking 4-5s to load(blame mangadee)
4. Go back to chapter list, click on download next 5 chapters again(or next 10 chapters  if I am confident that the series is good)
5. Wait for like a minute before the next chapter is downloaded
6. Continue reading

Having only the next 2 chapters always downloaded negates this annoyance. It's not about internet or storage space, I have plenty of both. I am really quick at dropping series so I don't like to download every chapter, but I need to download them to get a deent reading experience.

**Comment by CarlosEsco** [comment]
Here's an easy solution download 5 chapters. Read see the transition page say you are about to start chapter 5 then back out and download more.

**Comment by DuccinatorAlpha** [comment]
That's what I usually try, and I almost always fail. The transition pages in webtoon mode are pretty small and I just skip through them without reading. Going back and downloading the next 5 chapters isn't that bad. Waiting for the next chapter to download is however an issue. (Blame Mangadex servers)

**Comment by infected36** [comment]
This feature would be pretty handy. It looks like someone managed to implement it on the main tachiyomi. It's not a necessity, it's more of convenience.

`[Link to the Tachi thread about it](https://github.com/inorichi/tachiyomi/issues/3295) `
