### ISSUE TITLE
[Bug] TCB scans isn't showing any manga

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#816]
### Device information
* Tachiyomi version: 1.0.17
* Android phone & version: Oneplus 7t & android 10

## Steps to reproduce
1. Go to browse 
2. Click on TCB scans

### Expected behavior
Shows you the manga that they have

### Actual behavior
No results found

### Other details
Works fine in webview and this is probably because they changed their website's design

**Comment by joseph619** [comment]
Post on extensions repo, this has nothing to do with J2K
