### ISSUE TITLE
[Bug] Can't Track new manga via MAL (Error 401)

### ISSUE THREAD

**Issue by titlekungCh** [Jays2Kings/tachiyomiJ2K#819]
### Device information
* Tachiyomi version: 1.0.17
* Android phone & version: Samsung Galaxy Tab S6 Lite & Android 11

## Steps to reproduce
1. Open new manga page
2. Click Tracking

### Expected behavior
App automatically input manga name into tracking search bar, then the list of manga appear to choose

### Actual behavior
App did automatically input manga name but the toast appear with text "Error 401" and it keeps loading but nothing happens after that no matter how long I waited

### Other details
- I tried searching manga name on my own in tracking, it didn't work either.
- Old manga which have been tracked is still working.

**Comment by CarlosEsco** [comment]
Log out of mal then relogin

**Comment by titlekungCh** [comment]
Now its ERROR 400 instead
