### ISSUE TITLE
[Bug] App crashes on selecting categories to include in global update

### ISSUE THREAD

**Issue by dustter** [Jays2Kings/tachiyomiJ2K#82]
### Device information
* Tachiyomi version: 0.9.7
* Android phone & version: Samsung Galaxy Note 8, Android 9.0

## Steps to reproduce
1. Go to Settings/Library/Categories to include in global update
2. Tick any other **ONE** category than "All"
3. See the crash hapenning.

### Expected behavior
It shouldn't crash on OK tap.

### Actual behavior
It does crash.

### Other details
Example included in the gif. About 4 people reproduce the same thing, so has to be fork-related.
Also, to add, I bolded that ONE category cause the issue seems to happen only when you truly select only 1 other category than "All". If you choose any amount of multiple ones, it doesn't crash.  Also the crash is not happening anymore when switching between those custom created categories.
![20200123_172457](https://user-images.githubusercontent.com/54286558/73003166-76604280-3e05-11ea-90ae-865217a84ee1.gif)

**Comment by Jays2Kings** [comment]
Fixed as of 0.9.75
