### ISSUE TITLE
[Feature Request] Make thumbnail bigger

### ISSUE THREAD

**Issue by ourslfs** [Jays2Kings/tachiyomiJ2K#821]
So after trying tachiyomiSY, noticed that thumbnail a bit bigger and there's less gap between them which has more clean look. Also scrolling seems more clunky in tachij2k(maybe because thumbnails more smaller and more compressed because of it, idk?). So, i wonder if it could be done, maybe as additional setting in display option? Here's what it looks like in comparison.
![Screenshot_20210516-221131](https://user-images.githubusercontent.com/78319733/118410036-2a8a7a00-b696-11eb-89c8-e8fb0ea49f77.jpg)
![Screenshot_20210516-221120](https://user-images.githubusercontent.com/78319733/118410039-2c543d80-b696-11eb-884d-c5e5f7c15fd6.jpg)

**Comment by CarlosEsco** [comment]
Last I knew (previously closed tickets and discord) there are no plans to change the margins

**Comment by Jays2Kings** [comment]
This isn't changing because of how it's designed with the unread badge
