### ISSUE TITLE
[Feature Request] Update multiple extensions at once

### ISSUE THREAD

**Issue by Schadows** [Jays2Kings/tachiyomiJ2K#824]
### Why/User Benefit/User Problem
When several extension are updated at the same time, it becomes a very tedious operation to do for the user, having to clic the update button to download the new version, and clic to confirm the installation, for each and every updated sources.
Not sure if it is a android limitation, a Tachiyomi (original) limitation.

### What/Requirements
Would it be possible to provide a way to update all extension at once (kind of like what the Play Store does)?

**Comment by CarlosEsco** [comment]
the best that could be done is a batch download, but at the end of the day it requires root to install an apk without manual intervention which is not something that is planned
