### ISSUE TITLE
[Feature Request] hidden/locked category

### ISSUE THREAD

**Issue by XxJibril** [Jays2Kings/tachiyomiJ2K#825]
### Why/User Benefit/User Problem
having a secret/hidden secure category would provide even more privacy for users when they are passing the phone to someone else (i'm particularly thinking of the NSFW mangas here...after going through a couple embarrassing events lol)

### What/Requirements
the idea is to be able to password/fingerprint lock a category of our choice, it will look normal like any other other category but with a few perks:
-require a password/fingerprint when you want to expand the said category into full view
-also require the password/fingerprint to disable the lock
-mangas read in the hidden category won't register the history/recent tab (default incognito mode)
-updating the library would exclude the hidden tab (which can only be updated manually once the category is expanded
-if the category is collapsed, the search bar will completely ignore everything inside of it and only include it in the search if it's expanded (unlocked)
-the mangas in the hidden category would be hidden in any "Group library by...'' option except when ''categories'' is selected, and the specific category unlocked
-when it comes to backing up, it should backup the hidden category alongside the others just like usual

**Comment by Jays2Kings** [comment]
there's already a fingerprint lock and an incognito mode, this only makes this far more complicated
