### ISSUE TITLE
[Feature Request] The ability to pin manga in a category

### ISSUE THREAD

**Issue by DuccinatorAlpha** [Jays2Kings/tachiyomiJ2K#83]
### Why/User Benefit/User Problem
People with too many unread manga can lose track of what they are reading and have trouble finding a manga in their library(especially when binging). A feature where a user can pin a few manga to the top would help. The feature may also help keep of favourites for some people.

### What/Requirements
The user long presses a manga(or mangas) and pins it on the top for that particular category using the 3 dots. Pinned manga could be highlighted by having a pinned icon or having an opaque boundary or something.

**Comment by Jays2Kings** [comment]
This is just what drag & drop does. You can select manga and move them to the top or bottom. Making a pin system just duplicates the logic
