### ISSUE TITLE
Add option to make and select your own custom theme

### ISSUE THREAD

**Issue by PRIYAANK2510** [Jays2Kings/tachiyomiJ2K#830]
So this feature is like giving users an option to select theme for himself, By categorizing theme in two parts :
1. App Theme : It will be the color of major portion of the app that will consist color option of : Amoled Black, Dark & Light Theme
2. Accent Color: It will consist of color picker which user can select according to his likings.

This Feature will attract more user because of more UI selection option. It will give the better UI Design and design is a major part which most user considered while using any app.

So this feature will also minimize your burden of creating new themes as after this user can select his own theme.

**Comment by joseph619** [comment]
Already requested several times and rejected
