### ISSUE TITLE
Search Icon is better than search box

### ISSUE THREAD

**Issue by PRIYAANK2510** [Jays2Kings/tachiyomiJ2K#831]
You have updated the UI with new search box instead of old design where search icon was there. I think older Search Icon look much better than this new search box as Search Icon provide the app Minimalistic look which makes the UI look much better

AND

You should increase the size of thumbnail of the manga a little bit just like tachiyomi neko manga thumbnail size are perfect as it gives them a perfect look.

**Comment by CarlosEsco** [comment]
ui is not going back.  AS for thumbnail size that is configurable
