### ISSUE TITLE
[Bug] Problem with removing the dates on anilist

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#833]
### Device information
* Tachiyomi version: 1.0.17
* Android phone & version: Oneplus 7t/android 10

## Steps to reproduce
1. Go to a manga,manhwa and etc
2. Click track 
3. Click on anilist
4. Set a date
5. Remove the date

### Expected behavior
The date should be removed

### Actual behavior
The date will not be removed

### Other details
The date cannot be removed from within the app, but it can be removed from the anilist site or app

**Comment by KasukeLp23** [comment]
Yeah, I also have the same problem
