### ISSUE TITLE
[Bug] can't update to the newest version

### ISSUE THREAD

**Issue by D1012** [Jays2Kings/tachiyomiJ2K#835]
### Device information
* Tachiyomi version: v1.0.16
* Android phone & version: huawei y6s, version 9

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Updating to v1.0.17

### Actual behavior
Always pop up the notification of updating but it does not continue to update

### Other details
Additional details and attachments.

**Comment by fleurc** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/releases/tag/v1.0.17

You have to download from Release, from app it doesn't work

**Comment by Jays2Kings** [comment]
See the above comment
