### ISSUE TITLE
[Feature Request] Add a feature to exclude a manga from auto downloading in a category

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#841]
### Why/User Benefit/User Problem
There are mangas that drop 2 chapters everyday and when you're not caught up, it still auto downloads the new chapters and it's waste of internet 

### What/Requirements
1- go to settings 
2- go to downloads 
3- make an option to exclude manga/comic it's going to show your library and you can select the certain manga you don't want to automatically download or if you select a manga in your library there will be an option to exclude form the auto downloads

**Comment by CarlosEsco** [comment]
make a category that is not set to download, and add those manga to that category?

**Comment by FireNation323** [comment]
> make a category that is not set to download, and add those manga to that category?

I have too many categories and I want the manga I'm reading to be in my reading category and it makes things look cleaner

**Comment by FireNation323** [comment]
> you can have manga in multiple categories though

Even if I have the same manga in another category, in the main Tachiyomi if you go to settings>downloads you can exclude that category and it won't download even if you have same manga in an auto download category, but in tachij2k you can't exclude categories.

**Comment by Jays2Kings** [comment]
With a3a4edbde you will soon be able to put it in a category to exclude from downloading
