### ISSUE TITLE
[Feature Request] Add scroll bar to browse through sources faster 

### ISSUE THREAD

**Issue by Saad3894** [Jays2Kings/tachiyomiJ2K#846]
### Why/User Benefit/User Problem
(explain why this feature should be added)

### What/Requirements
(explain how this feature would behave)

---
Please add a scroll bar to the right of the screen when browsing through manga on different sources.

Just like the one in the library, updates, history.

Also the scroll bar should display 1-100, 100-200, 300-400 etc when scrolling down.

This will very helpful in locating where you left off if the app closes or resets which forces you to start browsing from the beginning. So you don't have to keep scrolling down again to figure out where you left off.

**Comment by joseph619** [comment]
This is not possible without pagination, as app has to load entire library of a source first

**Comment by Jays2Kings** [comment]
As mentioned the entire list of manga isn't loaded so this is impossible
