### ISSUE TITLE
[Bug] Super laggy

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#85]
Hi,

I just went from the original Tachiyomi to this version and find it extremely laggy. Any fix for this?

**Comment by joseph619** [comment]
This is a known issue yes.

**Comment by joseph619** [comment]
The bug is a known issue yes. In the meantime, you can restore backup on Stable until the lag is fixed.

**Comment by vongdong** [comment]
> 
> 
> The bug is a known issue yes. In the meantime, you can restore backup on Stable until the lag is fixed.

I don't mind it. I can deal with it as long as I don't switch categories fast.

**Comment by joseph619** [comment]
> I don't mind it. I can deal with it as long as I don't switch categories fast.

I would recommend you join Discord for more support and discussions.

**Comment by Jays2Kings** [comment]
Lag gone. Fixed in 0.9.76
