### ISSUE TITLE
[Bug] TuMangaOnline doesn't show anything

### ISSUE THREAD

**Issue by hoshiyon** [Jays2Kings/tachiyomiJ2K#850]
Device information: Xiaomi Redmi note 7
Tachiyomi version: latest 1.0.17

Android phone & version: Android 10 QKQ1

When i tried to open the extension "TuMangaOnline" it shows error 403, i tried with the solution offered in the tachiyomi website but there isn't a capcha to enter the site.

Another thing it's that this problem seems to be exclusive to the main page because when i tried to open a manga previously marked in my library it shows without any problem.

Expected behavior:
To show mangas on the main page and to be able to search for manga with the filters.

Other details:
I attached some images to show the problem
![Screenshot_2021-05-28-13-04-24-720_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/84986239/120020386-9edaec80-bfb7-11eb-8b09-4ac5600c6884.jpg)
![Screenshot_2021-05-28-13-22-42-908_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/84986239/120020414-a8fceb00-bfb7-11eb-908d-5b90547e9099.jpg)
![Screenshot_2021-05-28-13-04-12-339_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/84986239/120020430-aef2cc00-bfb7-11eb-84de-be1d8599415e.jpg)

**Comment by KasukeLp23** [comment]
Extension fixed a few days ago.
