### ISSUE TITLE
Bottom Bar button pressing is laggy

### ISSUE THREAD

**Issue by siker498** [Jays2Kings/tachiyomiJ2K#852]
**App version:**
Latest
**Android version:**
11
**Issue/Request:**
Clicking on the buttons in the bottom toolbar is laggy
**Steps to reproduce (if applicable)**

 1. Open app
 2. Press button on bottom
 3. Profit

**Other details:**

**Comment by Jays2Kings** [comment]
Fixed in 0fa3eef40
