### ISSUE TITLE
[Feature Request] Match ripple colour with theme

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#853]
### Why/User Benefit/User Problem
Same as in Stable, match ripple colour to that of the app theme

### What/Requirements
Relevant PRs 

https://github.com/tachiyomiorg/tachiyomi/pull/5142
https://github.com/tachiyomiorg/tachiyomi/pull/5144
https://github.com/tachiyomiorg/tachiyomi/pull/5159

**Comment by Jays2Kings** [comment]
closed with 990d5ebdd
