### ISSUE TITLE
[Bug] Grid size selection bar shows numbers more than once

### ISSUE THREAD

**Issue by ric0369** [Jays2Kings/tachiyomiJ2K#854]
### Device information
* Tachiyomi version: 1.0.17
* Android phone & version: s21, android 11

## Steps to reproduce
1. First step
go to display options in library

2. Second step
move the grid size bar

### Expected behavior
numbers should appear once each

### Actual behavior
the numbers 3, 2, and 1 appear twice each

### Other details
https://user-images.githubusercontent.com/71677337/120220102-3cc5f580-c20a-11eb-8a9a-43516fd554dc.mp4

**Comment by Jays2Kings** [comment]
This is as expected, since larger devices will have more options
