### ISSUE TITLE
Delete files for un-favorited manga

### ISSUE THREAD

**Issue by Light-Wing** [Jays2Kings/tachiyomiJ2K#86]
**App version:** 0.9.75

**Android version:** 9

**Issue/Request:** both in a way

**Steps to reproduce (if applicable)**

 1. Add manga to favorite
 2. Download some chapters
 3. Remove manga from favorite
 4. At this point I expect the downloaded chapters to be deleted, or to at least get a button on the bottom of the screen to remove those files... (At least that's what happens in regular tachiyomi)

**Other details:**
This is the only thing I feel like is missing from your version of tachiyomi, and I'm loving the app...
I'm in the middle of forking my own version of tachiyomi to  a SFW version, and just found yours, and I'm probably going to use it instead, I was just going over the changed files, to find what I'm going to change, and as of yet, I couldn't find where it is that when a user removes a manga which has downloaded chapters, you get a "snack" with a "delete" button to delete those files, right now I'm your version there is an "undo" button in its place...

**Comment by CarlosEsco** [comment]
The downloaded chapters are deleted

**Comment by Light-Wing** [comment]
when I checked it, I just pressed the bookmark and waited a few seconds and pressed it again... I'm used to removing downloaded files that way (for individual mangas), but in your version I get an undo button, instead of the confirm delete button
here are 2 images of the differences...
here the user is presented with the question if the user wants to delete it...
<img width="332" alt="inorichi tachi" src="https://user-images.githubusercontent.com/23284632/73489285-59cd8880-4378-11ea-8a6e-6e5e5188247e.png">

here the user gets asked if to undo the last action
<img width="337" alt="J2K tachi" src="https://user-images.githubusercontent.com/23284632/73489286-59cd8880-4378-11ea-9102-5c218aea259b.png">

after checking what you wrote, you made it so the user has a few seconds to cancel what he did (either by pressing the button again, or by pressing the undo button...) if the user does not change their mind fast enough, then the files are deleted any way...

I'm guessing you thought it out and chose this to be the better option, and I can think of the reasons why it makes sense, it will just take a bit to get used to...  

thanks for replying

**Comment by Jays2Kings** [comment]
To add this this, the chapters won't be deleted until the snack bar at the bottom disappears, and it won't disappear until touch the screen again (after a set amount of time passes first) or leave the current screen
