### ISSUE TITLE
[Feature Request] Custom library update frequency

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#863]
### Why/User Benefit/User Problem
I would like my library to be updated every 15-20 mins and one hour is the lowest you can go

### What/Requirements
1- Go Settings > library > library update frequency
2- add an option to set a custom time to the already existing list

**Comment by CarlosEsco** [comment]
No.  If anything 1 and 2h will be removed.  You are ddosing sites for no reason except for your inpatients

**Comment by FireNation323** [comment]
> No.  If anything 1 and 2h will be removed.  You are ddosing sites for no reason except for your inpatients

What?

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/commit/569df39fb88e534fa0deb5b9a412f84936006859

**Comment by fleurc** [comment]
That was such a bad explanation given to someone. The thought process that you can DDoS a site because one person decided to update every hour or two is ludicrous. I love J2K but this is such an idiotic decision i am baffled.

**Comment by CarlosEsco** [comment]
@fleurc  it's very simple there are people with 1000s of manga from one source.  Chapters don't get updated nearly that often that you need hourly checks.  People are sending out 1000s of requests for the off chance they get 1 chapter updated..  What benefit does this provide, besides getting sources to ban tachiyomi more?

**Comment by fleurc** [comment]
@CarlosEsco true enough, that makes more sense tbh. This is a much better way to communicate about such a change instead of the way it was previously said.
