### ISSUE TITLE
[Bug] Manga and Doujishi Status' Change to "Unknown Status" After Editing Details

### ISSUE THREAD

**Issue by SunBreaker1** [Jays2Kings/tachiyomiJ2K#866]
### Device information
* TachiyomiJ2K version: 1.0.17
* Android phone & version: Samsung S10e - Android 11

## Steps to reproduce
Manga
1. Select and ongoing manga and go to edit
2. In edit, add a tag (changing title might also have an effect, I personally haven't tried this)
3. Save the edit
4. No matter if the manga is ongoing or completed, the status will change to "unknow status.

Doujinshi
1. Similar to the manga, go to edit 
2. Add a tag or change the name
2.5. If the status isn't listed, change the status to completed
3. These edits will make the Doujinshi to have a "unknown status"
3.5. Manually changing the status to "complete" will still give the "unknown status"

### Expected behavior
Adding tags, changing name, or status should not result in the "unknow status" to appear as these changes should only change what the local device and user see, and not conflict what the source says about the Manga/Doujinshi.

### Actual behavior
Depending on the thing being edited, the Manga and/or Doujinshi have their status' changed to "unknown status" because of these edits

### Other details
This bug has been previously mentioned in the submission #849, however I would like to expand on this issue with this submission

**Comment by enaaab460** [comment]
Facing the same issue after manually setting Manga title. The status becomes unknown and the Manga appears in the library which has unread filter even though all chapters are read. 
Fixes itself when I reset the name. But frustrating nonetheless.

**Comment by Jays2Kings** [comment]
Fixed in v1.0.18 (i think, its definitely fixed in current versions)
