### ISSUE TITLE
[Feature Request] Update Frequency Longer Than 2 Days

### ISSUE THREAD

**Issue by fleurc** [Jays2Kings/tachiyomiJ2K#869]
Why/User Benefit/User Problem
I would like to be able to have Tachiyomi update every 15/30 days, since a lot of manga have montly updates, or even weekly or biweekly updates. It'd be beneficial both for phone use, give less strain on sources, and would allow for a better battery life for my phone (I think).

What/Requirements
1- Go Settings > library > library update frequency
2- add an option to set a weekly, bi weekly, or monthly option of udates frequency.

**Comment by joseph619** [comment]
In the meantime, you can create category for slow updating manga, blacklist the category from auto update, and manually update the category when you feel like it.

**Comment by fleurc** [comment]
That does work nicely too, i just don't know how to go about doing that? How would i change the update frequency of a specific category instead of changing for all of them? currently it's set for 2 days, but it's be useful for my case to make it even longer, maybe a week or 2 since that's the normal update cycle for manga. If you can help me a bit on how to set up update frequencies for individual categories i'd be really grateful.

**Comment by fleurc** [comment]
I think i may have found the way, would still be a welcomed change, since if i have to do what you posed i'll have to separate the categories differently to what i have set up. Either way, it's an idea, since i know that slower updates are work for coders, but will alliviate the amount of strain on sites to check for updates. Something i feel is worth discussing over.

**Comment by joseph619** [comment]
You can have the same manga in multiple categories btw, no need to remove them from existing categories.

**Comment by fleurc** [comment]
Ye, but that to me kind of defeats the purpose of making categories, even more so if i'm controlling the update frequency of a category since the manga would update then on both categories, wouldn't it?

**Comment by Jays2Kings** [comment]
weekly option added in 656192f7c
