### ISSUE TITLE
[Feature Request] Better indicator for already added Manga in search results

### ISSUE THREAD

**Issue by MxFlix** [Jays2Kings/tachiyomiJ2K#87]
### Why/User Benefit/User Problem
Currently, in the search results, the only indicator for whether a specific search result is already in My Library is that the cover is faded out. However, that is sometimes hard to distinguish when a Manga's cover is already very light, and sometimes the cover is still loading, completely blank or otherwise not visible.

### What/Requirements
There could either be some sort of icon in a corner of the cover (or where the cover would be in case there's none), or the text could be faded out, similar to the list view in the catalogue.

**Comment by joseph619** [comment]
This has been added in MD2 beta I think

**Comment by CarlosEsco** [comment]
@Jays2Kings this can be closed
