### ISSUE TITLE
[Feature Request] Anime viewing support

### ISSUE THREAD

**Issue by MXV3R1CK** [Jays2Kings/tachiyomiJ2K#870]
Why/User Benefit/User Problem
I would like the anime features included in aniyomi added to this fork as I love the feature but like the ui of this fork better.

What/Requirements
1. Add tab for anime
2. Integrate aniyomi anime features
3. Add anime sources

**Comment by joseph619** [comment]
No

@CarlosEsco

**Comment by fleurc** [comment]
Aside from the fact that it's aniyomi's main feature, it's what differentiates them, there is some legality behind what they are doing. I think that's the reasoning. Aside from J2K being built Manga First, so the question would come back as: would it even work nicely if implemented? Can it just "simply" be implemented?

**Comment by CarlosEsco** [comment]
Nah dog
