### ISSUE TITLE
[Feature Request] a randomizer that picks a random manga in your library

### ISSUE THREAD

**Issue by Koupla** [Jays2Kings/tachiyomiJ2K#873]
Why/User Benefit/User Problem
-users can get a random manga if they cannot choose something to read

**Comment by fleurc** [comment]
Wouldn't it be better to have a recommended tab that recommends based on your library of Manga?

**Comment by Koupla** [comment]
> Wouldn't it be better to have a recommended tab that recommends based on your library of Manga?

that would be another feature that I wanna see as well

**Comment by DaviDeMeo** [comment]
A button on the category hopper would be good? you could enable it from settings
