### ISSUE TITLE
[Feature Request] New Track Provider: Goodreads

### ISSUE THREAD

**Issue by volkanturkut** [Jays2Kings/tachiyomiJ2K#874]
### Why/User Benefit/User Problem
Tachiyomi doesn't just have the manga, it also has the comics, and goodreads has both to track. It would be nice to use Goodreads to keep track of both.

### What/Requirements
It should work like any other track provider. Must follow the progress of comics and manga.

**Comment by arkon** [comment]
Didn't Goodreads shut down their public API?

**Comment by volkanturkut** [comment]
> Didn't Goodreads shut down their public API?

I checked now and yes shutdown in December 8th 2020
