### ISSUE TITLE
[Bug] Comick extension update error

### ISSUE THREAD

**Issue by Kiriao** [Jays2Kings/tachiyomiJ2K#875]
### Device information
* Tachiyomi version: v 1.0.17
* Android phone & version: Samsung A8+(2018) | Android verisoin 9

## Steps to reproduce
Reinstall the extenstion but nothing change

### Other details
On the comick.fun "Komi-san wa Komyushou Desu." is updated to chapter 311 but in the Tachiyomi comick extentsion getting error but some of my comick manga is still able to update.

![image](https://user-images.githubusercontent.com/48480973/122707414-957a3280-d28c-11eb-94e1-089f902382df.png)

**Comment by CarlosEsco** [comment]
Does it work in regular main app Tachiyomi?

if yes then this ticket belong here.
if no then this ticket belongs here https://github.com/tachiyomiorg/tachiyomi-extensions/

**Comment by Kiriao** [comment]
Ok i will post there.
