### ISSUE TITLE
[Bug] Duplicated field number in backup model

### ISSUE THREAD

**Issue by qgustavor** [Jays2Kings/tachiyomiJ2K#878]
### Device information
Not applicable: bug found by checking source-code.

### Steps to reproduce
Not applicable: bug found by checking source-code.

### Expected behavior
Every field in the backup model, including J2K specific values, [as defined here](https://github.com/Jays2Kings/tachiyomiJ2K/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupManga.kt#L42-L47) ([permalink](https://github.com/Jays2Kings/tachiyomiJ2K/blob/11467cdb01a907a9b3b1c4a60128ede6bcde99f8/app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupManga.kt#L42-L47)) needs to have an unique field value.

### Actual behavior
Both `customDescription` and `customGenre` fields share the same field number, `803`.

### Other details
I found this issue while working on a automatic Mangadex migration tool using Mangadex's legacy mapping API (as the normal Tachiyomi migration don't works well with renamed manga). I don't know how Tachiyomi is serializing those backups: the Protobuf library I used simply disallowed two fields with the same field number. Maybe it's ignoring one of those fields, or both, I don't know, I don't use any of those fields so I just ignored those when working with the backup files.

I tried reporting this [by commenting in the commit that added this bug](https://github.com/Jays2Kings/tachiyomiJ2K/commit/c21b91bc026213993a67089ef4bc76c68ade4445#r50610254) but seems better to move it to an issue so it can be properly tracked.

**Comment by DaviDeMeo** [comment]
There is also a problem in [BackupSource.kt](https://github.com/Jays2Kings/tachiyomiJ2K/blob/cee7c30a02073d60ac63d73b3118a950aaf83cf9/app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupSource.kt#L9) and [BackupHistory.kt](https://github.com/Jays2Kings/tachiyomiJ2K/blob/cee7c30a02073d60ac63d73b3118a950aaf83cf9/app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupHistory.kt#L8) where the field number is set to 0 which is not in [spec](https://developers.google.com/protocol-buffers/docs/overview#assigning_field_numbers). Changing it may break backup but is a bug nonetheless (Kotlin/kotlinx.serialization#1566)

**Comment by Jays2Kings** [comment]
The first can be fixed, however the latter is in sync with upstream. You should raise an issue on tachiyomiorg regarding that instead
