### ISSUE TITLE
[Bug] extension search stopes working after installing an extension

### ISSUE THREAD

**Issue by sainAk** [Jays2Kings/tachiyomiJ2K#880]
### Device information
* Tachiyomi version: 1.0.17
* Android phone & version: asus max pro m1, Android 11

## Steps to reproduce
1. Search for any extension
2. Install an extension
3. Search for another extension

### Expected behavior
Search works

### Actual behavior
Search doesn't work

### Other details

https://user-images.githubusercontent.com/46787056/123418668-f41a1600-d5d6-11eb-9d6a-7ca34055cf7e.mp4

**Comment by SunBreaker1** [comment]
Have you tried backing out of the extensions tab and selecting it again? This might reset the search and should allow you to search for extensions normally.

Also yes, I've also encountered this problem before.

**Comment by sainAk** [comment]
> Have you tried backing out of the extensions tab and selecting it again? This might reset the search and should allow you to search for extensions normally.
> 
> Also yes, I've also encountered this problem before.

Yep it works if I do that, but I faced this senario when I was re-installing the app so I had to close and reopen search for each install.
