### ISSUE TITLE
[Feature Request] Staggered grid covers in display option

### ISSUE THREAD

**Issue by CVIUS** [Jays2Kings/tachiyomiJ2K#881]
### Why/User Benefit/User Problem
People who are used to 2 rows and likes to replace manga covers due to the low quality covers provided by some sources will likely benefit this feature. Also, this will make the UI more saxy.

Enabling uniform grid covers in display options crops the cover that the user wanted to use (if the size of the cover is large), which kinda ruin its look (in my opinion). Below are the example pictures that shows the difference when uniform grid covers are enabled & disabled in display options (This is in my case).

Uniform grid covers is disabled (manga covers are large and have different sizes)
![Screenshot_20210626-195919](https://user-images.githubusercontent.com/84634607/123512693-80056e00-d6bb-11eb-98f0-5d9664aefb40.jpg) 1st

Uniform grid covers is enabled (crops the user's chosen cover)
![Screenshot_20210626-200205](https://user-images.githubusercontent.com/84634607/123512696-81cf3180-d6bb-11eb-8ba1-b105ef687e32.jpg) 2nd

.
.
.

Users have different preferences in choosing a manga cover they want to use, and the picture below might show the case from their side.
![Screenshot_20210626-195844](https://user-images.githubusercontent.com/84634607/123512877-80eacf80-d6bc-11eb-89c4-daf5af212fc6.jpg) 3rd (uniform grid covers disabled)

### What/Requirements
The GIF below shows how staggered grid looks like.
![gfgstaggeredgridlayout](https://user-images.githubusercontent.com/84634607/123512981-0ff7e780-d6bd-11eb-8cd0-c1ca44284ae7.gif) 4th ©geeksforgeeks

Hope you get the point of my request. Thank you!

**Comment by Sidepunch** [comment]
Woah that would be a cool feature

**Comment by doncovet** [comment]
That seems really niche and I love it
