### ISSUE TITLE
Black theme is broken

### ISSUE THREAD

**Issue by SlamZDank** [Jays2Kings/tachiyomiJ2K#886]
### Device information
* Tachiyomi version: 1.0.18
* Android phone & version: Samsung j3 (16) / android 7.1.2

## Steps to reproduce
1. Set the theme to amoled chocolate strawberries or flat lime or the amoled variant of dark blue
2. Restart the app

### Expected behavior
The app must have the theme presets applied

### Actual behavior
The app defaults to the blue version of amoled (default)
(the background becomes dark when restarting the app with the dark blue amoled theme applied)
![Screenshot_20210705-231113](https://user-images.githubusercontent.com/83764499/124521432-5d740300-dde7-11eb-9920-281dd1ce03df.png)
![Screenshot_20210705-231356](https://user-images.githubusercontent.com/83764499/124521442-65cc3e00-dde7-11eb-8779-993f76046bcd.png)
![Screenshot_20210705-231427](https://user-images.githubusercontent.com/83764499/124521457-7381c380-dde7-11eb-894a-45e22d55ea99.png)

### Other details
When the app is restarted and reverts to the default amoled the more and download section of manga becomes white
![Screenshot_20210705-231545](https://user-images.githubusercontent.com/83764499/124521416-4d5c2380-dde7-11eb-8bcc-1d5e349033da.png)
(the dark and light themes are working as intended)

**Comment by SlamZDank** [comment]
Thanks for the hotfix!

**Comment by SlamZDank** [comment]
it appears that if you have an amoled theme applied in v 1.1.0 then change the language setting and then click on the back button the amoled theme will once again break.

**Comment by Jays2Kings** [comment]
I'll further look into it for a future release, but this wont be a hotfix unless more issues arise

**Comment by Jays2Kings** [comment]
Actually @SlamZDank make a similar issue on [Tachiyomi repo](https://github.com/tachiyomiorg/tachiyomi/issues), the issue exists there as well, and the person responsible can help look into it

**Comment by Jays2Kings** [comment]
closed with ae65677a3
