### ISSUE TITLE
[Feature Request] Add ability to hide chapters in chapter list for manga in My Library

### ISSUE THREAD

**Issue by GreatestFool** [Jays2Kings/tachiyomiJ2K#89]
It is technically possible to skip chapters by enabling *skip read chapters* in settings, however it's cumbersome and incredibly impractical for larger manga. I made a [feature request for it on the main line](https://github.com/inorichi/tachiyomi/issues/2542), though I don't think it's the kind of feature to make it into the main line so I'm posting it here too. Hopefully I'm not breaking some kind of unspoken github code of conduct.

### Why/User Benefit/User Problem

When a source has multiple versions of the same chapter (mangadex does this because anyone can add theirs), the user ends up having to skip a few chapters worth when reading because the same one comes over and over again. It's pretty annoying and breaks from the smooth reading flow. 

Here's an example from One Punch Man using mangadex as a source:

![20200125_135248](https://user-images.githubusercontent.com/3003484/73121415-19d26400-3f7a-11ea-93fe-f62be9e361f2.jpg)

### What/Requirements

When pressing the context menu (three dots) on a chapter, as well as when long pressing a page inside a chapter to open the context menu (or something similar), have a button like "Hide chapter" that hides it in the chapter list as well as automatically skipping it while reading so it won't interrupt the user.

**Comment by Jays2Kings** [comment]
As the other requests mentions there is ways around it. If you're logged into mangadex you can also hide translators on the website and it reflects in app

**Comment by GreatestFool** [comment]
I see.

On site you can switch between scanlator groups, would changing the ways chapters are shown be something you'd be willing to implement? Like having alternate versions of a chapter show only as one and let the user switch between scanlator groups within the relevant chapter? That would at least solve the chapter list bloat.
