### ISSUE TITLE
[Feature Request] option tomove side navigation icons to the bottom

### ISSUE THREAD

**Issue by asdkant** [Jays2Kings/tachiyomiJ2K#890]
### Why/User Benefit/User Problem
I'm using a tablet in portrait mode, so horizontal space is at a premium while vertical space is plenty (basically the opposite of every desktop screen nowadays)

### What/Requirements
A toggle so people like me can have the big side navigation icons back at the bottom.
Inteligent placing according to the orientation as a third option in the toggle would be nice, but since I always use portrait mode it would't add much to my particular use case.
Another nice to have would be the option to decide which of the four sides of the screeen to use (again, the bottom is enough for me, but someone else may find the extra flexibility useful)

**Comment by ccrowles** [comment]
Agreed, I use a tablet in portrait mode and side icons take away quite a lot of thumbnail space, an option to choose if we want it on side or on bottom would be great. 

(Also the side placement makes the screen look asymmetrical which is kinda ugly, but that's just me being nitpicking.)

**Comment by Shelaba** [comment]
I very much feel the same way. I switched from Tachiyomi proper solely because of this change, and their stance on not giving people the option to choose while still having the software be able to choose based on dpi.

**Comment by hasandroid32** [comment]
I feel the same way as well. Navigation icons on the bottom was good.

**Comment by skules** [comment]
Agreed, Navigation buttons at the side is horrible on a tablet. Need them back at the bottom or an option to hide them.

**Comment by GrimCrim95** [comment]
I agree I use a tablet too and not only does the sidebar makes navigation harder, but it makes it harder to differentiate between it and the accessibility button I have on the left side of the screen (it basically has all of the basic tablet functions that are ddifficult to  do because of mobility/tremor/hand weakness relatedissues)and I can't move it because the left side is also where I have the accessibility settings whereit  won't read touch in certain regionsof the screen because that's how I hold the tablet.

**Comment by d4rky-pl** [comment]
I wanted to spend some time with the new UI before I start complaining but I have to agree - it feels _off_ and it's inconsistent anyway because it disappears when browsing the source directly. I'd love an option to move it back to the bottom.

**Comment by d4rky-pl** [comment]
Thank you. This issue can now be closed 🙂

**Comment by CarlosEsco** [comment]
Protrait mode now always shows bottom nav while landscape shows side nav
