### ISSUE TITLE
[Bug] Failing to install extensions

### ISSUE THREAD

**Issue by Frank1907** [Jays2Kings/tachiyomiJ2K#892]
### Device information
* Tachiyomi version: 1.1.0
* Android phone & version: Android 10 on Xiaomi Mi 10

## Steps to reproduce
1. Go in extensions
2. Try to install any extension

### Expected behaviour
Extensions should be installed

### Actual behaviour
Give error and it doesn't install the extension

### Other details
Just as a reminder, in all newer Xiaomi devices, there are some MIUI optimization that are enabled by default and can be disabled (in developer settings) at some costs and they already create problems with certain .apk
I tried disable them and the new installer work but you should keep in mind that:
1) disable the MIUI optimization is somewhat limiting (at least for me)
2) from my experience most of the time the issue is related to the apk file that contains multiple installers or something like that. In your specific case the older installer worked just fine without any problem at all so it really seems strange to me that now the same apks gives problems (but for sure I'm just ignorant)

Please introduce a switch to use the older installer or, if this is a bug on your side, try to fix it

Let me know if you need me to do some other tests or give you some logs or things like that

**Comment by arkon** [comment]
I looked into this a bit and apparently Xiaomi, in classic Xiaomi fashion, breaks this Android functionality by allowlisting specific apps to use the PackageInstaller API.

cf. https://github.com/android-police/apkmirror-public/issues/116

It seems like MIUI "Optimizations" could be programmatically detected though, so maybe the app could warn users about it.

**Comment by Frank1907** [comment]
Yea it can be detected. It would be nice as I said if there is a switch to enable the legacy since xiaomi phones are common.

**Comment by Jays2Kings** [comment]
This is a duplicate but I'll leave it open since a suggestion was also made

**Comment by Jays2Kings** [comment]
warning added with 248d57600

**Comment by Caio99BR** [comment]
I don't know if this can help, but installing via MIUI download manager (press on file downloaded on notification) give a warning and allow to install normally with optimizations enabled

![Screenshot_2021-09-22-00-23-24-001_com google android packageinstaller](https://user-images.githubusercontent.com/7280407/134278599-4f574991-b666-42d6-a815-6541e732fbc8.jpg)

![Screenshot_2021-09-22-00-23-35-762_com google android packageinstaller](https://user-images.githubusercontent.com/7280407/134278579-f205b1c9-a393-4660-8937-a0514fc35611.jpg)
