### ISSUE TITLE
[Tracking Request] please add Animeplanet as an option

### ISSUE THREAD

**Issue by Saltyapplepies** [Jays2Kings/tachiyomiJ2K#893]
### Why i want anime planet for tracking
(I don't use any other tracking website other than anime planet and it is too late for me to change it. So please do listen to my request)

**Comment by DaviDeMeo** [comment]
Anime planet doesn't expose a public API yet. The last info of any kind is from the [announcement](https://www.anime-planet.com/forum/threads/coming-soon-export-functionality-public-api.329899/) from 2018:
> Public API : End of June goal (or sooner if we can swing it). For basic information. Scope: anime database basic info lookup (manga, other types either as a v2 or in the same release). User anime/manga list updating capabilities.

**Comment by Saltyapplepies** [comment]
> Anime planet doesn't expose a public API yet. The last info of any kind is from the [announcement](https://www.anime-planet.com/forum/threads/coming-soon-export-functionality-public-api.329899/) from 2018:
> 
> > Public API : End of June goal (or sooner if we can swing it). For basic information. Scope: anime database basic info lookup (manga, other types either as a v2 or in the same release). User anime/manga list updating capabilities.

Oh well, thanks tho ^^

**Comment by Jays2Kings** [comment]
Closing this since this is on Animeplanet first, it can be brought back whenever they decide to have an api
