### ISSUE TITLE
[Feature Request] App Update Notification 

### ISSUE THREAD

**Issue by Vinny0P** [Jays2Kings/tachiyomiJ2K#894]
### Why/User Benefit/User Problem
It would be great if this feature is gonna be added, users wouldn't have to go to the site and download the newest version to update the app anymore.

### What/Requirements
A notification will appear about an app update, like the one in the Neko fork.

**Comment by ccrowles** [comment]
There is already an update popup that appears when you open the app, though. It downloads the new update in the background if you tap "agree", you just have to swipe down the notification panel when it finishes and tap on the download to install it.

**Comment by Vinny0P** [comment]
> There is already an update popup that appears when you open the app, though. It downloads the new update in the background if you tap "agree", you just have to swipe down the notification panel when it finishes and tap on the download to install it.

Oh, I don't know why but mine doesn't have the update pop-up at all, only my Neko app has it. I checked the app notifications in settings too and all of it is toggled on, I'll just try re-installing the app.

**Comment by ccrowles** [comment]
> > There is already an update popup that appears when you open the app, though. It downloads the new update in the background if you tap "agree", you just have to swipe down the notification panel when it finishes and tap on the download to install it.
> 
> Oh, I don't know why but mine doesn't have the update pop-up at all, only my Neko app has it. I checked the app notifications in settings too and all of it is toggled on, I'll just try re-installing the app.

Yeah that's odd, I got the update popup not even an hour ago so I'm pretty sure it works, at least for me. There should be a big popup when you open J2K if there's a new version available, it literally covers 80% of the app screen and you can either tap "agree" (or install, can't remember) or something like cancel/remind me later/stuff like that to temporarily not update. On which version are you? Because in the popup I remember something like "if you're on [x] version you have to manually update first", can't remember which version though.

**Comment by Vinny0P** [comment]
> > > There is already an update popup that appears when you open the app, though. It downloads the new update in the background if you tap "agree", you just have to swipe down the notification panel when it finishes and tap on the download to install it.
> > 
> > 
> > Oh, I don't know why but mine doesn't have the update pop-up at all, only my Neko app has it. I checked the app notifications in settings too and all of it is toggled on, I'll just try re-installing the app.
> 
> Yeah that's odd, I got the update popup not even an hour ago so I'm pretty sure it works, at least for me. There should be a big popup when you open J2K if there's a new version available, it literally covers 80% of the app screen and you can either tap "agree" (or install, can't remember) or something like cancel/remind me later/stuff like that to temporarily not update. On which version are you? Because in the popup I remember something like "if you're on [x] version you have to manually update first", can't remember which version though.
> 
> EDIT: Found the message here in the github too, here's the screenshot:
> ![image](https://user-images.githubusercontent.com/12866474/124587268-b9767000-de57-11eb-9f7c-a0e1c60785f0.png)

The app was v1.0.17 when I first downloaded it, this is my first time manually updating the app. My app is v1.1.0 right now.
