### ISSUE TITLE
[Feature Request] Add e-ink theme

### ISSUE THREAD

**Issue by hanxin1997** [Jays2Kings/tachiyomiJ2K#896]
### Why/User Benefit/User Problem
I hope users of the e－ink have a better experience

### What/Requirements
There is a mode dedicated to e-ink

**Comment by Jays2Kings** [comment]
Can you give an example of what this means? A screenshot or reference will do

**Comment by hanxin1997** [comment]
> Can you give an example of what this means? A screenshot or reference will do

You can refer to the e-lnk theme of {Perfect viewer} in the play store
The e-lnk theme is mainly black and white, because e-lnk can only recognize black and white pictures, and the refresh rate of e-lnk is very low, so I hope that it can be set without animation.

**Comment by CarlosEsco** [comment]
@hanxin1997 it's your request, could you at least send screenshots of PV's e-ink theme.

**Comment by hanxin1997** [comment]
> @hanxin1997 it's your request, could you at least send screenshots of PV's e-ink theme.
![Screenshot_2021-07-07-19-14-22-688_io legado app](https://user-images.githubusercontent.com/58620096/124750184-bc588a00-df57-11eb-8b93-11be3d8e516f.jpg)
![Screenshot_2021-07-07-19-14-17-809_io legado app](https://user-images.githubusercontent.com/58620096/124750187-bfec1100-df57-11eb-80a0-bcdfa4491fab.jpg)
This is a screenshot of another software that I think is done well in e-ink mode
The color contrast is obvious. Switching to the e-ink theme, the color becomes black and white, and there is no transition animation during the whole process.

**Comment by Jays2Kings** [comment]
Basically the theme in upstream called yin yang, which is added in 0ebdbe174
