### ISSUE TITLE
[Feature Request] MD2 white theme

### ISSUE THREAD

**Issue by RayyanCW** [Jays2Kings/tachiyomiJ2K#90]
### Why/User Benefit/User Problem
Just to make the app looks cooler and matches md2 design guidelines for android

### What/Requirements
1. White header
2. Dark statusbar icon
*You can refer to many google apps to confirm ( messages, keep, etc )

**Comment by CarlosEsco** [comment]
This will be a major enhancement.  Lots of view need updated for MD2

**Comment by Jays2Kings** [comment]
I'd like to implement md2 at some point but that's not high priority at this time. I won't close it but this won't happen for a while

**Comment by DragoCubed** [comment]
but what *is* 'MD2'? Google updated the Material Design guidelines but they allow developers to use colour, especially for branding. I think by 'MD2', you mean Google's Material Theme.

Sorry I'm being pedantic

**Comment by Jays2Kings** [comment]
Added
