### ISSUE TITLE
[Bug] App crashes after i go to settings > general

### ISSUE THREAD

**Issue by DeltaKiloOne** [Jays2Kings/tachiyomiJ2K#901]
### Device information
* Tachiyomi version: v1.1.0
* Android phone & version: Samsung A21s Android 10

## Steps to reproduce
1. Go to settings 
2. Go to general 

### Expected behavior
Should show me the stuff in general settings like themes n stuff

### Actual behavior
App crashes after I touch general in settings.

### Other details
Restarting the app or phone doesnt solve the issue for me.

**Comment by WIZARD012358** [comment]
It happened to me too
Just restart your phone

**Comment by DeltaKiloOne** [comment]
@WIZARD012358 doesnt work I tried it.

**Comment by DeltaKiloOne** [comment]
It's fixed for me now I opened the app switched on dark mode from the quick access panel then went to settings > general it worked
