### ISSUE TITLE
[Bug] Shared download folder

### ISSUE THREAD

**Issue by SrW0nka** [Jays2Kings/tachiyomiJ2K#902]
### Device information
* Tachiyomi version: 1.1.0
* Android phone & version: Galaxy A 80 in A11

## Steps to reproduce
1. Change downloads folder to Tachiyomi downloads folder 
2. J2K will recognize de downloads and you be able to read
3. Try change the reading mode

### Expected behavior
Works as expected 

### Actual behavior
Force close the app

### Other details
Additional details and attachments.
https://i.imgur.com/7s6cCBb.mp4

**Comment by SrW0nka** [comment]
[tachiyomi_crash_logs.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/6785627/tachiyomi_crash_logs.txt)

**Comment by Jays2Kings** [comment]
784bd2298

**Comment by SrW0nka** [comment]
thanks
