### ISSUE TITLE
[Feature Request] Add the ability to forcibly turn off/on Tablet Mode!

### ISSUE THREAD

**Issue by PythonLog** [Jays2Kings/tachiyomiJ2K#904]
Dear developers, please add the ability to forcibly disable / enable tablet mode!
_Tablet mode:_
The bottom panel **(Library Recents Browse)** is on the left side of the screen.
_Phone Mode (Smartphone):_
The bottom panel is at the bottom of the screen. _(As it was before the current version of Tachiyomi J2K)_
Tablet interface (_for me personally_, it is extremely inconvenient and hurts my eyes.) For those who like the tablet interface, but their smartphone can activate the tablet mode.
Requirements:
In "**Settings**"> "**General**" add the item "_Change device type_" in the submenu there will be items "**_Phone_**" and "**_Tablet_**", after selecting the desired mode, a window will appear asking you to restart the application.
When you turn on the "_Phone Mode_" items from **_Settings> General_** "_Side navigation icon alignment_" disappear.

**Comment by CarlosEsco** [comment]
Dear user https://github.com/Jays2Kings/tachiyomiJ2K/issues/890
