### ISSUE TITLE
New chapters appear begore the first chapter

### ISSUE THREAD

**Issue by xampl3** [Jays2Kings/tachiyomiJ2K#905]
**App version:1.1.0**

**Android version:11**

**Issue/Request: new chapters appear before the first chapter in chronological order 
![Screenshot_20210707-232759](https://user-images.githubusercontent.com/46006154/124831413-76adb880-df7b-11eb-873a-5236fb8059cf.png)
**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details: only appeared in the latest version **

**Comment by CarlosEsco** [comment]
Mangadex issue with their api.
