### ISSUE TITLE
[Feature Request] Little UI changes 

### ISSUE THREAD

**Issue by SrW0nka** [Jays2Kings/tachiyomiJ2K#907]
1. When "show number of items"  is enabled, show the number in the search  box and category hopper
![Screenshot_20210708-075847_TachiyomiJ2K](https://user-images.githubusercontent.com/76596575/124911373-0cb90180-dfc3-11eb-8f45-9de26e790dc3.jpg)
![Screenshot_20210708-075841_TachiyomiJ2K](https://user-images.githubusercontent.com/76596575/124911374-0d519800-dfc3-11eb-84e9-a11106b374d1.jpg)

2. Use secondary theme color to highlight the selected items 
![Screenshot_20210708-080103_TachiyomiJ2K](https://user-images.githubusercontent.com/76596575/124911505-32dea180-dfc3-11eb-9e0d-2b5b262b8912.jpg)

3. darken/smoke selected itens/itens in library 

4. Long press in tracking UI copy to clipboard the manga name 
5. Add a option to "pin/unpin" the extension when swipe to some side (we have "hide" for both sides today)

**Comment by Jays2Kings** [comment]
Closing this since most of these have been addressed
5. has already been discussed since its pointless with the button, and people arleady have a hard enough time realizing swiping has actions
