### ISSUE TITLE
[Bug] Start date of reading on MyAnimeList

### ISSUE THREAD

**Issue by KasukeLp23** [Jays2Kings/tachiyomiJ2K#908]
### Device information
* Tachiyomi version: 1.1.0
* Android phone & version: SAMSUNG, 7.1.1

## Steps to reproduce
1. Start reading a manga

### Expected behavior
The start date of reading is automatically placed in the tracking

### Actual behavior
Date is not placed in place

### Other details
Capture taken:

![Screenshot_2021-07-06-16-48-12](https://user-images.githubusercontent.com/70596255/124947649-a38eb980-dfd5-11eb-8dd2-34451631aca0.jpg)

**Comment by SrW0nka** [comment]
honorable mention to kitsu that dont have the option to select dates

**Comment by Jays2Kings** [comment]
I'm not able to replicate this issue. FYI if you have already tracked this manga on MAL by other means, tachij2k will not override or add any new info to the tracker.

If thats the case, you can remove from MAL and readd to verify this

**Comment by Jays2Kings** [comment]
Closing this since this is now outdated, if this is still an issue you can reply back here
