### ISSUE TITLE
[Feature] Allow users to ignore File Permissions Required prompt (Android 11)

### ISSUE THREAD

**Issue by katarai** [Jays2Kings/tachiyomiJ2K#910]
### Why/User Benefit/User Problem

Tachiyomi seems to work fine without giving the File Permissions requested in the prompt, yet it doesn't seem possible to dismiss the prompt permanently (or at least until attempting to use a feature that would actually require it).

I'd like to request the feature to dismiss the prompt semi-permanently.

### What/Requirements

I imagine this would manifest as a checkbox on the prompt to stop displaying it until we try to use a feature (downloads, local reads, auto-backups) that would actually require it.

===

Note:

Please let me know if I'm misunderstanding the reasons to grant the File Permissions to the app, but in my experience it seems completely fine to not provide those permissions. As a user who doesn't have auto-backups, doesn't download chapters, and doesn't read locally stored manga, it seems like more of an annoyance than anything else at the moment.

I admit some surprise that the manual backups seem to work without any issue without the File Permissions, but I was able to create a manual backup without any issue.

**Comment by Nabawe** [comment]
+1
