### ISSUE TITLE
[Bug] Library screen have cropped filters

### ISSUE THREAD

**Issue by Sarkwer** [Jays2Kings/tachiyomiJ2K#911]
### Device information
* Tachiyomi version: 1.1.0
* Android phone & version: huawei mediapad m5 android 9

## Steps to reproduce
1. Just open library

### Expected behavior
Should work as previous version where i can see the filters above the tablet default button menu

### Actual behavior
As it is shown in the attach the filters are now cropped. 

### Other details

![Screenshot_20210709_005945_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/32063209/125004807-379e6680-e052-11eb-86a7-1d33eed2afc1.jpg)

**Comment by Jays2Kings** [comment]
This is fixed as of 1.1.1
