### ISSUE TITLE
[Bug] Infinity loading in trackers 

### ISSUE THREAD

**Issue by SrW0nka** [Jays2Kings/tachiyomiJ2K#912]
### Device information
* Tachiyomi version: 1.1.0
* Android phone & version: Galaxy A80 in A11

## Steps to reproduce
1. Try tracking some manga (put a random name to be sure thats return "no results"

### Expected behavior
Display the erro and stop loading 

### Actual behavior
Keeping loading animation forever unltil you back

### Other details
![image](https://user-images.githubusercontent.com/76596575/125005256-b636dc00-e031-11eb-8d42-d2406de74df8.png)

**Comment by Jays2Kings** [comment]
closed with a688ef0ae
