### ISSUE TITLE
[Feature Request] Chapter list sorting + first page after opening thumbnail

### ISSUE THREAD

**Issue by vongdong** [Jays2Kings/tachiyomiJ2K#92]
Seems like most manga chapter lists start from the bottom. Can am option be made so it either starts at the top or the bottom? They randomly start at either end on different manga. Also I've noticed when you change the sorting order from ascending to descending it's only for individual manga, can that be made for all manga?

Basically when I open a chapter list I want it to start from the top with the latest chapter and swipe up to see older chapters.

Would be great to see an option on which page (info page or chapter list) shows up first when opening a thumbnail too.

Please make these settings available in the global settings, 'settings > library' page.

**Comment by joseph619** [comment]
I suggest you add Global setting so that it's easier for Jay to understand.

**Comment by vongdong** [comment]
> 
> 
> I suggest you add Global setting so that it's easier for Jay to understand.

Just edited it. Is that better?

**Comment by joseph619** [comment]
I suggesting adding the term Global settings for Page list ordering to your description, but Jay should understand what you mean

**Comment by vongdong** [comment]
> 
> 
> I suggesting adding the term 'Global settings' for Page list ordering to your description, but Jay should understand what you mean

Oh okay. I'll just add it anyway.

**Comment by Mechanical-sanity** [comment]
I agree, I started to use this version and it is so much better than tachiyomi, but this issue kind of bothers me

**Comment by Jays2Kings** [comment]
Added
