### ISSUE TITLE
[Feature Request] Improve the experience of e-ink reader

### ISSUE THREAD

**Issue by XGMO9** [Jays2Kings/tachiyomiJ2K#920]
### Why/User Benefit/User Problem

Hope to improve the experience of e-ink reader

### What/Requirements
Turn on optimization for eink devices through options, including the following options,Because the refresh rate of eink devices is low
1. Disable in-app animation
2. Divide the long list into multiple short lists of exactly one screen size

**Comment by CarlosEsco** [comment]
1.  You can disable animations on your device right?
2.  There is an option iirc to show only the selected category that should get you some slightly better refresh.  I doubt paged scrolling is going to be added though

**Comment by XGMO9** [comment]
> 1. You can disable animations on your device right?
> 2. There is an option iirc to show only the selected category that should get you some slightly better refresh.  I doubt paged scrolling is going to be added though

1.Yes, but some in-app animations cannot be prohibited
2.Thanks for your reply, i will try

**Comment by Jays2Kings** [comment]
For 1. you can go to developer settings and turn off all animations, you can look up how to do this online
As carlos said 2. isn't going to happen so im closing this

**Comment by vinipsmaker** [comment]
> You can disable animations on your device right?

I can't on my Bigme Inknote color. I can't access Android developer options on Bigme Inknote color.

Anyway, thanks for the great app.

> Hope to improve the experience of e-ink reader

A fully black & white (minimum to no grayscale tricks) high-contrast theme would also help tons.

**Comment by zanjie1999** [comment]
Some animations don't seem to be turned off, such as pop-ups

all animations  in developer settings is disable
