### ISSUE TITLE
[Feature] Sync read chapters for kitsu

### ISSUE THREAD

**Issue by SrW0nka** [Jays2Kings/tachiyomiJ2K#921]
### Why/User Benefit/User Problem
This help the peoples  that don't  using  tracking to start do it

### What/Requirements
Like what already happens in AniList, when you add tracking  to a manga that you reading the app auto set the read chapters into the tracker but this don't happen to kitsu (idk for mal)

**Comment by Jays2Kings** [comment]
Already covered in https://github.com/Jays2Kings/tachiyomiJ2K/commit/000be367223822fce2cc483c8a38c830a3225504

**Comment by SrW0nka** [comment]
ohhh okay, thanks  again jay 😳
