### ISSUE TITLE
[Feature Request] category display

### ISSUE THREAD

**Issue by Sidepunch** [Jays2Kings/tachiyomiJ2K#922]
### Why/User Benefit/User Problem
I've recently decided to use tachiJ2K instead of tachiyomi stable but I am still not used it reason being the category display format in library.i know this is a selfish request and the only benefit it does to tachiyomi users who want to switch to tachiJ2K. But please add a option to switch between tachiyomi library format (matrix of categories) and tachiJ2K format( folders of categories).

Please let me know if it's not possible.
Thanks for your time and work.

### What/Requirement
tachiJ2K format
![Screenshot_20210714-163248](https://user-images.githubusercontent.com/86877694/125611875-b4c9ed57-f689-4e90-b842-e821a606492b.png)

Tachiyomi format
![Screenshot_20210714-163248](https://user-images.githubusercontent.com/86877694/125611949-e903a69e-239f-417d-a41b-d174575bb94d.png)
![Screenshot_20210714-163300](https://user-images.githubusercontent.com/86877694/125612001-409097be-7c1a-4bb6-97e7-0a91b7dbe531.png)
![Screenshot_20210714-163303](https://user-images.githubusercontent.com/86877694/125612031-6fcfb6ca-d178-49e6-8e25-7c40af6e0ec7.png)

**Comment by CarlosEsco** [comment]
Already declined before.  Best you are gonna get is the drop down that shows the categories at the top

**Comment by CarlosEsco** [comment]
also you only posted regular tachiyomi screens

**Comment by Sidepunch** [comment]
> Already declined before. Best you are gonna get is the drop down that shows the categories at the top

Phew, I thought I wouldn't even get replied thanks for reading . I guess I'll have to get used to it eventually.

**Comment by Sidepunch** [comment]
> also you only posted regular tachiyomi screens

Shit I messed up , sorry.

**Comment by CarlosEsco** [comment]
you can enable show only 1 category, and use the category hopper or the drop down at top. If you are wanting it to only show 1 category on the screen at a time

**Comment by Sidepunch** [comment]
> you can enable show only 1 category, and use the category hopper or the drop down at top. If you are wanting it to only show 1 category on the screen at a time

Thanks I will use it from now on ☺️
