### ISSUE TITLE
[Feature Request] allow the category hopper to cycle through completely 

### ISSUE THREAD

**Issue by 05k-44** [Jays2Kings/tachiyomiJ2K#923]
### Why/User Benefit/User Problem
This feature would allow the user with a large library and many categories to quickly move from the top to bottom (by pressing the up button on the category hopper) and bottom to top (by pressing down on the category hopper) while looking in their library 

### What/Requirements
Make it so that when you are at the bottom of your library, and press the down option on the category hopper it'll send you to the first category, and the opposite for the top to bottom category

**Comment by Jays2Kings** [comment]
No point of this since you can long press the category hopper arrow to move all the way to the top of bottom of the screen
