### ISSUE TITLE
[Bug] [MIUI] Can't install extension

### ISSUE THREAD

**Issue by Mylloon** [Jays2Kings/tachiyomiJ2K#926]
### Device information
* Tachiyomi version: 1.1.1
* Android phone & version: Mi Note 10 Lite | Android 11

## Steps to reproduce
1. Open extension tab
2. Try to install an extension

### Expected behavior
Starting the installation process

### Actual behavior
Do not install the extension because of MIUI optimization "enabled"

### Other details
MIUI optimizations are disabled but I can't install extension.
![IMG_20210715_011140](https://user-images.githubusercontent.com/29067904/125705250-0821de32-f4ca-44cc-9a37-2bfb9c374ad2.jpg)
![IMG_20210715_011159](https://user-images.githubusercontent.com/29067904/125705255-2baea99a-c622-4a24-ad94-0f2f026ed6a3.jpg)

**Comment by Jays2Kings** [comment]
I have rereleased v1.1.1 https://github.com/Jays2Kings/tachiyomiJ2K/releases/tag/v1.1.1 with the fix
please redownload and try again

**Comment by bosco404** [comment]
Try installing the extension from file manager after downloading, that's what i did

**Comment by arisudesu** [comment]
Mind explaining changes to installation process? Extensions installed fine before v1.1.0 without toggling optimisations. I think this is a regression.

Also this:
> Do not blame me for you picking a bad phone
With all my respect to you as to a developer. You're not in position to judge what's good and what's bad here. Blame your tools (e.g. Android framework) for being a pile of crap and not working the same way on every device. Sorry.

**Comment by CarlosEsco** [comment]
@arisudesu He is 100% in position to judge what is good and bad, you chose a manufacturer that purposely is breaking the package installer provided by the android framework.  

 https://github.com/android-police/apkmirror-public/issues/116

**Comment by Mylloon** [comment]
> I have rereleased v1.1.1 https://github.com/Jays2Kings/tachiyomiJ2K/releases/tag/v1.1.1 with the fix
> please redownload and try again

I redownloaded and it's working, thanks

**Comment by arkon** [comment]
> Blame your tools (e.g. Android framework) for being a pile of crap and not working the same way on every device.

You should be blaming Xiaomi for braking the Android framework...

**Comment by bosco404** [comment]
> > Blame your tools (e.g. Android framework) for being a pile of crap and not working the same way on every device.
> 
> You should be blaming Xiaomi for breaking the Android framework...

Christ!
