### ISSUE TITLE
Global Screen Orientation

### ISSUE THREAD

**Issue by DumbCodeGenerator** [Jays2Kings/tachiyomiJ2K#928]
**Issue/Request:**
Maybe I'm just blind, but do this app has some way to use screen orientation from "default" settings on ALL mangas/comics? I'm tired of switching it almost on every manga I read from extensions(in the library it's working fine almost)

**Comment by Safuez** [comment]
Setting --> Reader --> Orientation
![Screenshot_20210715-214351564.jpg](https://user-images.githubusercontent.com/81817527/125807789-ff23033d-6d15-4bf7-9eb2-e28318fa3b35.jpg)
