### ISSUE TITLE
[Bug] Download(ed) badge missing after chapter update

### ISSUE THREAD

**Issue by Zenothia** [Jays2Kings/tachiyomiJ2K#93]
### Device information
* Tachiyomi version: 0.9.76
* Android phone & version: 9

## Steps to reproduce
You have downloaded previous chapters and then there is a new chapter update. Sometimes when you have downloaded the chapters, the badge (red icon number) is missing along with the "DOWNLOADED" reminder on the chapters info. It may and may not occur on all manga but it will happen eventually.
While you can actually read the chapter without redownloading (the image files actually exist when you check with file manager), deleting just one chapter will delete the whole book (all downloaded chapters in this particular buggy manga entry).

For now, the solution is simply to read all the chapters before deleting them and disable automatic remove after read.

This bug will trigger when manual or automatic download new chapters enabled.

**Comment by Jays2Kings** [comment]
Can you specify a manga or the sources you usually see this problem on, trying this out doesn't seem to happen for me, and deleting all manga chapters shouldn't happen ever

**Comment by Zenothia** [comment]
I use Mangakakalot as source. It happened to:
Metropolitan System
Kenja no Mago
Gotoubun no Hanayome

I don't think it specific to these manga because it happen only when there is a new chapter downloaded. The "deleting all" occur only when these bug triggered.

**Comment by Jays2Kings** [comment]
Please check in 0.9.8 if you're still having issues with this, I've changed how the caching works and should be fine now. If not please check and make sure the folder name matches the manga title

**Comment by joseph619** [comment]
User handy replied in a month. Should be closed now.

**Comment by Jays2Kings** [comment]
Makes sense to me
