### ISSUE TITLE
[Bug] Miui optimization must be disabled 

### ISSUE THREAD

**Issue by wankio** [Jays2Kings/tachiyomiJ2K#932]
Miui optimization already disabled but it still say that when i'm trying to update extensions

---

### Device information
* Tachiyomi version: Lastest
* Android phone & version: Android
*

**Comment by bosco404** [comment]
What device?

**Comment by Jays2Kings** [comment]
Please reinstall the release of v1.1.1, see the comments here https://github.com/Jays2Kings/tachiyomiJ2K/issues/926#issuecomment-880284271 

The [link](https://github.com/Jays2Kings/tachiyomiJ2K/releases/tag/v1.1.1) to the app is at the bottom under assets
