### ISSUE TITLE
[Feature Request] Double Pages:  Manual Toggle for splitting/joining source pages

### ISSUE THREAD

**Issue by h-hyuuga** [Jays2Kings/tachiyomiJ2K#938]
### Why/User Benefit/User Problem

TachiyomiJ2K already does a pretty great job producing the double page view, but there are tons of edge cases that make it difficult to produce the correct result.

Giving the user some control would allow them to correct these issues as they read

### What/Requirements

This feature I assume from a UI/UX standpoint would best be served with:

* A gesture (for convenience)
* An entry in a menu (for redundancy)

Both would activate a toggle which:

* On a  **tachiyomi-joined double spread** forces the lower numbered page to display on its own, then recomputes its automated merging for subsequent pages
* On a **single page** forces tachiyomi to join it with the following page, then recomputes its automated merging for every page after that

### Other

If you could point me to the relevant code, I'd be willing to take a stab at this

**Comment by Jays2Kings** [comment]
Not sure what you mean since images that are double pages display the previous page on their own if it doesnt have another page with it. There's also a button in the toolbar to shift which pages are joined
