### ISSUE TITLE
[Bug] Weird Flickering Interchapters

### ISSUE THREAD

**Issue by MagnesG** [Jays2Kings/tachiyomiJ2K#94]
### Device information

* Tachiyomi version: 0.9.76
* Android phone & version: Poco F1 & Android 9

## Steps to reproduce
1. Reach the end of any chapter.

### Expected behavior
No flickering.

### Actual behavior
The inter chapter segment flickers.

### Other details
![Screenshot_20200202-142100_Tachiyomi](https://user-images.githubusercontent.com/58797465/73604176-524fee80-45c7-11ea-8632-6ec659eafa35.png)
![Screenshot_20200202-142042_Tachiyomi](https://user-images.githubusercontent.com/58797465/73604177-524fee80-45c7-11ea-8ef3-3b44418819b7.png)
![Screenshot_20200202-142051_Tachiyomi](https://user-images.githubusercontent.com/58797465/73604178-524fee80-45c7-11ea-89af-912f4db75208.png)

**Comment by Jays2Kings** [comment]
Can you provide a few more details, such as what app theme you're using and what page background, viewer type, etc.

**Comment by Riztard** [comment]
mine too

Device information
Tachiyomi version: 0.9.76
Android phone & version: Xiaomi Redmi 4X & Android 9

and im use dark theme, background smart by page, viewer webtoon

**and i think the smart background was the culprit**, when im change it to black it become normal 

http://tinyimg.io/i/lWjgvbj.png
http://tinyimg.io/i/uXFNFdD.png
http://tinyimg.io/i/txzJiPc.png

**Comment by Jays2Kings** [comment]
This has helped me understand it more, I'll try to fix it quickly

**Comment by Jays2Kings** [comment]
Issue fixed as of [0.9.761](https://github.com/Jays2Kings/tachiyomiJ2K/releases/tag/v0.9.761)
