### ISSUE TITLE
[Bug] Manga dissapearing after being pressed in library

### ISSUE THREAD

**Issue by NiceBlue31** [Jays2Kings/tachiyomiJ2K#942]
### Device information
* Tachiyomi version: J2K 1.1.1
* Android phone & version: Samsung S10 & Android 11

## Steps to reproduce
1. Enter library
2. Select any manga
3. Go back

### Expected behavior
Manga should not dissapear after going back.

### Actual behavior
Manga looks like its being deleted.

### Other details
[Youtube video](https://youtu.be/DDbElPf9Bxs)

**Comment by CarlosEsco** [comment]
What is the sort order you are using

**Comment by NiceBlue31** [comment]
> What is the sort order you are using

Title

**Comment by CarlosEsco** [comment]
The title is updating.  If you notice in your library view the title contains quotes.  Refresh all your metadata should update all those titles
