### ISSUE TITLE
[Bug] Tachij2k hard crashes when you try to edit categories GU configuration

### ISSUE THREAD

**Issue by Clouddark75** [Jays2Kings/tachiyomiJ2K#949]
### Device information
* Tachiyomi version: 1.2.1
* Android phone & version: 10

## Steps to reproduce
1. First step
Go to Config > Library - Global Updates 

2. Second step
Select Categories and when you try to disable updates for any or even click on it, J2k will hard crash. 

### Expected behavior
It should not crash and allow you to edit the categories updates configuration. 

### Actual behavior
Hard crash. 

### Other details
Additional details and attachments.

**Comment by Jays2Kings** [comment]
Please add crash logs via settings -> advanced -> dump crash logs and attach here

**Comment by Clouddark75** [comment]
--------- beginning of crash
08-19 18:50:36.352 16159 16159 E AndroidRuntime: FATAL EXCEPTION: main
08-19 18:50:36.352 16159 16159 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 16159
08-19 18:50:36.352 16159 16159 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.materialdialogs.QuadStateMultiChoiceDialogAdapter.itemClicked$app_standardRelease(QuadStateMultiChoiceDialogAdapter.kt:205)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.materialdialogs.QuadStateMultiChoiceViewHolder.onClick(QuadStateMultiChoiceViewHolder.kt:29)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.view.View.performClick(View.java:6659)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6631)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.view.View.access$3100(View.java:790)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26187)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:907)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
08-19 18:50:36.352 16159 16159 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
08-19 18:50:46.319 16490 16501 E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
08-19 18:50:47.825 16376 16387 E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
08-19 18:50:48.354 16490 16501 E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]

**Comment by Clouddark75** [comment]
> Please add crash logs via settings -> advanced -> dump crash logs and attach here

There, sorry for the late response!
