### ISSUE TITLE
[Bug] Date format changed from English (UK) to default

### ISSUE THREAD

**Issue by Riztard** [Jays2Kings/tachiyomiJ2K#95]
### Device information
* Tachiyomi version: 0.9.761 
* Android phone & version: Xiaomi Redmi 4X & Android 9

## Steps to reproduce
video reproduce bug https://streamable.com/1k9i5
1. choose manga
2. choose chapter that not been chached yet
3. close chapter
4. close manga
5. open manga 

### Expected behavior
the date format should be 24/12/19

### Actual behavior
the date format return to 12/24/19

### Other details
this bug has been here quite some time, i just doesnt realize the cause till now

**Comment by Riztard** [comment]
oh addition on language setting, its still English (UK)
to return back i need to force stop or clean recent program

**Comment by Jays2Kings** [comment]
There's now a setting in general as of v0.9.8 to always use a date format now, so this shouldn't happen anymore

**Comment by Riztard** [comment]
thank you, my king
