### ISSUE TITLE
[Feature Request] Update all Exensions Function

### ISSUE THREAD

**Issue by SunBreaker1** [Jays2Kings/tachiyomiJ2K#951]
### Why/User Benefit/User Problem
Normally apps stores have an "Update all" function that allows all the updates to be cued up and download all the updates for all the apps in that cue. In TachiJ2K, this feature doesn't exist. Meaning all extensions have to be updated manually. 

### What/Requirements
Understandably, extension updates don't happen often that this feature is a necessity. However is would be a nice quality of life addition for those who have a large amount of extensions installed, don't update extensions as soon as they release, or access the app infrequently and have multiple extension updates waiting for them upon opening the app.

**Comment by CarlosEsco** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/944
