### ISSUE TITLE
[Feature Request] Merging different sources for the same manga

### ISSUE THREAD

**Issue by Pillow-Fan** [Jays2Kings/tachiyomiJ2K#954]
### Why/User Benefit/User Problem
Some sources give an incomplete list of a manga's chapters or temporarily stop uploading, forcing the user to add the same manga from another source and having duplicates in their library.

### What/Requirements
With this function the library would only show one entry per manga which upon being tapped would show the usual manga page but by sliding left or right, the user has the possibility to choose from which source they want to read from and sync the read chapters from all sources saved. Below a rough edit of how it could be done.

The app should ideally automatically find the duplicates of a manga but in case not all copies are added correctly, the user should be given the chance to manually add duplicate to a manga via a dedicated button.

![PicsArt_08-01-02 10 02](https://user-images.githubusercontent.com/28104347/127770405-fd758139-7bb5-4179-8f09-65499fc48b6c.jpg)

**Comment by CarlosEsco** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/313
