### ISSUE TITLE
MyAnimeList Manga syncs not working since April 29

### ISSUE THREAD

**Issue by Itsfurqan1337** [Jays2Kings/tachiyomiJ2K#955]
**App version:** 1.2.1

**Android version:** 8.0.0

**Issue/Request:** MAL Sync not working

**Other details:**
I haven't noticed it before but after recently checking it, TachiJ2K does not auto sync the chapters with my MAL Account and instead it gives an HTTP error 401 when I tried deleting and retracking a manga. 
This is happening since April 29 as the last chapter that was synced was on that date according to MAL
![WhatsApp Image 2021-08-02 at 1 45 00 AM](https://user-images.githubusercontent.com/65011832/127784836-2614a9b6-855c-436a-b5cb-0997aaa62777.jpeg)

**Comment by CarlosEsco** [comment]
Logout and relogin
