### ISSUE TITLE
"Add to library" button revamp?

### ISSUE THREAD

**Issue by omaronly** [Jays2Kings/tachiyomiJ2K#956]
I just think the heart in add to library option looks odd that's all.

so if you just remove the heart or do something else there it would look better Iguess.

---

### Why/User Benefit/User Problem
-It'll look better

### What/Requirements
-Just remove the heart I guess
![IMG_20210802_144821](https://user-images.githubusercontent.com/44256630/127837392-77408078-38ea-48fd-ba20-58995a1c44c0.jpg)

**Comment by CarlosEsco** [comment]
I'm confused how that looks better?  Are you suggesting the same thing for tracking too?

![Screenshot_20210802-075918_TachiyomiJ2K.jpg](https://user-images.githubusercontent.com/2092019/127858530-dd434b51-9399-4019-89cf-067e42304025.jpg)

**Comment by omaronly** [comment]
> I'm confused how that looks better? Are you suggesting the same thing for tracking too?
> 
> ![Screenshot_20210802-075918_TachiyomiJ2K.jpg](https://user-images.githubusercontent.com/2092019/127858530-dd434b51-9399-4019-89cf-067e42304025.jpg)

Welp
that'll look weird then.

**Comment by Jays2Kings** [comment]
nah dog
