### ISSUE TITLE
[Feature Request] show list of manga that had a url change

### ISSUE THREAD

**Issue by ayhamo** [Jays2Kings/tachiyomiJ2K#959]
### Why/User Benefit/User Problem
This feature is very useful for users who have a lot of manga as myself, for 500 manga, if one had a URL change, I'd have to migrate all the 500 manga to the same source to identify it fix it( with bug https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6763) which is very annoying and long, and as of recent, I must do it weekly because lot of manga is having URL change, as mangakakalot manga provides a URL change notification if updated manually for the single manga, I think it would be good to provide a list of changed URL manga when there is a library update so that I can migrate it only, not the 500 manga

### What/Requirements
when the app/user start global library update, it should collect manga that had a URL change in a list, and display it as a separate notification beside new manga updates

**Comment by Jays2Kings** [comment]
I'm not creating a separate notification just for an issue with certain sources. Enabling "show a notification for errors" in library update settings should be enough
