### ISSUE TITLE
[Bug] cloudfare error

### ISSUE THREAD

**Issue by Samk19** [Jays2Kings/tachiyomiJ2K#96]
### Device information
* Tachiyomi version: 0.9.75
* Android phone & version: 7.1.1

## Steps to reproduce
1. While Opening some chapters from readmangatoday and kissmanga.

### Expected behavior
Chapters should open perfectly. Without using 1.1.1.1 app

### Actual behavior
 java.io.IOException error cannot bypass cloudfare and exits 

### Other details
Error not present on official Tachiyomi dev app 

Current soln restart app and change dns to 1.1.1.1 and it starts working. Also if not then second soln to one in web app and exit. But Reoccurs after some time.

Kindly fix this issue.

**Comment by aveon268** [comment]
Same issue i am also facing
![IMG_20200202_211344](https://user-images.githubusercontent.com/60576959/73610879-1be39500-4602-11ea-8bbf-d3199ee536b9.jpg)

**Comment by joseph619** [comment]
Is this still an issue? If not please close this.

**Comment by Samk19** [comment]
On some chapter it is still present

**Comment by Jays2Kings** [comment]
Closing since this is a stale issue
