### ISSUE TITLE
Auto filter by genre/tags

### ISSUE THREAD

**Issue by goosebumps48** [Jays2Kings/tachiyomiJ2K#960]
### Why/User Benefit/User Problem
easier to filter manga by genre than clicking tags/genre

### What/Requirements
When clicking on genres/tags under the manga description, it automatically filters by the selected genre/tags

**Comment by SunBreaker1** [comment]
If you know what specific tag your looking for, then try using the search bar at the top. Although the search function leave a lot to be desired, most of the time failing to search for the tag input. Multi tag searching would also be nice. I believe the best answer to this would be to implement the filtering options that some sources use, such as MangaDex or MangaLife.
