### ISSUE TITLE
[Feature Request] Set default reading mode for each source/extension in extension settings

### ISSUE THREAD

**Issue by ggermain1** [Jays2Kings/tachiyomiJ2K#963]
### Why/User Benefit/User Problem

Many of the extensions/sources are for only one type of content (manga, comic, webtoon), so allowing the user to set a default reading mode for everything from a specific source would easily allow for the correct reading mode to be used by default for different types of content.

For example: If a user sets R2L for all their manga sources, Webtoon for their manhwa, and L2R for their comics, all three will have the correct defaults with minimal extra effort.

### What/Requirements

Allow the user to set a default reading mode for each source in the extension's settings, so the Default setting on individual issues uses what's been set for that source.

**Comment by Jays2Kings** [comment]
Not happening with both the fact the app automatically tries to figure out the series type by tags and sources, and the fact extensions can host more than just one type of reading style

If you can list specific examples of where this will be useful, I can expand the auto reading mode, but your original idea is a no go

**Comment by ggermain1** [comment]
It does seem to be working though. Currently I have the default reader mode set to "Left to Right" because I read a lot of comic books. When I start to read manga, even when "manga" is in the tags and the series type is set to "manga", it still reads the manga from left to right. Could it be a source/extension issue?

**Comment by Jays2Kings** [comment]
The auto reader mode does not take into account manga should be RTL, because manga is the default series type when the type is unknown, so everything you read would default to RTL. I'm also not changing it since there's those that read manga in LTR or vertical etc.

My suggestion would be to default the reading mode to RTL and have the comics be tagged correctly so they default to LTR. This is a manga reading app first, so if youre using it as a manga reading app second, it's going to push back

**Comment by ggermain1** [comment]
I have another question. When looking at comics on the extension ReadComicOnline, a comicbook extension, all the comics on there seem to be considered manga because the info page of all the comics say "About this manga" but when looking on another extension ComicExtra, another comicbook extension, all the comics are considered comics since the info pages say "About this comic". Why is that? I ask this because it seems that when it says "About this comic" the reader mode is set to LTR but when it says "About this manga" the reader mode is set to RTL.

**Comment by MedKing3** [comment]
> If you can list specific examples of where this will be useful, I can expand the auto reading mode, but your original idea is a no go

I think adding a custom default orientation is also a good idea. For example, I only read mangas from Mangasee so I want to set the default reader mode and orientation to right to left and landscape. I only read webtoons from webtoons.com (obviously) so I want to set the default for this source to webtoon and portrait.

**Comment by Jays2Kings** [comment]
ReadComicOnline is now being considered as a comic source so this issue is being closed
