### ISSUE TITLE
[Bug] transition lag while scrolling

### ISSUE THREAD

**Issue by Samk19** [Jays2Kings/tachiyomiJ2K#97]
### Device information
* Tachiyomi version: 0.9.75
* Android phone & version: 7.1.1

## Steps to reproduce
1. Open app and scroll to chapters or personal created categories there a very big noticable lag.

### Expected behavior
Smooth transition expected while scrolling

### Actual behavior
Transition appears like the app is hang....thought starts working after few seconds but with noticable lag

### Other details
Translation set to zero in dev mode

**Comment by joseph619** [comment]
Update your app, and also enable Auto update. This has been fixed already.

**Comment by Samk19** [comment]
@joseph619  
updated to v0.9.761
still little lag present but much better that earlier. Also how do you set auto update 
unable to find that setting

**Comment by joseph619** [comment]
Close this issue since it's fixed
