### ISSUE TITLE
[Bug] Tracking does not properly activate

### ISSUE THREAD

**Issue by ItsLogic** [Jays2Kings/tachiyomiJ2K#98]
### Device information
* Tachiyomi version: 0.9.76
* Android phone & version: Huawei Mate 20 pro Android 9.0

## Steps to reproduce
Restore backup with tracked manga.

### Expected behavior
Manga should connect to tracking service like normal

### Actual behavior
A group of manga showed tracking tab with missing reading status and missing score. The tracking also does not sync chapters when they are read

### Other details
Refreshing tracking metadata does not work. Each manga needs to have the tracking page manually refreshed

Example image of manga with broken tracking:
![image](https://user-images.githubusercontent.com/38233332/73614430-f0a77880-45f6-11ea-8b8f-b88789d3a040.png)

my discord is@Draff#0001 so if my backup is needed or something just message me there

**Comment by joseph619** [comment]
Are you using Anilist?

**Comment by ItsLogic** [comment]
Yes I am

**Comment by aniik8pv2** [comment]
same issue.
when i try to manually update the tracking the app crashes

**Comment by GreatestFool** [comment]
I'm having the same issue with MyAnimeList.

**Comment by Battler624** [comment]
I am having this issue with both anilist and myanimelist, i thought maybe resyncing would fix but now i cant login into myanimelist.

Also I noticed that this doesn't affect all mangas, kingdom (from mangadex) is working perfectly (with both trackers) but nothing from mangaplus is getting tracked correctly (or rather, at all).

I cant really tell if its related to extension (I definitely hope now)

**Comment by CarlosEsco** [comment]
Is this still an issue on the latest version?

**Comment by ItsLogic** [comment]
Oh no its not I thought I had closed this issue when it got fixed sorry.
Ill close it now
