### ISSUE TITLE
[Bug] Kissmanga.in black Cover

### ISSUE THREAD

**Issue by Gensmyawk** [Jays2Kings/tachiyomiJ2K#980]
When you click a manga in kissmanga.in then go back the cover will turn to black..

**Comment by Jays2Kings** [comment]
this is an extension issue, it happens on main tachi too, just slightly differently but still.

Raise an issue on the [extension repo](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose) not here
