### ISSUE TITLE
[Bug] The loading circle that appears when you click the arrow to go to the next chapter in the reader is cut in half.

### ISSUE THREAD

**Issue by ric0369** [Jays2Kings/tachiyomiJ2K#983]
### Device information
* Tachiyomi version: 121
* Android phone & version: 11

## Steps to reproduce
1. Click the arrow to go to the next chapter.

### Expected behavior
The loading circle should appear whole, not in half.

### Actual behavior
The loading circle is cut in half.

### Other details
https://user-images.githubusercontent.com/71677337/131941346-4641a44f-c32d-4dc9-9a4e-e73911a3bd19.mp4

**Comment by Jays2Kings** [comment]
Fixed in 1.3.0
