### ISSUE TITLE
[Feature Request] Confirmation Dialogue to delete a manga from library

### ISSUE THREAD

**Issue by DuccinatorAlpha** [Jays2Kings/tachiyomiJ2K#99]
### Why/User Benefit/User Problem
I pressed delete when trying to change the category labels, although the info option appeared, I swiped up hastily trying to get the manga back, only to lose it forever because the info option disappeared
### What/Requirements
Just a small confirmation dialog with OK, Cancel buttons when delete is pressed should be enough.

**Comment by Jays2Kings** [comment]
Lol you need to panic less, but I can add it back, that's a fair request

**Comment by CarlosEsco** [comment]
1 material step forward, 2 back

**Comment by Jays2Kings** [comment]
I went back and forth on actually adding it for a while, checking how each app does it, but since tachi doesn't have a trash to retrieve unfavorited manga, the need for the dialog sadly makes sense

**Comment by joseph619** [comment]
This should be fixed now I think?

**Comment by Jays2Kings** [comment]
Sure is
