### ISSUE TITLE
[Feature Request] bring back custom language selector

### ISSUE THREAD

**Issue by WojciechJ** [Jays2Kings/tachiyomiJ2K#991]
"Custom app language has been removed, same as main Tachiyomi"

So you leave me with half translated thing without any options to change it?
This version was supposed to be better. What is the reason for custom language removal? I would much prefer it in english as it has always been. The only option right now is to change the system language. You can change so many details, but the most basic thing got taken away.

**Comment by CarlosEsco** [comment]
@TheDucker1 @WojciechJ   feel free to contribute
https://hosted.weblate.org/user/Jays2Kings/

**Comment by kice** [comment]
I just want to use language that is not I set for my system.
I would like to know why remove language selection option.
