### ISSUE TITLE
Please fix this problem

### ISSUE THREAD

**Issue by cathrin13** [Jays2Kings/tachiyomiJ2K#999]
When i scroll to read the next chapter, i can't see the number which one is next. Please fix the bug. And in history, please make the button that select all manga to delete easily in one click. When i download,  sometimes it doesn't download even i restart to download again. Please fix this problem. Thank you. I love tachiyomi apps 😍

**Comment by CarlosEsco** [comment]
Please open one ticket current issue and appropriately title the issue

**Comment by Jays2Kings** [comment]
For bugs use the right template and follow it.

**Comment by cathrin13** [comment]
I am sorry.. i m new here so i don't know how to use 😬
